### ISSUE TITLE
Low resolution text on high resolution (mac) displays

### ISSUE THREAD

**Issue by olehermanse** [pyglet/pyglet#1]
There have been various issues in the past, related to the resolution scaling on high dpi displays. This is one of them.

Using the standard hello world example, the text is rendered with lower resolution on retina displays.

This is because text is rendered on an intermediate texture before the frame buffer, and the size of this texture is based on the projection, not the frame buffer. (Typically, a mac has 2x resolution scaling in both directions, meaning that if you create a window with width=800 and height=600, the frame buffer and actual pixel resolution will be 1600x1200).

**Related tickets:** [bitbucket #248](https://bitbucket.org/pyglet/pyglet/issues/248/font-rendering-is-low-resolution-on-mac-os) [bitbucket #78](https://bitbucket.org/pyglet/pyglet/issues/78/text-looks-terrible-or-doesnt-work-with)

There is a **workaround** posted [here](https://bitbucket.org/pyglet/pyglet/issues/249/workaround-for-text-low-resolution-font).
(Changing the projection to force text rendering to use bigger textures.)

**Example code:**

```python3
__docformat__ = 'restructuredtext'
__version__ = '$Id$'

import pyglet

window = pyglet.window.Window()
label = pyglet.text.Label('Hello, world',
                          font_name='Times New Roman',
                          font_size=36,
                          x=window.width//2, y=window.height//2,
                          anchor_x='center', anchor_y='center')


@window.event
def on_draw():
    window.clear()
    label.draw()


pyglet.app.run()
```

**Windows screenshot:**

![hello_world_win](https://user-images.githubusercontent.com/4048546/61186203-e2960880-a662-11e9-819b-101d95ae7ad0.png)

**Mac screenshot:**

<img width="752" alt="hello_world_mac" src="https://user-images.githubusercontent.com/4048546/61186205-e45fcc00-a662-11e9-8953-0bc1cf245875.png">

( You might have to look close or zoom to notice that the text is low resolution. )

**Comment by olehermanse** [comment]
[There is a workaround posted here.](https://bitbucket.org/pyglet/pyglet/issues/249/workaround-for-text-low-resolution-font) (Changing the viewport to force text rendering to use bigger textures.

**Comment by benmoran56** [comment]
@olehermanse we can have a look at putting the workaround directly into the default TextLayoutGroup: https://github.com/pyglet/pyglet/blob/master/pyglet/text/layout.py#L534
That way the state is set and unset properly when rending the text.

**Comment by olehermanse** [comment]
@benmoran56 What do you mean by setting the state? I think the proper fix would be to use the `get_frame_buffer_size()` method, that I saw you discussing in Discord, to set the size of the glyph texture, instead of the viewport size. But then you have to be careful when rendering the texture into the viewport, making sure to scale it based on the ratio of the framebuffer to the viewport.

**Comment by olehermanse** [comment]
I don't think my workaround is _great_. People want to be able to control the viewport size, and still have nice text, as can be seen in [bitbucket #78](https://bitbucket.org/pyglet/pyglet/issues/78/text-looks-terrible-or-doesnt-work-with).

**Comment by einarf** [comment]
Looks like I accidentally referenced this issue in an unrelated commit message. I guess we should be careful with using `#<number>` in commit messages and comments unless actually referencing issues or pull requests 😄
