### ISSUE TITLE
GLU not found

### ISSUE THREAD

**Issue by ishan-gaur** [pyglet/pyglet#1009]
Facing a similar issue as the original issue. My output for the debug commands is the same. I also see libglu1-mesa when doing an apt search but can't find the package when using ctypes.utils.find_library. The comment before mine in the original issue shows the relevant test results mentioned in the original thread. Just wanted to call attention to this in case there is any help you all can offer. Please let me know if there is any other information about my setup that I can provide. Thanks! 

_Originally posted by @ishan-gaur in https://github.com/pyglet/pyglet/issues/456#issuecomment-1840006915_

**Comment by ishan-gaur** [comment]
Seems there are some issues with conda environments and the IDE people are using. Got resolved for me by installing libglu in the conda environment. https://anaconda.org/conda-forge/libglu

**Comment by benmoran56** [comment]
Thanks for commenting what the solution was, for future people.
