### ISSUE TITLE
'Arc' object has no attribute 'radius'

### ISSUE THREAD

**Issue by dougolson** [pyglet/pyglet#1012]
Description
Just trying to to some simple animation. Circle works fine, but I wanted to try Arc in hopes of eventually animating spherical waves as expanding concentric lines, and I get an AttributeError. Looking at the source code, the Circle has a getter and setter for radius, but the Arc does not.  I cloned the source and added the following to the Arc class and the arc animated as expected:

    @property
    def radius(self):
        """The radius of the arc.

        :type: float
        """
        return self._radius

    @radius.setter
    def radius(self, value):
        self._radius = value
        self._update_vertices()

**System Information:**
Mac OS Catalina 10.15.7 on an ancient 2012 macbook pro

**How To Reproduce**
import pyglet
from pyglet import shapes

window = pyglet.window.Window(960, 540)
batch = pyglet.graphics.Batch()
x_pos = window.width//2
y_pos = window.height//2
# arc = shapes.Circle(x_pos, y_pos, radius=100, color=(50, 225, 30), batch=batch)
arc = shapes.Arc(x_pos, y_pos, radius=100, start_angle=-1, angle=2, color=(50, 225, 30), batch=batch)

arc.dx = 10.0

def animate(dt):
    arc.radius += arc.dx * dt

pyglet.clock.schedule_interval(animate, 1/60.0)  # update at 60Hz
fps_display = pyglet.window.FPSDisplay(window=window)

@window.event
def on_draw():
    window.clear()
    fps_display.draw()
    batch.draw()

pyglet.app.run()

**Comment by benmoran56** [comment]
Hello Doug, 

If you have time to do a pull request for that addition, it would be appreciated.

**Comment by benmoran56** [comment]
This is in the latest releases, so closing. Thanks again.
