### ISSUE TITLE
Add thickness support to BezierCurve.

### ISSUE THREAD

**Issue by kingadami** [pyglet/pyglet#1029]
I am going to add the same thickness support to the BezierCurve class that I did to the Arc class.  I will make the get_segment function common and used by both.

**Comment by kingadami** [comment]
Here is what I have so far (Blue is an Arc and Red is a Curve).  This was a fairly easy change to make.
![CurveAndArc](https://github.com/pyglet/pyglet/assets/1959762/b5b84521-1693-42a9-90a3-df4a3b215ce5)

**Comment by benmoran56** [comment]
Looks good visually.

**Comment by kingadami** [comment]
Another question related to curves is do you want the concept of a 'closed' curve.  Basically it would be just like the closed parameter for `pyglet.shapes.Arc` in that it would connect the start and end with a straight line.  I don't care either way, I am just asking for completeness.

**Comment by kingadami** [comment]
Also, I went ahead and added the pull request so you can start reviewing it.  Currently, I have just added segment support to BezierCurve and that is it.
