### ISSUE TITLE
Texture.delete() method broken

### ISSUE THREAD

**Issue by ericbrandon** [pyglet/pyglet#1031]
This is using pyglet 2.0.10, python 3.10, ubuntu 22.04, running on x86 Mac mini hardware.

```python
texture = image.get_texture()
texture.delete()
```

This code consistently yields this error when the delete() is run.
```
File "/home/ebrandon/cfplay/myenv/lib/python3.10/site-packages/pyglet/image/__init__.py", line 1227, in delete
    glDeleteTextures(1, self.id)
ctypes.ArgumentError: argument 2: TypeError: expected LP_c_uint instance instead of int
```

I was able to work around the problem with the following code that manually frees up the texture from OpenGL:

```python
import ctypes
from pyglet.gl import glDeleteTextures
# Create an array of one unsigned int
texture_id_array = (ctypes.c_uint * 1)(texture.id)
# Call glDeleteTextures with the correct argument type
glDeleteTextures(1, texture_id_array)
texture.id = None
```

**Comment by pushfoo** [comment]
To confirm, x86 or amd64? I don't see x86 builds [listed for 20.04](https://releases.ubuntu.com/focal/), but there were x86 macs at one point on intel processors not using the i-series branding.

**Comment by ericbrandon** [comment]
Sorry, I meant amd64 build of Ubuntu 22.04.  This is running on late 2014 Intel Mac mini hardware.

**Comment by benmoran56** [comment]
Thanks for opening the ticket. 
This explicit Texture.delete() method was just added recently, and we missed this one. I fixed it in master, so will be included in the next point release.
