### ISSUE TITLE
CONVERTING TO EXE USING PYINSTALLER HAS ERROR

### ISSUE THREAD

**Issue by happyleibniz** [pyglet/pyglet#1035]
**Describe the bug**
I'm trying to convert this python file with pyglet in it,repo:https://github.com/happyleibniz/Minecraft_python_Edition
it shoud convert to a exe file and run correctly but it throws a error:
pygame 2.5.2 (SDL 2.28.3, Python 3.11.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
Loading the game...
Traceback (most recent call last):
  File "pyglet\resource.py", line 453, in file
KeyError: 'gui/logo.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 307, in <module>
    logo = pyglet.resource.image("gui/logo.png")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyglet\resource.py", line 575, in image
  File "pyglet\resource.py", line 500, in _alloc_image
  File "pyglet\resource.py", line 456, in file
pyglet.resource.ResourceNotFoundException: Resource "gui/logo.png" was not found on the path.  Ensure that the filename has the correct captialisation.
[5864] Failed to execute script 'main' due to unhandled exception!

PS:all py files have been tested,all correct
**System Information:**
windows 10 x64 ,in vmware

**How To Reproduce**
...
```
# Loading screen
glClearColor(1, 1, 1, 1)

glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)
glLoadIdentity()

glMatrixMode(GL_PROJECTION)
glLoadIdentity()
gluOrtho2D(0, WIDTH, 0, HEIGHT)

**_logo = pyglet.resource.image("gui/logo.png")_**
logo.blit(WIDTH // 2 - (logo.width // 2), HEIGHT // 2 - (logo.height // 2)

)
pygame.display.flip()
#

sound = Sound()
scene = Scene()
gui = GUI(scene)
blockSound = BlockSound(scene)
player = Player(gl=scene)

player.position = [0, -9000, 0]
```
...
<img width="840" alt="屏幕截图 2024-01-10 165732" src="https://github.com/pyglet/pyglet/assets/121920485/a1388226-c34a-4be2-a7f1-102fadf8caa0">

**Comment by benmoran56** [comment]
What does your PyInstaller .spec file look like? You will need to provide the source/destination paths when building your .exe. 

However, I see that you're mixing pyglet and pygame. This may cause unexpected issues. You should confirm the working path when launching the game.

**Comment by happyleibniz** [comment]
like this:
# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='main',
)
<img width="359" alt="屏幕截图 2024-01-10 183939" src="https://github.com/pyglet/pyglet/assets/121920485/b7ea8b4d-2400-45a4-b271-e5c3c0ae66cf">

**Comment by happyleibniz** [comment]
the destination path is the_main_dir/dist/thefile.exe  ,and i moved the exe file to the destination path(and the _internal folder)

**Comment by benmoran56** [comment]
Your data files should probably be moved _inside_ of the `_internal` folder.

**Comment by benmoran56** [comment]
I was unable to get your project to package correctly on my Linux machine. It runs fine, but PyInstaller cannot find PyOpenGL for some reason. 

A pure pyglet application is usually very easy to bundle. Considering your assets are in an "assets" folder, you can do:
```sh
pyinstaller --add-data=assets:assets  hello.py
```
I have attached a sample project, if you want to review the .spec file. (It may be different for Windows/macOS, so you probably can't use it as-is).
[pyglet_pyinstaller.zip](https://github.com/pyglet/pyglet/files/13900868/pyglet_pyinstaller.zip)

Nuitka also works quite well:
```sh
nuitka3 --standalone --include-data-dir=assets=assets hello.py 
```

**Comment by happyleibniz** [comment]
thanks i have created a exe successfully:D

**Comment by shenjackyuanjie** [comment]
try to use nuitka LOL
