### ISSUE TITLE
TypeError: expected string or buffer

### ISSUE THREAD

**Issue by mghanei** [pyglet/pyglet#104]
Hi,
I'm trying to run this code:

```
import pyglet

display = pyglet.canvas.get_display()
screens = display.get_screens()
window = pyglet.window.Window(fullscreen=True, screen=screens[1])

pyglet.app.run()
```

and I get this error:

> Traceback (most recent call last): File "/home/pi/netcomShopTV/idk.py", line 5, in window = pyglet.window.Window() File "/usr/local/lib/python2.7/dist-packages/pyglet/init.py", line 359, in getattr import(import_name) File "/usr/local/lib/python2.7/dist-packages/pyglet/window/init.py", line 1890, in gl._create_shadow_window() File "/usr/local/lib/python2.7/dist-packages/pyglet/gl/init.py", line 209, in _create_shadow_window _shadow_window = Window(width=1, height=1, visible=False) File "/usr/local/lib/python2.7/dist-packages/pyglet/window/xlib/init.py", line 171, in init super(XlibWindow, self).init(*args, **kwargs) File "/usr/local/lib/python2.7/dist-packages/pyglet/window/init.py", line 642, in init self._create() File "/usr/local/lib/python2.7/dist-packages/pyglet/window/xlib/init.py", line 265, in _create self.context.set_vsync(self._vsync) # XXX ? File "/usr/local/lib/python2.7/dist-packages/pyglet/gl/xlib.py", line 265, in set_vsync warnings.warn(e) TypeError: expected string or buffer

**Comment by benmoran56** [comment]
Thanks for opening the ticket.

Can you give me more information on your system?

**Comment by mghanei** [comment]
> 
> 
> Thanks for opening the ticket.
> 
> Can you give me more information on your system?

Device: Raspberry pi 4 
OS: Raspbian Buster, version September 2019
Pyglet Version: 1.4.8
Python: 2.7

**Comment by benmoran56** [comment]
This is an exception for a Raspberry Pi specific issue. It's supposed to raise a warning, and pass without crashing. If possible, could you try editing line 265 in `/usr/local/lib/python2.7/dist-packages/pyglet/gl/xlib.py`, and changing:

```warnings.warn(e)```
to
```warnings.warn(e.message)``` or ```warnings.warn(e.args)```

Also, could you give it a try on Python 3 and see if you get the same crash?

**Comment by mghanei** [comment]
> 
> 
> This is an exception for a Raspberry Pi specific issue. It's supposed to raise a warning, and pass without crashing. If possible, could you try editing line 265 in `/usr/local/lib/python2.7/dist-packages/pyglet/gl/xlib.py`, and changing:
> 
> `warnings.warn(e)`
> to
> `warnings.warn(e.message)` or `warnings.warn(e.args)`
> 
> Also, could you give it a try on Python 3 and see if you get the same crash?

I changed it to warnings.warn(e.message) and it worked.
Thanks!

**Comment by benmoran56** [comment]
Thanks for confirming. I'll get that fix into the next release. 

If you have python 3 on your Raspberry Pi, could you also confirm that as well?

**Comment by mghanei** [comment]
I tried to run the code on python3. It works, but when I try to close the window, I get this error:

> /usr/local/lib/python2.7/dist-packages/pyglet/gl/xlib.py:265: UserWarning: glXSwapIntervalMESA is not exported by the available OpenGL driver.  MESA_swap_control is required for this functionality

It has something to do with graphic... But I don't have this problem with python 2.7!

**Comment by benmoran56** [comment]
Thanks for confirming. I'll get this change into the next release. 

The "UserWarning" is expected. 
The reason is that the OpenGL driver on Raspberry Pis advertise that they support vsync, but the function is not there. Instead of crashing, we want to continue and print a warning.

**Comment by benmoran56** [comment]
This has been pushed out in the last release, so I'll go ahead and close this. Thanks again for opening the ticket.
