### ISSUE TITLE
docs: Framebuffer and Renderbuffer (pyglet.image.buffer) are not documented

### ISSUE THREAD

**Issue by tmewett** [pyglet/pyglet#1040]
As of writing, v2.0.10, this module has no documentation on the website. https://pyglet.readthedocs.io/en/latest/

(The docstrings themselves are a bit redudant too)

**Comment by benmoran56** [comment]
I'm going to try working on this (and some other documentation updates) soon.

**Comment by benmoran56** [comment]
The image.buffer module is now included in the API documentation builds.
Docstrings were updated a bit, and this section of the `image` programming guide was updated: 
https://pyglet.readthedocs.io/en/latest/programming_guide/image.html#framebuffers
https://pyglet.readthedocs.io/en/latest/modules/image/buffer.html

If you thing something should have more detail, let us know.
