### ISSUE TITLE
get instanceGUID from DirectInputDevice

### ISSUE THREAD

**Issue by wolke6000** [pyglet/pyglet#1051]
It would be nice to get the instanceGUID from DirectInputDevice's, just like the product GUID.

It is actually accessible (see [here](https://github.com/pyglet/pyglet/blob/0581e2d17db7c9298e1e9dfeec3d1b3215c878e0/pyglet/input/win32/directinput.py#L412)), but is not stored in the DirectInputDevice object.

I suggest storing that as an object variable (string) and having it accessible via an `get_instance_guid()`-method.
Here's a sample implementation:
```python
i = device_instance.contents.guidInstance
self.instance_guid = (f"{i.Data1:08x}-{i.Data2:04x}-{i.Data3:04x}-" +
           "".join(f"{x:02x}" for x in i.Data4[:2]) +
           "-" + "".join(f"{x:02x}" for x in i.Data4[2:]))
```

**Comment by benmoran56** [comment]
This can certainly be added if it's useful. 
Same question as my comment in your other issue:  Any reason why not just expose the struct directly?

**Comment by wolke6000** [comment]
> This can certainly be added if it's useful. Same question as my comment in your other issue: Any reason why not just expose the struct directly?

no reason. i'm not that deep into ctypes and pyglet, but i guess you want to encapsulate everything into python, right?
Maybe a GUID-class would be a good solution for this and #1050

**Comment by wolke6000** [comment]
I'm sorry, but why is this closed?
Is this rejected?
In 2eb3cfe you changed how the productGUID is retrieved, but there is still no implementation for the instanceGUID.

**Comment by benmoran56** [comment]
This was just an oversight. The instance guid has also been added in the development branch.
