### ISSUE TITLE
Method on_joyhat_motion doesn't work on Linux

### ISSUE THREAD

**Issue by SulzerChemtech** [pyglet/pyglet#106]
Hi! Method **on_joyhat_motion** doesn't work on Linux. I suggest adding support for Linux.
Current code (pyglet/input/base.py):
```
def add_hat(control):
            # 8-directional hat encoded as a single control (Windows/Mac)
            self.hat_x_control = control
            self.hat_y_control = control
            
            @control.event
            def on_change(value):
                if value & 0xffff == 0xffff:
                    self.hat_x = self.hat_y = 0
                else:
                    if control.max > 8:  # DirectInput: scale value
                        value //= 0xfff
                    if 0 <= value < 8:
                        self.hat_x, self.hat_y = (( 0,  1),
                                                  ( 1,  1),
                                                  ( 1,  0),
                                                  ( 1, -1),
                                                  ( 0, -1),
                                                  (-1, -1),
                                                  (-1,  0),
                                                  (-1,  1))[value]
                    else:
                        # Out of range
                        self.hat_x = self.hat_y = 0
                self.dispatch_event('on_joyhat_motion', self, self.hat_x, self.hat_y)

        for control in device.get_controls():
            if isinstance(control, AbsoluteAxis):
                if control.name in ('x', 'y', 'z', 'rx', 'ry', 'rz', 'hat_x', 'hat_y'):
                    add_axis(control)
                elif control.name == 'hat':
                    add_hat(control)
            elif isinstance(control, Button):
                add_button(control)
```
My suggetion:
<pre>
        def add_hat(control):
            <b>if control.name == "hat_x":
                self.hat_x_control = control
            elif control.name == "hat_y":
                self.hat_y_control = control
            else:</b>
                self.hat_x_control = control
                self.hat_y_control = control
            
            @control.event
            def on_change(value):
                <b>if control.name == "hat_x":
                    self.hat_x = value
                elif control.name == "hat_y":
                    self.hat_y = -value
                else:</b>
                    if value & 0xffff == 0xffff:
                        self.hat_x = self.hat_y = 0
                    else:
                        if control.max > 8:  # DirectInput: scale value
                            value //= 0xfff
                        if 0 <= value < 8:
                            self.hat_x, self.hat_y = (( 0,  1),
                                                      ( 1,  1),
                                                      ( 1,  0),
                                                      ( 1, -1),
                                                      ( 0, -1),
                                                      (-1, -1),
                                                      (-1,  0),
                                                      (-1,  1))[value]
                        else:
                            # Out of range
                            self.hat_x = self.hat_y = 0
                self.dispatch_event('on_joyhat_motion', self, self.hat_x, self.hat_y)

        for control in device.get_controls():
            if isinstance(control, AbsoluteAxis):
                if control.name in <b>('x', 'y', 'z', 'rx', 'ry', 'rz'):</b>
                    add_axis(control)
                elif control.name <b>in ('hat', 'hat_x', 'hat_y'):</b>
                    add_hat(control)
            elif isinstance(control, Button):
                add_button(control)
</pre>

**Comment by benmoran56** [comment]
Hi, thanks for opening the ticket. Just for clarity, the code was written as it was originally because most Linux joystick drivers treat the joystick HAT as just another analog control.  Your change looks reasonable, but would be breaking for some users. 

To solve this type of issue, there is already an alternative "GameController" API which is in the master branch (to be included in the 2.0 release). This API mimics what SDL2 and other game engines do, but creating a virtual device that is consistent across platforms. You can have a look here: https://github.com/pyglet/pyglet/blob/master/pyglet/input/base.py#L536
There are also some supporting modules in the parent directory. 

I wasn't planning on backporting this to 1.4, but it's an option if there is demand.

**Comment by benmoran56** [comment]
Hi @SulzerChemtech, 

have you had a chance to look at the new GameController API, and if so, what are you thoughts on that?

**Comment by benmoran56** [comment]
I'm going to close this for now, but please reopen a new ticket if you want to follow up. 
Thanks!
