### ISSUE TITLE
Xbox 360 Controller isn't recognized anymore

### ISSUE THREAD

**Issue by derUli** [pyglet/pyglet#1060]
**Describe the bug**
I have a Xbox 360 USB controller which was detected by pyglet until version 1.5.28.
But in any 2.x version it can not detect it.

**System Information:**

**Controller:**
Vendor: Diswoe
Model name: 179999

```
Platform
------------------------------------------------------------------------------
platform:  Windows-10-10.0.22631-SP0
release:   10
machine:   AMD64

Python
------------------------------------------------------------------------------
implementation: CPython
sys.version: 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]
sys.maxint: 9223372036854775807
os.getcwd(): C:\Users\uli\Documents

pyglet
------------------------------------------------------------------------------
pyglet.version: 2.0.12
pyglet.compat_platform: win32
pyglet.__file__: C:\Users\uli\AppData\Roaming\Python\Python311\site-packages\pyglet\__init__.py
pyglet.options['audio'] = ('xaudio2', 'directsound', 'openal', 'pulse', 'silent')
pyglet.options['debug_font'] = False
pyglet.options['debug_gl'] = True
pyglet.options['debug_gl_trace'] = False
pyglet.options['debug_gl_trace_args'] = False
pyglet.options['debug_gl_shaders'] = False
pyglet.options['debug_graphics_batch'] = False
pyglet.options['debug_lib'] = False
pyglet.options['debug_media'] = False
pyglet.options['debug_texture'] = False
pyglet.options['debug_trace'] = False
pyglet.options['debug_trace_args'] = False
pyglet.options['debug_trace_depth'] = 1
pyglet.options['debug_trace_flush'] = True
pyglet.options['debug_win32'] = False
pyglet.options['debug_input'] = False
pyglet.options['debug_x11'] = False
pyglet.options['shadow_window'] = True
pyglet.options['vsync'] = None
pyglet.options['xsync'] = True
pyglet.options['xlib_fullscreen_override_redirect'] = False
pyglet.options['search_local_libs'] = True
pyglet.options['win32_gdi_font'] = False
pyglet.options['headless'] = False
pyglet.options['headless_device'] = 0
pyglet.options['win32_disable_shaping'] = False
pyglet.options['dw_legacy_naming'] = False
pyglet.options['win32_disable_xinput'] = False
pyglet.options['com_mta'] = False
pyglet.options['osx_alt_loop'] = False

pyglet.window
------------------------------------------------------------------------------
display: <pyglet.canvas.win32.Win32Display object at 0x0000026A0211E610>
screens[0]: Win32Screen(x=0, y=0, width=1920, height=1080)
config['double_buffer'] = 1
config['stereo'] = 0
config['buffer_size'] = 32
config['aux_buffers'] = 4
config['sample_buffers'] = 0
config['samples'] = 0
config['red_size'] = 8
config['green_size'] = 8
config['blue_size'] = 8
config['alpha_size'] = 0
config['depth_size'] = 24
config['stencil_size'] = 0
config['accum_red_size'] = 16
config['accum_green_size'] = 16
config['accum_blue_size'] = 16
config['accum_alpha_size'] = 16
config['major_version'] = 3
config['minor_version'] = 3
config['forward_compatible'] = None
config['opengl_api'] = 'gl'
config['debug'] = None
context: Win32ARBContext(id=2656435023824, share=Win32Context(id=2656425919952, share=None))

window.context._info
------------------------------------------------------------------------------
gl_info.get_version(): (3, 3)
gl_info.get_vendor(): NVIDIA Corporation
gl_info.get_renderer(): NVIDIA GeForce GT 1030/PCIe/SSE2

pyglet.gl.glx_info
------------------------------------------------------------------------------
GLX not available.

pyglet.media
------------------------------------------------------------------------------
audio driver: <pyglet.media.drivers.xaudio2.adaptation.XAudio2Driver object at 0x0000026A08710810>

pyglet.media.ffmpeg
------------------------------------------------------------------------------
FFmpeg not available.

pyglet.media.drivers.openal
------------------------------------------------------------------------------
Library: <CDLL 'openal32', handle 10000000 at 0x26a08ecbbd0>
Version: 1.1
Extensions:
   ALC_ENUMERATE_ALL_EXT
   ALC_ENUMERATION_EXT
   ALC_EXT_CAPTURE
   ALC_EXT_EFX

pyglet.input.wintab
------------------------------------------------------------------------------
WinTab not available.
```

**How To Reproduce**

Just plug the controller to an USB port and try to detect it using pyglet.

**Comment by benmoran56** [comment]
As of pyglet 2.0, there is a new Controller interface that coexists with the Joystick interface. For Xinput devices, they should appear under
```py
controllers = pyglet.input.get_controllers()
```
This interface is preferred for any dual analog stick devices, such as Xbox, PlayStation, etc. controllers. 
You can also disable Xinput support on Windows with the following option, immediately after importing pyglet:
```py
import pyglet
pyglet.options['win32_disable_xinput'] = True
```
It's also worth checking that your controller appears in the list of low level devices:
```py
pyglet.input.get_devices()
```

**Comment by derUli** [comment]
pyglet.input.get_controllers() returns an XInputDevice.
It is also returned by pyglet.input.get_devices()

But pyglet.input.get_joysticks() doesn't return it anymore.
Regardless of the value of win32_disable_xinput.

But shouldn't the old joystick API still be able to detect this device in 2.x?

**Comment by benmoran56** [comment]
Xinput has to be disabled in order for the device to show in `get_joysticks`. It's not possible to initialize devices under DirectInput and Xinput at the same time. 

If you're still seeing the Xinput devices, make sure that you set the pyglet option immediately after importing pyglet (before any submodules).

That said, using the Controller interface is usually recommended unless you are using actual analog Joysticks, like flight sticks. Is this for a game, or another type of application?

**Comment by derUli** [comment]
The win32_disable_xinput doesn't work for me.

```
Python 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyglet
>>> pyglet.options['win32_disable_xinput'] = True
>>> pyglet.input.get_joysticks()
[]
```

It's just I am developing a game using Arcade and Arcades get_game_controllers() method is just an alias for Pyglets get_joysticks()
So I started with their tutorial which is still using the Joystick interface.

So I can't avoid to write my event handling code new using the new API?

**Comment by benmoran56** [comment]
Can you confirm that in your last example, that the XInput device still shows up under `get_devices` as well? If so then it's a bug, but should be easily fixable.

I'm pretty sure Arcade alias pre-dates the pyglet Controller API by just a bit. In any case, the differences between Joysticks and Controllers mostly come down to event names and signatures. Controllers also have support for rumble effects, which is not currently supported on the Joystick interface. Have a look `examples/input/controller.py` for reference.

**Comment by benmoran56** [comment]
There was indeed a bug. The `win32_disable_xinput` option should now work as expected.
If you can try with the latest code from master, let me know if you still have issues.

**Comment by benmoran56** [comment]
Fixed in the latest point releases.
