### ISSUE TITLE
Unexpected PNG output from ColorBufferImage.save

### ISSUE THREAD

**Issue by JnyJny** [pyglet/pyglet#107]
Platform: macOS 10.15.2
Python: 3.7.5
Pyglet: 1.4.8

[Short Reproducer Gist](https://gist.github.com/JnyJny/4996d87cce5e9209b3d271a62b139c25.js)

I'm attempting to render text to a window and then save the window contents to a PNG formatted file.

<img width="1070" alt="Screen Shot 2019-12-19 at 9 42 00 AM" src="https://user-images.githubusercontent.com/876947/71187019-dcc0d680-2243-11ea-95b0-694e1bba6462.png">

The top window in the screenshot (white text on black)  is the window output from the reproducer above. The bottom larger window is the `output.png` generated using:

```
pyglet.image.get_buffer_manager().get_color_buffer().save("output.png")
```

The PNG output appears to be a mask (guessing) and the dimensions of the file are double what was requested (1024x512 for the PNG versus 512x256 for the pyglet window). The goal was to have a PNG with white text on a black background with the same dimensions as the window.

Any help with this would be much appreciated.

**Comment by einarf** [comment]
I'm guessing the double size issue is related to this being on a mac using retina resolution (2.0 x pixel ratio). If your window size is 512x256 the actual pixel buffer size is 1024x512. That is to be expected and probably the correct behavior. (Unless I'm missing a detail here)

**Comment by caffeinepills** [comment]
By default OpenGL windows actually have 0 alpha. You will need to force alpha into the buffer by calling the following after creating the window:
`pyglet.gl.glClearColor(0,0,0,1)`
Then your screenshot will have the black background. Hope that helps.

**Comment by JnyJny** [comment]
@einarf clear thinking and I agree. My eventual plan is to render text to an off-screen buffer and write it directly without displaying it to a screen, so that should resolve the dimensional discrepancy.

@caffeinepills that did the trick. Thank you very much for your timely advice.
