### ISSUE TITLE
some mp3 files cannot be loaded

### ISSUE THREAD

**Issue by chcarmen** [pyglet/pyglet#109]
Hi, guys, I found a issue in pyglet\media\codecs\ffmpeg.py.
for some mp3 files, they cannot be loaded, due to the following reason:
```
def ffmpeg_file_info(file):
   --snip--
    entry = avutil.av_dict_get(file.context.contents.metadata, asbytes('date'), None, 0)
    if entry:
        info.year = int(entry.contents.value)
```
in this function, it gets the 'date' value from file info and make it into int. 
It works for some mp3 files, like their 'date' is '2010', BUT it doesn't work for some other mp3 files, like their 'date' is '2010-10-1',it cannot convert this kind of string into int,  so it throws an exception here, then lead to the following issue:
```
Exception ignored in: <function FFmpegSource.__del__ at 0x0E64F340>
Traceback (most recent call last):
  File "xxx\lib\site-packages\pyglet\media\codecs\ffmpeg.py", line 579, in __del__
    ffmpeg_free_packet(self._packet)
AttributeError: 'FFmpegSource' object has no attribute '_packet'
```
which is the same issue as mentioned in #99. i am not sure why #99 is closed, but this issue does still exsit and also in #99, nobody points out the reason.

back to above code, if i change it from 'int(entry.contents.value)' to 'asstr(entry.contents.value)' , it works. 
so I am wondering if this is a bug?

**Comment by benmoran56** [comment]
Thanks for opening the ticket, and thanks for digging into the issue. It does indeed look like a bug. Casting to a string, as you've done, looks like the logical solution. I'll have a look at this later today.

**Comment by benmoran56** [comment]
I have pushed the fix to the 1.4-maintenance branch, and it will be in an upcoming release. If you could confirm if this fixes the issue, that would be great! You can install pyglet from the 1.4 branch, or update via pip with the following command: 
```pip install --upgrade --user git+https://github.com/pyglet/pyglet@pyglet-1.4-maintenance```
Thanks!

**Comment by chcarmen** [comment]
Thanks Benjamin for your quick response and fix, I tried the latest version of the 1.4-maintenance branch, it works well for all the mp3 files I have. Thanks again!

**Comment by benmoran56** [comment]
Great!  The fix will be in the next release, which should be in the next week or so. I'll close this for now, but please reopen it if you see any other issues. 

-Ben

**Comment by vishalmote** [comment]
Following is my sample code :

```
import pyglet
vidPath = 'five.mp4'
win = pyglet.window.Window()
player = pyglet.media.Player()
source = pyglet.media.StreamingSource()
mediaLoad = pyglet.media.load(vidPath)
player.queue(mediaLoad)
player.play()

@win.event
def on_draw():
    if(player.source and player.source.video_format):
        player.get_texture().blit(50,50)

pyglet.app.run()
```

Following is error even after installing pyglet@pyglet-1.4-maintenance as per the instruction :


```
$ python vishal_code.py 
Traceback (most recent call last):
  File "vishal_code.py", line 6, in <module>
    mediaLoad = pyglet.media.load(vidPath)
  File "/home/vishal/.local/lib/python2.7/site-packages/pyglet/media/__init__.py", line 133, in load
    loaded_source = decoder.decode(file, filename, streaming)
  File "/home/vishal/.local/lib/python2.7/site-packages/pyglet/media/codecs/ffmpeg.py", line 1041, in decode
    return FFmpegSource(filename, file)
  File "/home/vishal/.local/lib/python2.7/site-packages/pyglet/media/codecs/ffmpeg.py", line 460, in __init__
    self._file = ffmpeg_open_filename(asbytes_filename(filename))
  File "/home/vishal/.local/lib/python2.7/site-packages/pyglet/media/codecs/ffmpeg.py", line 143, in ffmpeg_open_filename
    raise FFmpegException('Error opening file ' + filename.decode("utf8"))
pyglet.media.codecs.ffmpeg.FFmpegException: Error opening file five.mp4
Exception AttributeError: "'FFmpegSource' object has no attribute '_packet'" in <bound method FFmpegSource.__del__ of <pyglet.media.codecs.ffmpeg.FFmpegSource object at 0x7f9ea815a810>> ignored
$ 
```

I am using ubuntu 18, ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers, python 2.7 version,

please help

**Comment by vishalmote** [comment]
I just upgraded ffmpeg to following version and my sample is started working


`ffmpeg version 4.2.2-0york0~18.04 Copyright (c) 2000-2019 the FFmpeg developers
`

**Comment by benmoran56** [comment]
Hi vishalmote,  that makes sense because the ffmpeg support was mostly tested with 4.x.   Thank you for commenting again with the solution.

**Comment by vishalmote** [comment]
> Following is my sample code :
> 
> ```
> import pyglet
> vidPath = 'five.mp4'
> win = pyglet.window.Window()
> player = pyglet.media.Player()
> source = pyglet.media.StreamingSource()
> mediaLoad = pyglet.media.load(vidPath)
> player.queue(mediaLoad)
> player.play()
> 
> @win.event
> def on_draw():
>     if(player.source and player.source.video_format):
>         player.get_texture().blit(50,50)
> 
> pyglet.app.run()
> ```
> 
> Following is error even after installing [pyglet@pyglet-1.4-maintenance](mailto:pyglet@pyglet-1.4-maintenance) as per the instruction :
> 
> ```
> $ python vishal_code.py 
> Traceback (most recent call last):
>   File "vishal_code.py", line 6, in <module>
>     mediaLoad = pyglet.media.load(vidPath)
>   File "/home/vishal/.local/lib/python2.7/site-packages/pyglet/media/__init__.py", line 133, in load
>     loaded_source = decoder.decode(file, filename, streaming)
>   File "/home/vishal/.local/lib/python2.7/site-packages/pyglet/media/codecs/ffmpeg.py", line 1041, in decode
>     return FFmpegSource(filename, file)
>   File "/home/vishal/.local/lib/python2.7/site-packages/pyglet/media/codecs/ffmpeg.py", line 460, in __init__
>     self._file = ffmpeg_open_filename(asbytes_filename(filename))
>   File "/home/vishal/.local/lib/python2.7/site-packages/pyglet/media/codecs/ffmpeg.py", line 143, in ffmpeg_open_filename
>     raise FFmpegException('Error opening file ' + filename.decode("utf8"))
> pyglet.media.codecs.ffmpeg.FFmpegException: Error opening file five.mp4
> Exception AttributeError: "'FFmpegSource' object has no attribute '_packet'" in <bound method FFmpegSource.__del__ of <pyglet.media.codecs.ffmpeg.FFmpegSource object at 0x7f9ea815a810>> ignored
> $ 
> ```
> 
> I am using ubuntu 18, ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers, python 2.7 version,
> 
> please help

Hi,

As above code was written in ubuntu 18. where issue is resolved by upgrading ffmpeg to 4 version.

but now I moved my code to rpi 3b+ now facing same kind of error on that machine, thing is that I am also able to successfully install ffmpeg4 on rpi3b+ machine using help of following url

https://johnvansickle.com/ffmpeg/


I have checked the version of ffmpeg which is showing proper version i.e. 4.2.2 something but still facing a same error in RPI3b+ machine. there is other issue exist related to my problem as well but discussion on that thread is ended without solution and asked to re-open a thread https://github.com/pvcraven/arcade/issues/257 on another repo.

**Comment by benmoran56** [comment]
Unfortunately we never got ffmpeg support working on the Raspberry Pi. 
This is not being actively worked on at the moment, but that could change if someone wants to contribute. 

In the mean time, unfortunately, the only option would be using `*.wav` files on Raspberry Pi.
