### ISSUE TITLE
on_draw getting called twice in a row for no apparent reason

### ISSUE THREAD

**Issue by matanox** [pyglet/pyglet#1094]
Nothing major, but `on_draw` is being called two times in a row on my wayland, for no apparent reason other than presumably this is wayland behavior on my Ubuntu 22.04 system. 

This persists with many different images, while the image is perfectly displayed all along. 

---

Here's a minimally reproducing example:

```python
import sys
import pyglet

window = pyglet.window.Window()
image = pyglet.image.load(sys.argv[1])
window.set_size(image.height, image.width)

def update(dt):
    print(f'update')

@window.event
def on_draw():
    print(f'draw')
    image.blit(x=0, y=0, z=0)

pyglet.clock.schedule_interval(update, 1/30)
pyglet.app.event_loop.run()
```

The output is:
```
draw
update
draw
update
draw
draw
update
draw
draw
update
draw
draw
update
draw
draw
update
draw
draw
update
draw
draw
update
draw
draw
update
draw
draw
update
draw
draw
```

(and so on endlessly two draws after each update)

On my machine, this is consistent across the following versions of pyglet:

- 2.0.5
- 20.15
- 2.1.dev2

# python -m pyglet.info output:
Platform
------------------------------------------------------------------------------
platform:  Linux-5.15.0-101-generic-x86_64-with-glibc2.35
release:   5.15.0-101-generic
machine:   x86_64

Python
------------------------------------------------------------------------------
implementation: CPython
sys.version: 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0]
sys.maxint: 9223372036854775807

pyglet
------------------------------------------------------------------------------
pyglet.version: 2.1.dev2
pyglet.compat_platform: linux
pyglet.__file__: ..../lib/python3.10/site-packages/pyglet/__init__.py
pyglet.options['audio'] = ('xaudio2', 'directsound', 'openal', 'pulse', 'silent')
pyglet.options['debug_font'] = False
pyglet.options['debug_gl'] = True
pyglet.options['debug_gl_trace'] = False
pyglet.options['debug_gl_trace_args'] = False
pyglet.options['debug_gl_shaders'] = False
pyglet.options['debug_graphics_batch'] = False
pyglet.options['debug_lib'] = False
pyglet.options['debug_media'] = False
pyglet.options['debug_texture'] = False
pyglet.options['debug_trace'] = False
pyglet.options['debug_trace_args'] = False
pyglet.options['debug_trace_depth'] = 1
pyglet.options['debug_trace_flush'] = True
pyglet.options['debug_win32'] = False
pyglet.options['debug_input'] = False
pyglet.options['debug_x11'] = False
pyglet.options['shadow_window'] = True
pyglet.options['vsync'] = None
pyglet.options['search_local_libs'] = True
pyglet.options['win32_gdi_font'] = False
pyglet.options['scale_with_dpi'] = False
pyglet.options['headless'] = False
pyglet.options['headless_device'] = 0
pyglet.options['win32_disable_shaping'] = False
pyglet.options['dw_legacy_naming'] = False
pyglet.options['win32_disable_xinput'] = False
pyglet.options['com_mta'] = False
pyglet.options['osx_alt_loop'] = False

pyglet.window
------------------------------------------------------------------------------
display: <pyglet.display.xlib.XlibDisplay object at 0x7f1efabe8850>
screens[0]: XlibScreen(display=<pyglet.display.xlib.XlibDisplay object at 0x7f1efabe8850>, x=1920, y=0, width=1920, height=1080, xinerama=True)
screens[1]: XlibScreen(display=<pyglet.display.xlib.XlibDisplay object at 0x7f1efabe8850>, x=0, y=0, width=1920, height=1080, xinerama=True)
config['double_buffer'] = 1
config['stereo'] = 0
config['buffer_size'] = 24
config['aux_buffers'] = 0
config['sample_buffers'] = 0
config['samples'] = 0
config['red_size'] = 8
config['green_size'] = 8
config['blue_size'] = 8
config['alpha_size'] = 0
config['depth_size'] = 24
config['stencil_size'] = 0
config['accum_red_size'] = 0
config['accum_green_size'] = 0
config['accum_blue_size'] = 0
config['accum_alpha_size'] = 0
config['major_version'] = 3
config['minor_version'] = 3
config['forward_compatible'] = None
config['opengl_api'] = 'gl'
config['debug'] = None
context: XlibContext(id=139771035172624, share=XlibContext(id=139771032907984, share=None))

window.context._info
------------------------------------------------------------------------------
gl_info.get_version(): (4, 6)
gl_info.get_vendor(): Intel
gl_info.get_renderer(): Mesa Intel(R) UHD Graphics 630 (CFL GT2)

pyglet.gl.glx_info
------------------------------------------------------------------------------
context.is_direct(): 1
glx_info.get_server_vendor(): SGI
glx_info.get_server_version(): 1.4
glx_info.get_server_extensions():
   GLX_ARB_context_flush_control
   GLX_ARB_create_context
   GLX_ARB_create_context_no_error
   GLX_ARB_create_context_profile
   GLX_ARB_create_context_robustness
   GLX_ARB_fbconfig_float
   GLX_ARB_framebuffer_sRGB
   GLX_ARB_multisample
   GLX_EXT_create_context_es_profile
   GLX_EXT_create_context_es2_profile
   GLX_EXT_fbconfig_packed_float
   GLX_EXT_framebuffer_sRGB
   GLX_EXT_get_drawable_type
   GLX_EXT_libglvnd
   GLX_EXT_no_config_context
   GLX_EXT_texture_from_pixmap
   GLX_EXT_visual_info
   GLX_EXT_visual_rating
   GLX_MESA_copy_sub_buffer
   GLX_OML_swap_method
   GLX_SGI_make_current_read
   GLX_SGIS_multisample
   GLX_SGIX_fbconfig
   GLX_SGIX_pbuffer
   GLX_SGIX_visual_select_group
glx_info.get_client_vendor(): Mesa Project and SGI
glx_info.get_client_version(): 1.4
glx_info.get_client_extensions():
   GLX_ARB_context_flush_control
   GLX_ARB_create_context
   GLX_ARB_create_context_no_error
   GLX_ARB_create_context_profile
   GLX_ARB_create_context_robustness
   GLX_ARB_fbconfig_float
   GLX_ARB_framebuffer_sRGB
   GLX_ARB_get_proc_address
   GLX_ARB_multisample
   GLX_EXT_buffer_age
   GLX_EXT_create_context_es2_profile
   GLX_EXT_create_context_es_profile
   GLX_EXT_fbconfig_packed_float
   GLX_EXT_framebuffer_sRGB
   GLX_EXT_import_context
   GLX_EXT_no_config_context
   GLX_EXT_swap_control
   GLX_EXT_swap_control_tear
   GLX_EXT_texture_from_pixmap
   GLX_EXT_visual_info
   GLX_EXT_visual_rating
   GLX_ATI_pixel_format_float
   GLX_INTEL_swap_event
   GLX_MESA_copy_sub_buffer
   GLX_MESA_query_renderer
   GLX_MESA_swap_control
   GLX_NV_float_buffer
   GLX_OML_swap_method
   GLX_OML_sync_control
   GLX_SGIS_multisample
   GLX_SGIX_fbconfig
   GLX_SGIX_pbuffer
   GLX_SGIX_visual_select_group
   GLX_SGI_make_current_read
   GLX_SGI_swap_control
   GLX_SGI_video_sync
glx_info.get_extensions():
   GLX_ARB_context_flush_control
   GLX_ARB_create_context
   GLX_ARB_create_context_no_error
   GLX_ARB_create_context_profile
   GLX_ARB_create_context_robustness
   GLX_ARB_fbconfig_float
   GLX_ARB_framebuffer_sRGB
   GLX_ARB_get_proc_address
   GLX_ARB_multisample
   GLX_EXT_buffer_age
   GLX_EXT_create_context_es2_profile
   GLX_EXT_create_context_es_profile
   GLX_EXT_fbconfig_packed_float
   GLX_EXT_framebuffer_sRGB
   GLX_EXT_no_config_context
   GLX_EXT_swap_control
   GLX_EXT_swap_control_tear
   GLX_EXT_texture_from_pixmap
   GLX_EXT_visual_info
   GLX_EXT_visual_rating
   GLX_MESA_copy_sub_buffer
   GLX_MESA_query_renderer
   GLX_MESA_swap_control
   GLX_OML_swap_method
   GLX_OML_sync_control
   GLX_SGIS_multisample
   GLX_SGIX_fbconfig
   GLX_SGIX_pbuffer
   GLX_SGIX_visual_select_group
   GLX_SGI_make_current_read
   GLX_SGI_video_sync

pyglet.media
------------------------------------------------------------------------------
audio driver: <pyglet.media.drivers.openal.adaptation.OpenALDriver object at 0x7f1efac433a0>

pyglet.media.ffmpeg
------------------------------------------------------------------------------
FFmpeg version: 4.4.2-0ubuntu0.22.04.1+esm3

pyglet.media.drivers.openal
------------------------------------------------------------------------------
Library: <CDLL 'libopenal.so.1', handle 1681330 at 0x7f1efacc6ef0>
Version: 1.1
Extensions:
   ALC_ENUMERATE_ALL_EXT
   ALC_ENUMERATION_EXT
   ALC_EXT_CAPTURE
   ALC_EXT_DEDICATED
   ALC_EXT_disconnect
   ALC_EXT_EFX
   ALC_EXT_thread_local_context
   ALC_SOFT_device_clock
   ALC_SOFT_HRTF
   ALC_SOFT_loopback
   ALC_SOFT_output_limiter
   ALC_SOFT_pause_device

pyglet.input.wintab
------------------------------------------------------------------------------
WinTab not available.
AL lib: (EE) alc_cleanup: 1 device not closed

----

According to `os.environ.get("XDG_SESSION_TYPE", "unknown")` I'm using wayland.

With the above configuration, this code also reproduces a variation of https://github.com/pyglet/pyglet/issues/1045 ― when the window is not visible, the update interval permanently goes down to one second (at which time the current issue does not occur) for as long as the window is not visible.

**Comment by matanox** [comment]
I wish I only had one call to `on_draw` in my soft-real time application, which would make my whitebox performance monitoring more full without twisting it to assume more than one call, but I can work around this in my performance tracking code. But other than this twisting my white-box benchmarking of all callbacks, I can't say this makes a difference if `on_draw` is really only drawing. Maybe this MRE will be handy for any case.

**Comment by matanox** [comment]
A minor modification of the MRE shows that the second draw is always superfluous, as the image remains perfectly visible even when:

```python
import sys
import pyglet

window = pyglet.window.Window()
image = pyglet.image.load(sys.argv[1])
window.set_size(image.height, image.width)

i = 0

def update(dt):
    global i
    print(f'update')
    i = 0

@window.event
def on_draw():
    global i
    if i == 0:
        print(f'draw {i} drawing')
        image.blit(x=0, y=0, z=0)
    else:
        print(f'draw {i} skipping its drawing')
    i += 1

pyglet.clock.schedule_interval(update, 1/30)
pyglet.app.event_loop.run()
```
i.e.:

```
draw 0 drawing
update
draw 0 drawing
update
draw 0 drawing
draw 1 skipping its drawing
update
draw 0 drawing
draw 1 skipping its drawing
update
draw 0 drawing
draw 1 skipping its drawing
update
draw 0 drawing
draw 1 skipping its drawing
update
draw 0 drawing
draw 1 skipping its drawing
update
draw 0 drawing
draw 1 skipping its drawing
update
draw 0 drawing
draw 1 skipping its drawing
update
draw 0 drawing
draw 1 skipping its drawing
update
draw 0 drawing
draw 1 skipping its drawing
.
.
.
```

**Comment by matanox** [comment]
When the update is slow, or slowed down synthetically by a `time.sleep(1/25)`, the double `on_draw` invocation does not happen; presumably pyglet just merges queued drawing requests by the compositor while they are still happening at a high rate as before.

**Comment by benmoran56** [comment]
It is the default behavior of `app.run` to schedule `Window.draw`, which is described in this section of the documentation: https://pyglet.readthedocs.io/en/latest/programming_guide/eventloop.html

You can pass `None` if you want to disable this behavior, and schedule this yourself. 

The clock will generally drop any missed schedules, rather than accumulating them.

**Comment by matanox** [comment]
Thanks, forgot about the 60Hz default draw scheduling. Thanks for pointing out all the implied information so succinctly. 

Is it the case that the compositor/OS never polls the window to trigger it's redrawing beyond those `on_draw` callbacks which are triggered by the event loop or the application's own scheduling as suggested?

**Comment by benmoran56** [comment]
> Is it the case that the compositor/OS never polls the window to trigger it's redrawing beyond those on_draw callbacks which are triggered by the pyglet event loop or the pyglet application's own scheduling of drawing as suggested?

Yes, It's the application's responsibility to update itself.

**Comment by matanox** [comment]
Finally took the leap, avoiding any global update interval. Is it okay to contribute a test that safeguards this scenario? it's a little similar to [this scenario](https://github.com/matanox/pyglet/blob/ded996a3268847f97d01856456a160d3486271e5/examples/window/camera_group.py#L160-L161) but very different, as I disable the default drawing callbacks, and dispatch the next update as soon as the current one ends.

This scenario is justified, as the objective is to poll a camera stream as quickly as it can run. 
___
Is there any necessity for an application to follow an idiomatic frame rate (on_draw interval) like 30Hz or 60Hz on any of the supported platforms?
