### ISSUE TITLE
Double-defined pyglet.key.SPACE

### ISSUE THREAD

**Issue by pushfoo** [pyglet/pyglet#1097]
TL;DR: `pyglet.key.SPACE` appears defined twice: once as the compose key, then as the ASCII space character

### Where?

1. At the end of the ASCII commands block (appears to be the same as the compose key):
https://github.com/pyglet/pyglet/blob/9fe927d1322f2e845288c9b10a54f1ded12b4d08/pyglet/window/key.py#L175-L186

2. In the Latin-1 block:
https://github.com/pyglet/pyglet/blob/9fe927d1322f2e845288c9b10a54f1ded12b4d08/pyglet/window/key.py#L327

**Comment by benmoran56** [comment]
Fixed in latest PR from Caffeinepills.
