### ISSUE TITLE
Swapping back from fullscreen moves the window up/left (win32, pyglet 2.1)

### ISSUE THREAD

**Issue by einarf** [pyglet/pyglet#1099]
This is new in 2.1. I can't reproduce it in 2.0.15.

If you toggle fullscreen and window mode repeatedly the window keeps moving slightly up and to the left. If you keep toggling the window can move outside the desktop area. The step it moves is likely equal to the size of the top bar of the window (and the left window border).

Quick example. Just press `F` a few times and see how the window moves. I don't know if this is an issue on multiple platforms.

```py
import pyglet

window = pyglet.window.Window()
label = pyglet.text.Label('Hello, world!',
                          font_size=36,
                          x=window.width // 2,
                          y=window.height // 2,
                          anchor_x='center',
                          anchor_y='center')

@window.event
def on_draw():
    window.clear()
    label.draw()

@window.event
def on_key_press(symbol, modifiers):
    if symbol == pyglet.window.key.F:
        window.set_fullscreen(not window.fullscreen)

pyglet.app.run()
```

**Comment by pushfoo** [comment]
Wayland + GNOME on Linux appears unaffected.

**Comment by benmoran56** [comment]
Strange one. I was able to replicate it with both pyglet 2.0.15, and 2.1, under Wayland and Xorg.

Gnome 46, pyglet 2.0.15, Xorg:  replicated
Gnome 46, pyglet 2.0.15, Wayland:  replicated
Gnome 46, pyglet 2.1, Xorg:  replicated
Gnome 46, pyglet 2.1, Wayland:  replicated

Assuming that this behavior did not occur in the past, I suspect that it might be an Xorg/Xwayland issue.
My system has xorg-server 21.1.13. @pushfoo are you running an older version by chance?

**Comment by pushfoo** [comment]
Gnome 3.38.5, but I don't have an `xorg-server` package. Here's [a gist of `dpkg -l | grep xorg-server`](https://gist.github.com/pushfoo/33c1445e1baf5e83b86ffc449cb5ea1f).

**Comment by benmoran56** [comment]
OK, so it doesn't occur in Xorg 1.17.

Also to note that on Gnome 46, the window never moves outside of the desktop area. It's also only being repositioned a few pixels up-left, and is more than the window border but less than the window title bar. That doesn't seem related.

**Comment by caffeinepills** [comment]
Should be resolved in the PR provided, feel free to try it out to confirm. Fixes on my Windows 10 machine.

**Comment by einarf** [comment]
Works 👍 

However I had to bypass a type check in `Options.__setitem__` when setting the audio attribute.

```py
pyglet.options["audio"] = ("openal", "xaudio2", "directsound", "pulse", "silent")
```

```
  File "pyglet\__init__.py", line 260, in __setitem__
    assert type(value).__name__ == self.__annotations__[key], f"Invalid type: '{type(value)}' for '{key}'."
AssertionError: Invalid type: '<class 'tuple'>' for 'audio'.
```

It's looking up the key `'<class 'tuple'>` in annotations, but the only key there is `tuple[str]`. That doesn't work very well. Also the annotation for audio should probably be `tuple[str, ...]` to indicate it's a tuple of varying number of strings.

**Comment by benmoran56** [comment]
I'm not sure if this is exactly the same issue on Linux, because at a glance, we're not manually setting the position after returning from fullscreen. Unless I missed it, we're relying on the Desktop Environment to put it back where it was.

**Comment by caffeinepills** [comment]
> I'm not sure if this is exactly the same issue on Linux, because at a glance, we're not manually setting the position after returning from fullscreen. Unless I missed it, we're relying on the Desktop Environment to put it back where it was.

I think so. https://github.com/pyglet/pyglet/blob/5645e6d97091d55f3db39b729fc4cce748349adf/pyglet/window/__init__.py#L911

**Comment by caffeinepills** [comment]
Issue was resolved. May need a separate ticket for Linux if behavior is still incorrect there.
