### ISSUE TITLE
Request: friendlier Display API for X11

### ISSUE THREAD

**Issue by ixjlyons** [pyglet/pyglet#11]
I've found that I need to pass a `ctypes.c_char_p` type as the name argument to `Display` to get it to work, which is somewhat cumbersome:

```python
import pyglet
import ctypes
display = pyglet.canvas.Display(ctypes.c_char_p(":2".encode('ascii'))
```

Would it be reasonable to detect a `str` type passed to `XlibDisplay` and do that conversion for the user so you could just write `display = pyglet.canvas.Display(":2")`?

edit: also note the docstring for [`Display.name`](https://pyglet.readthedocs.io/en/pyglet-1.3-maintenance/modules/canvas.html#pyglet.canvas.Display.name) says it's a str.

**Comment by benmoran56** [comment]
Fixed via PR #12 
Thanks again for your contribution!
