### ISSUE TITLE
Mouse event drop into pyglet window

### ISSUE THREAD

**Issue by Johndeep** [pyglet/pyglet#111]
This is a request for a feature, which I think it is not available in pyglet yet.

Are there plans to implement a feature similar to the "glfwSetDropCallback" in glfw or "SDL_DropEvent" in sdl(2)?

I just thought a drag'n'drop event for in dropping a file path to load data without always to reload the program for new data (especially if you quickly want to browse through several files at once) might be very useful. A tedious way would be writing a fully functional file manager, but I want to reserve this as my last resort for now. The normal way (but usually tedious for enduser) might be calling the program via terminal and file path as parameter.

**Comment by benmoran56** [comment]
Hi John,

There are no current plans to add drag and drop support, but it would be nice to have. Drag and drop works differently between platforms, so it would take a bit of work to do. Let's Mark this as an enhancement, and leave it open.

**Comment by Johndeep** [comment]
Thank you for considering this idea ^^

**Comment by nbroderick-code** [comment]
I second this idea!

As a work around, I have been using pymsgbox prompts to load data. It plays very nicely with pyglet. I copy a file path and paste it into the prompt box.

```
from pymsgbox import prompt

def open_this(path):
     # do something

@window.event
def on_mouse_press(x, y, button, modifiers):
       path = prompt('Load data from this file path:', "Select File")
       open_this(path)
```

**Comment by Johndeep** [comment]
Hmm, pymsgbox looks like it's build with Tkinter. It has the feeling of it at least, good idea.

But unfortunately, since it is not the only feature I needed, I already went with GLFW (wrapper in python) some time ago and wrote some "ready to go" functions from pyglet from scratch (it was handy to use it in pyglet though). GLFW already has mouse event drop implemented. Furthermore, the shader version is newer, which is what I also needed to be reliable recent.

Still, I am a bit confused that the shader in pyglet seems to only run 1.3 reliable enough.. maybe it will be different with pyglet 2 or something.

Maybe future pyglet could make that mouse drop event work in Gnome too. In Gnome currently, drag'n'drop is not working for most of the apps out there. Funny is that I not noticed it before actually trying to drag anything at work on Gnome, since I'm a faithful user of Xfce.

**Comment by caffeinepills** [comment]
I added a file drop event for Windows here today if anyone wants to test it, based off 1.5 branch: https://github.com/caffeinepills/pyglet/tree/drop_event

Example:
```import pyglet

window = pyglet.window.Window(800, 600, file_drops=True)

@window.event
def on_file_drop(x, y, paths):
    print("FILES DROPPED:", paths)
    print("AT POSITION", x, y)

pyglet.app.run()```

Unfortunately, I don't have any Mac or Linux computers, so I can't really test to add support there. However, I'm positive both OS's support it, so it shouldn't be too tough if someone wants to add it sometime.

**Comment by caffeinepills** [comment]
Also just added Linux support, I realized I could setup a VM of Ubuntu to test things. Seems to work ok for me on a VM. Test it out, let me know of any issues.

**Comment by benmoran56** [comment]
Linux works too :+1:

**Comment by nbroderick-code** [comment]
Whaaat. You guys are the best! Can't wait for this to be merged!

**Comment by Johndeep** [comment]
Cool, in any case a nice addition to the pyglet library!

**Comment by benmoran56** [comment]
Just wanted to mention before closing, that this feature is in latest pyglet releases, thanks to the hard work by @caffeinepills! 
OSX support has not yet been added due to lack of development hardware, but hopefully we can get some support for adding that in the near future as well.
