### ISSUE TITLE
Problem playing mp3 files using pyglet

### ISSUE THREAD

**Issue by lipeng1109** [pyglet/pyglet#1114]
**Describe the bug**
I'm in the process of using it and any answers would be greatly appreciated，An error occurred when playing local mp3: 
ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': Connection refused

**System Information:**
 NVIDIA GeForce RTX 3090
 NVIDIA-SMI 535.154.05   
 Driver Version: 535.154.05   
 CUDA Version: 12.2 
 Ubuntu 20.04.1 LTS

**How To Reproduce**
 my code:
import pyglet
# music = pyglet.resource.media('music.mp3')
pyglet.options['audio'] = ('openal', 'pulse', 'xaudio2', 'directsound', 'silent')
explosion = pyglet.media.load('/data/lipeng/code/ComfyUI/output/audio/comfyUI_20240520034325429867_zh-CN-YunjianNeural.mp3', streaming=False)
explosion.play()

**Comment by benmoran56** [comment]
This is not a pyglet issue. It looks like something mis-configured with PulseAudio, or some other process accessing the raw ALSA device. If you do an internet search for these errors you can find many results.

For mp3 playback in particular, you will need either GStreamer or FFmpeg available. You can first test with simple wave files to ensure that is working. That, or some audio made with `pyglet.media.synthesis`.

**Comment by benmoran56** [comment]
I'll close this due to lack of follow up, but if you still have questions please feel free to comment or re-open.
