### ISSUE TITLE
Why Vec2 `__mul__` uses an scalar but `__add__` uses a Vec2?

### ISSUE THREAD

**Issue by alejcas** [pyglet/pyglet#1118]
I see that `Vec2.__mul__` multiplies by a scalar value when `__add__` or `__sub__` arguments are `Vec2`.

Then you have the `Vec2.dot` that multiplies by another `Vec2`.

Where's the addition / subtraction with an scalar (maybe `add` /  `sub` method)?

Isn't this somehow inconsistent?

I would expect all python operators (*, /, +, -, etc.) to work the same way: expecting all of them either an scalar or another Vec2.

Thanks

**Comment by DigiDuncan** [comment]
The functionality of `Vec2 * scalar` is incredibly important to maintain. I would personally hope that `__mul__` can take either:
```python
>>> v = Vec2(2.0, 4.0)
>>> v * 2
Vec2(4.0, 8.0)
>>> v * Vec2(1.5, 2.0)  # or v * (1.5, 2.0), since Vec2s are just tuples
Vec2(3.0, 8.0)
```

This is incredibly helpful for things like scale (where an objects size might be `(1000, 500)`, and doubling it as in `* 2` would make the new size `(2000, 1000)`.)

However, the same can't be said for `_add__`; what does it mean to add `2` to `(2.0, 4.0)`? Should that be assumed to mean `(2.0 + 2, 4.0 + 2)`? Realistically, I'd expect it to throw a `ValueError` (or more specifically, something like a `DimensionMismatchError`.)

**Comment by alejcas** [comment]
My point is that standard operator math is inconsistent: some use of Vec2 and others scalar.
I'm not saying it's not important or wrong to have Vec2 mul using an scalar.

**Comment by DragonMoffon** [comment]
In linear algebra (The math field from which vectors come), you can't multiply two vectors together. It is a useful feature and a convenient developer experience by allowing for piecewise multiplication. `Vec2.dot` is fundamentally NOT the multiplication of two vectors and should not be treated as such.

**Comment by alejcas** [comment]
ok, closing the issue,

**Comment by alejcas** [comment]
Seems that at the end my request was all added by einarf in #1151

Vecs are now much nicer to use.
