### ISSUE TITLE
xlib support broken in Python 3.7.6 (and possibly other new Python releases)

### ISSUE THREAD

**Issue by hoechenberger** [pyglet/pyglet#112]
```python
$ python -V
Python 3.7.6
$ python -c 'from pyglet.libs.x11 import xlib'
...
Traceback (most recent call last):
  File "/root/miniconda3/envs/pyglet/lib/python3.7/site-packages/pyglet/libs/x11/xlib.py", line 2962, in <module>
    XEHeadOfExtensionList.argtypes = [XEDataObject]
TypeError: item 1 in _argtypes_ passes a union by value, which is unsupported.
```
Tested with pyglet 1.4.8.
I suppose this is caused by a [bugfix](https://bugs.python.org/issue26628) that has made it into that Python release.

**Comment by benmoran56** [comment]
Thanks for opening the ticket, and the links.

I don't see an issue on my Linux machines with 3.8, but if I'm reading that Python bugfix correctly, this change will be in 3.9 as well. I'll have a look at this soon.

**Comment by hoechenberger** [comment]
> I don't see an issue on my Linux machines with 3.8, but if I'm reading that Python bugfix correctly, this change will be in 3.9 as well. I'll have a look at this soon.

Currently only 3.7.6 is broken, as it was just recently released and contains the change. I guess 3.8 will break with the next minor release, which will most likely contain the same fix.

**Comment by gperetin** [comment]
Confirming it is broken on Python 3.8.1.

```
(env) ❯ python -V
Python 3.8.1
(env) ❯ python -c 'from pyglet.libs.x11 import xlib'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/goran/Code/game-test/arcade-test/env/lib/python3.8/site-packages/pyglet/libs/x11/xlib.py", line 2962, in <module>
    XEHeadOfExtensionList.argtypes = [XEDataObject]
TypeError: item 1 in _argtypes_ passes a union by value, which is unsupported.
```

**Comment by benmoran56** [comment]
Thanks everyone for the feedback. Luckily the xlib function in question is not used by pyglet, so I was able to push a quick fix.  I'll see if I can push out a pyglet point release later today.  I can confirm this is now working on my machines with Python 3.8.1, but it should also be OK on 3.7.6 and others.

**Comment by benmoran56** [comment]
I just pushed out pyglet 1.4.9, which is now available for download or install via pip. 
If this problem still persists, please reopen this ticket. Thanks again for the detailed report!
