### ISSUE TITLE
Can I prevent pyglet shapes from blending?

### ISSUE THREAD

**Issue by MassPig** [pyglet/pyglet#1124]
I have the following code.
```
import pyglet

window = pyglet.window.Window(fullscreen=True)
batch = pyglet.graphics.Batch()

rectangle1 = pyglet.shapes.Rectangle(100, 100, 80, 80, color=(128, 0, 0, 128), batch=batch)
rectangle2 = pyglet.shapes.Rectangle(150, 150, 80, 80, color=(128, 0, 0, 128), batch=batch)

@window.event
def on_draw():
    window.clear()
    batch.draw()

pyglet.app.run()
```

Here is the result.
![grafik](https://github.com/pyglet/pyglet/assets/69081459/1ed30873-9cef-4dd5-953b-ea817d00a7e4)

I want to prevent the colors of the two rectangles from adding. Instead, the whole area should have just one color.
One way to archive this is to increase the alpha value to 255. But I need opacity in my final program.

Does pyglet support this kind of behavior? With google I found the commands `glEnable(GL_BLEND)`, `glDisable(GL_BLEND)`, and `glBlendFunc(GL_ONE, GL_ZERO)`. But they do not affect this behavior. 

Thanks in advance.

**Comment by benmoran56** [comment]
The `shapes` do not currently expose the Blend modes, but internally they are all doing:
```py
        self._group = self.group_class(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA, program, group)
```

Groups in pyglet are responsible for setting the OpenGL state. There is a default Group for all shapes, that sets blend modes:
https://github.com/pyglet/pyglet/blob/master/pyglet/shapes.py#L261

You can override this with a custom Group class, and set it on the Shape in question. I don't know if effect you are after is possible with blend modes alone, or if a custom shader is required here. If it _is_ possible with blend modes, you can experiment with the following code. You might also find this web app useful for experimentation, but i'm not sure how useful it will be:  https://andersriggelsen.dk/glblendfunc.php

```py
import pyglet

from pyglet.gl import *

window = pyglet.window.Window(fullscreen=False)
batch = pyglet.graphics.Batch()


class CustomBlendGroup(pyglet.shapes._ShapeGroup):

    def set_state(self):
        self.program.bind()
        glEnable(GL_BLEND)
        glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)


# Use the custom Group on the Rectangle Shape:
pyglet.shapes.Rectangle.group_class = CustomBlendGroup


rectangle1 = pyglet.shapes.Rectangle(100, 100, 80, 80, color=(128, 0, 0, 128), batch=batch)
rectangle2 = pyglet.shapes.Rectangle(150, 150, 80, 80, color=(128, 0, 0, 128), batch=batch)


@window.event
def on_draw():
    window.clear()
    batch.draw()


pyglet.app.run()
```

**Comment by zhengxyz123** [comment]
This is my found:

The custom group class should like:
```python
class CustomBlendGroup(pyglet.shapes._ShapeGroup):

    def set_state(self):
        self.program.bind()
        glEnable(GL_BLEND)
        glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_DST_ALPHA)
```

This is the screenshot
![Screenshot_20240617_204750](https://github.com/pyglet/pyglet/assets/58848782/ef6ac2d2-6d8c-417b-bfd9-447ebdbb974f)

Maybe it solve your problem, But I don't know "I need opacity in my final program" actually means.
