### ISSUE TITLE
Viewport setting seems odd when pixel ratio is not 1

### ISSUE THREAD

**Issue by ckemere** [pyglet/pyglet#1126]
I was trying to use window.viewport to simplify my calculations in terms of having the window centered at 0,0 in model space. I modified the code in `examples/model/model.py`, changing line 14
```
    window.viewport = (0, 0, *window.get_framebuffer_size())
```
to
```
    w, h = window.get_framebuffer_size()
    window.viewport = (-w/2, -h/2, *window.get_framebuffer_size())
```
and found that the cube moved twice as far on the screen as I had expected. (For ease of visualization, I also changed lines 33 and 39 `trans = Mat4.from_translation(Vec3(-1.75, 0, 0))` to `trans = Mat4.from_translation(Vec3(0 0, 0))` to center the cube in world space at 0,0,0.)

If I instead used
```
    window.viewport = (-w/4, -h/4, *window.get_framebuffer_size())
```
then the world is centered as expected. I believe this is because on my MacOS machine,`get_pixel_ratio()` returns `2.0`. (The requested window size is 720x480, but get_framebuffer_size() of course returns 1440 x 960.)

It seems like the OpenGL viewport should not care about the pixel_ratio, so I don't understand why this is occurring. I suspect this is more a misunderstanding on my part, but perhaps it is a bug in `perspective_projection` or `look_at`???

thanks!

**Comment by einarf** [comment]
The purpose of viewport is only to define what area of the screen we render to. 

This makes sure you render to the entire screen even if you have hidpi window
```py
window.viewport = (0, 0, *window.get_framebuffer_size())
```

The coordinate system of the window is decided by the projection. (`window.projection`). The configured projection is projected into the viewport meaning the viewport acts as a "screen". The smaller viewport you have the smaller the content will be.

**Comment by ckemere** [comment]
Please correct me if I'm wrong, but I believe the viewport defines the coordinates in render space that get mapped to window space. So by setting `window.viewport = (-w/2, -h/2, w, h)`, the bottom left pixel will map to (-w/2, -h/2) after all of the transformations are applied.

(I also just verified that I can place objects throughout the window with the viewport set as described here.)

**Comment by ckemere** [comment]
More confusion - I see that in Linux, with the same code, I find that `window.viewport = (0, 0, w, h)` produces the behavior I want (`pixel_ratio = 1.0`).

**Comment by benmoran56** [comment]
Einarf is correct here. 

The viewport in OpenGL, is usually used to determine which part of the visible screen you want to render into. In your case, you're stretching it off of the bottom left size of the screen. _Generally speaking_, you want the viewport to cover the viewable screen, and leave it like that. You might set the viewport temporarily smaller to renderer in a mini-map, or rear-view mirror in a car, etc., but _generally_ speaking you shouldn't touch it. 

Instead as Einarf suggested, use the `Window.projection` matrix to control the projection. If you only wish to translate the "camera", use the `Window.view` matrix. In the default shaders, both are multiplied together (MVP, or Model-View-Projection as it's called). 

See the `examples/model/fpscamera.py` example of how this works to move around a scene.

**Comment by ckemere** [comment]
Hi Ben/Einarf,

Yeah - the `model.py` code uses the `Mat4.look_at()` function to define a camera centered in the world. Maybe to summarize the issue - it seems like it doesn't actually center the view on MacOS with pixel_ratio=2. Screen shots attached freezing the first frame running the example code.

thanks
Caleb

![Linux](https://github.com/pyglet/pyglet/assets/1432092/5404b558-dee8-482b-b926-3c482a8865ef)
<img width="832" alt="MacOS" src="https://github.com/pyglet/pyglet/assets/1432092/4a1d7b7c-388e-4dd0-b45f-f5cad4001758">

**Comment by benmoran56** [comment]
Ah, I see the issue. The `Window.viewport` setter was updated to automatically handle pixel aspect ratio.
You can use the `on_resize(width, height)` values as-is, and no longer need to pass in `get_framebuffer_size()`. I updated the examples in Github to reflect that. 

For reference (Window class):
```py
    @viewport.setter
    def viewport(self, values: tuple[int, int, int, int]) -> None:
        self._viewport = values
        pr = self.get_pixel_ratio()
        x, y, w, h = values
        pyglet.gl.glViewport(int(x * pr), int(y * pr), int(w * pr), int(h * pr))
```

**Comment by ckemere** [comment]
Awesome. Now things look right. Sorry about the confusion and I appreciate your time!!!

**Comment by benmoran56** [comment]
No worries, it was a valid bug in the examples.
