### ISSUE TITLE
pyglet 2.x gives error "GL_FOG not defined"

### ISSUE THREAD

**Issue by billchen8888** [pyglet/pyglet#1130]
I tried  this example:   https://github.com/fogleman/Minecraft/blob/master/main.py

I get error like:
glEnable(GL_FOG)
NameError: name 'GL_FOG' is not defined.

I have to downgrade pyglet to 1.5.27 and then the code works.

Question - with the pyglet 2.x,  what is the right replacement for "glEnable(GL_FOG)" ?    I want to move forward, instead downgrade the pyglet version.

Thanks.

**Comment by zhengxyz123** [comment]
Unfortunately, `GL_FOG` and many functions were removed due to deprecation in pyglet 2.

If you want to implement a same effect, a shader should be used.

Besides, `Batch.add`, `glTranslatef`, `glRotatef`, `glOrtho`, `glMatrixMode` and so on is removed or deprecated in pyglet 2, which were also used in this project.

> From my own perspective, I think the mentioned repo is a good resource to learn pyglet, OpenGL and game development. Maybe you can ask several pyglet contributors to migrate it to pyglet 2.

**Comment by einarf** [comment]
Pyglet 1.x is using OpenGL 2.x
Pyglet 2.x is using OpenGL 3.3 core (or OpenGLES 3.2)

OpenGL 3.3 (core) was released in 2010 so there are plenty of resources out there.
The "core" part just means that a lot of the old "fixed pipleine" instructions was removed. `GL_FOG` is one of those. Likely more than 50% of functions and enums is gone. We mainly have textures, framebuffers, buffer and shaders doing the work.

There's still a `gl_compat` module in pyglet 2.x that can be used to access the fixed pipleine but pyglet's internal rendering is not compatible with the old instructions. You can however still use plain OpenGL with `gl_compat`. The downside is that your project will not work on MacOS or any other environment not being backwards compatible.

**Comment by caffeinepills** [comment]
Everyone is correct here, if you wish to use GL_FOG you will have to use the older version.

If upgrading, to 2.0 you will have to replace it with a shader. Unfortunately we don't really have any stand-in replacements for all deprecated GL functions, (especially for shaders). So this will have to be done for your use case.
