### ISSUE TITLE
Default shaders are not yet complete for v2.0

### ISSUE THREAD

**Issue by classner** [pyglet/pyglet#115]
Hi pyglet team,

after upgrading to version 2.0, I'm getting the error `AssertionError: 'normals' attribute not found in Shader`. The code has been working beautifully in 1.4. For the upgrade, I changed the names of previous `v3f/stream` and `n3f/stream` attributes of a vertex list to `vertex3f` and `normals3f` and there are no more warning. Then, however, I run into this assertion error.

**Comment by benmoran56** [comment]
Hi classner, 

For the 2.0 branch, it's just that the default shaders have not yet been finished, and don't actually have a `normals` attribute yet. I was planning on getting back to that when I start updating the `model` module.

Of course, I'm happy to accept pull requests if someone wants to work on the shaders.

In the mean time I'll change the title if this issue and leave it open until it's finished.

**Comment by classner** [comment]
Hi @benmoran56 ,

thanks a lot for this info! :)

**Comment by benmoran56** [comment]
Issue #117 contains an example of behavior that needs to be implemented.

**Comment by nickums** [comment]
A big fan of Pyglet, I am addressing the glsl examples in pythonstuff.org which all rely on Tristam Macdonald's  Shader.py 
Unfortunately this errors with:
 File "C:/Python/Python36/Dhruve and me/Pyglet\shader.py", line 40, in createShader
    src = (c_char_p * count)(*strings)
NameError: name 'c_char_p' is not defined
Sorry if this not the place for my query.

**Comment by benmoran56** [comment]
Hi @nickums Unfortunately I can't really offer much help with that, but It does look like those guides are targeted towards Python 2. That could be your issue.

The upcoming pyglet 2.0 (master branch) has built in shader classes now. It's not yet well documented, but you might be interested in giving that a try as well.

**Comment by nickums** [comment]
Thanks Benjamin. I look forward to the upgrade

**Comment by benmoran56** [comment]
Closing this as a lot has changed.
The Shader module is now documented in 2.0, and works well for most use cases.

There is also no plan to create a one-size-fits all shader. Instead, all pyglet modules have their own custom shaders, that suit their needs. VertexLists are now created from Shaders, so a suitable shader will need to be provided for custom use cases.
