### ISSUE TITLE
2.1.dev4 __init__.pyi causes all access type checks to fail

### ISSUE THREAD

**Issue by pushfoo** [pyglet/pyglet#1164]
**Describe the bug**
The .pyi's `Options` type only has `...`, so all access attempts fail type checks:

```python
@dataclass
class Options:
    ...

options: Options
```

**How To Reproduce**
1. `pip install -I -e pyglet==2.1.dev4` in a downstream project
2. Run type checking via pyright

**Possible solutions**
1. [thrift-pyi](https://pypi.org/project/thrift-pyi/) or similar
2. regex script to auto-update
3. Manual sync
If there's a yet unknown approach which is more expedient, I'm open to hearing it.

**Comment by shenjackyuanjie** [comment]
I'm sorry for that
fixing

**Comment by shenjackyuanjie** [comment]
fixed in #1165
