### ISSUE TITLE
Randomly getting : AssertionError: Region not allocated

### ISSUE THREAD

**Issue by Whiax** [pyglet/pyglet#1171]
**Describe the bug**
Hi! During the execution of a code, I randomly have an "AssertionError: Region not allocated" exception. 
It seems to be related to this old issue: https://github.com/pyglet/pyglet/issues/160 
This error happens when I attribute a sprite to a batch.

traceback:
```
  File ((mycode.py))
    "spr2.batch = my_batch"

  File pyglet\sprite.py:435 in batch
    self._vertex_list.delete()

  File pyglet\graphics\vertexdomain.py:267 in delete
    super().delete()

  File pyglet\graphics\vertexdomain.py:157 in delete
    self.domain.allocator.dealloc(self.start, self.count)

  File pyglet\graphics\allocation.py:264 in dealloc
    assert p >= 0 and size <= alloc_size - p, 'Region not allocated'  # noqa: PT018

AssertionError: Region not allocated
```

**How To Reproduce**
I made the following code to reproduce the error. This code doesn't make sense being presented like that but it's a simplified version of larger codes which are useful for my project but not for reproducing this issue.

Minimal code to reproduce:

1) put a debug.png near the script
2) run the code for a bit of time (<5minutes?, <100k iterations?, very inconsistent)
3) **AssertionError: Region not allocated** will happen randomly after some time

Script:
```
from pyglet.gl import *
import pyglet

#init
window = pyglet.window.Window(800, 600, resizable=True)
batch = pyglet.graphics.Batch()

#MySprite
class MySprite:
    cache_e_to_imgs = {}
    def __init__(self, e):
        
        if not e in MySprite.cache_e_to_imgs:
            MySprite.cache_e_to_imgs[e] = [pyglet.resource.texture(f'{e}.png')]
        
        imgs = MySprite.cache_e_to_imgs[e]
        anim = [pyglet.sprite.Sprite(img=img) for img in imgs]
        self.anim, self.frames = anim, imgs

#Visual component of an object
class MyVisualObject:
    def __init__(self, obj):
        self.object = obj
        
    #init sprite or skeleon
    def init(self, e=None):
        self.v = MySprite(self.object.name)

#An object
class MyObject:
    def __init__(self,name):
        self.name = name
        self.v = MyVisualObject(self)
        self.v.init()


data = {'i':0}
@window.event
def on_draw():
    glClearColor(.7,.7,.7,1)
    window.clear()
    
    #new_obj
    new_obj = MyObject('debug')
    img = new_obj.v.v.frames[0]
    
    print(data['i'], 'id(texture):', id(img))
    spr = pyglet.sprite.Sprite(img=img)
    spr.batch = batch
    
    data['i'] += 1
    batch.draw()

pyglet.app.run()
```
Someone else managed to reproduce this issue on his setup, I'm using the latest version of pyglet (2.0.16).
Thansk for trying to understand it!

**Comment by Whiax** [comment]
It seems that the issue is related to how the garbage collector interacts with pyglet.
Explicitly deleting ( sprite.delete( ) ) all sprites I create ("spr" and "new_obj.v.v.anim") instead of relying on gc seems to be a way to solve the issue. Without explicit deletion, the issue remains.
Thanks to caffeinepills and square789 for helping with this issue on Discord!

**Comment by caffeinepills** [comment]
No problem! I will close this for now as Whiax has resolved the issue via manual deletions.
