### ISSUE TITLE
Retirieve Pyglet Delta Time List

### ISSUE THREAD

**Issue by MassPig** [pyglet/pyglet#1192]
Hello,

Is it possible to get access to the delta times of a pyglet application? The best option I found is to use something similar to `FPSDisplay`, which samples the frame rate four times per second. Is it possible to retrieve the actual delta times from the `run()` method? 

I thought about using the delta time provided by the clock but was unsure whether these times are the same.

I need this to compute some statistics, so just rendering the delta times on screen will not suffice.

Thanks in advance!

**Comment by benmoran56** [comment]
Hello, 

pyglet doesn't store the delta times internally, but you can capture them yourself (in the same way FPSDisplay does) by using a `deque` from the `collections` module.  Everything scheduled on the clock has a delta time. `pyglet.app.run` internally schedules `Window.draw` on the clock (unless you pass None) as an interval. The Window instance dispatches two events whenever this method is called: `on_draw`, which for legacy reasons does NOT pass the delta time, and `on_refresh` which does include delta time. 
Assuming you are after the Window draw delta time, then you can switch from `on_draw` to `on_refresh` event handlers, and add the values to a deque that is big enough to capture enough samples for your needs.
