### ISSUE TITLE
Assigning values on the UniformArrays of ShaderProgram.

### ISSUE THREAD

**Issue by y0ngw00** [pyglet/pyglet#1194]
Hi, I'm trying to implement GPU skinning, but got stuck on assigning values to uniform mat4 arrays in the vertex shader through ShaderProgram class.

In my vertex shader, I have a uniform mat4[N]
`uniform mat4 pose[25];
`

Then I want to assign values on the shader_program['pose'] like this,
```
self.shader_program = ShaderProgram(vert_shader, frag_shader) // on the initialization process.
self.shader_program['pose']  = self.object.mesh.joint_bind_matrices // joint_bind_matrices is [N,16] arrays. This is process on the set_state of pyglet.graphics.Group class.
```

But I got this error,
`TypeError: this function takes at least 5 arguments (4 given)
`
In detail, this error happens on the` _UniformArray._update_uniform(self._ptr) `and `_UniformArray._update_uniform(data, offset=key)`

Could you show me any solutions to set values on the uniform mat4 arrays?

**Comment by benmoran56** [comment]
Hi @y0ngw00, this should be fixed in the latest point release. (The fix went in here: https://github.com/pyglet/pyglet/commit/f89cbae1afe18f8bd264f5b1e4ec9cf988c24cb8)

Can you try the latest 2.0.17 release and see if you are still having issues?

**Comment by y0ngw00** [comment]
Thanks for quick reply @benmoran56!
I uninstalled pyglet and install pyglet==2.0.17 via pypi.

I test with arbitrary matrices, but nothing changes.

Images below are the error and my vertex shader
![image](https://github.com/user-attachments/assets/d4d398e9-f18b-4405-bc3f-84b31a9abe49)
![image](https://github.com/user-attachments/assets/054bdbc4-0bb5-47e0-93ca-d66b120b02ee)

**Comment by benmoran56** [comment]
The traceback seems to be getting swallowed by the `renderer.run` call.
If you make a smaller example, example do you get any more informative traceback?

**Comment by caffeinepills** [comment]
I believe I see the issue, the matrix uniforms actually require an additional argument, which wasn't taken into account.

If you are able to test, replace these lines:
https://github.com/pyglet/pyglet/blob/5e0a26d885b9e42d2b72c0ca2a793311647a08a4/pyglet/graphics/shader.py#L400-L414

With this:
```py
    def _update_uniform(self, data: Sequence, offset: int = 0) -> None:
        if offset != 0:
            size = 1
        else:
            size = self._uniform.size

        if self._dsa:
            if self._is_matrix:
                self._gl_setter(self._uniform.program, self._uniform.location + offset, size, GL_FALSE, data)
            else:
                self._gl_setter(self._uniform.program, self._uniform.location + offset, size, data)
        else:
            glUseProgram(self._uniform.program)
            if self._is_matrix:
                self._gl_setter(self._uniform.location + offset, size, GL_FALSE, data)
            else:
                self._gl_setter(self._uniform.location + offset, size, data)
```

This works on my machine.

**Comment by y0ngw00** [comment]
Hi @caffeinepills.
It works well on my machine, too!
Thank you for your help and this issue is well addressed.
I will temporally use the fixed code and wait for the next release. Thanks again!
