### ISSUE TITLE
User font not loading and zero errors appear in console

### ISSUE THREAD

**Issue by GitBrincie212** [pyglet/pyglet#1195]
**Describe the bug**
I am making text display on the window with a custom font(more specifically the jetbrains mono font) and here is the code
When i run it, i get zero errors but the text doesn't use the jetbrains mono. I even tried to hardcode the string but still no results

**System Information:**
Macbook Pro 2018
2,6 GHz 6-Core Intel Core i7
16 GB 2400 MHz DDR4
Radeon Pro 560X 4 GB (GPU 1)
Intel UHD Graphics 630 1536 MB (GPU 2)

**How To Reproduce**
```py
class MyWindow(pyglet.window.Window):
    def __init__(self):
        super().__init__(OPTION_WIDTH, OPTION_HEIGHT, caption="...", resizable=True, vsync=False)
        pyglet.font.add_file("assets/jetbrains_mono.ttf")
        self.jetbrains_mono = pyglet.font.load('Jetbrains Mono', 16, dpi=300)
        self.debug_batch = pyglet.graphics.Batch()

    def on_draw(self) -> None:
        self.clear()
        pyglet.gl.glTexParameteri(pyglet.gl.GL_TEXTURE_2D, pyglet.gl.GL_TEXTURE_MAG_FILTER, pyglet.gl.GL_NEAREST)
        pyglet.gl.glTexParameteri(pyglet.gl.GL_TEXTURE_2D, pyglet.gl.GL_TEXTURE_MIN_FILTER, pyglet.gl.GL_NEAREST)
        fields = [
           f"Average FPS: {'%.3f' % (1 / (sum(self.delta_times) / len(self.delta_times)))}",
           f"Maximum FPS: {'%.3f' % (1 / min(self.delta_times))}",
           f"Minimum FPS: {'%.3f' % (1 / max(self.delta_times))}",
           f"Elapsed Time: {'%.3f' % self.elapse_time}",
           f"Current Scene: \"{self.scene.name}\""
        ]
        _ = [
                pyglet.text.Label(
                    text, 25, self.height - (index * 25) - 30,
                    font_name=self.jetbrains_mono.name, font_size=12,
                    batch=self.debug_batch
                )
                for index, text in enumerate(fields)
        ]
        self.debug_batch.draw()
```

**Comment by caffeinepills** [comment]
The font name is most likely incorrect. Looking at the fonts provided by JetBrains, they are separated by the typeface.

When you open the font, it should give you the font name; for example:

![image](https://github.com/user-attachments/assets/71e7bf61-c54c-4aa4-9010-98dc615260fe)
 
Try the name shown there.

Secondly, I would cache your labels in the initialization and update the text via `label.text = "new text"` as creating and destroying labels each frame will be slower.

**Comment by GitBrincie212** [comment]
1) I am using the light version that is packed in the jetbrains mono font

2) Good idea actually

**Comment by caffeinepills** [comment]
I would specify the light then in the name.
