### ISSUE TITLE
Wrong term In the Literal definition for ContentVAlign

### ISSUE THREAD

**Issue by drivingmenuts** [pyglet/pyglet#1198]
**Describe the bug**
In `customtypes.py`, the terms for the Literal `ContentVAlign` are given as `["left", "center", "top"]`. Should they not be `["bottom", "center", "top"]`?

**Comment by drivingmenuts** [comment]
Also, should `ContentVAlign` be named `VerticalAlign` for consistency (or `HorizontalAlign` be renamed `ContentHAlign`)?

**Comment by caffeinepills** [comment]
Good catch! Definitely an oversight, I have corrected this in the main branch.

As far as naming goes, they are slightly different. The alignment for horizontal is technically per line; not necessarily for the content. Having just `HAlign` didn't really seem very informational, and `ContentVerticalAlign` seemed too verbose.

**Comment by caffeinepills** [comment]
Fixed in https://github.com/pyglet/pyglet/commit/5b7b0b05f6189f98b8b024fe6e7b74533bc4d8a5
