### ISSUE TITLE
Include a py.typed marker file to show that pyglet is typed

### ISSUE THREAD

**Issue by viblo** [pyglet/pyglet#1205]
**Is your feature request related to a problem? Please describe.**
It would be nice if pyglet could contain the py.typed marker file, so that when I import pyglet I dont get type errors and for example mypy can type check my usage of pyglet

**Describe the solution you'd like**
Include a py.typed marker file (just an empty file in pyglet folder)

**Additional context**
https://typing.readthedocs.io/en/latest/spec/distributing.html#packaging-typed-libraries

**Comment by benmoran56** [comment]
Hi,
typing for pyglet is mostly done, but is still a work in progress. I wasn't aware this was still necessary, but we can add it if it will help some use cases.

**Comment by viblo** [comment]
So now when I have some code that import pyglet I need to do 
```
import pyglet #type: ignore
```
or else if I typecheck with mypy I get this error:
```
error: Skipping analyzing "pyglet": module is installed, but missing library stubs or py.typed marker  [import-untyped]
```

If Pyglet is ready for this Im not sure (I checked those things I used and they had types), but imho its still good to let the user have the option. It will still be possible to ignore the type if something is missing.

**Comment by benmoran56** [comment]
What is your IDE & code inspection setup?

The goal is to get pyglet typed at a useful level, that works for the majority of type checking tools. As you know typing in Python itself is still a work in progress, and sometimes different tools have different ideas on things. The pyproject.toml has a general list of things that are currently ignored, and also tool specific overrides. It should give a bit of a hint on what the current status is.

**Comment by viblo** [comment]
I use two typecheckers, pyright in VSCode (which is part of the pylance), and Mypy from command line. Pyright seems to not care about `py.typed`, while mypy requires it to do anything. 
I think the top comment here describes the issue quite well: https://github.com/python/typing/discussions/1429
Basically unless something is super-broken or the types are somewhere else, its better to have the file than not.

**Comment by viblo** [comment]
Some additional comments: 
- If I run Mypy or Pyright on Pyglet itself there are many type errors. 
- For my (limited) usage, if I add a `py.typed` file manually to Pyglet my code typechecks fine.

**Comment by benmoran56** [comment]
Added for next point release (v2.0.18). 
Please note that running mypy directly against the entire pyglet code base is not currently supported, but this should help projects that are importing pyglet.

**Comment by pushfoo** [comment]
@viblo you may have better luck with pyright (pylance if you're using VS Code):
1. The `pyglet.math` module uses `NamedTuple` for speed reasons
2. [The mypy project does not support `NamedTuple`](https://github.com/python/mypy/issues/5944#issuecomment-441285456):
   
![image](https://github.com/user-attachments/assets/c50f92bd-2f15-4ed4-b0de-71bf32cebfa9)

**Comment by viblo** [comment]
@pushfoo I am actually already using pyright, as I wrote earlier. Its just that I also use mypy. I maintain another library, Pymunk, and I think its good, if possible, to have types working for more than just one checker for libraries. Now, for the same reason I also fully understand that its lots of work to add types retroactively and that it might not even be possible to make perfect types for mypy, especially not without adjusting the API. I filed bug reports to both pyright and mypy when I added types to Pymunk. But in this isssue I only hoped for the py.typed marker file :)  

For the `pyglet.math` thing I think you linked the wrong thread or maybe I misunderstand? The issue is not that mypy does not support NamedTuples, it does. There are some limitations to the support which is described in your linked issue, but I dont think they apply to Pyglet, when I look for NamedTuple it looks to be only simple cases?

However, `pyglet.math` does use tuple as baseclass. And for cases when you inherit tuples there's a limitation when you restrict the arguments allowed as pyglet does. See https://github.com/python/typeshed/issues/228 which is what mypy finds when running it against `pyglet.math`.

**Comment by benmoran56** [comment]
I think we have similar ideas about typing, in general. 
I believe what pushfoo was saying is that, while pyglet is not exclusively supporting pyrite, mypy is still a bit too "noisy" to recommend. (Correct me if I'm wrong here).
The math module in particular is doing some non-standard things in the name of performance, so we can't "fix" it for mypy.

I'm personally in favor of a more "wait and see" approach to typing, because things are still changing in the Python world. 

We have at least implemented type hints for all user facing APIs so far, so inspection should be hopefully more useful to end users. We're working towards improving things with every release.
