### ISSUE TITLE
Changing the anchor point of an existing TextLayout that contains a FormattedDocument causes the text to misalign and overlap

### ISSUE THREAD

**Issue by CharlesHawkinsMSU** [pyglet/pyglet#1206]
**Describe the bug**
When I create a FormattedDocument and apply a style, such as italic, to only part of it using set_style, then create a TextLayout with that document, then assign any value to anchor_x or anchor_y for that TextLayout, the style segments of the text lose their horizontal alignment and appear to overlap one another when drawn. So for example if the FormattedDocument d contains the text "hello" and it has style {'italic': True} for the range (0,3), and I create l = TextLayout(document = d) and then assign any value to l.anchor_x or l.anchor_y, then the "hel" and "lo" will both be rendered at the same x coordinate, causing them to overlap.

Setting anchor_x or anchor_y in the TextLayout constructor does not trigger the bug, only assigning to them after the layout object is created. Re-assigning l.document = d after changing the anchor point corrects the glitch, so this seems a viable workaround for the time being. Setting them in the constructor also works as a workaround if you don't need to change them after, though this breaks compatibility with pyglet 2.0.10 which is still the version found in the Mint 22 default repo.

Assigning to anchor_x or anchor_y triggers the bug even if I assign the same value that they already had.

So far it seems that having style segments in the document that differ from one another in bold, italic, font_name, or font_size triggers the bug, but color does not (tested in pyglet 2.0.17)

**System Information:**
Python 3.12.5 (I also tested with 3.10.14 and it is also affected)

I tested Pyglet 2.0.10 through 2.1dev5:
- Pyglet 2.0.13 through 2.1dev5 are all affected
- 2.0.11 and 2.0.12 do not show the bug with anchor_x or anchor_y but instead show it when setting x or y (which 2.0.13+ do not)
- 2.0.10 is not affected at all as far as I can tell

Three OS installs on two machines are equally affected:
Fedora 40 / Wayland session (KDE) / Core i5-1240P
Mint 22 / X11 session (Cinnamon) / AMD CPU and GPU
Windows 10 with Python 3.12.6 and Pyglet 2.0.17 on the above AMD machine

**How To Reproduce**
```
import pyglet
win = pyglet.window.Window()
@win.event
def on_draw():
	d = pyglet.text.document.FormattedDocument('hello')
	d.set_style(0, 5, {'color': (255,255,255,255), 'font_size': 50})
	d.set_style(0, 3, {'italic': True})
	l = pyglet.text.layout.TextLayout(x = 300, y = 100, document = d)
	l.anchor_y = 'bottom'  # This line causes the glitch
	#l.document = d  # Uncommenting this line fixes the glitch
	l.draw()
pyglet.app.run()
```
![pyglet_hello](https://github.com/user-attachments/assets/a2672eea-7aca-4400-8cbf-96d6e71eae7f)

**Comment by benmoran56** [comment]
Thanks for the big report, and for taking the time to compare pyglet releases.

**Comment by caffeinepills** [comment]
The example has issues on its own (recreating layouts and not clearing the window). However, I have been able to reproduce the issue on my end. I did a PR for a fix that should resolve the issue, using the following example:

```py
from __future__ import annotations

import pyglet

win = pyglet.window.Window()

d = pyglet.text.document.FormattedDocument('hello')
d.set_style(0, 5, {'color': (255, 255, 255, 255), 'font_size': 50})
d.set_style(0, 3, {'italic': True})
l = pyglet.text.layout.TextLayout(x=300, y=5, document=d)
l.anchor_y = 'bottom'

@win.event
def on_draw():
    win.clear()
    l.draw()

pyglet.app.run()
```
