### ISSUE TITLE
Stadia Bluetooth controller not detected, wrong mapping

### ISSUE THREAD

**Issue by eruvanos** [pyglet/pyglet#1214]
**Describe the bug**
Stadia Controller (onMac) are not detected as controller

**System Information:**
MacOS: 14
pyglet version: 2.1.dev5

**Findings**

https://github.com/pyglet/pyglet/blob/f08008789f6a9134149c8313975132d7762cc009/pyglet/input/macos/darwin_hid.py#L624
Does not allow `BLUETOOTH LOW ENERGY`

After adding this, the controller is detected, but the triggers are not detected, because the axes are not detected.

Changing:
https://github.com/pyglet/pyglet/blob/d074003ffc033f4a4ac67a749794e4cb77a7a368/pyglet/input/base.py#L728

To:
`if ctrl.name in ('x', 'y', 'z', 'rx', 'ry', 'rz') or ctrl.raw_name in ('0x2:c4', '0x2:c5'):`
solves the issue.

> Unknown axis: element.usagePage=2, element.usage=197
> Unknown axis: element.usagePage=2, element.usage=196

**How To Reproduce**
Connect Stadia Controller to a Mac

```
import pyglet
from pyglet.input import ControllerManager

window = pyglet.window.Window()
cm = ControllerManager()

@cm.event
def on_connect(controller):
    print(f"Connected:  {controller}, {controller.guid}")

@cm.event
def on_disconnect(controller):
    print(f"Disconnected:  {controller}")

print(cm.get_controllers())

pyglet.app.run()
```

**Comment by benmoran56** [comment]
Hi @eruvanos, I've added the additional device type to the valid list.

Rather than updating `input.base.py`, we need to add an alias for these axis names in `darwin_hid.py`. 
See: https://github.com/pyglet/pyglet/blob/master/pyglet/input/macos/darwin_hid.py#L480
And: https://github.com/pyglet/pyglet/blob/master/pyglet/input/macos/darwin_hid.py#L545

I'm not sure if they should be aliased to z & rz, or something else (depends on how macOS handles the other axis). 
Can you see which aliases (names) are not already used? As long as they are not conflicting it will be OK.

**Comment by benmoran56** [comment]
Looking at the discussion on Discord, it looks like `x, y, z, rz` are in-use, so likely should be aliased to `rx` and `ry`. 
```py
Stadia5KYL-6a50
[Button(raw_name=0x9:1), Button(raw_name=0x9:2), Button(raw_name=0x9:4), Button(raw_name=0x9:5), Button(raw_name=0x9:7), Button(raw_name=0x9:8), Button(raw_name=0x9:b), Button(raw_name=0x9:c), Button(raw_name=0x9:d), Button(raw_name=0x9:e), Button(raw_name=0x9:f), Button(raw_name=0x9:11), Button(raw_name=0x9:12), Button(raw_name=0x9:13), Button(raw_name=0x9:14), AbsoluteAxis(name=x, raw_name=0x1:30), AbsoluteAxis(name=y, raw_name=0x1:31), AbsoluteAxis(name=z, raw_name=0x1:32), AbsoluteAxis(name=rz, raw_name=0x1:35), AbsoluteAxis(name=hat, raw_name=0x1:39), AbsoluteAxis(raw_name=0x2:c4), AbsoluteAxis(raw_name=0x2:c5), Button(raw_name=0xc:cd), Button(name=volume_up, raw_name=0xc:e9), Button(name=volume_down, raw_name=0xc:ea)]
```
So perhaps something like:
```py
_axis_names = {
    (0x01, 0x30): 'x',
    (0x01, 0x31): 'y',
    (0x01, 0x32): 'z',
    (0x01, 0x33): 'rx',
    (0x02, 0xc4): 'rx',
    (0x01, 0x34): 'ry',
    (0x02, 0xc5): 'ry',
    (0x01, 0x35): 'rz',
    (0x01, 0x38): 'wheel',
    (0x01, 0x39): 'hat',
}
```

If you can get any additional information on the names from the macOS side, that would also help to confirm what the aliases should be.

**Comment by eruvanos** [comment]
<img width="639" alt="image" src="https://github.com/user-attachments/assets/83b34e64-9acf-4c4c-abb3-c0c0d5fa2e41">

This is the underlying element:
<img width="685" alt="image" src="https://github.com/user-attachments/assets/58a1e0e2-5878-48f4-a74d-1edb207f3542">


Not sure which other information I could provide to support here :/

**Comment by benmoran56** [comment]
Can you try adding the `_axis_names` aliases on your local copy, and confirm the `examples/input/controller.py` example works as expected?

**Comment by eruvanos** [comment]
works (as long as I add the 'BLUETOOTH LOW ENERG')

**Comment by benmoran56** [comment]
You have also modified `input/base.py` as well, haven't you? 
```py
if ctrl.name in ('x', 'y', 'z', 'rx', 'ry', 'rz') or ctrl.raw_name in ('0x2:c4', '0x2:c5'):
```
Can you remove that, and try the `_axis_names` addition instead?

**Comment by benmoran56** [comment]
Fixed in master. Will be in the next point release.
