### ISSUE TITLE
sys.is_pyglet_doc_run is unintentionally TRUE, causing a NotImplementedError: abstract.

### ISSUE THREAD

**Issue by 3jz** [pyglet/pyglet#1215]
**Describe the bug**
With jupyter or ipython environment, pyglet.window.Window() causes "NotImplementedError: abstract".
sys.is_pyglet_doc_run is determined by whether sphinx is included in sys.modules. I suppose this is a logic for documentation.
But, sphinx is also imported with jupyter/ipython environment. So, this occurs.
`del sys.modules["sphinx"]` before `import pyglet`, I could avoid this problem.
If there are better way to avoid this, it may be helpful.

**System Information:**
Python           : 3.10.5
IPython          : 7.32.0
ipykernel        : 6.15.1
ipywidgets       : 7.7.1
jupyter_client   : 7.3.4
jupyter_core     : 4.11.1
jupyter_server   : 1.18.1
jupyterlab       : 3.4.3
nbclient         : 0.6.6
nbconvert        : 6.5.0
nbformat         : 5.4.0
notebook         : 6.4.12
qtconsole        : 5.3.1
traitlets        : 5.3.0

**How To Reproduce**
Run pyglet.window.Window() with jupyter or ipython environment.

**Comment by benmoran56** [comment]
Hi, thanks for opening the ticket.
We have recently updated our sphinx .conf file to set `sys.is_pyglet_doc_run = True` there, so we don't necessarily need this check in `pyglet.__init__.py` anymore. Let me see if I can remove that for the next point release.

**Comment by benmoran56** [comment]
Fixed in the upcoming point release, so will close this for now. Let me know if you still have issues after updating to v2.0.18 (to be out shortly).
