### ISSUE TITLE
Cannot read input device controls in Windows

### ISSUE THREAD

**Issue by 0leksandr** [pyglet/pyglet#1222]
I am trying to read the controls of a [Radiomaster TX12](https://www.radiomasterrc.com/products/tx12-mark-ii-radio-controller) radio controller input device. The device connects to a computer via USB-C port and is similar to a game joystick in terms that it has two 2D-sticks (position of which I am trying to read).

The code:
```python
import pyglet

device = [device for device in pyglet.input.get_devices() if device.name in (
    "Radiomaster TX12 Joystick",  # name in Windows and macOS
    "OpenTX Radiomaster TX12 Joystick",  # name in Linux
)][0]
device.open(exclusive=True)
for control in device.get_controls():
    print(control.name, control.value)
```

This code does work well with this exact device in macOS 15.0.1 and Linux 5.15.0 (Ubuntu 20.04.1), but does not work in Windows 10 19045.4894. In the case of Linux, I even use the same port of the same physical machine.
What I mean by not working: in Windows, the list of controls is identified correctly, but their values are all `None` or `False`, while in macOS/Linux they all have correct numeric values.

I use Python 3.12 and Pyglet 2.0.17.
The device is correctly identified and used by games (FPV simulators) on all 3 OSes.
No other program/process seems to "steal" control over the device from my Python script.
The device is not "mirrored/duplicated" - when I plug it into the computer, `pyglet` sees exactly +1 new device.

Side note: when I call `pyglet.input.get_controllers()`, I am getting a warning (not a problem for me, but might be a hint?):
- in Linux:
> pyglet/input/linux/evdev.py:600: UserWarning: Warning: EvdevDevice(name=OpenTX Radiomaster TX12 Joystick) (GUID: 0300000009120000544f000011010000) has no controller mappings. Update the mappings in the Controller DB.
- in macOS:
> pyglet/input/macos/darwin_hid.py:632: UserWarning: Warning: HIDDevice(name=Radiomaster TX12 Joystick) (GUID: 0300000009120000544f000000020000) has no controller mappings. Update the mappings in the Controller DB.
- in Windows:
> pyglet\input\win32\directinput.py:429: UserWarning: Warning: DirectInputDevice(name=Radiomaster TX12 Joystick) (GUID: 0300000009120000544f000000000000) has no controller mappings. Update the mappings in the Controller DB.

I will be glad to help investigate/fix this issue.

**Comment by benmoran56** [comment]
Hi, can you confirm if you get anything from the `examples/input/joystick.py` example? 

The `get_controllers()` output is expected. This type of device is better handled by the `Joystick` interface. 

You can also try setting `pyglet.options.win32_disable_xinput = True` (immediately after importing pyglet), but that likely won't have any effect.

**Comment by 0leksandr** [comment]
Hi! I just tried the example you provided, and it does work 🙂.
Although I did try simple code with joysticks previously (same as I did with devices in the code above - without windows, `event` annotation and calling `pyglet.app.run()`, like in the example), and the result was the same - the controls were empty.
So for me, that can be a solution - I will adapt my code to the one from the example.
Should I close this issue, or the problem is real? Originally I thought that working differently in different OSes is a problem.

**Comment by benmoran56** [comment]
Glad you got it working.
The reason is most likely due to the missing call to `pyglet.app.run()`.
Generally speaking, you need a running event loop for most things in pyglet. Not for everything, because implementations do differ between platforms. For that reason this is not really a bug. 

If you do not want to use `pyglet.app.run()`, you _can_ do it manually, but you have to tick the clock, and step the platform event loop manually. This needs to be done at a regular interval:  https://pyglet.readthedocs.io/en/latest/programming_guide/eventloop.html#creating-a-custom-event-loop

Since you're talking about multi-platforms, does the Joystick layout match across all platforms? 
If yes, you're in a lucky spot, and can use the Joystick interface without an additional work. 
If it does not, you have some options. 
1. make your own code to check the platform (`pyglet.compat_platform`) and map the axis/buttons.
2. make a custom Controller mapping string for each platform, and use the Controller interface. 

Both valid options.

**Comment by 0leksandr** [comment]
Thank you for the explanation and documentation hint!
It does not solve my original problem, although explains a lot. The event loop (either default or custom) I need to use is about listening or reacting to system events, but I need a momentary state of the device. So, not which stick a user moved and when or track the history of movements or what a reaction to the movement in Pyglet app should be, but rather what is the position of a stick at the current given moment. The way it smoothly works on other platforms made me think it should be able to do in Windows as well.

Either way, thank you for your time and explanation!

**Comment by benmoran56** [comment]
You can still query the control values directly from the Joystick, but you need the event loop running in order for them to be internally updated.
