### ISSUE TITLE
pyglet.graphics.vertexbuffer's documentation suggests to use create_buffer(), which was removed

### ISSUE THREAD

**Issue by Fat-Zer** [pyglet/pyglet#1233]
`pyglet.graphics.vertexbuffer`'s documentation [suggests][1] to use `create_buffer()` which was removed long time ago in 25ac7f4425eb9dd88afc5413076a6a1f245dc16c.

[1]: https://github.com/pyglet/pyglet/blob/master/pyglet/graphics/vertexbuffer.py#L3

**Comment by benmoran56** [comment]
This is updated in the latest doc build. Thanks for opening the ticket!
