### ISSUE TITLE
pyglet's astraea problems

### ISSUE THREAD

**Issue by ccanepa** [pyglet/pyglet#124]
- main menu items in astraea don't respond to mouse clicks (kbd navigation seems right)
 - unwanted sliding textures both at main menu  and into a level:

in main menu:

![astraea_1](https://user-images.githubusercontent.com/362220/72363312-693fa700-36d3-11ea-9f5f-9ca5b525dc96.jpg)
  
into a level:

![astraea_level](https://user-images.githubusercontent.com/362220/72363344-79578680-36d3-11ea-9730-3eb5fca6ef04.jpg)

win7-64, py38, pyglet as 
commit c4acb39f08b6097da9c71de374c63623522c698a (HEAD -> pyglet-1.4-maintenance,
 origin/pyglet-1.4-maintenance)
Author: Benjamin Moran
Date:   Tue Jan 14 10:21:06 2020 +0900

video: ati radeon R7 250 newish drivers: 19.9.2, so from last August

**Comment by benmoran56** [comment]
I had a look at that before, and I think the visual issues are driver related. It looks like Astraea is using some OpenGL tricks, which might not be well supported. We probably need to rewrite that code in Astraea. 

For the Mouse clicks, that should be simpler to fix.

**Comment by ccanepa** [comment]
I think the problem is that starfield.jpg is loaded into an atlas, and the code used to draw the starfield takes the entire atlas texture.

A lazy fix is to load startfield.jpg as a separate texture, as in

```
diff --git a/examples/astraea/astraea.py b/examples/astraea/astraea.py
index d4e14b3f..14f0d399 100755
--- a/examples/astraea/astraea.py
+++ b/examples/astraea/astraea.py
@@ -804,7 +804,8 @@ pointer_image_flip = resource.image('pointer.png', flip_x=True)
 explosion_sound = resource.media('explosion.wav', streaming=False)
 bullet_sound = resource.media('bullet.wav', streaming=False)
 
-starfield = Starfield(resource.image('starfield.jpg'))
+starfield_img = pyglet.image.load('starfield.jpg', file=pyglet.resource.file('starfield.jpg'))
+starfield = Starfield(starfield_img)
 player = Player(resource.image('ship.png'), wrapping_batch)
 win.push_handlers(player)
```
This corrects the visual problem in my system.

About the mouse: I see no on_mouse_... handler in the code, so mouse is not intended to work.
Maybe then the mouse pointer must be hiden?

**Comment by benmoran56** [comment]
Thanks Claudio,
I went ahead and fixed the background and hid the mouse cursor. It's now in the 1.4 branch, and will be in the next release. 

By the way, Instead of falling back to `pyglet.image.load`, you can do either of these:

```pyglet.resource.image('filename.png', altas=False)```
or
```pyglet.resource.texture('filename.png')```

They have the save effect, in that you will get a standalone Image/Texture. Images and Textures are mostly API compatible for high level usage such as Sprites, so either way will work.

**Comment by ccanepa** [comment]
`pyglet.resource.image('filename.png', altas=False)` 
shows better the intent, thanks.

And thanks for the prompt response on all te issues.

**Comment by ccanepa** [comment]
Just for completion, I did a pull and re-test, Astraea looks fine.

**Comment by benmoran56** [comment]
Yes I thought so too. I initially used texture, but then I made another commit to change it. 
Thanks for confirming!
