### ISSUE TITLE
Immediate mode in modern opengl?

### ISSUE THREAD

**Issue by fangzhangmnm** [pyglet/pyglet#1245]
Hi
Is there an elegant way of drawing a numpy array of points or triangles for a basic visualization, without start from writing a custom shaders and compile it and go through all the 20 chapters of nehe tutorial?

**Comment by benmoran56** [comment]
pyglet already has lots of built-in classes that make it easy to work with shaders. 
However, you can just re-use one of the default pyglet shaders if it suites your needs. For example, the shader for the `shapes` module. This shader only uses 2D positioning, but you can very easily extend it for 3D if necessary. To use it as-is:
```py
import pyglet

from pyglet.gl import GL_TRIANGLES


window = pyglet.window.Window()
batch = pyglet.graphics.Batch()

# re-use an existing Shader Program:
program = pyglet.shapes.get_default_shader()

# Examine the vertex attribute details:
for name, meta in program.attributes.items():
    print(name, meta)


# Make data for three vertices:
position = ('f', (100, 100,  200, 100,  150, 175))                                  # count = 2, so (2 * 3)
colors = ('Bn', (200, 50, 50, 255,  50, 255, 50, 255,  50, 50, 255, 255))           # count = 4, so (4 * 3)

# Make a vertex list
vlist = program.vertex_list(count=3, mode=GL_TRIANGLES, batch=batch,
                            # attribute data is passed in as kwargs:
                            position=position, colors=colors)


@window.event
def on_draw():
    window.clear()
    batch.draw()


pyglet.app.run()
```

This chapter in the documentation goes into more details about this, but feel free to ask if something is not clear. 
https://pyglet.readthedocs.io/en/latest/programming_guide/rendering.html

**Comment by fangzhangmnm** [comment]
@benmoran56 Thank you very much. I found the example folder is a good way to start. I used the `pyglet.model.get_default_shader()`. But your recommendation is much better since it does not require lots of material setup.
