### ISSUE TITLE
I would like to be able to create a new sprite without specifying the texture from the get go

### ISSUE THREAD

**Issue by OliPerraul** [pyglet/pyglet#125]
Since, i'm specifying animations right after, it makes it cumbersome to specify the texture first. Sprite is equipped with setters. How difficult would this be?

Thanks

````

import enum
import pyglet

# import cirrus.bounding_box

from objects.base_object import BaseObject

class Avatar(BaseObject):
    def __init__(self, *args, **kwargs):
# TODO: do not specify texture
        super(BaseObject, self).__init__(pyglet.resource.image('avatar/avatar_spritesheet.png'), *args, **kwargs)
        
        self.animations = {}

        sprite_sheet = pyglet.resource.image('avatar/avatar_spritesheet.png')
        sprites = pyglet.image.ImageGrid(sprite_sheet, rows=8, columns=12)

        self.animations['WalkForward'] = pyglet.image.Animation.from_image_sequence(
            [
                sprites[84],
                sprites[85],
                sprites[86]
            ],
            0.1,
            True)

````

**Comment by caffeinepills** [comment]
A sprite by definition has a texture, there are a few ways you can do this:
1) I'm assuming `BaseObject `here is a subclass of` pyglet.sprite.Sprite`. In which case, the simplest way is you can just move `super(BaseObject, self).__init__(texture_you_want_at_creation, *args, **kwargs)` after you have already loaded the animations (`self.animations`). It doesn't have to be the first call of `__init__`.

2) Don't subclass `Sprite`, just make sprite as a variable for your object that is called after you already have the texture.
`self.sprite = pyglet.sprite.Sprite(args_and_kwargs_here)`

3) At the start load a blank texture `blank_texture = pyglet.image.ImagePattern(color=(0, 0, 0, 0)).create_image(1, 1)` and use that one texture on creating sprites. Fill in the correct one later.

**Comment by benmoran56** [comment]
I personally just do method  2)  for my own projects, but these are all good options.

Unfortunately, creating a Sprite without a texture would require a heavy rewrite of the Sprite class. It would also require a bit more code bloat to handle the extra use case. We would like to avoid that whenever possible, since Sprites should be as lightweight as possible.
