### ISSUE TITLE
Enhance Document

### ISSUE THREAD

**Issue by Howld** [pyglet/pyglet#131]
Link: https://pyglet.readthedocs.io/en/latest/programming_guide/mouse.html
```
cursor = window.get_system_mouse_cursor(win.CURSOR_HELP)
window.set_mouse_cursor(cursor)
```
Sometimes I'm not clear about 'window' and 'win'. Please fix it.
```
win = pyglet.window.Window()
cursor = win.get_system_mouse_cursor(win.CURSOR_HELP)
win.set_mouse_cursor(cursor)
```

**Comment by einarf** [comment]
It could also be a great oppertunity to contibute to an open source project 😃 
The source file for that page is here : https://github.com/pyglet/pyglet/blob/master/doc/programming_guide/mouse.rst

**Comment by benmoran56** [comment]
Thanks for your pull request, @Howld! 
It will be in the upcoming v1.5 release. At that time, the documentation on https://pyglet.readthedocs.io/ will be updated.
