### ISSUE TITLE
import pyglet.gl causes NameError

### ISSUE THREAD

**Issue by chpurdy** [pyglet/pyglet#134]
On Python 3.7.6 (using Thonny IDE) I get the following error when importing `pyglet.gl`, which is actually being imported by `arcade`.  

OS: Ubuntu 19.04

``` python
>>> import pyglet.gl
Traceback (most recent call last):
    del base  # noqa: F821
NameError: name 'base' is not defined
```

**Comment by chpurdy** [comment]
Sorry, reloading the virtual environment resolved this issue.

**Comment by dniku** [comment]
I'm maintaining https://www.coursera.org/learn/practical-rl/home/welcome, and roughly once a month I am seeing reports of this issue whenever someone executes:

```python
import matplotlib.pyplot as plt
%matplotlib inline

import gym

env = gym.make("MountainCar-v0")
env.reset()

plt.imshow(env.render('rgb_array'))
```

I haven't been able to reproduce the issue myself, and I don't know what causes it, but the latest report was today, with code executed in Google Colab: https://colab.research.google.com/github/yandexdataschool/Practical_RL/blob/7eaf4d3/week1_intro/gym_interface.ipynb

According to `pip list -v`, Colab currently has pyglet 1.5.0.

Please reopen this issue, as it still occurs.

**Comment by benmoran56** [comment]
At the bottom of `pyglet/gl/__init__.py`, there is a call to `del base`:
```py
del base  # noqa: F821
```
To be honest, I'm not sure why this call is in place. It's harmless on a normal system or virtualenv, and it may be a workaround from the past that is no longer necessary. Removing this call does not cause any noticeable issue, and the test suite still passes. I'll look into this a bit more and see if it's safe to remove (which should fix the issue that Colab users are seeing), if that is indeed the cause.

**Comment by rudrapoudel** [comment]
I have also seen this error while using OpenAI Gym CarRacing-v0 env with xvfb-run.

More debugging narrow down to this issue- #202 

Any update or suggestion please?

**Comment by benmoran56** [comment]
I removed this seemingly unnecessary call in the `pyglet-1.5-maintenance` branch. Could you guys give it a try, and confirm if it works for you? 

If you are installing via pip, you can upgrade via: 
`pip install --upgrade --user https://github.com/pyglet/pyglet/archive/pyglet-1.5-maintenance.zip`

**Comment by benmoran56** [comment]
Closing this for now due to lack of feedback, but the fix will be in the next release.
