### ISSUE TITLE
Compatibility issue with Raspberry Pi

### ISSUE THREAD

**Issue by servusDei2018** [pyglet/pyglet#139]
Running pyglet on the Raspberry Pi crashes unless
`self._have_MESA_swap_control = config.glx_info.have_extension('GLX_MESA_swap_control')` (atm line 201) in `pyglet/gl/xlib.py:209pyglet/gl/xlib.py` is changed to `self._have_MESA_swap_control = config.glx_info.have_extension('GLX_EXT_swap_control')`.

Whether MESA or EXT is used can be determined by whether we are running on RPi or not; this should be added.

**Comment by benmoran56** [comment]
Hi @servusDei2018, which version of pyglet are you using?
`pyglet.version`

**Comment by servusDei2018** [comment]
1.4.10

**Comment by benmoran56** [comment]
Thanks.

Can you post the traceback from the crash?
Also, could you confirm that it does not crash if vsync is disabled?

**Comment by servusDei2018** [comment]
Hmmm, that's odd. After reverting my change, it doesn't seem to crash anymore so I can't reproduce it.

**Comment by benmoran56** [comment]
According to other users, it *should* work correctly with the latest pyglet release. 

One thing to be aware of though is that the raspberry pi lies about some missing features in the GL lib, so you may get a warning logged to the console with vsync.

**Comment by benmoran56** [comment]
I'll close this for now, but please re-open the ticket (or make a new one) if it turns out you're still having issues. 

Thanks!

**Comment by servusDei2018** [comment]
Sure. Thanks for the help!
