### ISSUE TITLE
[2.0] Separate GL viewport update from on_resize event handler

### ISSUE THREAD

**Issue by t-o-n-y-p** [pyglet/pyglet#143]
Current implementation updates GL viewport and projection inside `on_resize` event handler, which results in raising this event even if window size hasn't changed. 
The suggestion is to fire `on_resize` event only if window size has changed and update GL viewport and projection separately when needed.

**Comment by t-o-n-y-p** [comment]
Sample
```
import pyglet


window = pyglet.window.Window()
window.set_fullscreen(True)
window.set_fullscreen(False)


@window.event
def on_resize(width, height):
    print(f'on_resize: {width=}, {height=}')


pyglet.app.run()
```
result
```
on_resize: width=640, height=480
on_resize: width=640, height=480
on_resize: width=1366, height=768
on_resize: width=1366, height=768
on_resize: width=1366, height=768
on_resize: width=640, height=480
on_resize: width=640, height=480
on_resize: width=640, height=480
```
That's too much for just  size changes (initial one, going fullscreen and back).

**Comment by benmoran56** [comment]
It looks like the amount of `on_resize` dispatches is dependent on the OS platform code, since on Linux I'm only seeing three resize events (all as expected, and needed). The Windows platform abstraction might be a little too eager with dispatching the event. 

Looking at this function on line 989, we can see that it updates the _width and _height with the new w, h values: 
https://github.com/pyglet/pyglet/blob/master/pyglet/window/win32/__init__.py#L968

Maybe we can first compare if the previous values are equal or not, then dispatch the event if so. Something like: 
```py
        if w != self._width or h != self._height:
            self.dispatch_event('on_resize', self._width, self._height)
```

That dispatch code would need to be moved above the other code that updates the _width and _height values of course. 
Could you give that a try and see if it helps quiet things down?

**Comment by t-o-n-y-p** [comment]
Yeah, I've already investigated this before posting. This approach reduces the number of redundant events but doesn't fully solve the problem. 
`on_resize` event is also fired inside `set_visible` method which is called when the window is made visible either by the system or a user's code because GL viewport and projection has to be updated (otherwise user will see nothing on the screen), and this update is done by `on_resize` event handler which is an oversight. Potential fix would be a braking change, that's why I've targeted this for 2.0.

**Comment by t-o-n-y-p** [comment]
The latest idea discussed via discord chat was to reuse the `on_expose` event:
1) copy GL viewport and projection update code from the `on_resize` event handler to the internal method like `_set_framebuffer_size_callback` and call this method in `on_resize` and `on_expose` event handlers;
2) fire `on_resize` event after window size has changed;
3) fire `on_expose` event when window size has not changed but we have to update GL viewport and projection.
#3 covers cases when window was unminimized or brought from background to the front, in compliance with `expose` term.

How do you like this approach?

**Comment by einarf** [comment]
As long as this doesn't make trouble when the buffer size changes (and not window size). pyglet reports size in window coordinates, but I guess there is supposed to be a separate event for that?

**Comment by t-o-n-y-p** [comment]
@einarf I understand what you are talking about but I can't imagine real use cases where this can happen. Can you please clarify? And does new `on_scale` event by @caffeinepills cover them?

**Comment by caffeinepills** [comment]
Just a little investigation but there are actually only 3 events of `WM_SIZE` are _actually_ called in your example. The duplicates seem to be called by `self._legacy_setup()` during creation of the event loop.

```
  File "C:\Users\User\Desktop\test.py", line 20, in <module>
    pyglet.app.run()
  File "C:\Python36\lib\site-packages\pyglet\app\__init__.py", line 144, in run
    event_loop.run()
  File "C:\Python36\lib\site-packages\pyglet\app\base.py", line 164, in run
    self._legacy_setup()
  File "C:\Python36\lib\site-packages\pyglet\app\base.py", line 253, in _legacy_setup
    window.dispatch_pending_events()
  File "C:\Python36\lib\site-packages\pyglet\window\win32\__init__.py", line 657, in dispatch_pending_events
    EventDispatcher.dispatch_event(self, *event)
  File "C:\Python36\lib\site-packages\pyglet\event.py", line 416, in dispatch_event
    if handler(*args):
```

**Comment by benmoran56** [comment]
This is an old one, but I think we can finally close it. 
The `self._legacy_setup()` stuff has been removed now in v2.0, so the calls to on_resize are no longer excessive.
