### ISSUE TITLE
AVbin plays sound but not video

### ISSUE THREAD

**Issue by alan-frank** [pyglet/pyglet#144]

**Comment by einarf** [comment]
Do you have any more details information? What pyglet version are you currently using? What platform? Do you have any code to replicate the issue?

**Comment by benmoran56** [comment]
Hi @alan-frank 

I'm going to close this for now due to lack of reply, but please note that AVbin is no longer supported. If you get back to this issue, please feel free to re-open it, or open a new ticket. 

Thanks!
