### ISSUE TITLE
Segmentation fault with pyglet on raspberry pi

### ISSUE THREAD

**Issue by balajisriram** [pyglet/pyglet#148]
I am trying to use psychopy with a raspberry pi.

My installation:

 - raspberry pi 4b with raspbian buster
 - updated to latest software
 - installed psychopy [see https://github.com/balajisriram/BCore/blob/raspberry/setup_pi.sh I manually installed the dependencies for psychopy and then pip installed psychopy (v 2020.1.0) ]

When i try to open a window, it looks like psychopy calls `pyglet.GL.glLinkProgramARB(prog)` for multiple programs. When `prog=55`. I see an immediate segmentation fault and the process stops. 

Has anyone encountered this issue? Any solutions?

**Comment by benmoran56** [comment]
If the code works on a desktop PC, but not the Pi,  I would guess that the shaders are just not supported on the Raspberry Pi.

**Comment by balajisriram** [comment]
Thanks for the reply. IS there a sense of why it segfaults instead of errors out of the program? ALso, there is a check if the shader exists which clearly succeeds before failing to link for that shader.

**Comment by benmoran56** [comment]
Hi @balajisriram sorry for the delay. 

A segfault like this is likely something outside of Python, such as in one of the video driver modules. Unfortunately this type of thing is a little more difficult to troubleshoot than a nice Python traceback. 

What I would try to do, if possible, is to see if you can isolate the exact shader code that "program 55" uses. If you can find that, you can try to compile it just by itself (maybe easier using the current master branch of pyglet, which has built-in shader support). What would be good to see if it is indeed a video driver issue, or not.

**Comment by flowerbug** [comment]
adding this to my bash shell environment before running the program really helped me get a much better traceback than what was happening by default:

> PYTHONFAULTHANDLER=1 && export PYTHONFAULTHANDLER

**Comment by benmoran56** [comment]
Closing this now due it's age and lack conversation, but please follow up with a new ticket if needed.
