### ISSUE TITLE
Can't run pyglet loop in a separate process: "XIO:  fatal IO error 0 (Success) on X server ":0.0""

### ISSUE THREAD

**Issue by 3demax** [pyglet/pyglet#151]
I'm trying to run pyglet event loop in a separate process, and it mostly works (input events, scheduled events), however nothing is displayed and python exits with code 1
Program output is the following:
```
starting pyglet
pyglet started
PygletProcess started
update
draw
update
draw
PygletProcess stopped
XIO:  fatal IO error 0 (Success) on X server ":0.0"
      after 166 requests (166 known processed) with 11 events remaining.
```

The program in question:
```
from multiprocessing import Process

import pyglet


class PygletProcess(Process):
    def __init__(self):
        super(PygletProcess, self).__init__()
        self.event_loop = pyglet.app.EventLoop()

        self.window = pyglet.window.Window(fullscreen=True)
        self.window.set_caption('test')

        label2 = pyglet.text.Label(text='hello',
                                   x=0, y=0)

        @self.event_loop.event
        def on_window_close_loop(win):
            self.event_loop.exit()
            return pyglet.event.EVENT_HANDLED

        @self.window.event
        def on_window_close(win):
            self.event_loop.exit()
            return pyglet.event.EVENT_HANDLED

        @self.window.event
        def on_key_press(symbol, modifiers):
            if symbol == pyglet.window.key.ESCAPE:
                self.event_loop.exit()

        @self.window.event
        def on_draw():
            print('draw')
            pyglet.gl.glClearColor(0.92, 0.78, 0.60, 1)
            self.window.clear()
            label2.draw()

        def update(dt):
            print('update')

        interval = 1
        self.event_loop.clock.schedule_interval(update, interval)

    def run(self):
        print('PygletProcess started')
        self.event_loop.run()
        print('PygletProcess stopped')


if __name__ == "__main__":
    print('starting pyglet')
    pyg = PygletProcess()
    pyg.start()
    print('pyglet started')
```

If __main__ section is changed to call `pyg.run()` instead, everything works as expected, because it runs in single-process mode.

Versions tested:
```
Python 3.8.1
pyglet==1.5.0
pyglet==1.4.9
$ xdpyinfo | grep version
version number:    11.0
X.Org version: 1.20.7
```

Is this a bug or multiprocessing is not supported? 
How do I debug this further?

**Comment by benmoran56** [comment]
multiprocessing is known to work, but it's not specifically supported. 
The biggest issue you might face is that Window and OpenGL resources won't work correctly across processes. What you can try to do is move the pyglet import into your other process, such as the top of the run method.

**Comment by 3demax** [comment]
Thanks @benmoran56, that has helped on Linux too.
Though, I'm surprised that openGL resources get acquired on module import. Wouldn't it be more straightforward to acquire them upon creating a window instead?

**Comment by benmoran56** [comment]
pyglet creates a background OpenGL context (and invisible "Shadow Window") to allow loading resources (images/textures) before creating your Window. You can disable this behavior by setting the following option immediately after import: 
```pyglet.options['shadow_window'] = False```
That might also work for this case.

**Comment by benmoran56** [comment]
@3demax If you are able to find a solution, could we close the ticket?

**Comment by 3demax** [comment]
Oh, for sure! 
Thanks again for the help!
