### ISSUE TITLE
pyglet.sprite.Sprite Cannot Pause Animation

### ISSUE THREAD

**Issue by nbroderick-code** [pyglet/pyglet#152]
Pyglet lacks a feature and there is an easy fix, but I don't understand GitHub, so I am posting my solution here.

**### PROBLEM**
Pyglet has animated sprites, but cannot control playback of the animation.

Other users have noticed this issue. See [Link 1](https://swiftcoder.wordpress.com/2009/04/17/enhanced-animation-code-for-pyglet/) and [Link 2](https://github.com/tuomasj/pyglet-animatedsprite/blob/master/animatedsprite.py)

...but, I think their solution is not optimal.

**### SOLUTION**
See below. It is very simple. Maybe you can think of a better one.

```
import pyglet


class AnimatedSprite(pyglet.sprite.Sprite):
    """Sprite subclass providing pause & play control"""

    def __init__(self,
                         img, x=0, y=0,
                         blend_src=pyglet.gl.GL_SRC_ALPHA,
                         blend_dest=pyglet.gl.GL_ONE_MINUS_SRC_ALPHA,
                         batch=None,
                         group=None,
                         usage='dynamic'):
        pyglet.sprite.Sprite.__init__(self, img, x, y, blend_src, blend_dest,
                                      batch, group, usage)

        self._paused = False
        self.clock = pyglet.clock.get_default()
        self.dt = self.clock.tick()

    def _animate(self, dt):
        """
        overrides built-in function.
        Simply adds a check to see if this sprite is paused
        before executing the regular _animate code.
        creating a subclass necessitated a new pyglet clock because
        the clock used in the built-in code is not owned by the object.
        """
        if not self._paused:
            self._frame_index += 1
        if self._frame_index >= len(self._animation.frames):
            self._frame_index = 0
            self.dispatch_event('on_animation_end')
            if self._vertex_list is None:
                return  # Deleted in event handler.

        frame = self._animation.frames[self._frame_index]
        self._set_texture(frame.image.get_texture())

        if frame.duration is not None:
            duration = frame.duration - (self._next_dt - dt)
            duration = min(max(0, duration), frame.duration)
            self.clock.schedule_once(self._animate, duration)
            self._next_dt = duration
        else:
            self.dispatch_event('on_animation_end')

    def pause(self):
        """pause animation playback"""
        self._paused = True

    def play(self):
        """resume animation playback"""
        self._paused = False

```

**### USE CASE**
I have a small program, a slot machine game. It needs to play an animation every time the player wins. I made a short looping animation and saved it to a .png image sequence.
I want to use a single sprite, play the animation when the player wins, pause the animation once it's ended, and then play the animation again when we win again.

See below for a pseudo code use case.
```

ANIMATION = image.Animation.from_image_sequence(frames, period=1/30, loop=True)

SPRITE = AnimatedSprite(img=ANIMATION)
SPRITE.pause()

@SPRITE.event
def on_animation_end():
    SPRITE.pause()

def win():
    SPRITE.play()

@window.event
def on_key_press(symbol, modifiers):
    win()

@window.event
def on_draw():
    SPRITE.draw()
```

**Comment by nbroderick-code** [comment]
Also...if anyone is reading this, the docs for `image.Animation.from_image_sequence` show that `duration` is an argument. This is wrong. The argument is `period`.

https://pyglet.readthedocs.io/en/latest/modules/image/animation.html

**Comment by benmoran56** [comment]
Hi, thanks for opening the ticket. 

I wonder if the same thing could be accomplished by using the clock schedule/unschedule calls?
If so it could avoid the `if not self._paused` calls. 

And thanks for pointing out the discrepancy in the docs. That should be fixed.

**Comment by nbroderick-code** [comment]
Another possible solution:
Expand `pyglet.media.Player`. Allow it to accept an ` Animation`  or `Sprite` object as a source.

It already has good functions for playback control. Why not enable it to control pyglet animations?

https://pyglet.readthedocs.io/en/latest/modules/media.html

**Comment by nbroderick-code** [comment]
After much consideration, I think the animation class in pyglet should be removed.
Sprites should not be capable of having animations. Instead, an AnimatedSprite class should be created like below.

for someone trying to play a png sequence of images, the following class makes much more sense

```
from pyglet import sprite, clock, image
from os import listdir
from os.path import isfile, join
import natsort


class PngSeqPlayer:

    def __init__(self, window, fps=30, end="loop"):
        self.window = window
        self.folder = ""
        self.files = []
        self.image = image.ColorBufferImage(0, 0, 2, 2)  # blank, default image
        self.frame_index = 0
        self.playback_speed = 1
        self.fps = fps
        self._end_functions = {"loop": self._loop, "freeze": self._freeze,
                               "ping pong": self._ping_pong}
        self.end_function = self._end_functions[end]
        self.clock = clock.get_default()
        self.dt = self.clock.tick()
        self.sprite = sprite.Sprite(img=self.image)

    def open(self, folder):
        self.folder = folder
        self.files = self._get_files(folder)
        self._load_and_show(0)
        print(f'Resolution: {self.image.width} X {self.image.height}')
        self.window.set_size(self.image.width, self.image.height)
        self.play()

    def _get_files(self, path):
        """
        """
        onlyfiles = [f for f in listdir(path) if isfile(join(path, f))]
        onlyfiles = natsort.natsorted(onlyfiles)
        if not onlyfiles:
            raise Exception(f'No files found in {path}')
        else:
            print(f'Found {len(onlyfiles)} files.')
        return onlyfiles

    def _load_and_show(self, frame_index):
        file = self.files[frame_index]
        self.image = image.load(f'{self.folder}\\{file}')
        self.sprite.image = self.image

    def _animate(self, dt):
        """dt is a mandatory argument for all schedule-able functions."""
        self.frame_index += self.playback_speed
        if self.frame_index not in range(0, len(self.files)):
            self.end_function()
            return
        self._load_and_show(self.frame_index)

    def _loop(self):
        self.frame_index = 0

    def _ping_pong(self):
        self.playback_speed *= -1

    def _freeze(self):
        self.pause()

    def set_end_behaviour(self, end):
        self.end_function = self._end_functions[end]

    def play(self):
        self.clock.schedule_interval(self._animate, 1 / self.fps)

    def pause(self):
        self.clock.unschedule(self._animate)

    def toggle(self):
        if self.clock._current_interval_item:
            self.pause()
        else:
            self.play()

    def jump_to(self, frame):
        self.frame_index = frame % len(self.files)
    
    def set_playback_speed(self, speed):
        self.playback_speed = speed

    def draw(self):
        self.sprite.draw()
```

Use Case
Just point to a folder and go. Plug and play.

```
psp = PngSeqPlayer(window, fps=30, end="loop")
psp.open("D:\\2020\\pngSeqPlayer\\resources\\frame_numbers")
```

**Comment by benmoran56** [comment]
Why not just adding the pause/resume methods to the Sprite class? A simple subclass like this would work: 

```
class PausableSprite(pyglet.sprite.Sprite):

    _paused = False

    def pause_animation(self):
        if self._paused or not hasattr(self, '_animation'):
            return
        pyglet.clock.unschedule(self._animate)
        self._paused = True

    def resume_animation(self):
        if not self._paused or not hasattr(self, '_animation'):
            return
        frame = self._animation.frames[self._frame_index]
        self._texture = frame.image.get_texture()
        self._next_dt = frame.duration
        if self._next_dt:
            pyglet.clock.schedule_once(self._animate, self._next_dt)
        self._paused = False
```

Having a Sprite class that directly loads resources for frames would be outside of the scope for the default class, since it bypasses the abstractions for resource loading. It's a good thing to make a custom loader function for though. The ```Animation.from_image_sequence(images, duration=0.1, loop=True)``` classmethod is good for that use case.

**Comment by nbroderick-code** [comment]
### If implemented in the default class, your `pause_animation` and `resume_animation` methods would solve my original issue.

### However, I think there is a larger user experience issue with how pyglet implements animation.

I'm a hobbyist coder, but a professional animator, so please lend me your patience as I list my user experience issues: 

1. There was no way to pause the animation
2. There was no way to decide the end behavior of the animation. What happens after it reaches the last frame? Common options are: loop, ping pong, and freeze.
3. There was no way to jump to a specific frame
4. `Animation.from_image_sequence` doesn't seem memory efficient to me. 

> It requires that all frames be loaded into memory as image objects before they are transformed into an animation. Won't this tie the hands of people who are trying to use many many animated image sequences to make a game? Wouldn't a more memory efficient approach be to only load the frame that is needed when it is needed?

5. Lastly, `Animation.from_image_sequence` doesn't do what a user would expect it to do. 

> Below is what I was naively expecting it to do when I first used it. I think it might be worth baking some version of it into the default class because how else is the user supposed to interact with the `Animation.from_image_sequence` method? The user will always end up making some version of the below code when using that method. Right?

```
from pyglet import sprite, resource, image
from os import listdir
from os.path import isfile, join, splitext
import natsort

def create_animation(self, path, fps=30):
        resource.path = [path]
        resource.reindex()
        onlyfiles = [f for f in listdir(path) if isfile(join(path, f))]
        onlyfiles = natsort.natsorted(onlyfiles)
        print(f'Found {len(onlyfiles)} files.')

        frames = []
        for frame in onlyfiles:
            frames.append(resource.image(frame))
            print(f'loaded  {frame}')
        animation = image.Animation.from_image_sequence(frames, period=1 / fps,
                                                        loop=True)
        print("animation loaded")
        return animation

animation = create_animation("some//folder//path")
sprite = sprite.Sprite(img=animation)

```

Thanks for listening and taking me seriously. Just trying to add my two cents to the community.

**Comment by benmoran56** [comment]
No worries! 

Maybe to put it in perspective, pyglet has always tended to keep things simplistic where possible and let users build on top of that. To that point, the animation capabilities are "just enough" for typical 2D games or applications.  The reason we need to keep the Sprite class lean is that many games will often have hundreds or thousands of Sprite instances on screen, so it's important that the default class stay as lightweight as we can keep it.  A custom class like you've illustrated above is a good solution for something that's a little more flexible, but I don't think it would make sense to replace the current Sprite class.  A more robust subclass might be a good idea to add to the repository under /contrib, or potentially even alongside the existing Sprite class. 

1. Noted! 
2. This is intentionally left to the user, but a Sprite subclass could easily set a default method to handle some common behaviors. I'll post a code snippet below with an example. 
3. I'll show how to do this in the below code snippet. 
4. It's actually quite efficient, *if* you are using the `resource` module (which you are). With OpenGL based applications, it's ideal to load the resources beforehand as opposed to on-demand. This is because the images need to be transferred to the GPU, which is best done during startup or some loading scene due to overhead. Once on the GPU, rendering is done efficiently. 
5. It's left up to the user to load their images. One thing to note is that the `resource` module does not need the full path name. Just the file name is fine, as long as you don't have conflicting names within your folders. In that case the relative path + filename is better.  It might be better to separate the logic into two methods. In any case, a helper method like you've made is an OK solution. 

```
class AnimationPlayer(pyglet.sprite.Sprite):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._paused = False

    def pause_animation(self):
        if self._paused or not hasattr(self, '_animation'):
            return
        pyglet.clock.unschedule(self._animate)
        self._paused = True

    def resume_animation(self):
        if not self._paused or not hasattr(self, '_animation'):
            return
        frame = self._animation.frames[self._frame_index]
        self._texture = frame.image.get_texture()
        self._next_dt = frame.duration
        if self._next_dt:
            pyglet.clock.schedule_once(self._animate, self._next_dt)
        self._paused = False

    @property
    def frame_index(self):
        return self._frame_index

    @frame_index.setter
    def frame_index(self, index):
        # Bound to available number of frames
        self._frame_index = max(0, min(index, len(self._animation.frames)-1))

    def on_animation_end(self):
        print("Animation Ended!")
        # Do some predefined action
```

**Comment by nbroderick-code** [comment]
Very interesting bit of programming philosophy! Thanks for hearing me out and explaining the gaps in my knowledge.

I love pyglet so much! Thanks for helping to make it. 👍

**Comment by benmoran56** [comment]
No worries, and I'm glad it's useful! 

If you happen to use Discord, the pyglet Discord server is a good place to ask for ideas and get help from other users. There is also the pyglet mailing list.

**Comment by nbroderick-code** [comment]
I'm going to close this issue as I've opened a new one on a different topic and don't want to be an attention hog.

Additionally, I feel like this has reached its conclusion.
