### ISSUE TITLE
Entire viewport placed in left bottom quarter of window

### ISSUE THREAD

**Issue by vibrant** [pyglet/pyglet#154]
There is some bug on MacOS Catalina where if I initiate a window sized 300 x 300, place the sprite at 300 x 300 - then I get what's seen in the attachment - a window that's 600 x 600 and the sprite is in it's center with only a quarter of it visible.

Any idea how to fix it?

I'm on:
cocos2d==0.6.8
pyglet==1.5.0

Sample code:
cocos.director.director.init(width=300, height=300)

And then a layer with:
cocos.sprite.Sprite(pyglet.resource.animation('player.gif', rotate=-90))
sprite.position = 300, 300
self.add(sprite, z=1)

<img width="303" alt="Screenshot 2020-03-01 at 18 30 35" src="https://user-images.githubusercontent.com/323183/75630434-0eaecb80-5beb-11ea-9070-f40142821caf.png">

**Comment by einarf** [comment]
I'm guessing the viewport is set using values from `window.get_size()` instead of `window.get_framebuffer_size()`.

**Comment by vibrant** [comment]
I just moved to plain pyglet from cocos, and no issues.  Thanks for your reply, closing this since it seems to be a cocos issue.
