### ISSUE TITLE
Convert an ImageData to a numpy array

### ISSUE THREAD

**Issue by bohanyang** [pyglet/pyglet#155]
Hi I'd like to first thank you for developing pyglet. It is an awesome library! 

My question is the same as a stackoverflow question, but no one answers that question. This is why I am posting this question here.  I apologize if this is an inappropriate question on Github. Below is the link. (https://stackoverflow.com/questions/55742197/how-to-change-a-pyglet-image-into-a-numpy-array)

I'd like to take a screenshot and change it to a numpy array while running a game. I used pyglet.image.get_buffer_manager().get_color_buffer().get_image_data(), which returns an ImageData. Get_data() returns a pyglet.image.c_ubyte_Array.   If you don't mind, I'd like to ask how to convert an ImageData object or c_ubyte_Array to a numpy array? 

Thank you,
Bohan Yang

**Comment by agricolab** [comment]
Is anything wrong with the following approach?
``` python
import pyglet
import numpy as np
ibar = pyglet.image.get_buffer_manager().get_color_buffer().get_image_data()
np.asanyarray(ibar.get_data())
```

**Comment by bohanyang** [comment]
Hi Agricolab, thank you I appreciate your help. Problem solved!
