### ISSUE TITLE
pyglet openal player not loop

### ISSUE THREAD

**Issue by Fredkiss3** [pyglet/pyglet#162]
I’m trying to loop sound in pyglet. It does work when my driver is `pulse`, but when switching to `openAL` (the default driver), the sound plays only once.
This is my code :

```python
import pyglet
from pyglet import media

# Uncomment this code to see the difference 
# pyglet.options['audio'] = ('pulse', 'openal', 'directsound', 'silent')

music = pyglet.resource.media('test.wav', streaming=True)
player = pyglet.media.Player()

# Loop & play music
player.loop = True
player.queue(music)
player.play()

if name == "__main__":
    pyglet.app.run()
```

My system : `ubuntu 18.10`
pyglet version : `1.5.0`

**Comment by benmoran56** [comment]
Hi Fred, 

You will need a running event loop (`pyglet.app.run`) in order for the audio buffers to be refilled, and events to be fired. The PulseAudio backed is callback based so it still might play, but it's not recommended due to bugs.

**Comment by Fredkiss3** [comment]
> Hi Fred,
> 
> You will need a running event loop (`pyglet.app.run`) in order for the audio buffers to be refilled, and events to be fired. The PulseAudio backed is callback based so it still might play, but it's not recommended due to bugs.

Sorry, i removed the part of code where event loop is because i thinks it was not , in but i didn't forget it (i edited my code to see it).

The bug comes when i use the default driver. But if i change the driver to `pulse`, the sound loop, so i don't understand why with `openAL` the sound does not loop... :cry:

**Comment by benmoran56** [comment]
Oh I'm sorry, I misread your post as well. 

Actually, there was a bug with OpenAL and events. This should be fixed in the 1.5-maintenance branch, and will be in the next point release.

**Comment by Fredkiss3** [comment]
Thanks ! I'm waiting for it ! :grin:

**Comment by Fredkiss3** [comment]
Sorry to ask this again but how do i install the pylget 1.5-maintenance version ?

**Comment by Fredkiss3** [comment]
> Sorry to ask this again but how do i install the pylget 1.5-maintenance version ?

I did figured it out.

I have downloaded and installed the `pylget-1.5-maintenance` version but it behaves the same.

**Comment by benmoran56** [comment]
Give this a try to install directly from github: 
```
pip install --upgrade --user git+https://github.com/pyglet/pyglet@pyglet-1.5-maintenance
```
You can check `pyglet.version` to make sure you have the latest code. It should be `1.5.1` for the currently unreleased version.

**Comment by benmoran56** [comment]
I'm going to close this since it's fixed in the latest releases. If you still have questions or issue, please reopen this issue, or create a new one. Thanks!
