### ISSUE TITLE
Disconnecting controller crashes pyglet

### ISSUE THREAD

**Issue by ChrisLR** [pyglet/pyglet#163]
After successfully using a Joystick (Xbox Controller 360) a crash occurs if that controller is disconnected.
Here is the relevant traceback
  File ",,,\pyglet\app\__init__.py", line 107, in run
    event_loop.run()
  File ",,,\pyglet\app\base.py", line 170, in run
    self._run()
  File ",,,\pyglet\app\base.py", line 183, in _run
    platform_event_loop.step(timeout)
  File ",,,\pyglet\app\win32.py", line 120, in step
    func()
  File ",,,\pyglet\input\directinput.py", line 191, in _dispatch_events
    0)
  File ",,,\pyglet\com.py", line 138, in _call
    ret = self.method.get_field()(self.i, self.name)(obj, *args)
  File "_ctypes/callproc.c", line 933, in GetResult
OSError: [WinError -2147024866] The system cannot read from the specified device

On Windows 10
Can reproduce manually.

Maybe we could add a try catch near directinput.py  line 187 around
self._device.GetDeviceData(ctypes.sizeof(dinput.DIDEVICEOBJECTDATA),
                                   ctypes.cast(ctypes.pointer(events),
                                               dinput.LPDIDEVICEOBJECTDATA),
                                   ctypes.byref(n_events),
                                   0)

**Comment by benmoran56** [comment]
Thanks for opening the ticket, Chris. I'll have a look at this soon.

**Comment by benmoran56** [comment]
That did the trick. I confirmed it's preventing the crash on my Windows VM. The fix is in the pyglet-1.5-maintenance branch, and will be in the next point release (which should be very soon).

Perhaps adding an `on_disconnect` event to the Device class would be a good idea, so that these things could be handled by users.

**Comment by benmoran56** [comment]
This fix is in the latest point release. Let me know if you still have any issues!
