### ISSUE TITLE
debug_gl_trace doesn't display GL 3+ function names

### ISSUE THREAD

**Issue by G-glop** [pyglet/pyglet#168]
Windows 10, python 3.8.2, latest master:
```
import pyglet
pyglet.options['debug_gl_trace']=True
import pyglet.gl
```
Output is wall of `<WinFunctionType object...>` (all calls to `glGetStringi`), with a few properly named functions at the top - like the older `glGetString`. Seems like the newer GL functions are not being decorated properly.

**Comment by einarf** [comment]
@benmoran56 Is this related to the new `gl` and `gl_compat` module I am supposed to generate?

**Comment by benmoran56** [comment]
Sorry for the slow reply! 

I'll try to have a look at this sometime soon, after finishing up a few things for the 1.5 branch.

**Comment by benmoran56** [comment]
Sorry for leaving this issue hanging for such a long time. This should be working as expected now, so i'm going to close the ticket. 
If you still see any issues on your end, please follow up!
