### ISSUE TITLE
Apple persistence problem

### ISSUE THREAD

**Issue by retrosnob** [pyglet/pyglet#182]
Animated gif: https://drive.google.com/file/d/18k7h_xIlaBtjK3eYxx5LZipiKXDS6ETZ/view?usp=sharing

**Comment by benmoran56** [comment]
Thanks for opening the ticket. The persistent state warning is not pyglet specific, but appears to happen with other libraries that open a window as well. We have an existing ticket open with a potential: #6 
Also please have a look at the last post in a similar issue for the Matplotlib library: https://github.com/matplotlib/matplotlib/issues/6242
Setting the override, then deleting the key seems to indicate that it's a result of some leftover cruft from a previous Python install. Give those two commands a try, and see if that gets rid of the warning for you. 

As for the recursion error on exit, this is a known issue. Unfortunately none of the current contributors can duplicate it. It seems to affect newer Macs only.  The open issue can be found at: #5 
I might be able to get access to a newer Mac in the near future and take a look at this myself.

**Comment by retrosnob** [comment]
Thanks! I will give it a try. BTW is there a forum where we can discuss Pyglet? I'm teaching with it.

**Comment by benmoran56** [comment]
We have a Discord server at: https://discord.gg/QXyegWe which is fairly active. 
There is also a mailing list which is not quite as active these days: http://groups.google.com/group/pyglet-users

**Comment by retrosnob** [comment]
Thank you.
