### ISSUE TITLE
Pyglet modifies Python standard library inspect module

### ISSUE THREAD

**Issue by visatish** [pyglet/pyglet#184]
It seems that certain versions of Pyglet (< 1.5.0, not sure where it ends) modify the `inspect` module of the Python standard library [here](https://github.com/pyglet/pyglet/blob/v1.4.10/pyglet/event.py#L167), adding a handle to `getfullargspec` to enforce Python 2 backwards compatibility. This is dangerous as certain other libraries (i.e. Tensorflow 1.15.0 [here](https://github.com/tensorflow/tensorflow/blob/v1.15.0/tensorflow/python/util/tf_inspect.py#L52)) rely on the absence of this function for their own backwards compatibility.

It would be nice if this could be handled in a less-intrusive manner. I'm not sure if there's an easy way to do so, as it seems that other libraries are just writing their own custom fallbacks. At the very least a warning should be added.

**Comment by benmoran56** [comment]
Hi, thanks for opening the ticket. This was indeed removed in 1.5+ since Python 2 support was dropped. Updating to pyglet 1.5.x would be of course recommended. Is there any specific platform that is still stuck on Python2 and that this is causing an issue for? If so I could have a look at dusting off the 1.4 branch and pushing out a small update.

**Comment by visatish** [comment]
Hi,

Hmm not exactly, it's really just some legacy research code that is still running on Python 2 and needs to be updated. If a fix is easy, it would be much appreciated. Otherwise we can patch it locally.

**Comment by benmoran56** [comment]
That's a good reason, and this is an easy fix, so I pushed out a 1.4.11 release. 
If you could give that a try, that would be great.

**Comment by visatish** [comment]
Yes, it works great now! Thanks and keep up the great work!
