### ISSUE TITLE
pls add

### ISSUE THREAD

**Issue by twistcharlie** [pyglet/pyglet#187]
please add a collision detection 
idk how the heck you add it but please add it

**Comment by twistcharlie** [comment]
ooh it says it on discord

**Comment by DoAltPlusF4** [comment]
...

**Comment by DoAltPlusF4** [comment]
Please be a little more specific, do you want collision detection, collision resolution, or just a full physics engine? Do you want it to be realistic? If so you should try Pymunk. Do you want SAT detection or AABB and do you want swept detection or not?

**Comment by DoAltPlusF4** [comment]
Also for issues on GitHub please try and summerise your problem in the title. "pls add" is not very helpful.

**Comment by twistcharlie** [comment]
I try and add mystery to my titles also  idk what type off collision maybe AABB or just shape ones like square, circle, and ect shapes

**Comment by twistcharlie** [comment]
also object collision is the type i want u guys to add (well by object i mean like sprites i think)

**Comment by DoAltPlusF4** [comment]
Id recommend that you research collision detection and resolution yourself as you clearly don't understand it. 
Don't expect others to do all the work for you via spoon-feeding and unnecessary updates.

**Comment by twistcharlie** [comment]
well I've done a lot of research and don't know how I asked for help and well I don't understand(i asked help on another discord server as well still didn't understand) so when u say research I HAVE DONE IT AND FAILED SO this was my last idea also this is necessary (well to me it is )

**Comment by twistcharlie** [comment]
also dont know what u me by spoon-feeding

**Comment by DoAltPlusF4** [comment]
> also dont know what u mean
by spoon-feeding
Instead of figuring it out yourself, you are asking us to make the code and "spoon-feed" it to you, This results in you not really learning very much compared to if you tried to do it yourself.

**Comment by twistcharlie** [comment]
ooh and I only ask after I do a lot of research and tried some ideas and if I do get given code then I try and make sense of it and if I don't then I don't use it also I only ask after me trying (for 1, 2 or 1 and half days and after research)

**Comment by DoAltPlusF4** [comment]
Just a tip, send us the code that doesn't work, and then ask how to fix it. Don't just ask for a bunch of code. This helps *you* learn how to improve in future, and it helps us by understanding your problem better.

**Comment by twistcharlie** [comment]
hmm(i do sometimes if I think there's a way to fix (i think)) okay then ill give the little code that i deleted

**Comment by twistcharlie** [comment]
#solid block
    if player.player_X == block1.block1_X + 40:
        player.player_X += player.player_speed


that's the code and the problem is I need to set the Y part size of the block so it won't have problems and yes ik this is only for 1 side

**Comment by benmoran56** [comment]
Thanks for opening the ticket.  Unfortunately, built-in physics/collision resolution is outside of the scope of the pyglet project. Simple AABB collision detection can be done fairly easily if you follow a tutorial. Or you may want to look at one of the libraries available that you could use, such as::
https://github.com/viblo/pymunk
or
https://github.com/solidsmokesoftware/pecrs-py
