### ISSUE TITLE
GL context issue for multiple display

### ISSUE THREAD

**Issue by shashikg** [pyglet/pyglet#188]
Why the default setting is such that it always uses the `gl.current_context` while creating a new window. This creates an issue when you don't provide any context while creating a window for another display.

https://github.com/pyglet/pyglet/blob/237235a298332bf46217edf823d44bf98fcf7eb8/pyglet/window/__init__.py#L586-L587

If there isn't any specific reason should I create a PR that changes it? i.e. creates a new context in default case independent of `gl.current_context`

**Comment by benmoran56** [comment]
Thanks for opening the ticket. 

It is not reusing the same context - it's being referenced for OpenGL object sharing. 
Does that answer your question? If not, are you having some sort of issue?

**Comment by shashikg** [comment]
Yes, so when I was trying to create a new window for another display it throws an error saying can not create GL Context. But when you send a context while creating a new window using `config.create_context(None)`. You don't get an issue. Even when you explicitly change the context referenced by `pyglet.gl.current_context` to the new context, then also the issue get resolved.

**Comment by shashikg** [comment]
I created a colab file demonstrating the issue (using virtual display):
https://colab.research.google.com/drive/1-3VuCaWNbFagYQvUOPHNEJMo9ErRxR_0

**Comment by benmoran56** [comment]
Ah, colab. I believe that platform has some limitations with OpenGL contexts. This is not specifically pyglet related, so it might not make sense to change the default behavior in pyglet. Instead, manually creating and passing contexts to the Window (as you've done) may be necessary for right now.  Also, thank you for creating the link. I'll have a look, and see if there is something we could do to fallback smoothly.

**Comment by shashikg** [comment]
@benmoran56 as I said before the colab file was just to demonstrate the issue. you will get the same issue even if you run it on your machine. I am attaching the output of my terminal for your ref:

```
1
1
Traceback (most recent call last):
  File "pyglet_gl_context_issue.py", line 48, in <module>
    win = pyglet.window.Window(width=600, height=400, display=pyglet_display_2)
  File "/home/shashi/anaconda3/envs/tf-easyRL/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py", line 165, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/shashi/anaconda3/envs/tf-easyRL/lib/python3.7/site-packages/pyglet/window/__init__.py", line 591, in __init__
    context = config.create_context(gl.current_context)
  File "/home/shashi/anaconda3/envs/tf-easyRL/lib/python3.7/site-packages/pyglet/gl/xlib.py", line 204, in create_context
    return XlibContextARB(self, share)
  File "/home/shashi/anaconda3/envs/tf-easyRL/lib/python3.7/site-packages/pyglet/gl/xlib.py", line 314, in __init__
    super(XlibContext13, self).__init__(config, share)
  File "/home/shashi/anaconda3/envs/tf-easyRL/lib/python3.7/site-packages/pyglet/gl/xlib.py", line 218, in __init__
    raise gl.ContextException('Could not create GL context')
pyglet.gl.ContextException: Could not create GL context
```

**Comment by benmoran56** [comment]
Can you post an example that will show the crash, using only pyglet? (No external libraries)
