### ISSUE TITLE
Add a new method to the `text.Label` class for creating a texture from the label. 

### ISSUE THREAD

**Issue by benmoran56** [pyglet/pyglet#19]
A useful feature to have would be to create a texture from a `text.Label`. Users could create a Sprite out of these textures, and easily scale/rotate them. 

The Label class seems most appropriate for this, as it's aimed at simple lines of text.

**Comment by zipandrar** [comment]
text to png to texture

from PIL import Image, ImageDraw, ImageFont, ImageFilter
width = 600
height = 100
image = Image.new('RGBA', (width, height), (255, 255, 255,0))
font = ImageFont.truetype('font.ttf', 100)
draw = ImageDraw.Draw(image)
draw.text((10, 10), u'text123', font=font, fill=color())
# blur
#image = image.filter(ImageFilter.BLUR)
image.save('code.png', 'png')

png then to the texture???

or can you get texture from the "image" directly with save it to png????

**Comment by zipandrar** [comment]
pil image is color    600x100 tuple
>>> c[600]
(255, 255, 255, 0)

pyglet 's loaded image color is about  600x100x4 string
>>> p.data[0:10]
'\xff\xff\xff\x00\xff\xff\xff\x00\xff\xff'

**Comment by benmoran56** [comment]
Decided to close this for now.
