### ISSUE TITLE
EventLoop hooks issue - window can't be close

### ISSUE THREAD

**Issue by redepass** [pyglet/pyglet#190]
Hello, while trying example code from documentation about eventLoop hooks, the close button of my window doesn't react and the window doesn't close. Code:

`import pyglet

event_loop = pyglet.app.EventLoop()

@event_loop.event
def on_enter():
    print("entering loop") #this is printed

@event_loop.event
def on_window_close(window):
    print("window is closed") 
window = pyglet.window.Window()
event_loop.run() #my window doesn't close when hitting "esc or clicking on the window close button
#pyglet.app.run() #if instead of the following line I use the normal pyglet.app.run(), the window can be closed but none of the print statement are executed.
` 

Maybe I didn't understand something correctly?
Except for that issue, Pyglet is great, thank you for it!
Pyglet version 1.5.4 on OS X (same under Linux)

**Comment by redepass** [comment]
I also tried this (replacing the event_loop.run() statement) but same behaviour as simply pyglet.app.run():
`
pyglet.app.eventLoop = event_loop
pyglet.app.run()`

**Comment by redepass** [comment]
from the doc (just added the import statement and created a window):
`import pyglet

window = pyglet.window.Window()
event_loop = pyglet.app.EventLoop()

@event_loop.event
def on_window_close(window):
    event_loop.exit()
    return pyglet.event.EVENT_HANDLED
window = pyglet.window.Window()
event_loop.run()`

the window is also not closable here

**Comment by Gabaa** [comment]
I get the same thing when I run your code.

In your second comment, you wrote:
`pyglet.app.eventLoop = event_loop`
which doesn't work, since the event loop in `pyglet.app` is called `event_loop`.

So try `pyglet.app.event_loop = event_loop` before either `pyglet.app.run()` or `event_loop.run()`, both should work.

**Comment by redepass** [comment]
Thank you for you answer, it works!
I then close the issue.

It is worth noting that the doc could be clearer on the subject because as is, the presented code doesn't work as explained.
