### ISSUE TITLE
docs error

### ISSUE THREAD

**Issue by spewil** [pyglet/pyglet#201]
hi, 

loving pyglet so far-- i especially want to emphasize the usefulness of an OpenGL wrapper that let's you choose how much control you'd like over, say, a main application loop (w.r.t. timing, etc). This is a really nice balance between abstraction and control, something I found difficult to achieve with pygame and vispy, to name a few, which allows one to embed pyglet very easily into a larger app. 

anywho-- slight error in the docs with this line:

```python
platform = pyglet.window.get_platform()
```
seen [here](https://pyglet.readthedocs.io/en/latest/programming_guide/context.html?highlight=context#simple-context-configuration) which throws a `NotImplemented` 

i opted for 

```python
pyglet.canvas.get_display()
```

**Comment by benmoran56** [comment]
Thanks for opening the ticket. I think I updated this recently, but it might not have made it to readthedocs. I'll have a look at that.

**Comment by benmoran56** [comment]
This is updated now on ReadTheDocs. You might have to refresh your browser to see the change. 

Thanks for opening the ticket, and for your kind words. I'm glad you're enjoying pyglet!
