### ISSUE TITLE
multiple windows on osx 

### ISSUE THREAD

**Issue by spewil** [pyglet/pyglet#203]
Hi there, 

trying to understand why I'm getting this error

```python
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 237, in 'calling callback function'
  File "/Users/spencerw/miniconda3/envs/bmi38/lib/python3.8/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1120, in objc_method
    args = convert_method_arguments(encoding, args)
  File "/Users/spencerw/miniconda3/envs/bmi38/lib/python3.8/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1000, in convert_method_arguments
    new_args.append(ObjCInstance(a))
  File "/Users/spencerw/miniconda3/envs/bmi38/lib/python3.8/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 921, in __new__
    if not isinstance(object_ptr, c_void_p):
RecursionError: maximum recursion depth exceeded while calling a Python object
Segmentation fault: 11
```

running the multiple window example [here](https://github.com/pyglet/pyglet/blob/master/examples/multiple_windows.py), specifically when i try to click (firing the callback). 

also interestingly the "windows" are tabs within one window, but i think this might be my default setting on osx / cocoa 

looks like the example is pretty old-- happy to make a PR for a fix, but would be good to understand the expected multiple windowing solution. my application needs to update graphics on several windows at each render. 

thanks!

**Comment by benmoran56** [comment]
Hi,
there was a bug affecting newer Macs, which is now fixed in the `pyglet-1.5-maintenance` branch. It will be in the upcoming point release. In the mean time, give that branch a try and let us know if it fixes it for you.

**Comment by spewil** [comment]
haven't tried the branch, but turning off `Prefer tabs when opening documents` in SysPref-->Dock fixed this issue. Will try the branch and comment as well

**Comment by benmoran56** [comment]
The fix in the maintenance branch is just for the `RecursionError` not the tabs. Did you mean switching to tab had an affect on that as well?

**Comment by spewil** [comment]
switching to `Do not prefer tabs` removes the error-- seems like just an OSX/Cocoa glitch when using tabs.

**Comment by benmoran56** [comment]
Since you got this figured out, I'll close this for now. Please reopen it, or a new ticket if you're still having issues. Thanks!
