### ISSUE TITLE
Possibility of bringing back clock.set_fps_limit?

### ISSUE THREAD

**Issue by ltbd78** [pyglet/pyglet#204]
The play_human function in nes-py no longer works as clock.set_fps_limit is deprecated with the newest version of pyglet. (https://pypi.org/project/nes-py/)

**Comment by benmoran56** [comment]
Unfortunately there were some drastic internal changes, so it's not possible to add that back in. 
However, could you try just commenting out that line and see what happens? 
If the frame rate is limited at some other point it might work fine.

**Comment by t-o-n-y-p** [comment]
Modern game programming discourages FPS limits. 60 FPS is not a standard anymore.

**Comment by benmoran56** [comment]
Closing this for now, but please follow up if you need help updating your code.
