### ISSUE TITLE
The domain www.pyglet.org links to bitbucket.

### ISSUE THREAD

**Issue by siretty** [pyglet/pyglet#21]
The README.rst links to pyglet.org which redirects to the now unused bitbucket page for pyglet, that in turn links back to the github page 🔁

**Comment by benmoran56** [comment]
Hopefully we can get together a simple github-pages static site to point to instead.

**Comment by ixjlyons** [comment]
Also readthedocs is still connected to the bitbucket repo.

**Comment by benmoran56** [comment]
I have a placeholder static site up at https://pyglet.github.io. This is just a rough draft, and needs to be gone over by somebody with a decent eye for web design.

**Comment by benmoran56** [comment]
pyglet.org now links to the new website. Thanks Richard!
