### ISSUE TITLE
Unsuported controller caused IndexError when adding axis for righty for gamecontroller.

### ISSUE THREAD

**Issue by Ca7iburn** [pyglet/pyglet#212]
I had a problem with pyglet 1.5.5 where neither my PS4 controller nor a generic Gemix GP-50 USB controller would register the down or up presses. By going into the pyglet module's joystick code I could see that the on_axis does fire and normalizes the value to -1, but for some reason does not raise the event. 

After some searching I came across issue 106 (now closed) and tried the new game controller input suggested. When using the PS4 controller, everything seams to work for the most part, except for the right thumb stick that does not report being moved. As for the Gemix, the game crashed with an IndexError when trying to run add_axis(self._axis_controls[relation.index], name). 

> relation_string: a0
> relation_string: a1
> relation_string: a3
> relation_string: a4
> leftx
> 0
> [AbsoluteAxis(name=x, raw_name=ABS_X), AbsoluteAxis(name=y, raw_name=ABS_Y), AbsoluteAxis(name=z, raw_name=ABS_Z), AbsoluteAxis(name=rz, raw_name=ABS_RZ)]
> lefty
> 1
> 
> [AbsoluteAxis(name=x, raw_name=ABS_X), AbsoluteAxis(name=y, raw_name=ABS_Y), AbsoluteAxis(name=z, raw_name=ABS_Z), AbsoluteAxis(name=rz, raw_name=ABS_RZ)]
> rightx
> 3
> [AbsoluteAxis(name=x, raw_name=ABS_X), AbsoluteAxis(name=y, raw_name=ABS_Y), AbsoluteAxis(name=z, raw_name=ABS_Z), AbsoluteAxis(name=rz, raw_name=ABS_RZ)]
> righty
> 4
> [AbsoluteAxis(name=x, raw_name=ABS_X), AbsoluteAxis(name=y, raw_name=ABS_Y), AbsoluteAxis(name=z, raw_name=ABS_Z), AbsoluteAxis(name=rz, raw_name=ABS_RZ)]
> Traceback (most recent call last):
>   File "pyglet_x.py", line 130, in <module>
>     joysticks = input.get_game_controllers()
>   File ".../pyglet/input/evdev.py", line 422, in get_game_controllers
>     [_create_game_controller(device) for device in get_devices(display)]
>   File ".../pyglet/input/evdev.py", line 422, in <listcomp>
>     [_create_game_controller(device) for device in get_devices(display)]
>   File ".../pyglet/input/evdev.py", line 417, in _create_game_controller
>     return GameController(device)
>   File ".../pyglet/input/base.py", line 705, in __init__
>     add_axis(self._axis_controls[relation.index], name)
> IndexError: list index out of range

As you can see, there are 4 axis listed and the relation.index gives an index of 0,1,3 and 4, with index 4 being out of bounds.  When mapping keys in _map_pair the relation_string is used to get the index, but it does not seem to correspond with the number of axis on this controller.

After some further digging I found out that you are using Sam Lantinga's SDL_ gamecontrollerdb.h to generate your database. I fixed the issue by adding the steam key bindings to the gamecontrollerdb as per the instructions in Sam's comments. 

The underlying problem is not fixed though, an unsupported controller that is misidentified like mine could still give IndexErrors, or incorrect bindings.

**Comment by benmoran56** [comment]
Thanks for opening the ticket. I made a quick commit to `master` with a catch for invalid indices. This should prevent crashing on invalid configurations (at least for axis and buttons). 

I'll close this for now, but If you still have issues, please reopen the ticket.
