### ISSUE TITLE
maybe TextureBin.add should pass the 'border' kwarg to TextureAtlas ?

### ISSUE THREAD

**Issue by ccanepa** [pyglet/pyglet#214]
Looking at https://github.com/pyglet/pyglet/blob/752fc37eb7badd68067578f1a27a4b52c0cf66dd/pyglet/image/atlas.py#L277
in 1.5.maintenance.

looks that 
`atlas = TextureAtlas(self.texture_width, self.texture_height)`
wants to be
`atlas = TextureAtlas(self.texture_width, self.texture_height, border=self._border)`

else 'border' will be a no-op for texture bins

**Comment by benmoran56** [comment]
Lets close this one, and focus conversation in the other ticket.
