### ISSUE TITLE
maybe pyglet.resource.image should accept kwarg 'border' ?

### ISSUE THREAD

**Issue by ccanepa** [pyglet/pyglet#215]
When images with solid color in the border are mixed with images with full transparent pixels in the border the render may show interpolation artifacts in the transparent borders.

Currently theres no way to tell pyglet.image.resource to add a 1 px (0,0,0,0) guard around images.

A workaround can be to load images with solid borders as separate textures, atlas=False, but that will require more cycles to swap textures when rendering.

If  pyglet.resource.image were made to accept kwarg 'border', with the same semantic as in TextureBin the problem could be fixed without impacting performance.

The docs should also suggest where and how to use 'border'  

Demoing the problem:

Render with artifacts:
![pyglet_borders_with_artifacts](https://user-images.githubusercontent.com/362220/83264005-d9882a00-a195-11ea-9014-7e18d97aa844.png)

Correct render:
![pyglet_borders_correct](https://user-images.githubusercontent.com/362220/83264025-e3aa2880-a195-11ea-903b-0618d5c1469f.png)

script: 

```python
# file: pyglet_borders.py

import pyglet
from pyglet.sprite import Sprite

# get the image files from
# https://github.com/los-cocos/cocos/blob/master/test/grossini.png
# https://github.com/los-cocos/cocos/blob/master/test/background_image.png

img_name = 'grossini.png'
bg_name = 'background_image.png'
repeats = 500


##############################

window = pyglet.window.Window(640, 480)

img = pyglet.resource.image(img_name)
w, h = window.width, window.height
x = (w - img.width) // 2 + 26; y = (h - img.height) // 2 + 54
sps = [Sprite(img, x=x, y=y) for i in range(repeats)]
for i, e in enumerate(sps):
    e.rotation = 20 * i
    e.scale = 2.0

bg = pyglet.resource.image(bg_name)

@window.event
def on_draw():
    window.clear()
    bg.blit(0,0)
    for b in sps:
        b.draw()
    
def update(dt):
    pass

if __name__ == '__main__':
    pyglet.clock.schedule_interval(update, 1 / 30.)
    pyglet.app.run()
```

**Comment by caffeinepills** [comment]
I checked the latest version and it does include the border keyword argument to the Atlas from the resource file.
```
        try:
            texture_bin = self._texture_atlas_bins[bin_size]
        except KeyError:
            texture_bin = pyglet.image.atlas.TextureBin(border=True)
            self._texture_atlas_bins[bin_size] = texture_bin
``

https://github.com/pyglet/pyglet/blob/pyglet-1.5-maintenance/pyglet/resource.py#L536

**Comment by ccanepa** [comment]
@caffeinepills ???
maybe this was intended for the other 'border' issue?

extra info:
pyglet at commit
    commit 2608d7dfaeba79522f00222b7e533016d4b77aa4 (HEAD -> pyglet-1.5-maintenance, origin/pyglet-1.5-maintenance)
    Author: caffeinepills
    Date:   Tue May 26 20:40:52 2020 -0500
        * Fix argument that takes a pointer that prevents seeking on 32 bit. (#210)

If I edit pyglet.image.atlas as in
```
     def add(self, img):
         """Add an image to the atlas.
@@ -274,6 +277,6 @@ class TextureBin:
                 if img.width < 64 and img.height < 64:
                     self.atlases.remove(atlas)

-        atlas = TextureAtlas(self.texture_width, self.texture_height)
+        atlas = TextureAtlas(self.texture_width, self.texture_height, border=Tr
ue)
         self.atlases.append(atlas)
         return atlas.add(img)
```

the artifacts dissapear.

**Comment by caffeinepills** [comment]
Oh I see what you are saying, it doesn't actually pass the border attribute from bin to atlas.
https://github.com/pyglet/pyglet/blob/pyglet-1.5-maintenance/pyglet/image/atlas.py#L277

Seems like a bug.

I also agree there should be a border argument or setting for resource that lets you specify if you want a border or not for the atlas. Also support for a larger border (2 pixels for instance).

**Comment by benmoran56** [comment]
Thanks @ccanepa and @caffeinepills! I merged this in, so it will be in the next point release. I'll try to get that out this weekend.
