### ISSUE TITLE
about Atlases, border_size and pyglet.resource.image

### ISSUE THREAD

**Issue by ccanepa** [pyglet/pyglet#217]
per-image border size can't possibly work
 - pyglet.resource.Loader has only two TextureBin s where to add a new image
 - the current TextureBin.add implementation implicitly uses the border size provided in the TextureBin instantiation, and does not accept an explicit border_size in the add method

I think theres a design problem that predates the last PR.
I was writing a draft to mayself, and probably to coment in the PR, about what feels bad in the current design. It is late, so I will post the draft as is; it was intended to understand the problem and try to suggest a possible fix. Here we go:

# Lets review the actual code that deals with image padding
 not only the changes in the PR, all of them.

## module atlas

class Allocator: does not know about 'border'
- method alloc(width, height): the caller must do the 'border' math

class Atlas:
- receives 'border' at construction time, stored at atlas._border
- atlas.add(img): does not receive 'border' info;
	- always applies implicitly atlas._border
	 - returns a texture region

class TextureBin:
	- receives 'border' at construction time, stored at bin._border
	- bin.add(img): does not receive 'border' info
	  - if an existing atlas has space, add the image to it, which will use the atlas._border
	  - if no space, adds a new atlas, with border=bin.border
	  - returns the texture region returned by the atlas

## This tells that:
- all images in an atlas will have a border guard with size 'border', the same specified at atlas creation
- all images in a bin will have a guard border of 'border' size, where border was specified at TextureBin creation time.
- pros: consistence both in the same run and different runs which load in different order or different images (more enemies maybe)
- cons: if not all images need padding, or need different paddings, the images will pack a bit less efficiently

## module resource

class Loader, methods
- `__init__`:
  - initializes self._texture_atlas_bins = {}, a container of TextureBin 's used to store image resources
- image(name, ..., atlas=True, atlas_border=1)
  - basically, ignoring the flip_z and rotate params, if img seen before, returns the cached image,	else calls Loader._alloc_image(name, atlas=atlas, atlas_border=atlas_border) to get a texture region that it will cache and return.
  - It returns a texture not in an atlas or a texture region in one of the TextureBin in self._texture_atlas_bins

- _alloc_image(self, name, atlas=True, atlas_border=1)
   - if not atlas or img size too big to fit in a bin returns a texture not in an atlas; 'border' correctly not applied here
  - else returns bin.add(img), when bin is the TextureBin returned by 
 Loader._get_texture_atlas_bin(width, height, atlas_border)		
  - returns a texture not in an atlas or a region into one of the TextureBin in self._texture_atlas_bins
		
- _get_texture_atlas_bin(img.width, img.height, atlas_border)
  - if the texture size is too big, returns None, else it derives a key from the texture size needed,
  - if there is a bin for that key, it returns that bin,
  - else, creates a TextureBin with border= the param 'border' received in the call, adds the bin to available bins and returns the new bin

## This tells that:

- the promise in Loader.image to allow independent border size cannot posibily hold with this implementation, because they are at most two bins, and bin.add does not accept a border_size param.

- each TextureBin in self._texture_atlas_bins gets the border size set by the first image that enters the bin. Very unstable.
 
# Simplify

### fast and simple use case

Be it for new users or experiended users doing a fast prototype, an uniform k-pixel image padding by default will work most of the time. The precise k value may depend on level of zooming.

At this level the user will not want to build a custom loader, so it will not use directly Atlas or TextureBin; only pyglet.resource.image

A member Loader.default_image_padding can hold the k value, which has an initial value=1

This value is allowed to change before the first call to pyglet.resource.image / Loader.image, ReadOnly after that.

Here theres a design decision to be done: allow or not to specify a border_size in Loader.image ?

Lets look at advanced use cases before take a decision

### advanced use cases

The purpose is not to build an advanced api, more like explore what probably be its needs so that
 design decisions for the easy case dont innecesary limit the advanced cases

It is safe to say there will be a fight between diferent criteria for grouping images, by example
  - group the ones that will share drawing params (to minimize gl state changes)
  - group to minimize texture changes while rendering some geometry
  - group by time-of-life affinity, to minimize fragmentation
  - this set of images must live in the same texture (for some critical shader)

Whatever the compromise reached, it will end with some image groups, and a loader that will take an image, a hint and based on the hint will assign the image to that group.

I don't see 'desired padding' an important criteria to group images, the other criteria are more significative.

So I would say that Atlas and TextureBin, which expresses some units of grouping, don't need to force an additional 'group by padding'

Hence:
- remove the atlas_border param in `__init__` and it associated member ._border from Atlas and TextureBin

- augment the method add from
  `	add(self, img)`
  to
  `    add(self, image, border_size=0)`

Now border_size does not limit grouping by more important criteria in the advanced case.
The small price to pay in the advanced case is that somehow a border_size must be obtained when checkin-in an image; this can be implicitly passed in the hint, or as an explicit separate argument.

It does not impact the simple use case because border_size can be provided by Loader.default_border_size, or, if pyglet.image.loader is allowed to receive a border_size, from there.
Now it is no problem to mix different border_sizes in the bins used by Loader.

Loader.image signature must change from:
```	def image(self, name, flip_x=False, flip_y=False, rotate=0, atlas=True, atlas_border=1)```
to ( If we allow to pass border_size in the simple use case )
```	def image(self, name, flip_x=False, flip_y=False, rotate=0, atlas=True, atlas_border=None)```
```          #atlas_border None means use atlas_border = Loader.default_image_padding```
or (if per-image border_size are not allowed)
```	def image(self, name, flip_x=False, flip_y=False, rotate=0, atlas=True)```
 
# Recap changes suggested	

- Atlas and TextureBin does not receive a border param in `__init__`, not have related member ._border
- Atlas and TextureBin change the add method from
    add(img)
  to
    add(img, border_size=0)
- class Loader gains a new instance member (property?) 'default_border_size', initialized to 1 that can be changed before the fist call to image is made, then its remains ReadOnly
- Loader.image changes in the way show above

## Backward compatibilty

Behavior for the simple case is the same as was desired before the PR was done, implicitly use border_size=1

Advanced cases, which directly access Atlas and TextureBin, may need adjustments if they expected some default padding to be provided.

At this time, I bet the principal customer for advanced cases is pyglet itself (fonts, animations, ...), so theres a need to evaluate how hard would be to adjust

Extenal advanced users: if the use cases in pyglet are resolved, a request for coments could be done in the mailing list ?

**Comment by benmoran56** [comment]
Thanks for taking the time to write that up Claudio. I realized the issue as soon as I saw your ticket, but I didn't think of it at the time. 

I also had the same thought - to add the border argument to the `add` method. I'll have a look at this today/tonight, and make an update with that first step. We can then look it over again and make sure it looks reasonable before I push out the next release.

**Comment by benmoran56** [comment]
I had a quick look, at I think using a `default_border` class attribute will work well. This is the same technique we currently use for the Texture class, and min/mag filter defaults. Something like this: 
```py
class TextureAtlas:

    default_border = 0

    def __init__(self, width=2048, height=2048):
        ....

    def add(self, img, border=None):
        ....
        border = border or self.default_border
```

This will allow you to set a default border for **all** TextureAtlases/Bins: 
```
pyglet.image.atlas.TextureAtlas.default_border = 2
```
Or, set the default for a specific TextureAtlas/Bin after instantiating: 
```
my_atlas = pyglet.image.atlas.TextureAtlas()
my_atlas.default_border = 1
```
And of course users can provide a border size when calling the `add` method, to explicitly set the border regardless of what the default might be: 
```py
my_atlas.add(img, border=2)
```

The `resource` module will probably just pass in the border argument to `add`, with the the default being 1.

What do you think?

**Comment by benmoran56** [comment]
I pushed my changes into the `pyglet-1.5-maintenance` branch so you can have an easier look.

**Comment by ccanepa** [comment]
I think it can work.
Maybe not have a separate default_border in the resource module now that
there is the class default,

**Comment by ccanepa** [comment]
Looking at the commit diff I spotted some small issues:

** things that I see as bugs

atlas.py

- both in Atlas.add and TextureBin.add
  - in the docsting, looks like
  ```
            `border` : int
                Leaves specified pixels of blank space around
                each image added to the Atlas.
  ```
    should be
  ```
            `border` : int or None
                Leaves specified pixels of blank space around
                each image added to the Atlas.
                if None, border = self.default_border is used
  ```
    and maybe the 'blank space' should change to more explicit wording, like 'fully transparent" or color (0, 0, 0, 0)

- the line
  ```border = border or self.default_border```
  should be
  ```border = self.default_border if border is None else border```
  (the first version fails when border==0)

resource.py

- in Loader
  ```    def _alloc_image(self, name, atlas=True, border=1):
  ```
  should be
  ```    def _alloc_image(self, name, atlas=True, border=None)
  ```
  Why have two default_border managements when resource can use the one in atlas ?
  It is simpler to understand and modify  only one system

- in Loader, method _get_texture_atlas_bin(self, width, height) has a problem in this block
  ```
        # Large images are not placed in an atlas
        max_texture_size = pyglet.image.get_max_texture_size()
        max_size = min(2048, max_texture_size)
        if width > max_size or height > max_size:
            return None
  ```
It does not cover some corner cases, like
```  ( (width + border > pyglet.image.get_max_texture_size())
      and (width <= pyglet.image.get_max_texture_size())
      and (max_size == pyglet.image.get_max_texture_size())
      and border >0 )
```
 An image with those conditions will not fit in any TextureBin texture region, because the region size, when including the pading, would be greater than max texture size available from openGL
Yet it would fit in a texture not included in an atlas, because tx_size <= max gl tx size

One tentative way to fix would be to leave this block alone, catch in the code below thar block the exception for 'gl texture request fails because texture too big' and return None in that case.   

Other more compicate will be to try something similar to this : add a border=None kwarg, to receive border, and change the block to
  ```
        # Large images are not placed in an atlas
        real_border = TextureBin.default_border if border is None else border
        max_texture_size = pyglet.image.get_max_texture_size() - real_border
        max_size = min(2048, max_texture_size)
        if width > max_size or height > max_size:
            return None
  ```
I dont like that  TextureBin.default_border ; it would be safer to have a Loader.default_size

Lunch time, I will left here for now

**Comment by ccanepa** [comment]
I see in Loader
```
def image(self, name, flip_x=False, flip_y=False, rotate=0, atlas=True, border=1)
```
and
```
def animation(self, name, flip_x=False, flip_y=False, rotate=0, border=1)
```
It is similar to the line
```
def _alloc_image(self, name, atlas=True, border=1)
```
mentioned in the comment above.

Three points in which the default_border set in Atlas and TextureBin are disregarded.

From a higher level point of view
- Atlas and TextureBin are containers which can be used from one or more loaders
- Each loader may want to use its own default_border
- So it is simpler if  default_border is kept in the loader code; in particular for the pyglet default loader, pyglet.resource.Loader. As an instance member, for good mesure.
- and then change those ,border=1) to ,border=None) 

thats my 2c

**Comment by caffeinepills** [comment]
In my view:

> Atlas and TextureBin are containers which can be used from one or more loaders

While true, if you intend to use atlas and bin's, using separate loaders is actually negative, because you are creating separate atlases which defeats the purpose of them. (Multiple loaders do not share the same atlas bins)

> Each loader may want to use its own default_border

I think this removes functionality. I can use or not use a border even with a separate function call with any image. As a class level, I would have to change it before and after every load. Otherwise that means I will no longer be able to load certain images with no border, and some images with a border in the same loader to the same atlas.

> So it is simpler if default_border is kept in the loader code; in particular for the pyglet default loader, pyglet.resource.Loader. As an instance member, for good mesure.

The default loader is also a private module variable, which makes trying to modify a class variable appear improper to a user (example:`pyglet.resource._default_loader.atlas_border = 1`), not sure it's the best fit or maybe just make it public? Also it is inconsistent in that there is no other class variables for Loaders which users set, which seems out of place.

> and then change those ,border=1) to ,border=None)

I think it's important to keep the variable type consistent and `0` should have the same effect as `None` in this case, as in no border.

**Comment by ccanepa** [comment]
On Mon, Jun 1, 2020 at 3:35 PM caffeinepills <notifications@github.com>
wrote:

> In my view:
>
> Atlas and TextureBin are containers which can be used from one or more
> loaders
>
> While true, if you intend to use atlas and bin's, using separate loaders
> is actually negative, because you are creating separate atlases which
> defeats the purpose of them. (Multiple loaders do not share the same atlas
> bins)
>
You want to pack together images with some affinity, and keep separated
from ones with other affinities. Think blend modes, or interpolation modes.
One big TextureBin can be detrimental.

> Each loader may want to use its own default_border
>
> I think this removes functionality. I can use or not use a border even
> with a separate function call with any image. As a class level, I would
> have to change it before and after every load. Otherwise that means I will
> no longer be able to load certain images with no border, and some images
> with a border in the same loader to the same atlas.
>
???
```
class MyLoader:
    def __init__(self, path=None, script_home=None, default_border=0):
        self.default_border = default_border
        ...

     def image(self, name, flip_x=False, flip_y=False, rotate=0,
atlas=True, border=None):
         border = self.default_border if border is None else border
         ...
 ```
User code will not need to specify border if it is using the default, nor
change anything before calling image if it wants a different border


> So it is simpler if default_border is kept in the loader code; in
> particular for the pyglet default loader, pyglet.resource.Loader. As an
> instance member, for good mesure.
>
> The default loader is also a private module variable, which makes trying
> to modify a class variable appear improper to a user (example:pyglet.resource._default_loader.atlas_border
> = 1), not sure it's the best fit or maybe just make it public? Also it is
> inconsistent in that there is no other class variables for Loaders which
> users set, which seems out of place
>
I said instance variable, not class.
The 'private' card I can't contest


> .
>
> and then change those ,border=1) to ,border=None)
>
> I think it's important to keep the variable type consistent and 0 should
> have the same effect as None in this case, as in no border.
>

In my narration, border=0 means you want border==0, and border=None means
border will be set to default_border
In caller code,
myloader.image(..., border=0): means caller want's exactly 0 border
calling without an explicit border, or border=None, means caller is fine
with wathever default is set, and this meaning will not change if in the
evolution of usercode the default_border es changed.

-

**Comment by benmoran56** [comment]
I just made another push. I cleaned up a lot of the redundant arguments in `resource`, and fixed the logical error in the `_get_texture_bin` method (thanks for catching that!). 

For this iteration, I removed the `default_border` attribute for the TextureBin/Atlas classes. I wonder after all the discussion, do we really need it? Allowing users to explicitly request a border size when calling `add` methods might be enough for the time being.

**Comment by benmoran56** [comment]
The latest releases have the explicit border arguments for the `add` methods. Do you guys think we should take this further, or leave it for the time being?

**Comment by ccanepa** [comment]
I'm ok with leave as it is.
Thanks for all your work, cheers

**Comment by benmoran56** [comment]
I'll close this for now then, but in the future we can certainly have another discussion about improvements. Thanks for starting the conversation!
