### ISSUE TITLE
Font enhancements

### ISSUE THREAD

**Issue by caffeinepills** [pyglet/pyglet#221]
Font's in Pyglet for the most part are pretty simple, and that's good because the complexity these days for fonts can get out of control with multiple languages, ligatures, etc. While implementing DirectWrite to see how fonts could be improved, I've come across some features that would be nice, and some topics of discussion. Hopefully this can lead to more versatility with text rendering and the feature set catching up with the 21st century.

I know this is long, but feel free to just post about specific points if you have any input.

Features
------------
1) Weights

Right now all we support is bold=True or False, however there are a ton of options these days about different weight classes for each font. Arial Black for instance, would not be supported on another platform because we only allow "Bold" weight.

Windows has these classified as: thin, extralight, ultralight, light, semilight, normal, regular, medium, demibold, semibold, bold, extrabold, ultrabold, black, heavy, extrablack.

2) Spacing styles

Same with weights, there can also be additional styles.

Windows has these classified as: undefined, ultracondensed, extracondensed, condensed, semicondensed, normal, medium, semiexpanded, expanded, extraexpanded. This is something OpenType fonts support, so Windows supports it. I think it would stand to reason these could be supported across platforms in some manner.

3) Kerning

Kerning moves the advances so certain glyph combinations can either be closer or further apart for a more eye pleasing look. Right now we don't have any kerning loaded from the font (although custom kerning is supported through document layouts). This means a lot of fonts do not look as they should when compared to a proper rendering.

4) Unicode characters and color glyphs

A lot of unicode characters just show up as boxes currently and do not get rendered at all. There are plenty of fonts now that have colored glyphs (emojis, pictures, etc)

5) Antialiasing Render modes

Allow text to be rendered through antialiasing, aliased, or other modes. 

6) Render to texture/font renderer

Sometimes, you may want text as a texture for you to modify. Whether it's image transformations, 3D use, effects, shaders, or something else. 

Discussion
--------------------
Some concerns I have are regarding certain platform support. For instance, a lot of these high level options would only be available on certain Windows platforms. (For instance kerning is Windows 8 and above only) GDI Plus would be left behind, although it is technically deprecated.

Weights and Styles
---
From what I can see Windows supports both of these.

This would require these to be configurable from the document level and font level. (Some testing with this does work with directwrite, however removing the `bool(bold)` or `bool(italic)` from document causes errors with GDIPlus renderer, so this may require a deeper dive.)

**Some proposals:** 

This can either be done with bold=Bool or String. This way you can specify if you want simple bolding, True or False, but if you want something specific such as "Black" you can pass that in as a string. 

Change `bold` to `weight` for each platform, and make them pass a string on the bold style. Add style or stretch keyword that allows for condensing or expanded. 

Combine both into 'style' and allow people to specify something like 'bold condensed' and we can try to parse it out, and fallback to the default normal style if nothing can be found. (It might be possible to get the closest font, such as bold may exist, but condensed may not, so use bold regular for instance). Might be too much for users? Unsure. If we do that, we may end up having to throw italic in there as a 'style' as well. 'bold italic', 'bold italic condensed'.

[I should also note that there is another variation of italics called 'oblique' and can be supported in the same manner as whichever method we choose for weight/styles.]

Kerning
---

If kerning is available, should it be allowed by default, should this even be a user configurable option or for them to disable through font settings? I am unsure if one would NOT want kerning if it is available.

Another issue is a lot of newer custom fonts only support kerning from what they call the GPOS table which, as far as I can tell, Windows DirectWrite doesn't even support. The table would be something we would have to figure out how to parse ourselves from the font data itself. However there is an older 'kern' table that fonts can use, which a lot of fonts (even windows default ones) still utilize.

**Proposal**
Just allow kerning by default, if someone DOES want to disable it, they would have to set kerning to False on a font object itself. Specify only older style kern tables are supported in docs.

Unicode characters.
---
I have tested with GDI+ and while some unicode objects do show up, but a lot of newer ones just show up as black boxes. With the new font renderer for Windows it does allow these to be rendered, as well as to choose if they should be returned as color bitmaps. The issue is that the pyglet text renderer applies the blended color to all of the glyphs. Therefore you can never get the true color of the glyph if the string is a different color from white. I am not too familiar with the layouts, but I think this needs to be inserted or changed on the layout/iter level, or some sort of flag on the glyph that the color iterator can change to no color change. It's not a huge priority, but something to look into would be these type of character support on different OS's, and how we handle it.

However this support varies depending on OS, even earlier versions of Windows only support non-color unicode characters.

**Proposal**
Pyglet `option['color_fonts'] = True` is on by default. It will try to enable color fonts depending on OS/renderer support. Not all renderers support it, but the system should try.

Text Render Quality
---

There might be some cases where you do not want anti-aliasing text, maybe a text based game or pixel based game. Antialiasing text modes could break the style a person goes for. I agree this is probably a small use case, but perhaps an option should be allowed somewhere.

Proposal
`pyglet.options['antialias_font'] = True`

or

`pyglet.options['font_render'] = 'antialias'`

The issue is Windows has multiple different antialias modes: DEFAULT (Antialias), CLEARTYPE, GRAYSCALE, ALIASED. So not sure how best to handle OS specific render modes in that case. I am currently trying to experiment between Grayscale and Antialias. (Apparently Cleartype does not do well when rendered onto a transparent image since it doesn't have alpha and relies on a colored BG?)

Render to texture/Texture
----
This may be a two different additions, 

Rendering to Texture:  Take a pyglet label and render it to an off screen buffer and save it as a texture.

Pros: The image would be exactly like Pyglet's render, so there aren't any variation.
Cons: Possibly expensive? But otherwise possible.

Rendering through Glyph Renderer: Right now we essentially just take each letter, and use the font renderer to put one glyph a bitmap at a time. However, these could be modified to allow all of the text to be put on the bitmap at once.

Pros: More accurate font support. Here's the interesting thing is that in DirectWrite, (and GDI to some degree), it has it's own built in TextLayout interface, and this has a lot of built in features. For instance this can automatically space text kerning even with GPOS tables. It can also handle different languages that have fonts that read right to left, or even vertically, justifications, text wrappings, formatting, ligatures, etc. So technically it could support more than what Pyglet does, by going directly to the font renderer itself, this way it could support someone who wants true 1:1 accuracy of their fonts if Pyglet cannot handle their edge case scenario.

Cons: Since this is through the font renderer, the output may not be the same as Pyglet. For instance Pyglet has an HTMLLabel and most likely the renderer would not support HTML in this manner. So 1:1 would be impossible.

Highly platform dependent.

Well that's currently what I've run into, I know this is a lot, but I feel the font system probably hasn't been revisited since Windows 7 was released.

**Comment by t-o-n-y-p** [comment]
We should definitely continue to support Windows 7 for a while. It's share is still about 20-25%.
Thoughts about implementation:

- Weights and styles can be implemented using pyglet-provided Enums, user will just select right member.
- Kerning should be enabled by default, configurable, but ignored under the hood if not supported by the OS.
- OS-specific render quality can be also solved by Enums (for each platform).

Regarding rendering to texture: do you mean the current system with glyphs is about to be fully replaced by rendering to texture?

**Comment by caffeinepills** [comment]
DirectWrite has been merged into both branches now.
