### ISSUE TITLE
BUG: Simple video example does not work

### ISSUE THREAD

**Issue by larsoner** [pyglet/pyglet#222]
Based on `git bisect`, 6a409810cdb32bd1d73bd9b4aa3234c50372709d broke this minimal video example: it fails (black screen) on that commit but passes (plays video) on its parent 27ed0d9893372740cddccfee7d39f06c3d88638e. This example code uses [this video file](https://github.com/LABSN/expyfun-data/blob/master/video/example-video.mp4) but I imagine it would work for any:

```
import os
import pyglet

path = os.path.dirname(__file__) + '/example-video.mp4'
window= pyglet.window.Window()
player = pyglet.media.Player()
source = pyglet.media.StreamingSource()
MediaLoad = pyglet.media.load(path)

player.queue(MediaLoad)
player.play()


@window.event
def on_draw():
    if player.source and player.source.video_format:
        player.get_texture().blit(50,50)
    else:
        raise SystemExit(0)


pyglet.app.run()
```
The code seems to have diverged quite a bit so `git revert` does not work. But selective `git checkout` from the parent shows it was the changes to the `window` code -- adding this before `pyglet.app.run()` causes things to work again on 6a409810cdb32bd1d73bd9b4aa3234c50372709d:
```
@window.event
def on_resize(width, height):
    from pyglet import gl
    gl.glMatrixMode(gl.GL_PROJECTION)
    gl.glLoadIdentity()
    gl.glOrtho(0, width, 0, height, -1, 1)
    gl.glMatrixMode(gl.GL_MODELVIEW)
```
But on `master` this is an OpenGL error. Any ideas how to fix this properly?

**Comment by caffeinepills** [comment]
Master branch is based on upcoming 2.0 and is in development, and diverges quite a bit from current Pyglet (GL3 vs legacy GL). As such a lot of old legacy GL (the on_resize you posted) will not work with master branch or 2.0. Mixing the two branches are not recommended.

Use one of the official releases such as 1.5.5 (1.5.6 should be out soon) or the 1.5 maintenance branch.

**Comment by larsoner** [comment]
Oh wait it does work on `1.5-maintenance`. So it's just broken on `master` (even without the `resize` legacy code)...

**Comment by veyron-github** [comment]
You problem had solved? Can you test the code:
_print(pyglet.media.get_decoders())_
I will appreciate that if you put you out put here

**Comment by larsoner** [comment]
Now I have a different bug both on `master` and on `pyglet-1.5-maintenance`. I'm running Ubuntu 20.10 now so maybe there is some unrelated regression? Running the code above with a `import faulthandler; faulthandler.enable()` on Ubuntu 20.10 I get:
```
larsoner@bunk:~/Desktop$ python -ui video.py 
free(): invalid next size (normal)
Fatal Python error: Aborted

Thread 0x00007f1e28874640 (most recent call first):
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 497 in run
  File "/home/larsoner/python/pyglet/pyglet/media/codecs/gstreamer.py", line 63 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Current thread 0x00007f1e2d44b740 (most recent call first):
  File "/home/larsoner/python/pyglet/pyglet/clock.py", line 274 in call_scheduled_functions
  File "/home/larsoner/python/pyglet/pyglet/app/base.py", line 243 in idle
  File "/home/larsoner/python/pyglet/pyglet/app/base.py", line 182 in run
  File "/home/larsoner/python/pyglet/pyglet/app/__init__.py", line 107 in run
  File "video.py", line 25 in <module>
Aborted (core dumped)
```
Is it worth opening a new issue for this?

**Comment by benmoran56** [comment]
Are you getting a crash only when using `faulthandler`?  If not, what does the traceback look like without it? 
I can't replicate it on my Arch machine.

**Comment by larsoner** [comment]
> Are you getting a crash only when using faulthandler

No, I added `faulthandler` so we could at least see where in the Python stack things failed. Without it you get the same error just less information:
```
$ python -u video.py 
free(): invalid next size (normal)
Aborted (core dumped)
```

> I can't replicate it on my Arch machine.

FWIW I'm using stock Ubuntu 20.10 GTK (3.24.23) + Gstreamer (1.18.0) / PyGObject (3.38.0) + ffmpeg (7:4.3.1) I think. Maybe your versions are different from mine? Is it possible the 20.10 version(s) are newer and create a problem?

**Comment by larsoner** [comment]
> 
```
$ python -c "import pyglet; print(pyglet.media.get_decoders())"
[WaveDecoder('.wav', '.wave', '.riff'), GStreamerDecoder('.mp3', '.flac', '.ogg', '.m4a'), FFmpegDecoder('.mp3', '.ogg')]
```
The video in question is MP4, if it matters. And even this smaller snippet is enough to cause the problem, no need for any `on_draw` so it seems tied to the video processing:
```
import pyglet
path = './example-video.mp4'
window = pyglet.window.Window()
player = pyglet.media.Player()
source = pyglet.media.StreamingSource()
MediaLoad = pyglet.media.load(path)
player.queue(MediaLoad)
player.play()
pyglet.app.run()
```
If I `print(item.func)` in `clock.py` to see what is being called, I get:
```
<bound method Player.update_texture of <pyglet.media.player.Player object at 0x7f4d937c4fd0>>
```
If I dig into `player.py` and add a `return` before line 480:
```
image = source.get_next_video_frame()
```
then there is no crash. Moving the return to after this line, it still crashes. The `source` is question is the `MediaLoad` var, i.e.:
```
<pyglet.media.codecs.ffmpeg.FFmpegSource object at 0x7f131b3b0880>
```

I can also eliminate gstreamer by making `run(self):` just `return` rather than starting the glib thread -- then the crash still happens but the upper `gstreamer` trace disappears, leaving just the `call_scheduled_functions` one. Digging deeper into that with some debug `print` calls to see what in `FFmpegSource` actually gets called, I ended at this point in the stack trace:
```
...
process packet
append vid
decode video packet
ffmpeg decode video
  File "video.py", line 12, in <module>
    pyglet.app.run()
  File "/home/larsoner/python/pyglet/pyglet/app/__init__.py", line 107, in run
    event_loop.run()
  File "/home/larsoner/python/pyglet/pyglet/app/base.py", line 167, in run
    timeout = self.idle()
  File "/home/larsoner/python/pyglet/pyglet/app/base.py", line 237, in idle
    redraw_all = self.clock.call_scheduled_functions(dt)
  File "/home/larsoner/python/pyglet/pyglet/clock.py", line 294, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "/home/larsoner/python/pyglet/pyglet/media/player.py", line 493, in update_texture
    ts = source.get_next_video_timestamp()
  File "/home/larsoner/python/pyglet/pyglet/media/codecs/ffmpeg.py", line 986, in get_next_video_timestamp
    self._decode_video_packet(video_packet)
  File "/home/larsoner/python/pyglet/pyglet/media/codecs/ffmpeg.py", line 908, in _decode_video_packet
    result = self._ffmpeg_decode_video(video_packet.packet,
  File "/home/larsoner/python/pyglet/pyglet/media/codecs/ffmpeg.py", line 943, in _ffmpeg_decode_video
    traceback.print_stack()
<pyglet.media.codecs.ffmpeg_lib.libavcodec.AVPacket object at 0x7fc6e81e2dc0>
free(): invalid next size (normal)
Fatal Python error: Aborted

Current thread 0x00007fc6ecd02740 (most recent call first):
  File "/home/larsoner/python/pyglet/pyglet/clock.py", line 294 in call_scheduled_functions
  File "/home/larsoner/python/pyglet/pyglet/app/base.py", line 237 in idle
  File "/home/larsoner/python/pyglet/pyglet/app/base.py", line 167 in run
  File "/home/larsoner/python/pyglet/pyglet/app/__init__.py", line 107 in run
  File "video.py", line 12 in <module>
Aborted (core dumped)
```
When I then moved the `traceback.print_stack()` one line later, after the call to `avcodec.avcodec_decode_video2`, it didn't print. But then on some runs I got a different error:
```
get_next_video_frame completed
next video timestamp
decode video packet
malloc(): corrupted top size
```
So I'm not really sure what's going on, maybe some memory issue somewhere. Looking quickly into this a bit:
```
$ python -c "import pyglet; print(pyglet.lib.load_library('avcodec'))"
<CDLL 'libavcodec.so.58', handle 10fcbc0 at 0x7fddac98a6a0>
```
It looks like my `libavcodec.so.58` should come from:
```
$ locate libavcodec.so.58
/usr/lib/x86_64-linux-gnu/libavcodec.so.58
/usr/lib/x86_64-linux-gnu/libavcodec.so.58.91.100
```
Which I've zipped and uploaded in case someone wants to try it with and LD_LIBRARY_PATH (it's just the Ubuntu 20.10 one):

[libavcodec.so.58.91.100.zip](https://github.com/pyglet/pyglet/files/5770303/libavcodec.so.58.91.100.zip)

**Comment by larsoner** [comment]
Digging into this more on Ubuntu 21.04 (just upgraded), I still have this problem. However, it looks like if I change [this line](https://github.com/pyglet/pyglet/blob/master/pyglet/media/codecs/ffmpeg.py#L890):
```
        buffer = (c_uint8 * (pitch * height))()
```
to have a bit of slop:
```
        buffer = (c_uint8 * (pitch * height + 9))()
```
I get no segfaults. With 8 or fewer, I consistently have segfaults. So I think there must be something weird/incorrect going on with the buffer and / or `_ffmpeg_decode_video` calls where they end up changing bits of memory that they shouldn't.

**Comment by benmoran56** [comment]
Nice find!  I did a little digging into the libav documentation with this in mind. In particular, I'm wondering if this is it? 
https://libav.org/documentation/doxygen/release/9/group__lavc__decoding.html#ga9207dd7cb4ee4416f8fd1f7a63af34b7
My understanding is that some hardware accelerated decoder hardware will return data in larger chunks, since it's processing more bytes at a time. 
I've also seen some mention in the documentation about "buffer size alignment", as well as some functions for querying this, but maybe the addition of FF_INPUT_BUFFER_PADDING_SIZE is enough for our case.

**Comment by larsoner** [comment]
Indeed looking at:

https://ffmpeg.org/doxygen/2.7/group__lavc__decoding.html

It seems like both the audio and video buffers could use the `FF_INPUT_BUFFER_PADDING_SIZE` (or the newer name [`AV_INPUT_BUFFER_PADDING_SIZE`](https://ffmpeg.org/doxygen/3.3/group__lavc__decoding.html#ga8f5b632a03ce83ac8e025894b1fc307a)). Moreover this quote:

> Note: If the first 23 bits of the additional bytes are not 0, then damaged MPEG bitstreams could cause overread and segfault.

Makes it seem like these bytes should be zeroed out, too. I can try to take a stab at this with a PR if it would help.

**Comment by benmoran56** [comment]
Do you think we're good to close this issue now, or how do you feel about it?

**Comment by larsoner** [comment]
Yep, just forgot to add the closes tag to the PR!

**Comment by benmoran56** [comment]
No problem, and thanks again for the PR!
