### ISSUE TITLE
How does the pyglet library work？

### ISSUE THREAD

**Issue by huooyk** [pyglet/pyglet#23]
I would like to ask why pyglet does not provide a function to directly fill the window, but calls gl.glclearcolor and then window.clear. Sorry for any interruption

**Comment by benmoran56** [comment]
Hi hyooyk. Because of how OpenGL works, you only need to call glClearColor one time. After that, `Window.clear()` will clear the same color each time.  Does that answer your question?

**Comment by huooyk** [comment]
I mean why pyglet.window does not provide gl. glclearcolor packaging function, such as pyglet.window.clearcolor,

For example, pygame provides the pygame. surface. fill function

As a novice, to be honest, I haven't figured out how to draw a square quickly.Do not use pyglet.gl classes

**Comment by benmoran56** [comment]
The Pygame API is more suited to software rendering, whereas the pyglet API is based on OpenGL. 
I think the reason that there is no `pyglet.window.clearcolor` is that nobody asked for it :smile: 

pyglet does not provide high-level functions for drawing shapes. You have to use OpenGL primitives, as described here:  https://pyglet.readthedocs.io/en/latest/programming_guide/graphics.html
If you need help, please join the Discord channel. You can find the link in the Wiki, and Readme. 

If you're looking for something a bit simpler, you might want to check out http://arcade.academy
