### ISSUE TITLE
'NoneType' object has no attribute 'windows' when using cx_freeze

### ISSUE THREAD

**Issue by Jules78120** [pyglet/pyglet#233]
From pyglet, I only use this in my program:
`import pyglet.font as pyf`

`pyf.add_file("fonts/Dosis-Regular.otf")`

It runs fine (Python 3.8/Windows 10). But after freezing it with cx_freeze in order to get a standalone application, when I run my .exe, I get this error:

> Traceback (most recent call last):
> 
>   File "C:\Users\Jules\AppData\Roaming\Python\Python38\site-packages\pyglet\__init__.py", line 334, in __getattr__
>     return getattr(self._module, name)
> AttributeError: 'NoneType' object has no attribute 'windows'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Jules\AppData\Roaming\Python\Python38\site-packages\pyglet\__init__.py", line 334, in __getattr__
>     return getattr(self._module, name)
> AttributeError: 'NoneType' object has no attribute 'get_default'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Jules\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
>     module.run()
>   File "C:\Users\Jules\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
>     exec(code, {'__name__': '__main__'})
>   File "snake_main.py", line 12, in <module>
>   File "<frozen zipimport>", line 259, in load_module
>   File "C:\Users\Jules\Desktop\Python\2020\Snake\snake_menus.py", line 15, in <module>
>     import pyglet.font as pyf
>   File "C:\Users\Jules\AppData\Roaming\Python\Python38\site-packages\pyglet\font\__init__.py", line 67, in <module>
>     from pyglet.font.win32 import GDIPlusFont
>   File "C:\Users\Jules\AppData\Roaming\Python\Python38\site-packages\pyglet\font\win32.py", line 42, in <module>
>     from pyglet.font import base
>   File "C:\Users\Jules\AppData\Roaming\Python\Python38\site-packages\pyglet\font\base.py", line 45, in <module>
>     from pyglet.gl import *
>   File "C:\Users\Jules\AppData\Roaming\Python\Python38\site-packages\pyglet\gl\__init__.py", line 243, in <module>
>     import pyglet.window
>   File "C:\Users\Jules\AppData\Roaming\Python\Python38\site-packages\pyglet\window\__init__.py", line 1897, in <module>
>     gl._create_shadow_window()
>   File "C:\Users\Jules\AppData\Roaming\Python\Python38\site-packages\pyglet\gl\__init__.py", line 220, in _create_shadow_window
>     _shadow_window = Window(width=1, height=1, visible=False)
>   File "C:\Users\Jules\AppData\Roaming\Python\Python38\site-packages\pyglet\window\win32\__init__.py", line 132, in __init__
>     super(Win32Window, self).__init__(*args, **kwargs)
>   File "C:\Users\Jules\AppData\Roaming\Python\Python38\site-packages\pyglet\window\__init__.py", line 647, in __init__
>     app.windows.add(self)
>   File "C:\Users\Jules\AppData\Roaming\Python\Python38\site-packages\pyglet\__init__.py", line 340, in __getattr__
>     __import__(import_name)
>   File "C:\Users\Jules\AppData\Roaming\Python\Python38\site-packages\pyglet\app\__init__.py", line 128, in <module>
>     event_loop = EventLoop()
>   File "C:\Users\Jules\AppData\Roaming\Python\Python38\site-packages\pyglet\app\base.py", line 147, in __init__
>     self.clock = clock.get_default()
>   File "C:\Users\Jules\AppData\Roaming\Python\Python38\site-packages\pyglet\__init__.py", line 340, in __getattr__
>     __import__(import_name)
> ModuleNotFoundError: No module named 'pyglet.clock'

(Using cx_Freeze on my program worked fine before I used Pyglet.) I don't know if the problem comes from Pyglet or cx_Freeze.

**Comment by benmoran56** [comment]
It looks like the problem is that cx_Freeze is not including the `pyglet.font` module. You may have to force include `pyglet.font` in the appropriate cx_Freeze option.

**Comment by Jules78120** [comment]
Thanks for you reply. But cx_Freeze includes the pyglet.font module:
![Screen Shot 06-22-20 at 12 35 PM](https://user-images.githubusercontent.com/16976776/85278166-d88ca480-b484-11ea-83eb-7dedcde27782.PNG)

I just found the error, and it has nothing to do with pyglet, sorry: pywin32 was missing, that's why I got this error.
