### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Jackk242** [pyglet/pyglet#236]
Hello, I am trying to install pyglet into my python directory. I managed to clone from the git resource correct but when I am in Git Bash and cd into the pyglet package, I enter this:

`python setup.pt install --user`

And I get this: 

`bash: python: command not found`

Can someone help me figure out what's wrong?

**Comment by agricolab** [comment]
There is one spelling error in your first listing, and you probably meant  `setup.py`. Unrelated to this is that your bash claims it couldn't find a python command in your path. 
Considering you wrote that you used git bash, i assume you have a Windows10 machine. Windows 10 does not ship with Python, and you have to install it manually. Choose either the standard CPython https://www.python.org/downloads/, or one of the many distributions with various bells and whistles included  see https://wiki.python.org/moin/PythonDistributions. I usually suggest Anaconda https://www.anaconda.com/products/individual. If you have already installed a Python version, and want to use it with git bash, make sure it's in your path https://helpdeskgeek.com/windows-10/add-windows-path-environment-variable/ 


If you have Linux as OS:
You should be able to check with `which python`, which python it would use. On your machine, it likely returns nothing. On some distributions, Python 3 is called with `python3`. If `which python3` returns a valid path to your executable, you'd could install pyglet with `python3 setup.py install --user`.

**Comment by Jackk242** [comment]
Thank you for timely response, I managed to get it to work! Also, sorry about the spelling error.
