### ISSUE TITLE
Dictionary changed size during iteration

### ISSUE THREAD

**Issue by gkanarek** [pyglet/pyglet#237]
https://github.com/pyglet/pyglet/blob/c32556e92e854b9001da39fba70c4deb63c28878/pyglet/input/darwin_hid.py#L389

This loop is throwing a runtime error when closing a window. It's deleting elements from a dictionary during iteration.

**Comment by benmoran56** [comment]
Thanks for opening the ticket, and the code example.
We definitely shouldn't be deleting during iteration. Does this crash consistently on your machine?

**Comment by benmoran56** [comment]
This should now be fixed in the pyglet-1.5-maintenance branch, and will be in the next point release.
