### ISSUE TITLE
How to change the background color

### ISSUE THREAD

**Issue by linwaytin** [pyglet/pyglet#238]
Hi,

First, I need to thank you for this great project.
I spent hours on searching a GUI toolkit that can satisfy my needs, and this is the only one that works.

I am wondering if there is a simple way to change the background color of a window,
or I have to resort to OpenGL, which I'm not familiar with.
```python
import pyglet

win = pyglet.window.Window(width = 600, height = 400, caption = "Hello world")
win.set_location(100, 100)

label = pyglet.text.Label('Hello, world',
                          font_name='Times New Roman',
                          font_size=36,
                          x=win.width//2, y=win.height//2,
                          anchor_x='center', anchor_y='center')

@win.event
def on_draw():
    win.clear()
    label.draw()

pyglet.app.run()
```
For now, I got a window showing "Hello, world" in white, on a black background.
Is there a simple way to specify the colors?

Thank you.

**Comment by benmoran56** [comment]
I'm glad you're liking pyglet so far. 

Changing the background color does currently require OpenGL, but it's only  single command: 
`pyglet.gl.glClearColor(1, 1, 1, 1)`
It's RGBA, on a scale from 0-1 for each color channel.
I suppose the reason that nobody wrote a higher level abstraction for this, is just because it's so simple already.
Still, it might be nice to add to `Window`. I'll look into that. 

Also, In case you're interested, the OpenGL documentation can be read here: 
http://docs.gl/gl3/glClearColor

**Comment by linwaytin** [comment]
Thanks.
I'm curious that how I can specify which window the `gl` function acts on.

The manual says that every window has an `OpenGL` context. 
How could I manipulate these contexts?

Thank you.

**Comment by benmoran56** [comment]
You just need to switch to a Window to make it's context active: `window.switch_to()`
The contexts and Windows are tied together.

**Comment by linwaytin** [comment]
That works, thank you.
I noticed that when there are two windows overlapping, one can "erase" another, especially when I'm moving them.
I suppose that I need to redraw the window at some rate. 
How can I achieve this?
Sorry this may be a stupid question.

**Comment by benmoran56** [comment]
I'm not sure of exactly what you're seeing, but you will need to make sure you have an "on_draw" event for each window. If Window.clear() is not being called, you will see random graphical artifacts. 

By the way, if you use Discord, feed free to drop by our server for help. You can generally get fairly quick responses there: 
https://discord.gg/QXyegWe

**Comment by linwaytin** [comment]
My code is like this
```python
import pyglet
import pyglet.gl as gl

win = pyglet.window.Window(width = 600, height = 400, caption = "Hello world")
win.set_location(100, 100)
gl.glClearColor(1, 0, 0, 0.5)

label = pyglet.text.Label('Hello, world',
                          font_name='Times New Roman',
                          font_size=36,
                          x=win.width//2, y=win.height//2,
                          anchor_x='center', anchor_y='center')

win2 = pyglet.window.Window(width = 300, height = 200, caption = "Next world")
win2.set_location(200, 200)
win2.switch_to()
gl.glClearColor(0, 0.5, 0, 0.5)

@win.event
def on_draw():
    win.clear()
    label.draw()

@win2.event
def on_draw():
    win2.clear()

pyglet.app.run()
```

What I want is two windows with different colors.
Does the code look strange or is there a better way to do this?
Thank you.

I do not use Discord. I'll try it.
Thanks for invitation.

**Comment by benmoran56** [comment]
That code looks OK. There are many different ways to organize your code, and pyglet does not enforce any specific pattern. It also depends on how big your project will get.

**Comment by linwaytin** [comment]
I found I need the `on_expose()` event with `window.clear()` to redraw the window which was covered by another one.
This might be due to my window manager i3wm.
Thank you for your help.
