### ISSUE TITLE
pyglet.resource default loader cannot find files when running Unittests in Pycharm

### ISSUE THREAD

**Issue by lortimer** [pyglet/pyglet#241]
I'm trying to write a test using python's `unittest` library without using `patch` to mock Pyglet's `resource` module. Said another way, I want my code to be able to actually load an image using `pyglet.resource.image` during my test. I'm writing my test in Pycharm and using its built-in test runner to run the test.

I kept getting a `ResourceNotFoundException`, but I couldn't figure out why, because I triple-checked that the relative path from my working directory to the folder where the image was had been passed to `resource.path`, I had called `resource.reindex()`, and I spelled the filename correctly.

I did some debugging and found that `resource`'s `DefaultLoader` thinks the `script_home` is the directory where Pycharm keeps its `unittest` runner: `/home/<username>/Applications/pycharm-community-2020.1.1/plugins/python-ce/helpers/pycharm`. This is happening even though I explicitly set my run configuration's working directory to the root of my project, where my assets folder containing the image lives.

`pyglet.resource.get_script_home` is getting this directory on line 136: `main = sys.modules['__main__']`

Is there a way I can tell resource to use a custom `Loader` instance instead of the default while my tests are running?

**Comment by benmoran56** [comment]
To use a custom Loader, you can just subclass `pyglet.resource.Loader`, and provide your own `script_home` string and `path` list. Make sure to use forward slashes ( / ) in your paths. 

`myloader = pyglet.resource.Loader(script_home='/some/custom/path')`

**Comment by lortimer** [comment]
Thank you, this works well. 

My main issue is that I can't fully mock out Pyglet's image class when I'm writing a unit test for a subclass of `Sprite`, because the super class' `__init__` expects a real Pyglet image, not a unittest `Mock` object. I had no luck mocking `Sprite` - when my production code called `super().__init__(mock_image)`, it would always throw an error because my `Mock` object didn't have the correct attributes. For anyone who is looking for help doing this in the future, here are two solutions:

### Subclass Loader
If you want to subclass `Loader` as @benmoran56 suggests above, you can do something like this, where my actual production assets live in a directory called "assets" inside the root of my application, which is also my current working directory while running tests:

```python
import os
from pyglet.resource import Loader

class CustomResourceLoader(Loader):
    def __init__(self):
        super().__init__(path=['assets'], script_home=os.getcwd())
```
This means I can now use the `CustomResourceLoader` directly in my production code, or I can just use it in my tests. I prefer to only use this in my tests, because Pyglet does an excellent job of discovering assets packaged up with py2app or PyInstaller, and I don't want to mess with that. To just use this in my tests, I can patch `pyglet.resource` and provide a `CustomResourceLoader` instead of a `Mock`. That way, my production code still loads images using `pyglet.resource` while the game is running, and I can let it load real images and avoid my problem above during tests.

```python
class TestPlayer(TestCase):

    def setUp(self) -> None:
        self.image = get_test_image()

    @patch('src.player.player.resource', new=CustomResourceLoader())
    def test_loads_animation(self):
        # Test Code
        ...
```

### Load files with `pyglet.image.load`

My solution to this problem while I was waiting to hear from @benmoran56 was to create a helper method to load a test image from a directory of assets I keep around just for unit tests to use:

```python
import os
import pyglet

def get_test_image():
    file_path = os.path.join(os.getcwd(), 'test/test_assets/1x1.png')
    return pyglet.image.load(file_path)
```

Instead of allowing my production-code-under-test to load real images, I would instead use unittest's `mock.patch` decorator to inject a mock version of `pyglet.resource` into my production code. I then told the mock version of `resource.image` to return the image from my helper function:

```python
class TestPlayer(TestCase):

    def setUp(self) -> None:
        self.image = get_test_image()

    @patch('src.player.player.resource', autospec=True)
    def test_loads_animation(self, mock_resource: MagicMock):
        mock_resource.image.return_value = self.image
        ...
```
From here, I could mock out as much or as little as I want, because the production code has a real image created by Pyglet.

As I understand it, normally, you would want to avoid using `pyglet.image.load` because it creates a new texture each time you use it, even if you've already loaded that image before(?). `pyglet.resource.image` caches those for you. Since this is just for tests, it's unlikely you'll ever load enough images to eat up significant memory. I made my image file 1x1 pixel just in case.
