### ISSUE TITLE
Possiblity to create windows with transparent background

### ISSUE THREAD

**Issue by roipoussiere** [pyglet/pyglet#246]
I would like to create a window transparent background, where only shapes I draw on it are visible.

I used `window.Window.WINDOW_STYLE_BORDERLESS` to remove window borders:

```py
from pyglet import app, window, shapes
win = window.Window(width=400, height=400, style=window.Window.WINDOW_STYLE_BORDERLESS)
```

But how to remove the black background?

**Comment by benmoran56** [comment]
Unfortunately this is not currently possible to do in pyglet.

**Comment by roipoussiere** [comment]
May I ask why it's not possible? Is this technically not possible by design or just not implemented for now? Do you think I will be able to do it at lower lever with OpenGL functions?

Sorry to ask, but transparent background is required for my new project so this point will basicaly determine if I'm going to chose Pyglet or not. :)

**Comment by benmoran56** [comment]
It would need to be implemented in the window platform code for all platforms, but so far no one has done that work. It should be possible, but I don't think anyone is planning to work on it at the moment.

**Comment by benmoran56** [comment]
Implemented via https://github.com/pyglet/pyglet/pull/434
