### ISSUE TITLE
How to draw shapes with antialiasing?

### ISSUE THREAD

**Issue by roipoussiere** [pyglet/pyglet#247]
I would like to draw shapes on my window.

I started with this:

```py
circle = shapes.Circle(x=200, y=200, radius=200, color=(128, 128, 128))
circle.draw()
```

But is it possible to use antialiasing?

**Comment by benmoran56** [comment]
You will need to create an OpenGL configuration that has sample buffers enabled. 
The documentation can be found here:  https://pyglet.readthedocs.io/en/latest/programming_guide/context.html#opengl-configuration-options

It is recommended to use the following pattern when creating your Window: 
```py
try:
    # Try to create a window with multisampling
    config = pyglet.gl.Config(sample_buffers=1, samples=4)
    window = pyglet.window.Window(960, 540, config=config)
except pyglet.window.NoSuchConfigException:
    # Fall back to no multisampling
    print("Multisampling not available.")
    window = pyglet.window.Window(960, 540)
```
