### ISSUE TITLE
How to schedule a blocking event ?

### ISSUE THREAD

**Issue by benoitvalery** [pyglet/pyglet#250]
Hi there,

Suppose I have a list of events that I want to schedule at desired time points. But importantly, some of these events should block the scheduler.

For instance, imagine I want to execute 4 events respectively at 5, 10, 15 and 20 seconds in time. Imagine that my third event is blocking (for instance it prompts the user for some keyboard input) and I want to block the scheduler until this event has finished (input has been received), so my last event does not happen 5 seconds after the third event, but rather 5 seconds **after the third event has returned**.

What would by the general philosophy to achieve that ?

For now, I'm using the `schedule_once` method to schedule my events.
Thanks a lot for any help.

**Comment by benmoran56** [comment]
Hi, 

The only way to do that would be to have the third event schedule the fourth event, at the end. As in: put the call the `schedule_once` inside the code for the third event. 

Just to note, blocking inside of an event like that will block the entire pyglet event loop (as it's all on the main thread). Depending on what type of application you're making that might be OK, but for games or realtime simulations it might get messy.

**Comment by benoitvalery** [comment]
So, if I understand well, it means that I have to schedule remaining events each time a blocking event happens, at the end of it (?)
Do you suggest there is absolutely no other way ? For instance, couldn't I modify the scheduler logic depending on a boolean ? Or having multiple chronometer (one for instantaneous events, one for blocking events) ? Thanks for your quick reply. I'm discovering `pyglet`, it's a wonderful library, very well designed in my opinion. Actually, I'm trying to replace the `PyQt` library which I find not "elegant" (to say it in few) at all, in the following project : https://github.com/juliencegarra/OpenMATB

**Comment by benmoran56** [comment]
That makes sense to me since you don't know how long the second event will take.

What are the events actually doing?

**Comment by benoitvalery** [comment]
The OpenMATB is a multitasking environment. For experimental purpose, we want to trigger some events at various time points. One event consists, in general, in starting/stopping/pausing/resuming a task in the environment, or in modifying one of its parameters (the color of an element, the performance threshold, and so on), that will be concretely refreshed during the `update` method. But the scenario we are reading can also start a blocking task (for instance a questionnaire), more precisely a task that has no duration a priori. Actually, the feature I'm loogin after is a kind of "false" pause, or, say, a pause (regarding my scenario scheduling) that would not freeze the whole program (to allow the user to interact with the questionnaire for instance).

**Comment by benoitvalery** [comment]
Any other suggestion ? For now, I plan to schedule the next event at the end of my blocking (undefined duration) event.

Could one other solution be to use several clocks ? One clock for discrete events (one parameter is changing at a given time), this clock would be paused during blocking events.

**Comment by benoitvalery** [comment]
So, here is how I solved my own question, and some advice if someone has the same issue:
- Do not try to tweak the clock for that purpose
- Better is to handle various "durations" in a general scheduler (see example below)
- Better was also not to try to schedule all events at once (schedule_once in a loop) but retrieve and execute them as a function of the current scenario duration.

Here is a minimal example of my Scheduler, I omitted things that are specific to my case. If some are interested by more complete code, please let me know.

```python
import pyglet.clock
from pyglet.app import EventLoop

class Scheduler:   
    def __init__(self):
        self.clock = pyglet.clock.get_default()
        self.state = 'scenario'     # 'scenario' or 'blocking'
        self.durations = {k: 0 for k in ['scenario', 'blocking']}
        self.blocking_plugin = None
        
    def execute_one_event(self, event):
        # Event routine
        pass        
 
    def update_scheduler_state(self):
        # Schedule actions as a function of scheduler state (e.g., hide anything but the blocking thing)
        pass
            
    def toggle_scheduler_state(self):
        self.state = [k for k in self.durations if k != self.state][0]
    
    def poll_for_events(self):
        # Code that returns the next event
        pass

    def update(self, dt):
        self.update_scheduler_state()
        self.durations[self.state] += dt
        
        # Potentially retrieve the next scenario event
        if self.state == 'scenario':
            event = next(self.poll_for_events())
            if event is not None:
                self.execute_one_event(event)

    def run(self):
        self.clock.schedule_interval(self.update, 1./120)
        self.event_loop = EventLoop()
        self.event_loop.run()
```
