### ISSUE TITLE
macOS: Can't open new windows after old windows have been closed and app has been stopped

### ISSUE THREAD

**Issue by benmaier** [pyglet/pyglet#257]
I'm very new to pyglet, so I might be making an obvious mistake, apologies in advance. I'm trying to run pyglet multiple times in one Python session because I'm using it as a visualization tool rather than a stand-alone application.

Following problem: when one window is closed and the main event loop is halted, creating and running a second window is impossible. The new window seems to be created but is not shown. Instead, the old window (which should have been deleted, I guess) is shown again but cannot be closed.

I'm using pyglet 1.5.7 on macOS 10.14.6.

Here's some example code that I've adapted from #225 :

```python
import pyglet

# small window
window = pyglet.window.Window(50,50)

@window.event
def on_mouse_motion(x, y, dx, dy):
    print('on_mouse_motion', x, y, dx, dy)

pyglet.app.run()

print("I've been closed and halted!")

# large window
window2 = pyglet.window.Window(100,100)

@window2.event
def on_mouse_motion(x, y, dx, dy):
    print('on_mouse_motion', x, y, dx, dy)

pyglet.app.run()
```

here's a video of the behavior: https://imgur.com/a/YyukMxU

**Comment by benmaier** [comment]
Running 

```
pytest tests/interactive
```

in the `v.1.5.7` branch of the pyglet repo yields the same behavior for me.

**Comment by caffeinepills** [comment]
You are running `pyglet.app.run` twice. You only need to call it once.

Refer to this example on multiple windows: https://github.com/pyglet/pyglet/blob/pyglet-1.5-maintenance/examples/multiple_windows.py

**Comment by benmaier** [comment]
So you can really only run it once? As I said, pyglet is really not the focus in my application, it's only there to occasionally visualize something. It might happen that I run my package in a Jupyter notebook, visualize something, close the visualization, do something else, then visualize something again. As pyglet blocks other code during `pyglet.app.run()`, it seems impossible to me to let it run in the background while doing other stuff.

Also, how do you folks run interactive tests then? I ran into this problem because I have automated test functions that start a visualization on their own. When I'm using pytest, this causes a problem. That's why I tried running the pyglet-tests of this repository where I'm encountering the same problem. E.g. tests in [tests/interactive/text/](https://github.com/pyglet/pyglet/tree/master/tests/interactive/text) call `pyglet.app.run()` on three different occasions within the same pytest run. On my machine, the tests are therefore impossible to conduct. But since they should be possible to run (as they are part of a test suite), it led me to believe that pyglet apps can be stopped and restarted at runtime, hence my raising this issue.

**Comment by caffeinepills** [comment]
The interactive tests work fine for me, and so does your example (on Windows). Pyglet blocks other code during `app.run` because of the event system. If you want to implement and call the events in your own loop manually you can: https://pyglet.readthedocs.io/en/latest/programming_guide/eventloop.html#dispatching-events-manually

As for your issue, it's possible it's an OS specific issue, Jupyter, or something in your environment. Unfortunately I myself don't use Mac, but maybe someone here has some experience.

**Comment by benmaier** [comment]
I see, thank you for your comments and this reference. I guess I do have an environment/OS issue then.

**Comment by benmoran56** [comment]
Closing due to age, but please follow up if you still have questions.
