### ISSUE TITLE
on_resize causes vertex lists to render at wrong position

### ISSUE THREAD

**Issue by essickmango** [pyglet/pyglet#266]
Whenever i subclass pyglet.window.Window and define a 'on_resize' event handler, it changes the origin of the coordinate system to the middle of the window and the scaling to +-0.5 / width and +-0.5 / height.
```
import pyglet

class Win(pyglet.window.Window):
    def __init__(self):
        super(Win, self).__init__(400, 600)

        self.vlist = pyglet.graphics.vertex_list(3, ('v2i', (0, 0, 200, 0, 200, 200)), ('c3B', (100, 100, 100, 100, 100, 100, 255, 100, 100)))

    def on_draw(self):
        self.clear()
        self.vlist.draw(pyglet.gl.GL_TRIANGLES)

    def on_resize(self, width, height):
        pass


app = Win()
pyglet.app.run()
```

Just comment the on_resize block in the example and it works as intended.

Specs:
pyglet 1.5.7

Linux Mint 20 (Ubuntu 20.04)
Intel Core i7-8550
-> Intel UHD Graphics 620

**Comment by caffeinepills** [comment]
`on_resize` resets the projection to the correct area when the window changes dimensions. By overriding it, you are removing it's default behavior to where it does nothing.

You either need to not subclass window and create your own handler to push or restore `on_resize`'s default behavior:
```
    def on_resize(self, width, height):
        self._projection.set(width, height, *self.get_framebuffer_size())
```

**Comment by essickmango** [comment]
that makes sense and a super call fixes the issue, thanks. I'll look into amending the docs so that it's stated in the 'subclassing Window' section.
