### ISSUE TITLE
Pyglet crashes on macOS when configuring the OpenGL context version

### ISSUE THREAD

**Issue by kollmats** [pyglet/pyglet#272]
Hi,

I'm trying to use GLSL 3.3 on macOS High Sierra 0.13.1, pyglet 1.5.7. However, when trying to set the version like so:

```
from pyglet.window import Window
from pyglet.gl import Config
Window(config=Config(major_version=int(a), minor_version=int(b)))
```

I get the following crash:

> Traceback (most recent call last):
  File "test.py", line 6, in <module>
    from pyglet.window import Window
  File "/usr/local/lib/python3.7/site-packages/pyglet/window/__init__.py", line 648, in __init__
    self._create()
  File "/usr/local/lib/python3.7/site-packages/pyglet/window/cocoa/__init__.py", line 197, in _create
    self.context.attach(self.canvas)
  File "/usr/local/lib/python3.7/site-packages/pyglet/gl/cocoa.py", line 300, in attach
    self._nscontext.setView_(canvas.nsview)
AttributeError: 'NoneType' object has no attribute 'setView_'

Additional info:

It seems like pyglet invokes [NSOpenGLContext](https://developer.apple.com/documentation/appkit/nsopenglcontext/1436178-initwithformat?language=objc) of Cocoa with invalid parameters, causing it to return a None value (that does not happen for, e.g., OpenGL 2.1). This can happen due to an inconsistency in pixel formats (which I've checked and ruled out) or if the "share" parameter points to an invalid OpenGL context.

**Comment by kollmats** [comment]
After some further digging, I was able to get around this by disabling the pyglet shadow context. I also noticed that the documentation addresses this [here](https://pyglet.readthedocs.io/en/latest/programming_guide/context.html?highlight=shader#sharing-objects-between-contexts), but that the actual fix is somewhat different. 

The documentation suggests that the shadow context must be disabled before a ``Window`` is _created_, but my observation is that the shadow context has to be disabled before _importing_  ``pyglet.window``.

I took the liberty of creating a [PR](https://github.com/pyglet/pyglet/pull/273).

**Comment by einarf** [comment]
Just linking moderngl-window's pyglet window as well in case someone need a more specific example :  https://github.com/moderngl/moderngl-window/blob/master/moderngl_window/context/pyglet/window.py

**Comment by einarf** [comment]
Also, master branch makes 3.3 core context currently by default.

**Comment by einarf** [comment]
Also: If you are using pyglet's gl bindings for GL 3.3 core I made a moderngl-ish 3.3 core wrapper with pyglet in arcade : https://arcade.academy/arcade_gl.html
It could potentially save you a lot of time. It can be used with pyglet directly by instantiating a `Context`.

**Comment by einarf** [comment]
I am also seeing this when not using the default config in the current master branch. This is a new problem compared to 1.5.x. I might be able to look at this.

**Comment by benmoran56** [comment]
Hi Kollmats, your pull request is now in the current documentation.
If it's OK we can close this for now. Once pyglet 2.0 is released, it will default to the core profile (and shouldn't have these issues).

**Comment by kollmats** [comment]
Definitely! Thanks 👍
