### ISSUE TITLE
AttributeError: 'TextureBin' object has no attribute '_border'

### ISSUE THREAD

**Issue by yegarti** [pyglet/pyglet#275]
Hi,
I'm trying to run the examples over a cloned repo (master branch) and getting an error when running the 'image_viewer' example from examples/programming_guide/image_viewer.py over Python 3.8.
I'm getting this error:
```
Traceback (most recent call last):
  File "image_viewer.py", line 45, in <module>
    image = pyglet.resource.image('kitten.jpg')
  File "/home/yehudag/git/pyglet/pyglet/resource.py", line 587, in image
    identity = self._cached_images[name] = self._alloc_image(name, atlas, border)
  File "/home/yehudag/git/pyglet/pyglet/resource.py", line 526, in _alloc_image
    return bin.add(img, border)
  File "/home/yehudag/git/pyglet/pyglet/image/atlas.py", line 274, in add
    atlas = TextureAtlas(self.texture_width, self.texture_height, self._border)
AttributeError: 'TextureBin' object has no attribute '_border'
```

Example works under pyglet-1.5-maintenance.
Thanks.

**Comment by DoAltPlusF4** [comment]
The master branch is currently unstable, and the examples are thus undergoing a rewrite.
I would recommend using the `pyglet-1.5-maintenance` branch, as that is what is installed via PIP.
