### ISSUE TITLE
set_icon() is not working

### ISSUE THREAD

**Issue by yogarasu** [pyglet/pyglet#277]
I tried setting an icon on the window but It is not working.

I follow the document,
Added icons for all resolutions of 16x16, 24x24, 32x32, 48x48, 72x72, 128x128.

```python
window = pyglet.window.Window()
icon1 = pyglet.image.load('16x16.png')
icon2 = pyglet.image.load('32x32.png')
icon3 = pyglet.image.load('48x48.png')
icon4 = pyglet.image.load('72x72.png')
icon5 = pyglet.image.load('128x128.png')
window.set_icon(icon1, icon2, icon3, icon4, icon5)
```
https://pyglet.readthedocs.io/en/latest/programming_guide/windowing.html

My environment is as follows.
Please tell me if there are any improvements or mistakes regarding this matter.

```
Mac OS: 10.15.6
Python: 3.8.5
Pyglet: 1.5.7
```

**Comment by LennyPhoenix** [comment]
Do you get an error when running set_icon, or does it just not set the window icon correctly?

**Comment by caffeinepills** [comment]
Closing as unresponsible
