### ISSUE TITLE
static analysis tools problems with pyglet

### ISSUE THREAD

**Issue by Eric-Arz** [pyglet/pyglet#286]
this is based on #https://github.com/microsoft/pylance-release/issues/474

some static analysis tools including pylance have trouble providing correct and meaningful code completion for pyglet. After opening an issue for pylance their suggest to fix/improve this was this:

change pyglet/__init__.py

```
if True:
    app = _ModuleProxy("app")
    ...

if False:
    from . import app
    ...
```

If you change this to the following, it will retain its lazy loading but also work fine with Pylance:

```
from typing import TYPE_CHECKING

if not TYPE_CHECKING:
    app = _ModuleProxy("app")
    ...

if TYPE_CHECKING:
    from . import app
    ...
```

**Comment by LennyPhoenix** [comment]
This would probably be a good idea to add, it might fix a couple other problems with compilers such as Nuitka too.

**Comment by Eric-Arz** [comment]
Should i open a PR?

**Comment by LennyPhoenix** [comment]
Sure 👍

**Comment by Eric-Arz** [comment]
I made a pull request for the change: #https://github.com/pyglet/pyglet/pull/287
