### ISSUE TITLE
Bogus files in 1.5.8 zip distribution

### ISSUE THREAD

**Issue by AMDmi3** [pyglet/pyglet#291]
https://pypi.org/packages/source/p/pyglet/pyglet-1.5.8.zip distribuition contains some files not present in git, namely `pyglet/gl/eglcontext.py` and `pyglet/media/workerthreads.py`. The latter breaks packaging as it contains incorrect python2 style prints

```python
        if _debug:
            print 'MediaThread.stop()'
```

which break centralized `*.pyo` generation.

**Comment by benmoran56** [comment]
Ouch! Thanks for opening the issue. Looks like some un-commited test files from another branch slipped in.

**Comment by benmoran56** [comment]
Hi @AMDmi3 we just pushed out a v1.5.9 release, which should be clean. 
Please let me know if you see any issues.

**Comment by AMDmi3** [comment]
No problems with 1.5.9, I've already updated FreeBSD ports. Thanks!
