### ISSUE TITLE
display.get_screens() returns NotImplementedError:abstract

### ISSUE THREAD

**Issue by idioteque77** [pyglet/pyglet#292]
Trying to get a screen does not work, display.get_screens() returns NotImplementedError:abstract

pyglet version: 1.5.8
IDE: Spyder

Traceback (most recent call last):

  File "C:\Users\x\.spyder-py3\HelloWorld.py", line 12, in <module>
    screen = display.get_screens()

  File "C:\Program Files\WPy64-3850\python-3.8.5.amd64\lib\site-packages\pyglet\canvas\base.py", line 98, in get_screens
    raise NotImplementedError('abstract')

NotImplementedError: abstract

**Comment by LennyPhoenix** [comment]
Just tried this out and it seemed to work fine:
```py
Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyglet
>>> window = pyglet.window.Window()
>>> display = window.display
>>> display.get_screens()
[Win32Screen(x=0, y=0, width=1920, height=1080)]
```
How are you grabbing your display object?

**Comment by idioteque77** [comment]
Thanks LennyPhoenix. Intially, I tried this call (in Spyder) and got the reported error: 

display = pyglet.canvas.Display()
screen = display.get_screens()

When I try this call - or the one you posted - in the Python shell and in Pyzo, it works. No idea what causes the error in Spyder.
