### ISSUE TITLE
pyglet 1.5 crash when noisy.py loads ball image (windows)

### ISSUE THREAD

**Issue by ccanepa** [pyglet/pyglet#296]
noisy.py crashes with

```
(3.7.7) D:\dev\pyglet_pillow>python noisy.py
Traceback (most recent call last):
  File "noisy.py", line 66, in <module>
    class Ball(pyglet.sprite.Sprite):
  File "noisy.py", line 67, in Ball
    ball_image = pyglet.resource.image(BALL_IMAGE)
  File "d:\dev\cocos-testcmp\work\pyglet\pyglet\resource.py", line 575, in image

    identity = self._cached_images[name] = self._alloc_image(name, atlas, border
)
  File "d:\dev\cocos-testcmp\work\pyglet\pyglet\resource.py", line 502, in _allo
c_image
    img = pyglet.image.load(name, file=file)
  File "d:\dev\cocos-testcmp\work\pyglet\pyglet\image\__init__.py", line 191, in
 load
    image = decoder.decode(file, filename)
  File "d:\dev\cocos-testcmp\work\pyglet\pyglet\image\codecs\wic.py", line 386,
in decode
    bitmap_decoder, stream = self._load_bitmap_decoder(file, filename)
  File "d:\dev\cocos-testcmp\work\pyglet\pyglet\image\codecs\wic.py", line 311,
in _load_bitmap_decoder
    ole32.CreateStreamOnHGlobal(hglob, True, byref(stream))
TypeError: byref() argument must be a ctypes instance, not 'IUnknown'
```
Windows 7
py 3.7.7
pyglet 1.5 maintenance from github:
```
git log
commit 0de2c9b03ee645170c4aa678ba29de3504ba70e0 (HEAD -> pyglet-1.5-maintenance,
 origin/pyglet-1.5-maintenance)
Author: caffeinepills
Date:   Sun Oct 18 22:47:49 2020 -0500
```

**Comment by ccanepa** [comment]
In the previous (in branch 1.5 history) checkout,  a39ebc20, which is also pyglet release 1.5.8 noisy works normal, so the problem was introduced at 0de2c9b03, "Support for Xaudio2 driver" which changes a lot in com.py

**Comment by caffeinepills** [comment]
Currently out of town but I'm guessing line `stream = com.IUnknown()` needs to be `stream = com.pIUnknown()` which was missed in the refactor.

**Comment by benmoran56** [comment]
@caffeinepills 
I gave that a change, but then saw another issue further down the line. Trying to fix that gave me a deeper ctypes error, which I wasn't able to understand yet. 

I was thinking to push out a point update shortly. Do you think we should disable the WIC codec for the moment? The XAudio2 code on the other hand seems to be working well, so it seems a little overkill to roll that back as well.

**Comment by caffeinepills** [comment]
My apologies, `com.IUnknown` should be find/replaced for `com.pIUnknown` in the whole file . I started XAudio2 branch before I created WIC, so that's why it was missed.

**Comment by caffeinepills** [comment]
#298 should fix it, tested with noisy on Windows 10 and Python 3.7,

**Comment by ccanepa** [comment]
tested the merged PR, no problems.

**Comment by benmoran56** [comment]
Great! Thanks for the PR caffeine, and thanks for your testing @ccanepa!
I'll close this for now.
