### ISSUE TITLE
array.array.tostring has been removed in favor of tobytes in Python 3.9

### ISSUE THREAD

**Issue by tirkarthi** [pyglet/pyglet#302]
https://github.com/pyglet/pyglet/blob/bb9b9ffc6e07a8352dc5ccefbfd1d34f2b4f488e/pyglet/image/codecs/png.py#L73

https://docs.python.org/3/whatsnew/3.9.html#removed

**Comment by benmoran56** [comment]
Thanks for opening the ticket. This will be addressed in the next point release, due shortly.

**Comment by benmoran56** [comment]
This should be fixed in the 1.5.9 release which is out now. I'll close this for now, but please reopen if you see any issues. 
Thanks!

**Comment by tirkarthi** [comment]
Thanks @benmoran56 . For reference this was found through : https://github.com/openai/gym/pull/1804

**Comment by benmoran56** [comment]
Thanks. Looks like Github actually automatically referenced that issue as well. It looks like they are talking about targeting recent releases of pyglet on that issue, which is certainly a good idea. Lots of little bug fixes have gone in over the last year.
