### ISSUE TITLE
pyglet.window.Window : is it possible to change style ?

### ISSUE THREAD

**Issue by deltasfer** [pyglet/pyglet#308]
Hello there,
I am trying to create a window with pyglet that can altern between `borderless-maximized` window and `regularly-maximized` window.
By reading the documentation (and `pyglet/window/win32/__init__.py`) I found that we can not easily altern between these styles.

I am using for now the `window.set_fullscreen()` method but I have a problem with this method : while being fullscreen the window takes all the focus of the screen, even when the program is not captioned anymore (example : when I `alt-tab` i can't see my others running progams, ide or else, the pyglet window is freezed on the screen).
In comparison, a pyglet `borderless-maximized` is exactly what i'm looking for because of this non-focus parameter.

Is there any way I can achieve this ?
What are exactly the differences between a `borderless-maximised` and `fullscreen` window ?

I found nothing on the docs but maybe it's explained somewhere soo forgive me please 🙏 😄
I am using pyglet 1.5.8 with python 3.6.4

PS: I am french so sorry for the potential language mistakes ^^*

**Comment by benmoran56** [comment]
Hi deltasfer, 

I don't think most platforms support changing the Window style after creation.
For many games/applications, the Window is re-created instead. 
1. `Window.close()` the old window.
2. Create a new Window, with the new style. 

> What are exactly the differences between a borderless-maximised and fullscreen window ?

Generally speaking, "fullscreen" will change the monitor resolution. "borderless maximized" does not change the resolution. It just makes a borderless window, that is the same size as the desktop resolution.

**Comment by deltasfer** [comment]
Hmm i see..
The problem is that I defined my application as a child class of pyglet.window.Window.. soo I can't close the window and re-create it with the style without re-creating an instance of my App class isn't it?

My main.py is made pretty much like that :


    import pyglet

    class App(pyglet.window.Window):

        def __init__(self):

            style = None
            super(App,self).__init__(style=style)

            pyglet.clock.schedule_interval(self.gameloop,0.0000000000001)
            pyglet.app.run()

        def myothersfunctionsoftheclass():
            #...

        def on_key_press(self,symbol,modifiers):


        def gameloop(self,dt):

            # events
            # clear
            # draw
            # refresh
            
    def main():
        app = App()

    if __name__ == '__main__':
        main()

**Comment by benmoran56** [comment]
Yes, you wouldn't be able to do that if you're subclassing. Subclassing Window is simple and fine for most cases, but not something like this. You could just define Window as an attribute of App, and just push your event handlers. Something like this: 
```py
class App:

    def __init__(self):
        self.window = pyglet.window.Window()
        self.window.push_handlers(self)

        pyglet.clock.schedule_interval(self.gameloop, 1/120)
        pyglet.app.run()

    def myothersfunctionsoftheclass(self):
        pass

    def on_key_press(self, symbol, modifiers):
        if symbol == pyglet.window.key.SPACE:
            new_window = pyglet.window.Window(style=pyglet.window.Window.WINDOW_STYLE_BORDERLESS)
            new_window.push_handlers(self)
            self.window.close()
            self.window = new_window

    def gameloop(self, dt):
        self.window.clear()


def main():
    app = App()


if __name__ == '__main__':
    main()
```

**Comment by deltasfer** [comment]
All right then I will try this !
Thank you for your help <3
