### ISSUE TITLE
Travis CI: Pytest is failing right away without much feedback

### ISSUE THREAD

**Issue by cclauss** [pyglet/pyglet#31]
This happens locally on my Mac, on Travis on Linux and macOS on Python 2 and Python 3.

I would be happy to work together with someone on this.  On Travis (./.travis.yml) we are currently trying to install on Ubuntu 16.04.6 Xenial and it would be good to know if we are missing important __apt__ or __pip__ dependencies.  Is Bionic preferred over Xenial or should they both work?

* https://docs.travis-ci.com/user/gui-and-headless-browsers

**Comment by benmoran56** [comment]
Hi Clauss, 

Thanks for your help on this. Either Bionic or Xenial should be fine. For the tests themselves, we will want to limit them a bit. `pytest tests/unit` tests *should* be runable without any specific drivers available (but will likely still fail until we do a little cleanup). 

`pytest tests/integration` are tests that require an OpenGL context. If I understand it correctly, the Travis xvfb should provide the ability to create this context with a software renderer fallback, which should still be adequate for the tests. Maybe we also need to manually install some additional MESA libraries for this, if they're not included in the Travis base? 

`pytest tests/interactive` should not be run under CI.

**Comment by cclauss** [comment]
Ideas put into  #32
