### ISSUE TITLE
batch objects updated from functions/methods do not draw some objects

### ISSUE THREAD

**Issue by pedro-javierf** [pyglet/pyglet#317]
The following code creates a batch, adds a basic square shape to it, and draws it without problem:

```python
   import pyglet
   from pyglet import *

   window = pyglet.window.Window()
   mainBatch = pyglet.graphics.Batch()
   square = shapes.Rectangle(200, 200, 200, 200, color=(55, 255, 255), batch=mainBatch)
   fps_display = pyglet.window.FPSDisplay(window=window)

    @window.event
    def on_draw():
        window.clear()
        fps_display.draw()
        mainBatch.draw()


    pyglet.app.run()
```

However, if the batch is passed to a function or method, and such function updates the batch, then when it is drawn such object isn't drawn. **This seems to affect only some objects and not others.**

Code that doesn't work:

```python
 import pyglet
 from pyglet import *


 window = pyglet.window.Window()
 mainBatch = pyglet.graphics.Batch()

 updateBatch(mainBatch)


 fps_display = pyglet.window.FPSDisplay(window=window)

    @window.event
    def on_draw():
        window.clear()
        fps_display.draw()
        mainBatch.draw()


    pyglet.app.run()


 def updateBatch(batch=None):
     square = shapes.Rectangle(200, 200, 200, 200, color=(55, 255, 255), batch=batch)
```

I have tried different variations of this. For example, if the batch is a global variable (so it can be accessed from the method without passing it) it doesn't work either.

On the other hand, objects like labels, are being drawn. The following example works:

```python
def updateBatch(batch=None):
     score_label = pyglet.text.Label(text="Score: 0", x=100, y=75, batch=batch)
```

This seems to affect shapes, but perhaps sprites as well (see this person post, experiencing the same issue): https://www.reddit.com/r/learnpython/comments/94ti7j/pyglet_sprite_addition_to_batch_not_working_as/

**Hardware experiencing the issue:**
- NVIDIA Geforce GTX 1650
- Windows 10
- Python 3.8
- pyglet 1.5.11

**Comment by benmoran56** [comment]
Hi, 

Your issue is due to garbage collection. Sprites and Shapes will automatically delete themselves from the Batch when they fall out of scope. Labels do not have the same behavior (maybe they should?). Sprites have always had this behavior, and the new Shapes module was modeled after that behavior. 

In this example: 
```py
 def updateBatch(batch=None):
     square = shapes.Rectangle(200, 200, 200, 200, color=(55, 255, 255), batch=batch)
```
the `square` instance will fall out of scope and be deleted, since it's local to the function. You will need to return the object from the function, and make a reference to it somewhere.

**Comment by pedro-javierf** [comment]
That seems to solve it 👍 
Adding the `square` instances to a list in the main scope maintains a reference and the objects are no longer garbage-collected.
I make sure to clear() the list after the square has been drawn to the screen so then the memory is freed.

Thanks

**Comment by benmoran56** [comment]
Great! 

To be sure that it's freed immediately, you should call the `.delete()` method on the objects. In Python, the garbage collection is not guaranteed to be called immediately (especially with other interpreters, such as PyPy, etc.).

**Comment by matanster** [comment]
To avoid this explicit garbage collection prevention, can one build the batch in the calling function rather than while declaring the shapes?

**Comment by matanster** [comment]
Okay, I guess if we use class methods then we avoid the garbage collection more naturally, as in the example game code.

**Comment by matanox** [comment]
Is this because there's no good way for pyglet to mark shapes as being in use (in terms of garbage-collection) once adding them to a batch?
