### ISSUE TITLE
Positional Audio appears to not work with XAudio2

### ISSUE THREAD

**Issue by Cleptomania** [pyglet/pyglet#325]
I am using the 3D Positional Audio capabilities of Pyglet to handle sound panning in the 2D Engine [Arcade](https://arcade.academy)

This works fine, however I've noticed it only works with the OpenAL driver. When using XAudio2 I hear no difference in the audio, when using DirectSound I hear a very faint difference but definitely there. 

I've resolved this issue within Arcade by changing the driver priority to choose OpenAL first, which is perfectly acceptable for us for now I think, but figured I'd bring this up here.

Environment Tested With:

- Python 3.8.6
- Pyglet 1.5.11
- OS: Windows 10 Home 19041

I've setup a minimal example of this below, pressing Q to pan fully to the left, W for no panning, and E for panning fully to the right. You can play with the values if you want but this works extremely well for mimicking panning with OpenAL, however there is seemingly no effect at all with XAudio2:

```python
import pyglet
import math

pyglet.options["audio"] = ("xaudio2",)
# pyglet.options["audio"] = ("openal",)

class AudioTest(pyglet.window.Window):
    def __init__(self):
        super(AudioTest, self).__init__()
        self.sound = pyglet.media.load("sound.wav")
        self.player = pyglet.media.Player()

    def on_key_press(self, symbol, modifiers):
        if symbol == pyglet.window.key.Q:
            self.player.position = (-1.0, 0.0, math.sqrt(1 - math.pow(-1.0, 2)))
            self.player.queue(self.sound)
            self.player.play()
        if symbol == pyglet.window.key.W:
            self.player.position = (0.0, 0.0, math.sqrt(1 - math.pow(0.0, 2)))
            self.player.queue(self.sound)
            self.player.play()
        if symbol == pyglet.window.key.E:
            self.player.position = (1.0, 0.0, math.sqrt(1 - math.pow(1.0, 2)))
            self.player.queue(self.sound)
            self.player.play()


if __name__ == "__main__":
    print(pyglet.media.get_audio_driver())
    window = AudioTest()
    pyglet.app.run()
```

**Comment by caffeinepills** [comment]
I just tested it with our 3D audio example (examples/media/soundspace) and it sounds like it is behaving as it should.

Moving the listener to each of the sounds makes them louder, or moving each emitter to the listener works as well.

It's possible the orientations are reversed, but not entirely sure as it seems to work in the example with the various drivers.

Try adding this:
```listener = pyglet.media.get_audio_driver().get_listener()
listener.forward_orientation = (0, 0, 1)
listener.up_orientation = (0, -1, 0)
```

**Comment by caffeinepills** [comment]
#327 

Should solve the issue. Tested with your example and it is working now. Thanks for the report.

**Comment by Cleptomania** [comment]
Thanks for the quick fix on this. I'll close the issue since I see it's been merged in already.
