### ISSUE TITLE
sound delay with video by pyglet

### ISSUE THREAD

**Issue by veyron-github** [pyglet/pyglet#330]
Play video with Pyglet, the sound is delayed and out of sync with the video screen. I had choose many kind of video type, the problem is also coming, which is really bother me.
code like this:

import pyglet

window=pyglet.window.Window()

path='myvideo.mp4'
source=pyglet.media.load(path)
player = pyglet.media.Player()
player.queue(source)
player.play()
@window.event
def on_draw():
    window.clear()
    player.get_texture().blit(0,0)

pyglet.app.run()

**Comment by veyron-github** [comment]
Another thing is ,when the video start playing ,there was a noise can hear

**Comment by benmoran56** [comment]
Hi,  are you using Windows? 

You will need FFmpeg dlls for accelerated video playback. Windows has some support for decoding videos without FFmpeg, but it's only suitable for smaller files. You can check if FFmpeg is available by listing the decoders:
```py
pyglet.media.get_decoders()
```

**Comment by veyron-github** [comment]
> You will need FFmpeg dlls for accelerated video playback. Windows has some support for decoding videos without FFmpeg, but it's only suitable for smaller files. You can check if FFmpeg is available by listing the decoders:
I use Windows，and I have installed FFmpeg，following is when I check by decoders. 
I try the video files size from 39MB to 399MB，still have the problems. Do you mean that I should do some prepare work to do this?

 pyglet.media.get_decoders()
Out[2]: 
[WaveDecoder('.wav', '.wave', '.riff'),
 WMFDecoder['.asf', '.wma', '.wmv', '.mp3', '.sami', '.smi', '.3g2', '.3gp', '.3gp2', '.3gp', '.aac', '.adts', '.avi', '.m4a', '.m4v', '.mov', '.mp4', '.mkv', '.flac', '.ogg']]

**Comment by benmoran56** [comment]
Have a look at the documentation here. The easiest method is to put the FFmpeg DLLs 
in the `yourapp/lib` directory.

https://pyglet.readthedocs.io/en/latest/programming_guide/media.html#ffmpeg-installation

**Comment by veyron-github** [comment]
> Have a look at the documentation here. The easiest method is to put the FFmpeg DLLs
> in the `yourapp/lib` directory.
> 
> https://pyglet.readthedocs.io/en/latest/programming_guide/media.html#ffmpeg-installation

I have read the website several times, and try to follow the means from the readthedocs, but I didn't succeed. There is no problems to play the music, but it bothers me a lot when it comes to video . 
I have download the share build 64 for windows, and take it to the system path ( bin directory)，the problem happen as usual. And I want to try :
''This will allow pyglet to find the FFmpeg binaries in the lib sub-folder located in your running script folder.''. But the meaning here is not very clear . I want to search how to do this in the internet , but I can't find any tutorial.

Fianlly , I want to now, is there a way to achieve this that play a video by pyglet whether or not the computer has install the ffmpeg.  For example , I want to pack the .py file to the .exe file , in this way while I take this file to another computer , how it could work if the computer doesn't have ffmpeg?

**Comment by benmoran56** [comment]
If you have downloaded the correct shared libs, then they should go into a directory like this: 

```py
/myapplication/libs/     <----- put the FFmpeg dlls here
/myapplication/myapp.py
/myapplication/etc.py
```
Then, you need to tell pyglet where to look. 
```py
import pyglet
pyglet.options['search_local_libs'] = True

...

pyglet.app.run()
```

You can confirm if the dlls are found correctly by using the following function: 
```py
import pyglet
pyglet.options['search_local_libs'] = True

print("FFmpeg DDLs found: ", pyglet.media.have_ffmpeg())
```
If this does not work, you can try to create an FFmpeg decoder manually. If `have_ffmpeg()` is `False`, then this **will** crash. The error message might give you some ideas: 
```py
import pyglet
decoder = pyglet.media.codecs.ffmpeg.FFmpegDecoder()
```

> Fianlly , I want to now, is there a way to achieve this that play a video by pyglet whether or not the computer has install the ffmpeg. For example , I want to pack the .py file to the .exe file , in this way while I take this file to another computer , how it could work if the computer doesn't have ffmpeg?

Yes, you can do this. PyInstaller is know to work.

**Comment by veyron-github** [comment]
![directory-picture](https://user-images.githubusercontent.com/61876709/102901677-e01b1d80-44a8-11eb-892f-cb2419dfb1f4.png)
The share build I had download is ''ffmpeg-N-100449-g28aedc7f54-win64-gpl-shared'',which contains bin,  lib,  doc, include. I am not sure whether if  I should get 8 .dll files from bin directory, and take these to the libs directory of the script folder. 

And I when I use _pyglet.media.codecs.ffmpeg.FFmpegDecoder()_ ,I get this:
Traceback (most recent call last):
 
 File "I:\myfiles\Pythonwork\Pycharm\pythonProject\test\test-video.py", line 11, in <module>
    decoder = pyglet.media.codecs.ffmpeg.FFmpegDecoder()
AttributeError: module 'pyglet.media.codecs' has no attribute 'ffmpeg'

**Comment by veyron-github** [comment]
> If you have downloaded the correct shared libs, then they should go into a directory like this:
> 
> ```python
> /myapplication/libs/     <----- put the FFmpeg dlls here
> /myapplication/myapp.py
> /myapplication/etc.py
> ```
> 
> Then, you need to tell pyglet where to look.
> 
> ```python
> import pyglet
> pyglet.options['search_local_libs'] = True
> 
> ...
> 
> pyglet.app.run()
> ```
> 
> You can confirm if the dlls are found correctly by using the following function:
> 
> ```python
> import pyglet
> pyglet.options['search_local_libs'] = True
> 
> print("FFmpeg DDLs found: ", pyglet.media.have_ffmpeg())
> ```
> 
> If this does not work, you can try to create an FFmpeg decoder manually. If `have_ffmpeg()` is `False`, then this **will** crash. The error message might give you some ideas:
> 
> ```python
> import pyglet
> decoder = pyglet.media.codecs.ffmpeg.FFmpegDecoder()
> ```
> 
> > Fianlly , I want to now, is there a way to achieve this that play a video by pyglet whether or not the computer has install the ffmpeg. For example , I want to pack the .py file to the .exe file , in this way while I take this file to another computer , how it could work if the computer doesn't have ffmpeg?
> 
> Yes, you can do this. PyInstaller is know to work.



Today I have try this again, and I find that the directory must be name _lib_ which contains 10 .dll files (It can't be named _libs_ as what you say before). Only in this way to get the this:
_FFmpeg DDLs found:  True_

However，when I play the video the sound still delay , I use the code:
_decoder = pyglet.media.codecs.ffmpeg.FFmpegDecoder()
print(decoder)_
And the result is：_FFmpegDecoder('.mp3', '.ogg')_

I don't know how to do now.
![result](https://user-images.githubusercontent.com/61876709/102950805-526e1b00-4506-11eb-92ed-1438582302a0.png)

**Comment by benmoran56** [comment]
What type of video are you trying to play? (format, resolution, fps, etc.)
If you can provide a video sample, I can test it on my machine.

**Comment by veyron-github** [comment]
test file 1:
mp4
video——time 00:33:55; frame  width 1024，height 576; data rate 999kbps； total bit rate 1127kbps; frame rate 23.98 per second
sound——total rate 128kbps ; channel 2，stereo; Audio sampling frequency 44.100 kHz.

test file 2:
mp4
video——time 00:23:05; frame  width 1024，height 440; data rate 994kbps； total bit rate 1122kbps; frame rate 23.98 per second
sound——total rate 127kbps ; channel 2，stereo; Audio sampling frequency 44.100 kHz.

test file 3:
mp4
video——time 02:01:55; frame  width 1280，height 720; data rate 1387kbps； total bit rate 1483kbps; frame rate 24 per second
sound——total rate 95kbps ; channel 2，stereo; Audio sampling frequency 48.000 kHz.

Test code :

_import pyglet
pyglet.options['search_local_libs'] = True
print("FFmpeg DDLs found: ", pyglet.media.have_ffmpeg())
decoder = pyglet.media.codecs.ffmpeg.FFmpegDecoder()
print(decoder)

window = pyglet.window.Window(caption='video',resizable=True)

path = 'myvideo.mp4'
source = pyglet.media.load(path)
player = pyglet.media.Player()
player.queue(source)

player.play()

@window.event
def on_draw():
    window.clear()
    player.get_texture().blit(0,0)
pyglet.app.run()_

out put:
_FFmpeg DDLs found:  True
FFmpegDecoder('.mp3', '.ogg')
Process finished with exit code 0_


https://user-images.githubusercontent.com/61876709/102972414-f9b67680-4535-11eb-90c4-22ee4c963caa.mp4

**Comment by veyron-github** [comment]
> What type of video are you trying to play? (format, resolution, fps, etc.)
> If you can provide a video sample, I can test it on my machine.


I think I get the reason,  just as this code:
_decoder = pyglet.media.codecs.ffmpeg.FFmpegDecoder()
print(decoder)_

out put:
_FFmpegDecoder('.mp3', '.ogg')_

print(pyglet.media.get_decoders())

out put:
 [WaveDecoder('.wav', '.wave', '.riff'), WMFDecoder['.asf', '.wma', '.wmv', '.mp3', '.sami', '.smi', '.3g2', '.3gp', '.3gp2', '.3gp', '.aac', '.adts', '.avi', '.m4a', '.m4v', '.mov', '.mp4', '.mkv', '.flac', '.ogg'], FFmpegDecoder('.mp3', '.ogg')]

You can see that, the FFmpegDecoder only contains the sound format ('.mp3', '.ogg' ) ,not one video format there. So I think it wasn't the problem about the video format.  I am not sure how long I can deal with this problem, but I real need a way to play the video by pyglet.

I find that vlc is very useful to play the video in the PyQt and tkinter. Is there a way to use vlc in pyglet? Certainly, it could be best if the FFmpeg has no problem to use.

**Comment by caffeinepills** [comment]
The music video example is a bad example as there is no frame of reference for syncing, it doesn't follow any character's voice. I can't tell any difference to be honest.

Ffmpeg doesn't list all of the formats it supports as there are too many to list. It is mostly a fallback decoder incase there are problems with the others or you want hardware acceleration. 

You could try using the older audio driver as I believe it had some time adjustments to fix clock issues with slower machines when decoding video.

Add `pyglet.options["audio"] = ["directsound"]` after importing pyglet and see if that makes any difference in sync.

**Comment by benmoran56** [comment]
Closing due to lack of reply. Please open a new ticket if you still have issues.
