### ISSUE TITLE
Test tests/interactive/graphics/test_multitexture.py::test_multitexture hangs

### ISSUE THREAD

**Issue by tillea** [pyglet/pyglet#346]
Hi,
the Debian packaged version of pyglet (1.4.10) has received a [bug report](https://bugs.debian.org/980635) about a test that hangs and needs to be killed:

    tests/integration/window/test_window_caption.py::test_window_caption_from_argv PASSED [ 40%]
    tests/interactive/graphics/test_multitexture.py::test_multitexture 
    E: Build killed with signal TERM after 150 minutes of inactivity

I updated the packaging to the latest upstream version (1.5.14) and tried a local build which leads exactly to the same issue.  Debian builds are done in a quite restricted build environment.  To provide a X server environment xvfb is used.  Here is the actual call of the test suite that is used:

    xvfb-run --auto-servernum --server-num=20 -s "-screen 0 1024x768x24 -ac +extension GLX +render -noreset" python3.9 -m pytest -v -k "not interactive and not PulseAudio and not test_pulse and not test_player_play and not test_player_play_multiple and not test_player_silent_audio_driver and not test_freetype_face and not test_fontconfig and not test_linux_fontconfig and not test_driver and not test_openal and not ClockTimingTestCase"

I wonder whether you might spot any obvious issue with this testing procedure.  Debian recently switched to Python3.9 - may be this is causing some trouble since when Python3.8 was used the test was running nicely.
Kind regards, Andreas.

**Comment by benmoran56** [comment]
Thanks for opening the ticket. I was also able to replicate it locally. Multisampling is not something that is supported by all GL drivers, so it's also possible to be some bug specific to xvfb and Python 3.9. Running the test with a normal X/GL drivers do not have any issues. 

I would just suggest that you skip that test, since it's not really meaningful to do it headless anyway. In fact I would skip the entire `tests/interactive` suite. The interactive tests are mostly just stressing the OpenGL drivers (which is not very useful in this scenario).  

Out CI test string looks something like this: 
```py
pytest --ignore=tests/base --ignore=tests/interactive --ignore=tests/integration/media --ignore=tests/integration/font --ignore=tests/integration/platform/test_linux_fontconfig.py
```

On a last note, is it not possible to package the latest pyglet release in Debian? The 1.4.x branch is very old at this point, and has many issues that are fixed in later releases. There are also a few Python 3.8/3.9 specific fixes that have gone into recent releases, so I wouldn't recommend using the 1.4.x branch at all on Python > 3.7.  Let me know if there is anything I can do on our end that might help this along.

**Comment by tillea** [comment]
Hi Benjamin,

On Fri, Jan 29, 2021 at 01:36:09AM -0800, Benjamin wrote:
> Thanks for opening the ticket. I was also able to replicate it locally. Multisampling is not something that is supported by all GL drivers, so it's also possible to be some bug specific to xvfb and Python 3.9. Running the test with a normal X/GL drivers do not have any issues. 
> 
> I would just suggest that you skip that test, since it's not really meaningful to do it headless anyway. In fact I would skip the entire `tests/interactive` suite. The interactive tests are mostly just stressing the OpenGL drivers (which is not very useful in this scenario).  
> 
> Out CI test string looks something like this: 
> ```py
> pytest --ignore=tests/base --ignore=tests/interactive --ignore=tests/integration/media --ignore=tests/integration/font --ignore=tests/integration/platform/test_linux_fontconfig.py
> ```

Thanks a lot for the hint.  Since I'm not the official maintainer I will try to do as less as possible changes.  So if the package builds by simply exlcuding one single test I'd rather decide for this.  In case of further issues I'll follow your advise.
 
> On a last note, is it not possible to package the latest pyglet release in Debian? The 1.4.x branch is very old at this point, and has many issues that are fixed in later releases. There are also a few Python 3.8/3.9 specific fixes that have gone into recent releases, so I wouldn't recommend using the 1.4.x branch at all on Python > 3.7.  Let me know if there is anything I can do on our end that might help this along. 

I'll upload the latest upstream version if the test with some reverse dependencies will be successful.  Debian is currently in transition freeze and so I need to be a bit carefully but I definitely plan to upgrade the package to the latest version (specifically since Debian 11 will release with Python3.9 only).

Kind regards, Andreas.

**Comment by benmoran56** [comment]
That sounds like a good plan. There shouldn't be any breaking API changes from 1.4 -> 1.5; mostly just new things added and bugfixes.

**Comment by mr-c** [comment]
> That sounds like a good plan. There shouldn't be any breaking API changes from 1.4 -> 1.5; mostly just new things added and bugfixes.

Thanks, we did do the upgrade and the tests of other packages that use pyglet passed! This issue can be closed.
