### ISSUE TITLE
Error -13 returned loading media from io.Bytes using FFmpegDecoder

### ISSUE THREAD

**Issue by mcgoober** [pyglet/pyglet#352]
Problem:
on Windows 10, using the pyglet-ffmpeg module and when calling -
pyglet.media.load(io.Bytes(media_data_as_byte_array), streaming=False, decoder=pyglet.media.codecs.ffmpeg.FFmpegDecoder)
I get the following error: pyglet.media.codecs.ffmpeg.FFmpegException: avformat_open_input in ffmpeg_open_filename returned an error opening file C:\Users\user\AppData\Local\Temp\tmppgpnk36v Error code: -13

Debugging the problem:
When FFmpegSource is constructed in ffmpeg.py it creates a named tempfile which the media_data is written to. However I observed that the tempfile is 0 bytes, and cannot be opened by ffmpeg because python still has it open. Reading the docs about NamedTemporaryFile, it mentions that on Windows the tempfile cannot be opened by a second process unless the file is first closed by Python (which would remove the tempfile).
If I change the NamedTemporaryFile in the constructor for FFmpegSource in ffmpeg.py to not delete the tempfile on close, write the data and then close the tempfile before ffmpeg loads the data, then I can load the media and play it correctly (but leaves the tempfile on disk, which could be removed with a file delete later).
```
if file:
            file.seek(0)
            self._tempfile = tempfile.NamedTemporaryFile(delete=False)
            self._tempfile.write(file.read())
            self._tempfile.close()
            filename = self._tempfile.name
```

**Comment by benmoran56** [comment]
Interesting, I was unaware that Windows had that limitation with tempfiles. 
Maybe the easiest solution would just be to move the close logic into `__del__` for the FFMpegSource?

```py
def __del__(self):
    ....
    if self._tempfile:
        self._tempfile.close()
   ....
```

**Comment by mcgoober** [comment]
Thanks Ben, unfortunately we need Python to close the file handle before FFMPEG can open it. The only way to do that with NamedTemporaryFile is to call close(), so FFmpegSource needs to take control of the file deletion.
Basically self._tempfile_close() is needed before ffmpeg_open_filename(). 
I ended with my changes above, plus this mod to __del__.

```python
def __del__(self):
    ....
    if self._file and ffmpeg_close_file is not None:
        ffmpeg_close_file(self._file)
    if hasattr(self, '_tempfile'):
        os.remove(self._tempfile.name)
```
Moving the file removal to after the ffmpeg_close_file is probably a good idea too. I got other file access exceptions with ffmpeg still having a file handle open, and me trying to remove the file from under it.

**Comment by benmoran56** [comment]
We were talking about this again in the Discord, and we haven't been able to come to an ideal solution. Your solution works, but it might not be a good idea to make this the default behavior. The reason is that we can't guarantee that `__del__` will always be called. The `atexit` module was another idea, but in both cases we can't be sure that it will be called if the program terminates abruptly.

Perhaps it might be better if the FFmpeg decoder does not support file-like objects at all, and instead relies on the user to create their own NamedTemporaryFile to pass in. In this way, at least the user would be aware of the potential drawbacks. What do you think? 

It's also possible to extend the FFmpeg decoder so that it can accept a raw byte stream instead of just file paths, but I haven't looked into what it would take to do this yet.

**Comment by mcgoober** [comment]
Thanks for continuing to look at this issue. 
In my case I've got an file open that contains a set of artefacts, images, audio clips, etc. One of these is a video I'm playing. So my video is a decompressed, in memory, byte stream. If there was a way of playing it directly without creating a temp file, then that might be interesting. 
I was also playing with fixing FFmpegSource without directly modifying it, and I came up with this, which worked for my purpose. But you are correct, terminating the program abruptly doesn't remove the temp file.

```python
class MyFFmpegSource(ffmpeg.FFmpegSource):
    def __init__(self, filename, file=None):
        self._tempfile = None
        if file:
            self._tempfile = tempfile.NamedTemporaryFile(delete=False)
            self._tempfile.write(file.read())
            self._tempfile.close()
            filename = self._tempfile.name
        super().__init__(filename, None)

    def __del__(self):
        super().__del__()
        if self._tempfile:
            os.remove(self._tempfile.name)


class MyFFmpegDecoder(ffmpeg.FFmpegDecoder):
    def decode(self, file, filename, streaming=True):
        return MyFFmpegSource(filename, file)


video = pyglet.media.load("", file_data, streaming=False, decoder=ffmpeg.MyFFmpegDecoder())
```

**Comment by benmoran56** [comment]
That's a decent enough solution. 
In the mean time, I think it's best to roll back the built-in tempfile hack, since it's broken on Windows. 

To keep track of enhancing the decoder itself, I made a new ticket tagged as an enhancement idea. #396

**Comment by benmoran56** [comment]
Closing, because FFmpeg now properly handles loading from file-like objects in all recent versions.
