### ISSUE TITLE
Depth buffer precision

### ISSUE THREAD

**Issue by yataoz** [pyglet/pyglet#358]
Looks like the current implementation of depth buffer image is only 8 bit. https://pyglet.readthedocs.io/en/latest/modules/image/index.html#pyglet.image.DepthBufferImage

Is there any way to use more bits, e.g. 16 and 24, for depth buffer?

**Comment by benmoran56** [comment]
Sorry for missing this issue. 

You can create a custom `Config`, when making your windows. The various buffer sizes can be manually specified in this way. See this section of the documentation for details: 
https://pyglet.readthedocs.io/en/latest/programming_guide/context.html
Particularly this subsection:
https://pyglet.readthedocs.io/en/latest/programming_guide/context.html#simple-context-configuration

**Comment by benmoran56** [comment]
Closing this now due to age, but please feel free to follow up if you have any more questions.
