### ISSUE TITLE
obj file decode issue, mtl file with multiple materials

### ISSUE THREAD

**Issue by gizmoore** [pyglet/pyglet#361]
When trying to load a .obj file that referenced a material .mtl file with multiple materials, only the last material is saved.  Attached fix for this.
[obj.zip](https://github.com/pyglet/pyglet/files/6070686/obj.zip)

**Comment by benmoran56** [comment]
Thank you for opening the ticket, and supplying the fix. 

Do you have any example obj files that I can look at?

**Comment by gizmoore** [comment]
Sure thing, here you go: 
[3dmodel.zip](https://github.com/pyglet/pyglet/files/6076357/3dmodel.zip)

Originally downloaded from here: https://free3d.com/3d-model/cartoon-rocket-878331.html
then scaled to fit in a unit cube in Blender.  When I export .obj files from blender, i have to divide the Ns value in the .mtl by 10, otherwise will get an error during load in pyglet.  Not sure if that's a blender problem or pyglet problem.

**Comment by benmoran56** [comment]
Thanks a lot! 
I added your fix, and it will be in the next point release.

**Comment by benmoran56** [comment]
This is now in the latest release, so I'll go ahead and close this. Thanks for your fix!
