### ISSUE TITLE
Can't import 

### ISSUE THREAD

**Issue by h84221605** [pyglet/pyglet#364]
my laptop is macbook m1
python == 3.8.6 
pyglet == 1.5.11

and it will show error when i import pyglet

![1616256024669](https://user-images.githubusercontent.com/39433193/111876167-80191200-89d8-11eb-855d-b3a701b398e9.jpg)

**Comment by benmoran56** [comment]
Thanks for opening the ticket. Could you try again with a recent pyglet release? This should be fixed already.

**Comment by benmoran56** [comment]
Closing due to lack of reply. This should be fixed in the latest releases, but if you are still having issues, please reopen the ticket.
