### ISSUE TITLE
Does the EGL integration support GPU-accelerated rendering?

### ISSUE THREAD

**Issue by minqi** [pyglet/pyglet#367]
I am running pyglet 1.5.15 to perform headless rendering over a compute cluster using the EGL backend, by setting `pyglet.options['headless'] = True`. While this allows me to successfully run my python script without resorting to `xvfb-run`, I find that the speed is almost identical to running with `xvfb-run`, which does not support GPU acceleration. On the other hand, the same script runs at nearly 4-5x the speed on my Macbook Pro, which performs GPU-accelerated OpenGL rendering.

Since EGL support for pyglet does not seem openly advertised, and there are open GitHub issues around EGL support in pyglet, I wonder if there are some missing implementation details that might be leading the current EGL interface to not properly take advantage of the GPU. 

This may also be due to some configuration problems on the cluster machine, in which case, I would appreciate suggestions for how to pinpoint the issue. I know prior discussion on furthering EGL support was somewhat bottlenecked on access to a machine with EGL support, so I am more than happy to help on this, in case it is an issue on pyglet's side.

**Comment by benmoran56** [comment]
Hi minqi, 

Whether using EGL (headless) or Xlib, etc., the actual rendering is still done by the same OpenGL driver. It shouldn't have any large effect on the rendering performance. There might be some differences, such as the default color buffer sizes, etc., but I don't think if it would account for the differences you're seeing.

As you noticed the Headless backend is not yet complete (for example it has some circular imports and other missing things), so it's not advertised yet. You should be fine to keep using it, but you might see issues. 

If you have a desktop Linux machine available, you could do a more direct comparison of the headless/non-headless performance. I would expect that the performance should be about the same, but if not, that would be useful information.

**Comment by minqi** [comment]
Hi Ben, 

Thanks for the additional details. I used `gl_info.get_renderer()` to verify that pyglet does detect the proper GPU when running in headless mode. If `gl_info.get_renderer()` prints the GPU string, is it guaranteed that hardware acceleration is being used?

**Comment by benmoran56** [comment]
pyglet doesn't actually have any non-accelerated backend, so a working OpenGL context is required. 
The MESA driver stack in Linux _does_ offer a software OpenGL driver fallback, however (I think it's called LLVMPipe now). 

If `gl_info.get_renderer()` shows a string that looks like the right vendor and card, then it should be correct.

**Comment by minqi** [comment]
Thanks, Ben. I'm going to close this issue given your answer.
