### ISSUE TITLE
VertexList.resize does not draw new vertices outside old ones

### ISSUE THREAD

**Issue by Qlii256** [pyglet/pyglet#370]
I'm having this weird issue where I use a Batch and add a VertexList to it by calling Batch.add. I start with 3 initial vertices creating a simple square triangle. I then add more vertices based on pressing the mouse. The mouse position is then used as the new vertex position.

I call VertexList.resize with the new length of the vertices (that is all the previous vertices + the newly added one), then I update the VertextList.vertices with the new vertices (all the previous vertices + the newly added one) as an overwrite.

This works great as long as I click inside the model. As soon as I click outside the original model, the vertex is added, no error is thrown. But the vertex is not being drawn. When I click inside the model, it's "cutting" pieces off. I have a small video showing it off. I'm not sure if this is a Pyglet issue or something on my end. But I've been trying to figure it out for some time now and I can't get it to work the way I wanted to.

https://user-images.githubusercontent.com/14263762/113509653-14e24a80-9557-11eb-85df-f00ee5fd4af3.mp4

**Comment by benmoran56** [comment]
It's hard to say without looking at your code, but is it due to out-of-order drawing? Generally, OpenGL requires all of the vertex data to be sent in order (counter-clockwise/clockwise).

**Comment by Qlii256** [comment]
But why would it work when I start the scene, but not when changing after the fact?  I do have them in order btw (counter-clockwise). Because I simply add a new vertex at the end of the vertices. When I click my mouse between the start and end point (which is bottom left and top right), it should still be in order, right?

**Comment by benmoran56** [comment]
Can you post a short code example that shows the issue?

**Comment by Qlii256** [comment]
Creating a simple right triangle. Notice the last vertex points back to the first one, as I'm using GL_LINES opposed to GL_LINE_LOOP to work nice with batched rendering.
```python
batch = Batch()
vertices = (0, 0, 30, 0, 30, 30, 0, 0)
vertex_list = batch.add(len(vertices), GL_LINES, None, ('v2f', vertices))
```
Now in an update loop I catch if the user presses the left mouse button, and if so it returns the mouse position where the click happened.
```python
vertices = (0, 0, 30, 0, 30, 30, mouse_x, mouse_y, 0, 0)
vertex_list.resize(len(vertices))
vertex_list.vertices = vertices
```
I resize the vertex_list based on the new length of the vertices, I then apply (overwrite) the vertices with the new tuple just created. On the next draw call, the shape will be drawn as expected as long as the mouse click was inside the original shape. When clicked outside of the original shape, the line would be coloured black (hard to see), which got me thinking this was a colouring issue. But this does not work if I also update the color accordingly.
```python
vertex_list.color = ('c3B', (255, 255, 255) * len(vertices))
```

**Comment by benmoran56** [comment]
After adding some missing vertex points for GL_LINE, this example works on my machine: 
```py
import pyglet
from pyglet.gl import *


window = pyglet.window.Window()
batch = pyglet.graphics.Batch()


vertices = (100, 100, 230, 100,     # line 1
            230, 100, 230, 230,     # line 2
            230, 230, 100, 100)     # line 3
vertex_list = batch.add(len(vertices)//2, GL_LINES, None, ('v2f', vertices))


@window.event
def on_mouse_press(mouse_x, mouse_y, *args):
    global vertices

    vertices = list(vertices[0:-2]) + [mouse_x, mouse_y, mouse_x, mouse_y] + list(vertices[-2:])

    # vertices = (100, 100, 230, 100,              # line 1
    #             230, 100, 230, 230,              # line 2
    #             230, 230, mouse_x, mouse_y,      # line 3
    #             mouse_x, mouse_y, 100, 100)      # line 4

    vertex_list.resize(len(vertices)//2)
    vertex_list.vertices = vertices


@window.event
def on_draw():
    window.clear()
    batch.draw()


pyglet.app.run()
```

**Comment by Qlii256** [comment]
Yes that seems to work fine, but I made an error in my example code. Therefore, I'll give you an example of why my vertices look like before and after clicking, which seem okay to me and is in line with your code.

The first line is the previous vertices before applying the new, which is the second line (the vertices I set on start of the application). The third and fourth line are when I press the mouse button. Where the third line is the vertices before applying the mouse position (the fourth line). To me this seems correct, I do not "disturb" the last vertex back to the start of the shape.

```python
()
(170.0, 90.0, 470.0, 90.0, 470.0, 90.0, 470.0, 390.0, 470.0, 390.0, 353.0, 186.0, 353.0, 186.0, 170.0, 90.0)
(170.0, 90.0, 470.0, 90.0, 470.0, 90.0, 470.0, 390.0, 470.0, 390.0, 353.0, 186.0, 353.0, 186.0, 170.0, 90.0)
(170.0, 90.0, 470.0, 90.0, 470.0, 90.0, 470.0, 390.0, 470.0, 390.0, 353.0, 186.0, 353.0, 186.0, 207.0, 223.0, 207.0, 223.0, 170.0, 90.0)
```

**Comment by Qlii256** [comment]
I have finally solved my problem and it's completely on my end. First of all, it's `VertexList.colors` and not `VertexList.color`. Second, what I did wrong was recreating the whole color attribute, but same as the vertices, once the type is set, it's set. So when updating colors, only give it the actual tuple of colors, and not the data type such as `c3B`.

Thanks for all the help!

**Comment by benmoran56** [comment]
Great, I'm glad you got that figured out.
I wasn't considering color in my test, so I completely missed your syntax issue with color as well. 

By the way, you might consider joining the Discord server if you are in need of support with getting started. The link is in the README.
