### ISSUE TITLE
Warn user when driver appears to be Generic GDI on windows + ways of addressing it

### ISSUE THREAD

**Issue by pushfoo** [pyglet/pyglet#375]
This is partly @benmoran56 's idea from discord:
> [ I was wondering though if it would make any sense for pyglet to throw a warning if the renderer is "Generic GDI" :thinking:](https://discord.com/channels/438622377094414346/477394331112701952/833175648712392735)

 It was inspired by #374 , which turned out to be an issue with older intel integrated hardware that doesn't report GL capabilities properly under windows 10. To address this, the following steps could be taken:
1. Add notes to the documentation about what a generic GDI driver means, how to diagnose the cause, and how it can be addressed,
2. Display a warning when a generic GDI driver is detected and recommend the user check the documentation for ways to diagnose the cause and address it

If we also have in-depth access to hardware information, we might be able to save users and maintainers a lot of trouble by building in some checks that specifically detect troublesome generations of intel hardware to suggest the cause is something other than the driver not being installed.

**Comment by einarf** [comment]
Might be better to issue a warning if the reported opengl version is lower than 2.0. that would possibly indicate batches won't work, but they might still do (through extensions)

**Comment by pushfoo** [comment]
Per the discussion earlier in chat, the current consensus seems to be that this is best handled as a warning in the 1.5.X maintenance branch, with changes for 2.0 postponed until further discussion.

**Comment by pushfoo** [comment]
0e9a3b9 finishes this issue within the context of 1.5.
