### ISSUE TITLE
Label not fully redrawn, using multiple pyglet windows

### ISSUE THREAD

**Issue by gizmoore** [pyglet/pyglet#387]
[testMultWin.zip](https://github.com/pyglet/pyglet/files/6444482/testMultWin.zip)
The text label is initially drawn, but at times the main window's label won't redraw completely.  I attached an example, when you run the script, it looks fine initially, then after 5 seconds I re-scale the window and the label is only partially visible.  I'm clearing the screen and calling draw() on the labels each update, maybe I'm missing something here?

**Comment by benmoran56** [comment]
Thanks for opening the ticket, and sorry for the slow reply. 
I was able to replicate this on Linux. 

Can you confirm which OS you're using?

**Comment by gizmoore** [comment]
Hi, I was using windows 10.

**Comment by benmoran56** [comment]
Thank you, that helps narrow it down.

**Comment by caffeinepills** [comment]
Closing as this is an issue with `on_resize` having functionality that is predefined unlike other pyglet events. This is changed in 2.1 and possibly will be backported so on_resize does not need to call it's original hiearchy.

The solution is to call the default method.
```py
    def on_resize(self, width,height):
        super().on_resize(width, height)
        for win in WindowManager.window_list:
            win.set_size(width, height)         
        self.dock_windows()
 ```
Doing this resolved the issue for me.
