### ISSUE TITLE
FFMPEG streams not supported on Windows?

### ISSUE THREAD

**Issue by fladd** [pyglet/pyglet#397]
I cannot play a FLAC file as a streaming source under Windows 10 (64 bit):

```
  File "C:\Users\flokra\Documents\GitHub\ZAP\env\lib\site-packages\pyglet\media\codecs\ffmpeg.py", line 461, in __init__
    raise NotImplementedError('Loading from file stream is not supported')
NotImplementedError: Loading from file stream is not supported
```

It works just fine under MacOS though. What am I missing?

I installed ffmpeg correctly:
`pyglet.media.codecs.have_ffmpeg()` returns `True`
`pyglet.media.codecs.get_decoders()` returns `[WaveDecoder('.wav', '.wave', '.riff'), FFmpegDecoder('.mp3', '.ogg')]`

**Comment by fladd** [comment]
Ah, Windows had an older Pyglet version than MacOS.

But now I have another problem. On Windows, it seems that FLAC files are not opened with FFMPEG, but with WMFDecoder:
```

**Comment by caffeinepills** [comment]
If you want to force FFmpeg you can do so:

```
decoder = pyglet.media.codecs.ffmpeg.FFmpegDecoder()

media = pyglet.media.load(filename, decoder=decoder)
```

I have tried experimenting with getting file objects to load with ffmpeg, and while I got it playing audio, the seeking is less accurate than with filename seeking.

**Comment by caffeinepills** [comment]
Closing as the initial issues are resolved (using FFMPEG cross platform).

Seeking issues should be resolved with WMF decoder (tested on Windows 10 64 bit). If you encounter any, please provide examples and open a new issue.
