### ISSUE TITLE
Bug when opening FFmpegStreams under Windows

### ISSUE THREAD

**Issue by fladd** [pyglet/pyglet#400]
In `pyglet.media.codecs.ffmpeg.py` in line 464 a NamedTemproraryFile is created. The file is then left open, and the filename is later given (via `asbytes_filename`) to `ffmpeg_open_filename` in line 468, which will try to open and read from that file again.

However, according to the official Python documentation, this does not work on Windows: "Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; it cannot on Windows NT or later)." (https://docs.python.org/3.8/library/tempfile.html#tempfile.NamedTemporaryFile).

The solution is to instantiate `NamedTemporaryFile` with the `delete=False` parameter in line 464, and then close it after writing to it (and delete the file after closing it in the `__del__` method).

**Comment by benmoran56** [comment]
Please see https://github.com/pyglet/pyglet/issues/396 for more information.
