### ISSUE TITLE
Window instanciation triggers scheduler latencies

### ISSUE THREAD

**Issue by benoitvalery** [pyglet/pyglet#403]
Hi,
Using `pyglet==1.5.16`, I don't understand the following phenomena.
I have a simple class, like the following, that checks potential inputs of a custom response device, as fast as possible.
```python
class Software:
    def __init__(self):
        self.box = Customclass()
        
    def update(self, dt):
        key = self.box.get_key()
        if key is not None:
            print(key)

    def run(self):
        pyglet.clock.schedule(self.update)
        self.event_loop = pyglet.app.EventLoop()
        self.event_loop.run()
```
It works well (no lag), but, soon as I introduced a Window class into my software, any key that is hit, is printed with a small delay.
So, for instance, the following is lagging.
```python
class Software:
    def __init__(self):
        self.box = Customclass()
        self.win = pyglet.window.Window()
        
    def update(self, dt):
        key = self.box.get_key()
        if key is not None:
            print(key)

    def run(self):
        pyglet.clock.schedule(self.update)
        self.event_loop = pyglet.app.EventLoop()
        self.event_loop.run()
```
 I tried with both the `schedule` and the `schedule_interval` functions : same results, the window class seems to blame.
Maybe I should try to handle key events in an other way ?
Thanks for your advice !

[EDIT] : Of course, my program is much more complex than that, I just isolated here, in a MWE, the key elements of my problem.

**Comment by benmoran56** [comment]
Hello, 

What does your `self.box.get_key()` call do? 

Also, using `clock.schedule_interval` is almost always recommended. Using `clock.schedule` will usually just waste CPU, and can potentially choke out other events.

**Comment by benoitvalery** [comment]
Yes, I know that `clock.schedule_interval` is recommended :)
The `get_key` method is just a routine that checks for a potential input on a custom response box, that works with an Arduino Mega, through a serial port). But I think the box is not to blame since it works (with very good accuracy) in other setups. For instance, a simple 
```python
while True:
        key = self.box.get_key()
        if key is not None:
            print(key)
```
gives me very good results. As I said, only the presence of the Window class seems to trigger some delay (between the physical key hit and the print). Thanks.

**Comment by benmoran56** [comment]
Just adding a Window shouldn't affect the schedule unless something is blocking somewhere. 
You should try to confirm that the `dt` variable being passed to your `update` method looks correct. 
You can try something like `schedule_interval(self.update, 1/30)`, and expect a delta time of about `0.033`. 
Printing to the console is not always a good test, because on many systems you can't print that fast.

Can I ask why you're not using `pyglet.app.run`?

**Comment by benoitvalery** [comment]
Thanks for your responses !
No reason not to use `pyglet.app.run`, just the habit to run the EventLoop instead. But still, here is my new try: 
```python
class Software:
    def __init__(self):
        self.box = Customclass()
        self.win = pyglet.window.Window()
        pyglet.clock.schedule_interval(self.update, 1/30.)
        self.event_loop = pyglet.app.EventLoop()

    def update(self, dt):
        print(dt)
        key = self.box.get_key()
        if key is not None:
            print(key)

if __name__ == '__main__':
    soft = Software()
    pyglet.app.run()
```
In my terminal, update is correctly printing 0.33xx dt values.
So I tried several things: 

1. Without a window instantiation, I tried several interval values, and there is as much lag as the value is large. For instance, 1/30 gives me at least 0.5 seconds of lag, while 1/500 gives me no lag at all.
2. Window instantiation is clearly expands dt values. For instance, if I try 1/500, no window will give me `dt=0.002`, but a window will give me something like `dt=0.016`.

These two facts lead me to think that the Window, in my case, is slowing down the scheduler, and that I need a value above a certain threshold to have a correct "Response box refreshing". Still, I don't understand why...

Thanks again for your time.

**Comment by benmoran56** [comment]
Windows have vsync enabled by default, so when the Window is being redrawn as part of the event loop, it will not be able to run faster than your refresh rate.  Looks like 60Hz in your case (1/60). You can disable vsync with the `vsync=False` parameter when creating your windows.  That will probably give you the result you want. 

However, rather than polling get_box at such a high rate, is there an alternate event driven interface that you can use?

**Comment by benoitvalery** [comment]
I tried `vsync=False` and it did the trick.
As for polling my box in a more efficient manner, I'm not aware about other ways. Do you mean that I could handle box inputs almost as the keyboard (Handlers and stuff) ?

Anyway I must give my response box the best accuracy possible as I'm programming psychological experiment (I need something like a 5 milliseconds accuracy).

If you have any advice (readings in the manual or elsewhere) so I can discover more efficient ways, it is very welcome.

Thank again,
Benoît

**Comment by benmoran56** [comment]
I'm glad that did the trick.

Yes,  just like the keyboard events in pyglet. Do you have a link to the module you're using to talk to the "box"? I can have a quick look at it.

**Comment by benoitvalery** [comment]
Hi Ben,
Here is the class I'm using for now. It is still a draft. The core method of the class is the `get_keys` one, which relies on many others methods, and that I would like (as you understood) to schedule properly. There are also methods to switch on/off LED that are on my buttons.
Have a nice day.

```python
import serial, time, glob, signal, sys, pdb
from collections import namedtuple

class Box16:
    def __init__(self, baudrate=230400, prefix='ttyACM'):
        
        self.start_mark = '<'
        self.end_mark = '>'
        self.msg_buffer = str()
        self.message_completed = False
        self.message_started = False
        self.ser = None
        self.response_queue = list()
        
        self.buttons = {str(k):{'pressed':False, 'led_rgb':(0,0,0)}
                               for k in range(16)}
        
        signal.signal(signal.SIGINT, self.close_serial)
        self.setup_serial(baudrate, self.find_port_name(prefix))
        
    def close_serial(self, sig, frame):
        '''Ensure that the serial port is properly closed in case of error'''
        if self.ser is not None and self.ser.is_open == True:
            self.shut_down_leds()
            while self.ser.is_open == True:
                self.ser.close()
            print('Serial port closed')
            sys.exit()
        
    def find_port_name(self, prefix='ttyACM'):
        port_names = glob.glob('/dev/'+prefix+'[0-9]*')
        if len(port_names) > 0:
            return port_names[0]
        else:
            return None
    
    def setup_serial(self, baudrate, port_name):
        self.ser = serial.Serial(port=port_name, baudrate=baudrate, timeout=0)
        print(f"{port_name} opened at a baudrate of {baudrate}")
        self.wait_for_arduino()
    
    def wait_for_arduino(self):
        print("Waiting for Box16 setup()")
        while self.read_msg() != "Box16 is ready":
            time.sleep(0.05)
        print("Box16 is now ready")
    
    def read_msg(self):
        if self.ser.inWaiting() > 0 and self.message_completed == False:
            x = self.ser.read().decode("utf-8")
            if self.message_started == True:
                if x != self.end_mark:
                    self.msg_buffer += x
                else:
                    self.message_started = False
                    self.message_completed = True
            elif x == self.start_mark:
                self.msg_buffer = str()
                self.message_started = True

        if self.message_completed == True:
            self.message_completed = False
            # ~ print(self.msg_buffer)
            return self.msg_buffer
        return str()
        
    def send_msg(self, string_to_send):
        marked_string = self.start_mark
        marked_string += string_to_send
        marked_string += self.end_mark
        marked_string += '\n'
        self.ser.write(marked_string.encode('utf-8')) # encode needed for Python3
    
    def set_leds_RGB(self, leds):
        led_msg = str()
        if not isinstance(leds, list):
            leds = [leds]
        for i, l in enumerate(leds):
            self.buttons[l[0]]['led_rgb'] = (l[1],l[2],l[3])
            self.send_msg(f"R{l[1]}G{l[2]}B{l[3]}L{l[0]}")
            if len(leds) > 1 and l != len(leds):
                time.sleep(0.005)
    
    def signal_trial_start(self):
        '''Thomas W. Schubert & Alessandro D’Ausilio & Rosario Canto, (2013),
           Using Arduino microcontroller boards to measure response latencies.
           "the more promising strategy is to (1) signal the Arduino the beginning of a trial,
            (2) have it measure the reaction time itself, and then (3) send
            the measured latencies back."
        '''
        self.send_msg('T')
    
    def get_key(self, keylist=None, pressed=True):
        r = self.get_next_response(pressed)
        if r is not None:
            
            if keylist is None:
                keylist = self.buttons.keys()
                keylist = self.buttons.keys()
            elif not isinstance(keylist, list):
                keylist = [keylist]
            
            for k in keylist:
                if r['key'] == k:
                    self.flush_responses()
                    return r
                    
    def wait_keys(self, keylist=None, pressed=True):
        self.flush_responses()
        response = None
        while response is None:
            response = self.get_key(keylist, pressed=pressed)
    
    def key_is_pressed(self, key):
        return self.buttons[str(key)]['pressed'] == True
    
    def get_next_response(self, pressed=True):
        self.poll_for_response()
        if self.response_queue_size() > 0:
            state_r = [r for r in self.response_queue if r['pressed'] == pressed]
            if len(state_r) > 0:
                return state_r[-1]  # Return the last response recorded
            else:
                return None
        else:
            return None
    
    def poll_for_response(self):
        msg = self.read_msg()
        if len(msg.split(';')) == 3:
            num, rt, state = msg.split(';')
            self.buttons[str(num)]['pressed'] = state == 'pressed'
            self.response_queue.append({'key':str(num), 'rt':int(rt), 
                                        'pressed':state=='pressed'})
    
    def shut_down_leds(self):
        self.set_leds_RGB([(str(l), 0, 0, 0) for l in self.buttons.keys()])
    
    def response_queue_size(self):
        return len(self.response_queue)
    
    def clear_response_queue(self):
        self.response_queue = list()
    
    def flush_responses(self):
        self.poll_for_response()
        while self.response_queue_size() > 0:
            self.clear_response_queue()
            self.poll_for_response()
    
    def led_n_is_on(self, num):
        return self.buttons[num]['led_rgb'] != (0, 0, 0)
```

**Comment by benmoran56** [comment]
It looks like the `pyserial` module provides a standard file-like interface (including `serial.fileno()` method). 
This means you could use something like the [select](https://docs.python.org/3/library/select.html#module-select) module. 
This is very effience, and in fact, pyglet uses these same internal concepts for OS events. 

Are you running this application on Linux? If so, you can actually build an interface to pyglet's internal event system.

**Comment by benoitvalery** [comment]
Yes, the application is developed and intended to work with Linux (Debian Bullseye). I know nothing about this way of *listening* events, but I will take a look at the `select` module to see if I understand.
The first question that comes to my mind is : would such a method allow to *customize* the way I'm listening (and writing !) to my device ? Do you know a simple example that uses this way (maybe Pyglet is too much complicated to begin with ?).
Anyway I will also do some research on my own.
Thanks again for your precious advice !

**Comment by benmoran56** [comment]
The API is not documented, because it's internal (and different on every platform). I can give you some example code to get started though. pyglet is already "selecting" some file objects, so you can simply add yours to the list. 

```py
from pyglet.app.xlib import XlibSelectDevice
from pyglet.event import EventDispatcher

class SerialInterface(XlibSelectDevice, EventDispatcher):
    def __init__(self, serial):
        self.serial = serial

    def open(self):
        self.serial.open()
        # Let pyglet handle this SelectDevice:
        pyglet.app.platform_event_loop.select_devices.add(self)

    def close(self):
        pyglet.app.platform_event_loop.select_devices.remove(self)
        self.serial.close()

    def fileno(self):
        return self.serial.fileno()

    def poll(self):
        return True

    def select(self):
        # If new data is avilable to read,
        # this methon is called by pyglet.

        data = self.serial.read()   # ?
        self.dispatch_event('on_data', data)

    def __del__(self):
        self.close()


SerialInterface.register_event_type('on_data')
```

In this example code, `select` will be called by pyglet whenever data is available to read. You can then read it, parse it, or do whatever you need. I also made this an EventDispatcher, but this is optional.

**Comment by benoitvalery** [comment]
Wow, this is a big help for me ! Many thanks.
With some adjustments, I can now listen my serial port without the need for the `vsync=False` option.
I'm just finishing by presenting the full solution, some minor corrections and integration.
Again, Ben, a huge thank to you as you helped me to discover some features of pyglet that I didn't know about.

For other persons who might read, the example below is communicating with an Arduino program, so some slight modifications should be made to the code, depending on the kind of messages you want to input/output.

```python
import pyglet, serial

class SerialInterface(pyglet.app.xlib.XlibSelectDevice, 
                      pyglet.event.EventDispatcher):
    def __init__(self, port_name, baud_rate, timeout=0.005):
        self.serial = serial.Serial(port_name, baud_rate, timeout=timeout)  # This little timeout helps to receive non-truncated messages
        pyglet.app.platform_event_loop._select_devices.add(self)  # Note the first underscore in _select_devices

    def close(self):
        pyglet.app.platform_event_loop._select_devices.remove(self)
        self.serial.close()

    def fileno(self):
        return self.serial.fileno()

    def poll(self):
        return True

    def select(self):
        # If new data is available to read, this method is called by pyglet
        if self.serial.inWaiting() > 0:
            data = self.serial.readline()  # Could use the read() method and parse one char at the time (and set the timeout parameter to 0)
            self.dispatch_event('on_data', data)

    def __del__(self):
        self.close()

SerialInterface.register_event_type('on_data')

class Software:
    def __init__(self):
        self.window = pyglet.window.Window()  # Note we do not need the vsync=False parameter
        self.elapsed_time = 0
        self.box = SerialInterface('/dev/ttyACM0', 230400)
        self.box.push_handlers(self)  # Self will now listen the box instance for an 'on_data' event query.
        
        pyglet.clock.schedule_interval(self.update, 1/500.)
        self.event_loop = pyglet.app.EventLoop()
        
    def on_data(self, data):
        print(data)
        
    def update(self, dt):
        self.elapsed_time += dt
        print(self.elapsed_time)
        if self.window.alive == False:
            self.event_loop.exit()

if __name__ == '__main__':
    scotx = Scotx()
    pyglet.app.run()
```

**Comment by benmoran56** [comment]
I'm glad that it was useful, and thank you for sharing your working code. 

Good luck with your project!
