### ISSUE TITLE
GUI widget - allow control through code

### ISSUE THREAD

**Issue by samuelznewton** [pyglet/pyglet#408]
I think it would be helpful if the GUI widgets could be controlled through code.  So, for instance, if I have a toggle button, I should be able to toggle its state without a user actually clicking on it.  Or if I have a slider, I should be able to write code to set its value to 0.7 without a user touching it.  My understanding is that this should just be a few simple changes to the widgets.py file, so I could try coding it tomorrow if you'd like me to.

The only thing I'm not sure of is whether it would be better for that to dispatch any associated events or not.  I figure a boolean parameter can solve that, but I'm not sure which would be a better default.

**Comment by benmoran56** [comment]
I can see the use of that. Perhaps a general `value` property on the WidgetBase class? 
Something like: 
```py

    @property
    def value(self):
        raise NotImplementedError

    @value.setter
    def value(self, value):
        raise NotImplementedError
```

My thought is that these should _not_ dispatch the events. It doesn't seem to make sense to dispatch the "on_press/on_release" events, for example, when no user interaction has taken place.  Instead, I can see this code as being a way to set defaults, or restore values to a previous session. 
The value property should however, update the appropriate graphics as you would expect. 

Please feel free to give it a try! If this is for the current stable release, make sure to target the `pyglet-1.5-maintenance` branch.

**Comment by samuelznewton** [comment]
Okay, I gave it my best shot!  I've never actually contributed to an open-source project before, so please let me know if I've done anything wrong so I can fix it.

**Comment by benmoran56** [comment]
Thanks for the PR! 

Just to follow up on the discussion, I can see the use of a way to "disable" widgets.
Let me know if you have any other ideas, but I can think of two ways to make that work: 
1. Have the Widget's event handlers do an additional check for `if _enabled` or something similar. 
2. Remove the Widget from receiving the Window events, effectively disabling it.

**Comment by samuelznewton** [comment]
Method 1 is what I had in mind from the start, so that's what I did.  Thanks!

**Comment by samuelznewton** [comment]
2 contributions from 1 issue.  What a bargain!

Thanks for your help and patience!
