### ISSUE TITLE
"AttributeError: 'FreeTypeMemoryFace' object has no attribute 'name'" when calling font.add_file and font.add_directory

### ISSUE THREAD

**Issue by rmmbear** [pyglet/pyglet#409]
### Description of the issue:
While running modified hello world code I discovered that calling `pyglet.font.add_font` and `pyglet.add_directory` results in following error:
> AttributeError: 'FreeTypeMemoryFace' object has no attribute 'name'

### Test environment:
- Python 3.9.5
- Pyglet 1.5.18
- OS:  Linux Fedora 34 (kernel 5.12.12-300.fc34.x86_64)

Occurs in:
- ❌ release 1.5.18 
- ❌ branch pyglet-1.5-maintenance (00f314ffc77cb27693aadcb55ac3c5e305d94bea)

Does not occur in:
- ✔️ release 1.5.17
- ✔️ branch master (72cdc61c8ae3ae8912b539b9c2163c822ed338f1).

### Steps to reproduce:
1. Create and activate new virtual environment with `python3 -m venv --clear .venv;  source ./.venv/bin/activate`
1. Install pyglet 1.5.18 with `pip install pyglet==1.5.18`
2. Ensure a ttf font is present in CWD (next step uses [action_man.ttf](/pyglet/pyglet/tree/master/tests/data/fonts))
3. Run following snippet to trigger the issue `python3 -c "import pyglet; pyglet.font.add_file('action_man.ttf')"`
    - This results in AttributeError 
4. install previous release with `pip install pyglet==1.5.17`
5. Run the above snippet again to confirm the issue does not occur in 1.5.17

### Full traceback from step 4:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/m/Desktop/pyglet-bug-report/.venv/lib64/python3.9/site-packages/pyglet/font/__init__.py", line 186, in add_file
    _font_class.add_font_data(font)
  File "/home/m/Desktop/pyglet-bug-report/.venv/lib64/python3.9/site-packages/pyglet/font/freetype.py", line 218, in add_font_data
    cls._memory_faces.add(face)
  File "/home/m/Desktop/pyglet-bug-report/.venv/lib64/python3.9/site-packages/pyglet/font/freetype.py", line 146, in add
    self._dict[face.name.lower(), face.bold, face.italic] = face
AttributeError: 'FreeTypeMemoryFace' object has no attribute 'name'
```

**Comment by benmoran56** [comment]
Thank you for opening the ticket. 
I was able to reproduce the issue, and it should now be fixed. 
Could you try again with the `pyglet-1.5-maintenance` branch, and see if that fixes it?

**Comment by rmmbear** [comment]
Yup, that fixed it. Thanks!
