### ISSUE TITLE
Issue on drawing a png image

### ISSUE THREAD

**Issue by jason-bowen-zheng** [pyglet/pyglet#411]
![screenshot](https://user-images.githubusercontent.com/58848782/124087884-0687ca00-da85-11eb-9233-06b4833d35d1.png)

This is the pyglet logo, with alpha channel.

So I add following 2 lines of code:
```python
glEnable(GL_BLEND)
glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)
```

The issue solved:
![screenshot](https://user-images.githubusercontent.com/58848782/124088399-7bf39a80-da85-11eb-90e5-ced77dec21f8.png)

Is it a bug(pyglet 1.5.18)?

**Comment by benmoran56** [comment]
Hi, 

This is normal. You have to set the blending mode yourself.

**Comment by jason-bowen-zheng** [comment]
Ok, This is the second issue:

```python
import pyglet
from pyglet import image
from pyglet.gl import *
from pyglet.sprite import Sprite
from pyglet.text import Label
from pyglet.window import key, mouse

win = pyglet.window.Window(caption='caption', resizable=True)
l1 = Label('Title' , x=win.width / 2, y=win.height * 0.6,
        anchor_x='center', anchor_y='center', font_size=45)
l2 = Label('subtitle', x=win.width / 2, y=win.height * 0.5,
        anchor_x='center', anchor_y='center', font_size=30)

@win.event
def on_resize(w, h):
    l1.x = w / 2
    l1.y = h * 0.6
    l2.x = w / 2
    l2.y = h * 0.5

@win.event
def on_draw():
    win.clear()
    glClearColor(0.5, 0.69, 1.0, 1)
    l1.draw()
    l2.draw()

@win.event
def on_key_press(sym, mod):
    if sym == key.F2:
        image.get_buffer_manager().get_color_buffer().save('screenshot.png')

pyglet.app.run()
```

The screenshot:
![screenshot](https://user-images.githubusercontent.com/58848782/124093455-79477400-da8a-11eb-9de0-87fa48a26ef7.png)

I use `glClearColor` but the background color is still black unless I resize the window or type some letters.

**Comment by jason-bowen-zheng** [comment]
> Hi,
> 
> This is normal. You have to set the blending mode yourself.

It's not friendly for beginners!

**Comment by benmoran56** [comment]
I agree, but this is just how OpenGL does it. 

Your issue is that you are calling `window.clear`, before setting the color. 
OpenGL is a "state machine", so you only need to call it once. For example: 

```py
glClearColor(0.5, 0.69, 1.0, 1)
pyglet.app.run()
```
Or, you can put it here, _before_ the win.clear():
```py
@win.event
def on_draw():
    glClearColor(0.5, 0.69, 1.0, 1)
    win.clear()
    l1.draw()
    l2.draw()
```

For questions about learning pyglet, you should consider joining our Discord server (the link is at the top of the README).
