### ISSUE TITLE
Caret not shown within text

### ISSUE THREAD

**Issue by eruvanos** [pyglet/pyglet#421]
Hi,
I am working on the new GUI for arcade. To replace the current implementation we plan to migrate every text rendering to Pyglet. Also the InputText widget, which causes us a few problems.

![image](https://user-images.githubusercontent.com/9437863/126231893-c6374e91-071e-4735-ae34-f3558fa63366.png)

## Reproduce

Run [text input example](https://github.com/pyglet/pyglet/blob/master/examples/text/text_input.py).

## Expected
Caret shown at the cursor place

## Actual
No caret visible on MacOS, a gigantic one on Windows.

## Details
OS: Mac 10.15.7
pyglet-2.0.dev5

**Comment by einarf** [comment]
On windows I actually see a caret when the window opens initially. Pretty large blue line.

![unknown](https://user-images.githubusercontent.com/5418180/126233221-0449f874-d38d-4b94-b528-13f3a3d84591.png)

**Comment by benmoran56** [comment]
Can confirm on Linux that it's not working correctly either. 
I'm not sure yet what the cause is.

**Comment by benmoran56** [comment]
This should be working now in the latest `dev` release.
Please let us know if not.

**Comment by eruvanos** [comment]
In our case it looks like we have some offset.

![image](https://user-images.githubusercontent.com/9437863/133686895-76e11a57-3836-4630-97e3-4c6b93127f41.png)

We will check if this comes from our code.

**Comment by eruvanos** [comment]
Hi we figure out that the caret takes the `content_height`, but not the height of the layout.
So setting a size for the layout making it bigger then the actual text causes the caret to be off.

**Comment by eruvanos** [comment]
https://github.com/pyglet/pyglet/blob/0e9da20b162129b5dce9235c7da06ae3b86ee7e3/pyglet/text/caret.py#L392

replaced by: `y += self._layout.y + self._layout.height`

fixes it for us

**Comment by benmoran56** [comment]
Thanks for looking into that. Your fix looks like what it should have been. 
This should be fixed in the master branch now. If you can confirm that, I'll push out another dev release to target.

**Comment by eruvanos** [comment]
The fix works in our example. We still have an issue, that the caret disappears in front of the text. We will debug more to get what the problem is.

**Comment by eruvanos** [comment]
it is
