### ISSUE TITLE
Lack of __all__ causes easily avoidable warnings

### ISSUE THREAD

**Issue by loldebyte** [pyglet/pyglet#426]
PyInstaller's warnings (found at`./build/*/warn-*.txt` where * is the name of your packaged script) :
```python
missing module named pyglet.window.BaseWindow - imported by pyglet.window (top-level), pyglet.window.headless (top-level), pyglet.window.cocoa (top-level), pyglet.window.win32 (top-level), pyglet.window.xlib (top-level)
```
Inspecting the code made it clear that this issue was caused by the lack of `__all__`s in the aforementionned packages' `__init__.py`s

**Comment by benmoran56** [comment]
Closing as per the recent merge. Thanks!
