### ISSUE TITLE
Add support for circular segments in the pyglet.shapes module.

### ISSUE THREAD

**Issue by Ross-TheBoss** [pyglet/pyglet#428]
I think the **parameters 'angle' and 'start_angle'** and the **property 'rotation'** could be added to the **pyglet.shapes.Circle** class to allow for drawing circular segments using it. This would be implented in the same way that the pyglet.shapes.Arc class calculates points along a arc.

![A circular segment](https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Circle_arc.svg/1200px-Circle_arc.svg.png)

**Comment by benmoran56** [comment]
This sounds useful. As we talked about on Discord, it probably makes the most sense to make a new shape, named `Sector`.

**Comment by benmoran56** [comment]
Closing now, thanks to your pull request!
