### ISSUE TITLE
Event dispatching broken in master

### ISSUE THREAD

**Issue by ccanepa** [pyglet/pyglet#43]
Running pyglets examples/windows_event.py does not output keyboard or mouse events to the console. 

The commit that broke was 
commit 385f1ae2452ac733a0e4b5852b6a98475cea5f52 (HEAD)
Merge: 22fd9889 099e3852
Author: Benjamin Moran 
Date:   Tue Feb 19 12:32:22 2019 +0900

    EventDispatcher and Clock only hold weakref to methods --> not working

The previous commit does not show that defect 
commit 22fd98897778fb0f9cac8a68adf827bcc8496761 (HEAD)
Author: Benjamin Moran
Date:   Mon Feb 18 17:15:12 2019 +0900

    Add platform reqirement flags for resource loading integration test. --> working

win7 64bits, python 3.7.2

Discovered while testing cocos, issue https://github.com/los-cocos/cocos/issues/328

Is this an intended change in events API that missed to update the example script or is the events subsystem broken ?

**Comment by ccanepa** [comment]
edited the git log entries.

**Comment by benmoran56** [comment]
Hi Claudio, Thanks for opening the ticket. 

The example was broken. As the change says, the EventHandler now uses weak references. It was a necessary change, because there were issues with the EventHandler preventing proper garbage collection of dead objects. 

If you are seeing issues in Cocos, you can solve it by keeping a reference to all event handlers. 
Instead of this: 
```
window.push_handlers(SomeEventHandlerClass())
```
do this:
```
some_event_handler_class = SomeEventHandlerClass()
window.push_handlers(some_event_handler_class)
```
Basically, you need to make sure that you keep some reference to all handlers that are pushed. Does that make sense?

**Comment by ccanepa** [comment]
Thanks for your promt response Ben.

It makes sense.

Tonight I will look how it applies to cocos

Thanks

**Comment by ccanepa** [comment]
Yes, it was a case of .push_handlers(MyClass()), solved.

Thanks!

**Comment by benmoran56** [comment]
Great!  I think this is a good opportunity to update the docs so that we mention this behavior.

**Comment by ccanepa** [comment]
It would be useful to have  section with short compatibility notes. 

We have one for cocos, and this time includes our pyglet 1.4 compat notes discovered while fixing cocos to work with pyglet 1.4

link to the rst document that will be included in the next release (the Sphinx render is still not online)

https://raw.githubusercontent.com/los-cocos/cocos/cocos2019/docgen/compatibility_notes.txt

**Comment by benmoran56** [comment]
I added a note to the docstrings, and programming guide explaining usage of weak references.
