### ISSUE TITLE
When I define on_resize in window the sprites of my window no longer appear

### ISSUE THREAD

**Issue by flowerbug** [pyglet/pyglet#433]
This is in both pyglet dev version and maintenance 1.5.19 versions (but I have to change my code to use OrderedGroup instead of Group with maint branch).

The only other differences in my code between dev and maint version working or not working is an empty definition under window of:

```
    def on_resize (self, height, width):
        pass
```

my whole code is at:

https://github.com/flowerbug/npath
if i comment that code out my program works as expected.

**Comment by flowerbug** [comment]
I guess I do not understand python/pyglet well enough on this point.  The above is used as a plain def under the Window class, but if I move the definition from under my Window(): class and put it in the main program like below then the program works as it should but I don't understand why it is only this one function/event where this makes any difference...:


```
def main():

    window = Window(width=1, height=1, caption="Npath", resizable=True, fullscreen=False, visible=False)

    @window.event
    def on_resize (width, height):
        print ("on_resize : ", width, height)


    pyglet.clock.schedule_interval(window.update, 1/60.0) # update at 60Hz
    pyglet.app.run()
```

**Comment by benmoran56** [comment]
In your first example, you are **replacing** the Window.on_resize event handler. In the second example, you are "stacking" a new handler on top of the existing one.  There are a few different ways to attach/replace handlers, so I would recommend looking over this page in the docs for more info: https://pyglet.readthedocs.io/en/latest/programming_guide/events.html

With that said, the default `on_resize` handler is responsible for setting the OpenGL projection and Viewport (to an orthagonal projection). For modern OpenGL it's important that it gets called (or the user sets their own projection, such as for 3D).

**Comment by flowerbug** [comment]
ok thank you for the explanation.  :)  at least now i know the "Why".

if you don't consider this a bug then i'll close it.

**Comment by benmoran56** [comment]
I made a quick change to master so that it sets an orthographic projection on Window creation. This should mimic what was happening in pyglet 1.x, where legacy GL already defaulted to a simple orthographic projection.
