### ISSUE TITLE
Window is not exiting with pyglet.app.exit()

### ISSUE THREAD

**Issue by akshayicad** [pyglet/pyglet#449]
Hi @benmoran56 ,

I am using glooey and pyglet in my project and want  to use exit function in a button to exit the window created.
You can find my code here , It is just to show how I want to use `app.exit() ` but it is non responsive. Are you able to help ?

```
import pyglet
import glooey

class MyLabel(glooey.Label):
    custom_color = '#000000'
    custom_font_size = 12
    custom_alignment = 'center'
    
# Encode   
class MyButton(glooey.Button):
    Foreground = MyLabel
    custom_alignment = 'center'

    class Base(glooey.Background):
        custom_color = '#D3D3D3'
        custom_top_padding = -10
        custom_bottom_padding = -10
        custom_right_padding = -10
        custom_left_padding = -10

    def on_click(self, widget): 
        try:
            pyglet.app.exit()
        except Exception as e:
            print(e)
width, height=1342,960
window = pyglet.window.Window(width = width, height = height,caption='mesh display')
gui = glooey.Gui(window)
grid = glooey.Grid()
grid.add(0,0,MyButton("Exit"))

gui.add(grid)
pyglet.app.run()

```

![non responsive](https://user-images.githubusercontent.com/89796231/131371339-c2bf4016-86eb-4490-88cc-04ae1f859ba7.PNG)

**Comment by flowerbug** [comment]
try just exit() instead of pyglet.app.exit().

when i use pyglet.app.exit() nothing happens.  just using plain exit() and all stops as it should.

**Comment by benmoran56** [comment]
This example code works as expected on both my Linux machine, and Windows 10 VM. 

The "not responding" message in the title indicates that the application is frozen. I think something else might be going on here. You might want to try to uninstall / reinstall both pyglet and glooey for a start.

**Comment by akshayicad** [comment]
Hi @flowerbug, @benmoran56 thank you for your reply.

It worked by using both in a code.

```
exit()
pyglet.app.exit()
```
