### ISSUE TITLE
Graphics drivers do not support OpenGL 2.0.

### ISSUE THREAD

**Issue by IvDmNe** [pyglet/pyglet#454]
I am trying to render an environment in gym using pyglet. However, it throws an error:

> /home/ivan/.local/lib/python3.8/site-packages/pyglet/window/__init__.py:667: UserWarning: 
Your graphics drivers do not support OpenGL 2.0.
You may experience rendering issues or crashes.

And the rendered window is black. I suppose the problem is somewhere in pyglet.

I use Ubuntu 20.04, Nvidia geforce 1050ti and 470 version of driver. I tried to downgrade driver but without result.

I will appreciate any help.

**Comment by patataofcourse** [comment]
I experienced this issue too - and my graphics card (GeForce 1030) supports OpenGL up to 4.6.0.

This seems to be an issue with nVidia GPUs in systems running Linux (I was using Manjaro).

**Comment by benmoran56** [comment]
Please share the output of: `python -m pyglet.info`

You can also query the driver information with: `glxinfo |grep OpenGL`

Alternatively, you can query the OpenGL driver directly with the following commands: 
```py
from pyglet.gl import *
from ctypes import *

print(cast(glGetString(GL_VENDOR), c_char_p).value)
print(cast(glGetString(GL_RENDERER), c_char_p).value)
print(cast(glGetString(GL_VERSION), c_char_p).value)
```

**Comment by alexdevteam** [comment]
Can confirm the issue doesn't happen on my AMD RX 5600 XT on Manjaro. Seems to be a loader issue too, because `print(cast(glGetString(GL_VERSION), c_char_p).value)` returns an empty string with Nvidia cards.

**Comment by benmoran56** [comment]
If `glxinfo |grep OpenGL` shows then correct information, 
give the above code a try with a previous version of pyglet, such as 1.5.17, 1.5.18 or 1.5.18. (Just try a few older versions basically). 
If there was a regression, we can help find it that way.

**Comment by patataofcourse** [comment]
> Please share the output of: `python -m pyglet.info`
https://pastebin.com/pehbG953

> ```python
> from pyglet.gl import *
> from ctypes import *
> 
> print(cast(glGetString(GL_VENDOR), c_char_p).value)
> print(cast(glGetString(GL_RENDERER), c_char_p).value)
> print(cast(glGetString(GL_VERSION), c_char_p).value)
> ```
All of them return None. For reference, GL_VENDOR returns 7936, GL_RENDERER returns 7937, and GL_VERSION returns 7938.

> give the above code a try with a previous version of pyglet, such as 1.5.17, 1.5.18 or 1.5.18. (Just try a few older versions basically).
It seems to work up to 1.5.19 - so it's a regression on the latest version.

**Comment by patataofcourse** [comment]
4e0edb949fa634c1ef441d513b656cfd990d673a seems to be the commit that introduced the issue.

**Comment by benmoran56** [comment]
Thanks for doing that testing. That does narrow it down. It's strange that the Nvidia driver is having an issue with that, but at least we know what the issue is now. I'll make a quick update to the 1.5-maintenance branch to see if we can fix it.

**Comment by benmoran56** [comment]
Give this a try with the `pyglet-1.5-maintenance` branch. If you're installing with pip, you could do: 
```sh
pip install --user --upgrade git+http://github.com/pyglet/pyglet.git@pyglet-1.5-maintenance
```

**Comment by ASSANDHOLE** [comment]
I experienced the same issue with Ubuntu 20.04, RTX 3090, latest NVIDIA driver form official website. Update to pyglet-1.5-maintenance didn't seem to work.

**Comment by lyzsf** [comment]
1.5.19 no problem

**Comment by benmoran56** [comment]
Thanks for checking! 

I made another push to the 1.5-maintenance branch, so if you could give that another try it would be appreciated. 
It looks like it's related to some of the recent additions for optional transparent Windows. This doesn't affect AMD/Intel, so it's a little hard to pinpoint. For now, I moved all of the additional transparency-related attributes behind a if check.

**Comment by zzccppp** [comment]
I experienced the same issue with ArchLinux ,RTX 3070, after try the 1.5-maintenance branch, it runs well, thanks a lot for fix it

**Comment by ASSANDHOLE** [comment]
The new 1.5-maintenance branch seems to work fine!

**Comment by FelipeMartins96** [comment]
Hey, I'm still having this issue on a RTX 3080 with `NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4`.
