### ISSUE TITLE
Library "GLU" not found

### ISSUE THREAD

**Issue by amitjena200** [pyglet/pyglet#456]
I am using a Linux machine that has Ubuntu 18.04. Each time I execute the following block of code on Pycharm, I get an error saying "ImportError: Library "GLU" not found." 

 #########################
```
import gym
env = gym.make('CartPole-v0')
env.reset()
for _ in range(1000):
  env.render()
  env.step(env.action_space.sample())  # take a random action
env.close()
```
#########################
It's coming from the step where `glu_lib = pyglet.lib.load_library('GLU')` is called in the background.

I followed different suggestions on the internet and installed the following packages:
libosmesa6-dev,  freeglut3-dev, python-opengl, libglu1-mesa and libglu1-mesa-dev.

But, I can't get rid of the error. Any fix for this??

**Comment by benmoran56** [comment]
Doing an `apt search libGLU.so` on my Ubuntu 20.04 VM shows the package as `libglu1-mesa`, however if you're using Nvidia drivers it could be different. 

You can confirm if the libary is accessable with the following ctypes command: 

```py
>>> import ctypes.util
>>> 
>>> ctypes.util.find_library('GLU')
'libGLU.so.1'
>>> 
```

**Comment by amitjena200** [comment]
@benmoran56 , when I do `apt search libGLU.so`, I get `libglu1-mesa/bionic,now 9.0.0-2.1build1 amd64 [installed]`.
Also, `ctypes.util.find_library('GLU')` gives `'libGLU.so.1'`. But, still I am getting the same error in my code as before.

**Comment by benmoran56** [comment]
What happens if you just do something like:
```py
import pyglet

lib = pyglet.lib.load_library('GLU')
print(lib)
```

Also, are you running this over some kind of remote session, or in a thread? If the ctypes tests works, then it's strange that pyglet doesn't

**Comment by benmoran56** [comment]
Please post the output of `python -m pyglet.info` as well.

**Comment by benmoran56** [comment]
Do you still need help with this?

**Comment by jgibbons94** [comment]
I have encountered this problem as well when trying to package pyglet for guix.

**Comment by jgibbons94** [comment]
I added some debug output of my own to see where things fail. This is run in a container with everything pyglet says it needs.
<pre>pyglet-1.5.21 [env]$ pytest 
DEBUG: self.platform = linux
DEBUG: name = GL
DEBUG: platform_names = [&apos;libGL.so.1&apos;]
DEBUG: Checking for library libGL.so.1
error: libGL.so.1: cannot open shared object file: No such file or directory
DEBUG: Path = None
DEBUG: Checking for library GL
error: GL: cannot open shared object file: No such file or directory
DEBUG: Path = libGL.so.1
<font color="#AA0000">ImportError while loading conftest &apos;/home/porcupirate/Documents/tuxemon/pyglet-1.5.21/tests/conftest.py&apos;.</font>
<font color="#AA0000">tests/conftest.py:19: in &lt;module&gt;</font>
<font color="#AA0000">    from .base.event_loop import event_loop</font>
<font color="#AA0000">tests/base/event_loop.py:10: in &lt;module&gt;</font>
<font color="#AA0000">    from pyglet.graphics import Batch</font>
<font color="#AA0000">pyglet/graphics/__init__.py:165: in &lt;module&gt;</font>
<font color="#AA0000">    from pyglet.gl import *</font>
<font color="#AA0000">pyglet/gl/__init__.py:95: in &lt;module&gt;</font>
<font color="#AA0000">    from pyglet.gl.gl import *</font>
<font color="#AA0000">pyglet/gl/gl.py:45: in &lt;module&gt;</font>
<font color="#AA0000">    from pyglet.gl.lib import link_GL as _link_function</font>
<font color="#AA0000">pyglet/gl/lib.py:149: in &lt;module&gt;</font>
<font color="#AA0000">    from pyglet.gl.lib_glx import link_GL, link_GLU, link_GLX</font>
<font color="#AA0000">pyglet/gl/lib_glx.py:45: in &lt;module&gt;</font>
<font color="#AA0000">    gl_lib = pyglet.lib.load_library(&apos;GL&apos;)</font>
<font color="#AA0000">pyglet/lib.py:170: in load_library</font>
<font color="#AA0000">    raise ImportError(&apos;Library &quot;%s&quot; not found.&apos; % names[0])</font>
<font color="#AA0000">E   ImportError: Library &quot;GL&quot; not found.</font>
</pre>

**Comment by jgibbons94** [comment]
In the python REPL when I go to the directory where libGL.so.1 is found, this happens:
<pre>(ins)&gt;&gt;&gt; ctypes.cdll.LoadLibrary(f&quot;{os.getcwd()}/libGL.so.1&quot;)
&lt;CDLL &apos;/gnu/store/zxfaq3bs0vhw9jb2sdlaps0f7vfy6qis-mesa-20.2.4/lib/libGL.so.1&apos;, handle 228f050 at 0x7f4ccd3a7c70&gt;
</pre>
But if I just type the name of the library, I get an error:
<pre>&gt;&gt;&gt; ctypes.cdll.LoadLibary(&quot;libGL.so.1&quot;)
Traceback (most recent call last):
  File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;module&gt;
  File &quot;/gnu/store/sd2ic7bpv8fx3imy1j8xcjclx71sv6q0-python-3.8.2/lib/python3.8/ctypes/__init__.py&quot;, line 443, in __getattr__
    dll = self._dlltype(name)
  File &quot;/gnu/store/sd2ic7bpv8fx3imy1j8xcjclx71sv6q0-python-3.8.2/lib/python3.8/ctypes/__init__.py&quot;, line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: LoadLibary: cannot open shared object file: No such file or directory
</pre>
It appears ctypes.cdll.LoadLibrary either expects an absolute path or has hard-coded paths to look for shared objects.

**Comment by benmoran56** [comment]
On Linux, pyglet relies on `ctypes.util.find_library(path)` to locate shared libraries.
I suppose you've seen this already, but the ctypes documentation lists the methods it uses: 
https://docs.python.org/3/library/ctypes.html#finding-shared-libraries

Looking at your traceback, is libGL.so.1 in the same directory as pyglet? 
In that case, setting the LD_LIBRARY_PATH can work, if that's possible with Guix. 

pyglet also has an option for searching the local path for libraries: specifically the base directory, and the `/lib` subdirectory.
ie: `_local_lib_paths = [script_path, os.path.join(script_path, 'lib'), os.path.join(cwd, 'lib')]`
This is more intended for users of pyglet, not for pyglet to find the GL libs, but it might work if setting environmental variables is possible in GUIX. The environmental variable should be: `PYGLET_SEARCH_LOCAL_LIBS=True`

**Comment by jgibbons94** [comment]
I've had trouble getting `ctypes.util.find_library(path))` to respect `LD_LIBRARY_PATH` in a minimalistic container, but I found a common way for Guix to work around this issue.

**Comment by benmoran56** [comment]
Sorry I'm not very famiar with the way Guix containers or packages are built (but I have been interested to check it out), but if you were able to find a solution we can close this issue I think.

**Comment by jgibbons94** [comment]
Yes, close this issue.

**Comment by benmoran56** [comment]
Oops. I'll go ahead and close it here. Thanks for following up!

**Comment by lzytitan494** [comment]
I'm also getting the error `ImportError: Library "GLU" not found.`

## Running  ` !apt search libGLU.so` shows:
![image](https://github.com/pyglet/pyglet/assets/97222085/2c86ae7c-575a-4821-9de3-ec5ce296d422)

## Running `print(ctypes.util.find_library('GLU'))` shows:
`None`

## Running `pyglet.lib.load_library('GLU')` shows:
`ImportError: Library "GLU" not found.`

## Running `!python -m pyglet.info` shows:
Platform
------------------------------------------------------------------------------
platform:  Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
release:   5.15.90.1-microsoft-standard-WSL2
machine:   x86_64

Python
------------------------------------------------------------------------------
implementation: CPython
sys.version: 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0]
sys.maxint: 9223372036854775807
os.getcwd(): /mnt/d/coding/Python/Machine Learning Resource/Reinforcement Learning

pyglet
------------------------------------------------------------------------------
pyglet.version: 1.5.21
pyglet.compat_platform: linux
pyglet.__file__: /home/lzytitan/miniconda3/envs/rl/lib/python3.10/site-packages/pyglet/__init__.py
pyglet.options['audio'] = ('xaudio2', 'directsound', 'openal', 'pulse', 'silent')
pyglet.options['debug_font'] = False
pyglet.options['debug_gl'] = True
pyglet.options['debug_gl_trace'] = False
pyglet.options['debug_gl_trace_args'] = False
pyglet.options['debug_graphics_batch'] = False
pyglet.options['debug_lib'] = False
pyglet.options['debug_media'] = False
pyglet.options['debug_texture'] = False
pyglet.options['debug_trace'] = False
pyglet.options['debug_trace_args'] = False
pyglet.options['debug_trace_depth'] = 1
pyglet.options['debug_trace_flush'] = True
pyglet.options['debug_win32'] = False
pyglet.options['debug_x11'] = False
pyglet.options['graphics_vbo'] = True
pyglet.options['shadow_window'] = True
pyglet.options['vsync'] = None
pyglet.options['xsync'] = True
pyglet.options['xlib_fullscreen_override_redirect'] = False
pyglet.options['darwin_cocoa'] = True
pyglet.options['search_local_libs'] = True
pyglet.options['advanced_font_features'] = False
pyglet.options['headless'] = False
pyglet.options['headless_device'] = 0

pyglet.window
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lzytitan/miniconda3/envs/rl/lib/python3.10/site-packages/pyglet/__init__.py", line 334, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute '_create_shadow_window'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lzytitan/miniconda3/envs/rl/lib/python3.10/site-packages/pyglet/info.py", line 225, in _try_dump
    func()
  File "/home/lzytitan/miniconda3/envs/rl/lib/python3.10/site-packages/pyglet/info.py", line 97, in dump_window
    import pyglet.window
  File "/home/lzytitan/miniconda3/envs/rl/lib/python3.10/site-packages/pyglet/window/__init__.py", line 1918, in <module>
    gl._create_shadow_window()
  File "/home/lzytitan/miniconda3/envs/rl/lib/python3.10/site-packages/pyglet/__init__.py", line 340, in __getattr__
    __import__(import_name)
  File "/home/lzytitan/miniconda3/envs/rl/lib/python3.10/site-packages/pyglet/gl/__init__.py", line 95, in <module>
    from pyglet.gl.gl import *
  File "/home/lzytitan/miniconda3/envs/rl/lib/python3.10/site-packages/pyglet/gl/gl.py", line 45, in <module>
    from pyglet.gl.lib import link_GL as _link_function
  File "/home/lzytitan/miniconda3/envs/rl/lib/python3.10/site-packages/pyglet/gl/lib.py", line 149, in <module>
    from pyglet.gl.lib_glx import link_GL, link_GLU, link_GLX
  File "/home/lzytitan/miniconda3/envs/rl/lib/python3.10/site-packages/pyglet/gl/lib_glx.py", line 46, in <module>
    glu_lib = pyglet.lib.load_library('GLU')
  File "/home/lzytitan/miniconda3/envs/rl/lib/python3.10/site-packages/pyglet/lib.py", line 164, in load_library
    raise ImportError('Library "%s" not found.' % names[0])
ImportError: Library "GLU" not found.

pyglet.gl.glu_info
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lzytitan/miniconda3/envs/rl/lib/python3.10/site-packages/pyglet/info.py", line 225, in _try_dump
    func()
  File "/home/lzytitan/miniconda3/envs/rl/lib/python3.10/site-packages/pyglet/info.py", line 131, in dump_glu
    from pyglet.gl import glu_info
  File "/home/lzytitan/miniconda3/envs/rl/lib/python3.10/site-packages/pyglet/gl/__init__.py", line 95, in <module>
    from pyglet.gl.gl import *
  File "/home/lzytitan/miniconda3/envs/rl/lib/python3.10/site-packages/pyglet/gl/gl.py", line 45, in <module>
    from pyglet.gl.lib import link_GL as _link_function
  File "/home/lzytitan/miniconda3/envs/rl/lib/python3.10/site-packages/pyglet/gl/lib.py", line 149, in <module>
    from pyglet.gl.lib_glx import link_GL, link_GLU, link_GLX
  File "/home/lzytitan/miniconda3/envs/rl/lib/python3.10/site-packages/pyglet/gl/lib_glx.py", line 46, in <module>
    glu_lib = pyglet.lib.load_library('GLU')
  File "/home/lzytitan/miniconda3/envs/rl/lib/python3.10/site-packages/pyglet/lib.py", line 164, in load_library
    raise ImportError('Library "%s" not found.' % names[0])
ImportError: Library "GLU" not found.

pyglet.gl.glx_info
------------------------------------------------------------------------------
GLX not available.

pyglet.media
------------------------------------------------------------------------------
audio driver: <pyglet.media.drivers.pulse.adaptation.PulseAudioDriver object at 0x7f186d324b50>

pyglet.media.ffmpeg
------------------------------------------------------------------------------
FFmpeg not available.

pyglet.media.drivers.openal
------------------------------------------------------------------------------
OpenAL not available.

pyglet.input.wintab
------------------------------------------------------------------------------
WinTab not available.

Any fix for this?

**Comment by ishan-gaur** [comment]
Facing a similar issue, output for the debug commands is the same. I also see libglu1-mesa when doing an apt search and can't find the package when using ctypes.utils.find_library.
