### ISSUE TITLE
Documents are missing?

### ISSUE THREAD

**Issue by jason-bowen-zheng** [pyglet/pyglet#460]
I can't find anything in the documents of [pyglet.image](https://pyglet.readthedocs.io/en/latest/modules/image/index.html) and [pyglet.gui](https://pyglet.readthedocs.io/en/latest/modules/gui.html). Is it a mistake?

**Comment by Ross-TheBoss** [comment]
I found that in the latest build log (https://readthedocs.org/api/v2/build/14716714.txt), there are many AttributeError which may have prevented the pyglet.image and pyglet.gui documentation from being used in the website.

**Comment by Ross-TheBoss** [comment]
The [previous build log](https://readthedocs.org/api/v2/build/14704917.txt) however, doesn't have these errors

**Comment by jason-bowen-zheng** [comment]
Is it really solved? I haven't seen anything either.

**Comment by Ross-TheBoss** [comment]
Perhaps [this commit](https://github.com/pyglet/pyglet/commit/05a108b103d32dff4812efb358951f9e5ee4003e) has broken things. Specifically in the latest build log this error occurs 120 times:
 ```py
File "/home/docs/checkouts/readthedocs.org/user_builds/pyglet/checkouts/latest/pyglet/image/__init__.py", line 140, in <module>
    from pyglet.window import *
AttributeError: module 'pyglet.window' has no attribute 'BaseWindow' 
```
This error occurs the remaining 24 times:
```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyglet/checkouts/latest/pyglet/__init__.py", line 334, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'TextureRegion'
```

**Comment by benmoran56** [comment]
I think you're right. Thanks for investigating! 
I wonder if I should revert those `__all__` changes for a quick fix, or just try to fix the imports.

**Comment by benmoran56** [comment]
This should be fixed now. Thanks for opening the ticket!
