### ISSUE TITLE
1.5-maintenance image/__init__.py missing an import?

### ISSUE THREAD

**Issue by UplinkPhobia** [pyglet/pyglet#463]
I recently installed the 1.5-maintenance version, due to the recently closed OpenGL 2.0 issue ( #454 ). 
However it would seem that the pyglet.image module is missing a `from pyglet import gl` statement, causing errors such as `AttributeError: module 'pyglet.gl.gl' has no attribute 'current_context'`.

In case this is not a mistake and supposed to work, well it doesn't work for me.

**Comment by jason-bowen-zheng** [comment]
Issue #460 are talking about the similar issue.

**Comment by benmoran56** [comment]
This should be fixed in the latest 1.5.21 release. 
Please try that, and let us know if not.

**Comment by UplinkPhobia** [comment]
It seems to be working now, thanks!
