### ISSUE TITLE
not fit with pypy 3.10

### ISSUE THREAD

**Issue by shenjackyuanjie** [pyglet/pyglet#464]
i've tryed to use pyglet on pypy 3.10
in my [project](https://github.com/shenjackyuanjie/Difficult-Rocket)
it will raise some error when running on pypy 3.10
```
the game has unknown error , now outputting error message
Traceback (most recent call last):
  File "D:/githubs/DR/Difficult_Rocket.py", line 38, in <module>
    from Difficult_Rocket import main
  File "D:\githubs\DR\Difficult_Rocket\main.py", line 25, in <module>
    from Difficult_Rocket import client, server
  File "D:\githubs\DR\Difficult_Rocket\client.py", line 25, in <module>
    from pyglet.window import key, mouse
  File "D:\APPS\pypy\site-packages\pyglet\window\__init__.py", line 1917, in <module>
    gl._create_shadow_window()
  File "D:\APPS\pypy\site-packages\pyglet\gl\__init__.py", line 206, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "D:\APPS\pypy\site-packages\pyglet\window\win32\__init__.py", line 134, in __init__
    super(Win32Window, self).__init__(*args, **kwargs)
  File "D:\APPS\pypy\site-packages\pyglet\window\__init__.py", line 608, in __init__
    raise NoSuchConfigException('No standard config is available.')
pyglet.window.NoSuchConfigException: No standard config is available.
```
(my project have make a crash report system you can try it)

**Comment by benmoran56** [comment]
The 64bit version of PyPy is still broken on Windows, but should work on Linux. 
The 32bit version should work on both.

If this is not 64bit PyPy,
does the "helloworld.py" example work?

**Comment by shenjackyuanjie** [comment]
sorry, i have just see this commit
I'ts running pypy3.10 win64 ,but i didn't find win32 release of pypy
do you have link of pypy on PY3.8 win32?

**Comment by shenjackyuanjie** [comment]
i found pypy 7.3.3 win32 release. will try it soon

**Comment by shenjackyuanjie** [comment]
![A2PXZ U_W)CK9~` 75T8NWF](https://user-images.githubusercontent.com/54507071/135106711-3f6d001a-16d2-4132-9561-33961c685bfa.png)
tested
pypy 7.3.3 32bits work well on `hello_world.py`
pypy 7.3.6 64bits is broke and trace back is on screen

**Comment by benmoran56** [comment]
Thanks for confirming, in case others see this. 
Hopefully the PyPy team can stabilize the 64-bit release more in the future. 

I'll close the ticket for now.

**Comment by shenjackyuanjie** [comment]
got it，thanks
