### ISSUE TITLE
pyglet.media.codecs.get_decoders wrongly reports that any filename can be opened with any codec 

### ISSUE THREAD

**Issue by ccanepa** [pyglet/pyglet#47]
repro: use an extension not used in audio / video like ".123" and run this:

```python
decoders = pyglet.media.codecs.get_decoders('non_existing_file.123')
print("decoders:", decoders)
```

In my testbed, with no ffmpeg installed I got
`   decoders: [WaveDecoder('.wav', '.wave', '.riff')]`

(and got the same using 'test.mp3')

Looking at the code in `pyglet/media/codecs/__init__.py` for get_decoders I think the line

`decoders += [e for e in _decoders if e not in decoders]`
should be replaced by
```python
else:
    decoders = list(_decoders)
```

Additional bug: same problem in get_encoders, just below

I not checked if this change affects the following two functions, `add_decoder` and `add_encoder`

**Comment by benmoran56** [comment]
Hi Claudio, 
This seems like expected behavior to me. What should happen is:

1. If the filename is *not* recognized, try every decoder, in default order. 
2. If the file name *is* recognized, try the associated decoders first. Then try others if it fails.
3. If every decoder fails, return the error from the first decoder tried. 

The code therefore seems accurate, because the intention is to return a list of decoders, with the matching one first (if one matches). Does that make sense?  A crash is expected if no decoders are found.

**Comment by ccanepa** [comment]
Thats ... unexpected

For a function called get_decoders I would expect a docstring along the lines of

```python
def get_decoders(filename=None):
    """returns a list of decoders that declared it can handle the file extension

   If no filename is provided, a list of all decoders available is returned.
   """
```

From your description I would expect a docstring more like
```python
def get_decoders(filename=None):
    """returns a list of all available decoders, firsts the ones that declared can handle
        the extension (if any), then the decoders that don't recognize the extension.

If no filename provided a list of all decoders available is returned
```
In my opinion the first 
  - makes a cleaner API than the second
  - given the signature, it is problaby the expected semantic in the context of apps using a curated list of assets.

The second
  - the  semantic may have more sense in the context of a media player
  - but then the name don't looks as a good match. Maybe this?
```python
def prioritized_decoders(filename=None):
    """returns a list of all available decoders, firsts the ones that declared can handle
        the extension (if any), then the decoders that don't recognize the extension.

If no filename provided a list of all decoders available is returned
```
I can add a get_decoders_strict(filename=None) with my semantics in cocos or the app in trouble, so not a showstopper.

Perhaps the docstrings could be bettered in pyglet?

**Comment by benmoran56** [comment]
I've been thinking a lot of consolidating the codec operation in a future version of pyglet. 
We now have three modules that use codecs: media, image, and model. In all cases, the same code for add/get encoders/decoders is duplicated. I am thinking to create a simple `codecs` class that can be used by each module. 

In the mean time, we can't break the API suddently for 1.4, but I will clarify the docstrings.

**Comment by ccanepa** [comment]
Seems reasonable, thanks.

**Comment by benmoran56** [comment]
I went ahead and updated the docstrings for this. I'll revisit it in the future as well.
