### ISSUE TITLE
ScrollableTextLayout's scissor area resets to 0, 0, 0, 0 when with or height propert is set

### ISSUE THREAD

**Issue by einarf** [pyglet/pyglet#470]
The consequences of this bug is that no text is rendered after changing some layout properties.

The `scissor_area` is reset to `0, 0, 0, 0` when either of the with or height propert is set. It doesn't really matter of we use `begin_update/end_update` here. The same issue appears with or wothout it.

```py
import pyglet
from pyglet import gl

window = pyglet.window.Window()

text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua"
doc = pyglet.text.decode_text(text)
layout = pyglet.text.layout.ScrollableTextLayout(doc, 300, 200, multiline=True)

for group in layout.groups.values():
    print(group.scissor_area)

layout.begin_update()  # <- With without this doesn't really matter
layout.x = 10
layout.y = 10
layout.width = 300  # <- causes scissor_area to reset
layout.height = 200  # <- causes scissor_area to reset
layout.end_update()  # <- With without this doesn't really matter

@window.event
def on_draw():
    gl.glClearColor(0.5, 0.5, 5.0, 1.0)
    window.clear()
    layout.draw()

    for group in layout.groups.values():
        print(group.scissor_area)


pyglet.app.run()
```

This is caused by `_update()`. If we add the following method to `ScrollableTextLayout` it solves the problem.

```py
    def _update(self):
        super()._update()
        self._update_scissor_area()
```

I had not more time left to look at the underlying issue.

**Comment by benmoran56** [comment]
Thanks for looking into this. Your fix is exactly what's needed. The TextLayout and ScrollableTextLayout recreate everything on any updates, this step was missing from the ScrollableTextLayout. The IncrementalTextLayout does it's own custom update.

**Comment by einarf** [comment]
I can PR this if you want, but you migh as well just paste in the method and commit as well. Up to you.

**Comment by benmoran56** [comment]
Fixed in master!

**Comment by einarf** [comment]
❤️
