### ISSUE TITLE
pyglet/text/caret.py _blink()

### ISSUE THREAD

**Issue by mark-summerfield** [pyglet/pyglet#474]
1. I wish it was possible to globally switch off cursor blink (but ideally still show a steady cursor in the text widget that has the keyboard focus, if any). I am not the only one who can't work with blinking cursors; see https://jurta.org/en/prog/noblink Right now all I can do is follow `caret = pyglet.text.caret.Caret(...` with `caret.PERIOD = 0` for _every_ text layout. This does stop the blinking but also makes the caret invisible even in the widget that has the keyboard focus.
2. In `pyglet/text/caret.py` the `_blink()` method accepts a `dt` argument that isn't used at all, so ought to be dropped or prefixed `_dt` or actually used.

**Comment by benmoran56** [comment]
Hi Mark, 

Looking at the `text_input.py` example,
https://github.com/pyglet/pyglet/blob/pyglet-1.5-maintenance/examples/text/text_input.py
setting `self.caret.PERIOD = None` after creation should be enough to achieve what you want. 
This is a class attribute, so it can be set globally for all Caret instances:
`pyglet.text.caret.Caret.PERIOD = None`

**Comment by benmoran56** [comment]
Closing now due to lack of response, but please reopen it if youu want to follow up. 
Thanks!
