### ISSUE TITLE
pyglet.app.exit() opens another window with updated data without shutting down the previous window

### ISSUE THREAD

**Issue by gursheeshkour** [pyglet/pyglet#475]
Hi @benmoran56 

I'm working on a project using glooey & pyglet which consists of:

1.  A loop iterating over a folder of files.
2.  For every iteration gui opens a window to display that image file.
3.  The window also consists of a button("Next File"), so this button should basically shut down the existing window & re open a new window with new file.

What's happening is, glooey opens a new window with new data without shutting the old window, the old window becomes dead but doesn't shut down.
I used pyglet.app.exit() & also exit().
If I break the loop, then the window shuts down butI don't want to get out of the loop, I rather want it to shut & re open with next iteration.
<img width="992" alt="Screen Shot 2021-09-27 at 4 25 16 PM" src="https://user-images.githubusercontent.com/89859214/135097488-5cbb9eb3-25b4-4a2f-8dde-dc15440a68aa.png">

The following is the code that I'm unable to post as code:

`import pyglet
import glooey
import os

def create_window():
    width, height=1000,500
    window = pyglet.window.Window(width = width, height = height,caption='mesh display')
    gui = glooey.Gui(window)
    bg = glooey.Background()
    bg.set_color(new_color = 'white')
    gui.add(bg)
    grid = glooey.Grid()
    grid.add(0,0,MyButton2("NEXT"))
    gui.add(grid)
    pyglet.app.run()

class MyLabel(glooey.Label):
    custom_color = '#000000'
    custom_font_size = 12
    custom_alignment = 'center'  

class MyButton2(glooey.Button):
    Foreground = MyLabel
    custom_alignment = 'top right'         
    def on_click(self, widget):
        global next_flag
        next_flag = True
        exit()
        pyglet.app.exit() 

filename_list = ["a","b","c","d","e","f"]
next_flag = None

for obj in filename_list:  
    if next_flag is not None:
        next_flag = None
        exit()
        pyglet.app.exit()
    else:
        grid = create_window()`

Thanks in advance!

**Comment by benmoran56** [comment]
Great! I'm glad you got that solved, and thanks for following up.
