### ISSUE TITLE
Can't load font from .ttf files

### ISSUE THREAD

**Issue by shenjackyuanjie** [pyglet/pyglet#479]
![](https://cdn.discordapp.com/attachments/698692363354374315/893740923677208586/unknown.png)

when i tryed to check if the font file is loaded fine
it raise many traceback

**Comment by jason-bowen-zheng** [comment]
您是否能够确认 `Harmony_Sans_Black`（首字母大写、有下划线） 是最终的字体名称?

**Comment by shenjackyuanjie** [comment]
> 您是否能够确认 `Harmony_Sans_Black`（首字母大写、有下划线） 是最终的**字体名称**?
是的

**Comment by jason-bowen-zheng** [comment]
这么肯定的？So we should ask others help.

**Comment by shenjackyuanjie** [comment]
> 这么肯定的？So we should ask others help.

我都能在label里直接用这个字体，why not?

**Comment by jason-bowen-zheng** [comment]
因为该 issue 未解决使你又开了一个 issue

**Comment by jason-bowen-zheng** [comment]
这句话的表达逻辑很有问题...

**Comment by shenjackyuanjie** [comment]
> 这句话的表达逻辑很有问题...
```
a = Label(x=10, y=10, font_name='Harmony_Sans_Black')
a.draw()
```
我这么调用没问题

**Comment by shenjackyuanjie** [comment]
似乎没问题了，但是又不是完全没问题了（
