### ISSUE TITLE
error on rendering font

### ISSUE THREAD

**Issue by shenjackyuanjie** [pyglet/pyglet#483]
![](https://cdn.discordapp.com/attachments/463526340168122368/894551431158308894/unknown.png)
font_name='HarmonyOS_Sans_SC'
![](https://cdn.discordapp.com/attachments/463526340168122368/894552087021629440/unknown.png)
font_name=None

as the tiltle
wierd curve on rendering chinese
and also on english

**Comment by shenjackyuanjie** [comment]
pyglet version is github's version
at 2021 10 04

**Comment by caffeinepills** [comment]
You will need to provide an example, the font, and what it *should* look like.

**Comment by shenjackyuanjie** [comment]
> You will need to provide an example, the font, and what it _should_ look like.

got it wait please

**Comment by shenjackyuanjie** [comment]
![image](https://user-images.githubusercontent.com/54507071/135875823-6d8cf976-bb48-43ae-9d55-861f772ecd82.png)

It is a 4K pic
you can check it full screen
font 10 is still good
but when font 12 it became really bad
```
import pyglet

window = pyglet.window.Window()
label = pyglet.text.Label('Hello, world!',
                          font_size=36,
                          x=window.width // 2,
                          y=window.height // 2,
                          anchor_x='center',
                          anchor_y='center')
label2 = pyglet.text.Label('中文测试',
                           font_size=12,
                           font_name='HarmonyOS_Sans_SC',
                           x=50,
                           y=50,
                           anchor_x='center',
                           anchor_y='center')
label3 = pyglet.text.Label('English test',
                           font_name='HarmonyOS_Sans_SC',
                           font_size=12,
                           x=50,
                           y=100,
                           anchor_x='center',
                           anchor_y='center')
@window.event
def on_draw():
    window.clear()
    label.draw()
    label2.draw()
    label3.draw()
pyglet.app.run()

```

**Comment by shenjackyuanjie** [comment]
o!
sorry
[Uploading HarmonyOS_Sans_SC_Regular.zip…]()
!
(by the way, using system's defaut font will also get the same resolt

**Comment by caffeinepills** [comment]
You need to provide the actual font name. 

![image](https://user-images.githubusercontent.com/17804711/135877876-90782e7f-beec-48a6-993d-b724a1541d47.png)

**Comment by shenjackyuanjie** [comment]
> You need to provide the actual font name. Try removing underscores.
> 
> ![image](https://user-images.githubusercontent.com/17804711/135877876-90782e7f-beec-48a6-993d-b724a1541d47.png)

ok, i'm making a grath of font `fangsong`

**Comment by shenjackyuanjie** [comment]
![image](https://user-images.githubusercontent.com/54507071/135878654-11e095d5-6e44-40cd-9320-02dd64be4519.png)

4K pic

**Comment by shenjackyuanjie** [comment]
hmmmm
seems it happend not so obvious on `fangsong`

**Comment by shenjackyuanjie** [comment]
![image](https://user-images.githubusercontent.com/54507071/135879298-902b7f9f-85a2-4117-b57f-73ce30f7021a.png)

**Comment by shenjackyuanjie** [comment]
this is `HarmonyOS Sans SC`'s pic
4k

**Comment by caffeinepills** [comment]
Seems like it's using the correct font now for `HarmonyOS Sans SC`.

**Comment by shenjackyuanjie** [comment]
> Seems like it's using the correct font now for `HarmonyOS Sans SC`.
> 
> Some of the lower fonts look a little weird, but could be scaling. You could try the advanced font renderer if you are on Windows to see if there is any difference.

thanks
