### ISSUE TITLE
Do pyglet depend on avbin now?

### ISSUE THREAD

**Issue by jason-bowen-zheng** [pyglet/pyglet#484]
According to [English Wikipedia](https://en.wikipedia.org/wiki/Pyglet) and other language:
```
... with more additional capabilities supplied by the optional AVbin plugin ...
```
Is it out of date?

**Comment by jason-bowen-zheng** [comment]
Thanks for your explain. I'll update the English Wikipedia.

In addition, I'm translating the pyglet document(part) to Chinese and put it in WikiBooks, It may need your permission.

**Comment by jason-bowen-zheng** [comment]
@shenjackyuanjie Good luck!

**Comment by benmoran56** [comment]
Closing for now, but please follow-up if you need more information. 
Thanks!
