### ISSUE TITLE
Key Error: Resource not found

### ISSUE THREAD

**Issue by Bhaney44** [pyglet/pyglet#49]
Hi,

I am getting an error rendering some script with Pyglet and would appreciate any advice. The error I am getting is as follows:

```
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyglet/resource.py", line 435, in file
    location = self._index[name]
KeyError: 'default.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brianhaney/Desktop/Publications/National_Security/Missiles copy/Target_Paper_Coder/generate.py", line 2, in <module>
    import resources
  File "/Users/brianhaney/Desktop/Publications/National_Security/Missiles copy/Target_Paper_Coder/resources.py", line 11, in <module>
    default_image = pyglet.resource.image("default.png")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyglet/resource.py", line 554, in image
    identity = self._cached_images[name] = self._alloc_image(name,atlas=atlas)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyglet/resource.py", line 482, in _alloc_image
    file = self.file(name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyglet/resource.py", line 438, in file
    raise ResourceNotFoundException(name)
pyglet.resource.ResourceNotFoundException: Resource "default.png" was not found on the path.  Ensure that the filename has the correct captialisation.`
```

The specific script in the Pyglet resource.py file that is returning the error in line 435 is as follows:

```
`    def location(self, name):
        """Get the location of a resource.

        This method is useful for opening files referenced from a resource.
        For example, an HTML file loaded as a resource might reference some
        images.  These images should be located relative to the HTML file, not
        looked up individually in the loader's path.

        :Parameters:
            `name` : str
                Filename of the resource to locate.

        :rtype: `Location`
        """
        self._require_index()
        try:
            return self._index[name]
        except KeyError:
            raise ResourceNotFoundException(name)`
```

I am not sure how to fix the bug. The error says: "Resource "default.png" was not found on the path." However, I am not sure to what default.png is referring. Any advice or suggestions would be appreciated. I found this [resource](https://pyglet.readthedocs.io/en/latest/modules/resource.html) in the docs. I think there is a path error with the .png files I am trying to incorporate.

With thanks,

Brian

**Comment by caffeinepills** [comment]
The error is stating it could not find the file in path specified. Which is the default script path. 

```
  File "/Users/brianhaney/Desktop/Publications/National_Security/Missiles copy/Target_Paper_Coder/resources.py", line 11, in <module>
    default_image = pyglet.resource.image("default.png")
```

You need to make sure that file is in the same directory as your script. If you want to change the path of where to look for resources, you can specify that as well (refer to docs).

**Comment by benmoran56** [comment]
Hi @Bhaney44, are you still having trouble?

**Comment by Bhaney44** [comment]
Hey guys! Thanks for the help. @caffeinepills was right. I also found another end around, which I found to be easier.

Using:

`planet_image = pyglet.image.load('Saturn_1.png')`

Instead of:

`planet_image = pyglet.resource.image('Saturn_1.png')`

Works a lot better for me. With the image.load method, I can just load the image right from the same file as the script.

Thanks!

**Comment by benmoran56** [comment]
There is one side-affect to using `pyglet.image.load`. That is, it will create a separate texture on the GPU for each image. This is OK for a small amount of images, but will cause the rendering to slow down if you do too many.

**Comment by zipandrar** [comment]
pngPath=dir1+"\\"+filename
                pngPath=pngPath.replace("\\",'/')

then pyglet.resource.image(pngPath)

will get no error...

**Comment by benmoran56** [comment]
For `pyglet.resource`, you must use forward slashes only "/" for paths. Back slashes are not supported. This is for cross platform compatibility.  You can find the programming guide here:
https://pyglet.readthedocs.io/en/latest/programming_guide/resources.html#
And the API docs here: 
https://pyglet.readthedocs.io/en/latest/modules/resource.html
