### ISSUE TITLE
glPushMatrix gone in 2.0 dev 9

### ISSUE THREAD

**Issue by chunky** [pyglet/pyglet#492]
I'm using an nvidia jetson nano with almost entirely stock setup [version details below].

I installed pyglet in a venv, which came in as version 2.0.dev9. Not sure how that version was selected in particular, I didn't specify versions of anything.

And my existing code broke because, python.gl.glPushMatrix is missing:

```
$ python3 -m venv test_venv
$ source test_venv/bin/activate
$ python3 -m pip install pyglet==2.0.dev9
(test_venv) $ python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyglet.gl as gl
>>> gl.glPushMatrix()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pyglet.gl' has no attribute 'glPushMatrix'
>>> 

(test_venv) $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
(test_venv) $ uname -a
Linux ckjetson 4.9.253-tegra #1 SMP PREEMPT Mon Jul 26 12:13:06 PDT 2021 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by einarf** [comment]
Pyglet 2 are aiming for something closer to GL 3.3 core and all fixed pipleine pipleine functions are deprecated. You can still access them in `pyglet.gl_compat` module though, but at your own risk.

If you are using fixed pipleine stuff you might as well stick with 1.5.x for now.

**Comment by chunky** [comment]
Yeah, I've dealt with that now.

It would be nice if legacy wasn't "at my own risk", I suspect I'm not the only one with that use case, but I do understand the nature of modern pipelines meaning that use case probably needs to adapt or die.

**Comment by chunky** [comment]
I'm currently using batches for a lot of stuff [pretty much anything with a lifetime longer than a single frame], but I've always been unclear on the benefits and drawbacks of batches for things that will only live for a single frame [or change between each and every frame]

**Comment by benmoran56** [comment]
Drawing things individually  requires manually setting/unsetting the OpenGL state between each call. This can obviously get slow when dealing with a large number of objects. 

When using a Batch, all of your objects get drawn in as few draw calls as possible, usually consolidated by the Group and Texture. Even if some objects are coming and going each frame, it's still usually much faster to use a Batch. Basically everything that's currently in there gets drawn together, even if it's only there for the current draw call.

**Comment by einarf** [comment]
I would not worry too much about it right now. It's not like pyglet 1.5.x will disappear or no longer be maintained. We don't even know if the majority of the user base will eventually move over to 2.x.

Still, I'll give you something to start with. The matrix stack is gone in OpenGL 3.3. This means you will have to use `pyglet.math,Mat4` for matrices. This type also replaces `glOrtho`, `gluPerspective` and various other things.

https://github.com/pyglet/pyglet/blob/379484525081dc53521a82f1de56e6e7ad208d5e/pyglet/math.py#L699-L771

The global projection matrix you instead set on the window itself
```py
window.projection = Mat4.orthogonal_projection(...)
```
Same with the global modelview
```py
window.view = Mat4()
```

Rotation/translation is done using basic matrix math with the `Mat4` type. These matrices are something you could also set in groups (batch groups).

You could probably also use an extrenal library like pyglm if needed.
