### ISSUE TITLE
release pyglet 1.4.3 ?

### ISSUE THREAD

**Issue by ccanepa** [pyglet/pyglet#50]
It would be possible to make a 1.4.3 release ?

I want to release cocos, and it would make sense that the setup pointed to a pyglet version working well with cocos.

I'm done testing cocos with pyglet master, so ready to release. 

pyglet master has an unreleased fix to https://github.com/pyglet/pyglet/issues/45

Thanks.

**Comment by benmoran56** [comment]
Hi Claudio, 

Sure, I think I can push this out very soon.

**Comment by benmoran56** [comment]
Done! It's up on PyPi now.

**Comment by ccanepa** [comment]
hey, thanks!
