### ISSUE TITLE
Feature Request: Collision Detection System

### ISSUE THREAD

**Issue by TheAlphaReturns** [pyglet/pyglet#504]
Would like a collision system for pyglet. Please allow it to detect collisions between sprites, other sprites, and `pyglet.shape`'s.

Maybe:

```py
list_of_items = [item2, item3, ...]
@window.event
def on_collide(item1, list_of_items): #if item1 collides with any item in the list
    print("It has collided")
```

**Comment by LennyPhoenix** [comment]
There are existing physics libraries out there such as [pymunk](https://github.com/viblo/pymunk). I think collision detection might be a bit out of scope for pyglet itself, however it is fairly simple to implement yourself. Here is a [good article](https://gamedevelopment.tutsplus.com/tutorials/how-to-create-a-custom-2d-physics-engine-the-basics-and-impulse-resolution--gamedev-6331) I would recommend using, it contains info on collision detection but you can take it further with resolution too.

**Comment by benmoran56** [comment]
I would have to agree that it's a bit out of scope. Pymunk is a good suggestion for complex simulations, and should integrate smoothly without much trouble. 

For simple AABB collision detection, it would be fairly easy to roll your own.
