### ISSUE TITLE
Empty InputText raises AssertionError

### ISSUE THREAD

**Issue by eruvanos** [pyglet/pyglet#505]
Deleting the last letter from a input box, raises assertion exception

## Reproduce

Run [text input example](https://github.com/pyglet/pyglet/blob/master/examples/text/text_input.py).
Delete all letters from an input field.

## Expected
Empty field is shown, caret is blinking

## Actual
Assertion error.

## Details
OS: Mac 10.15.7
pyglet-2.0.dev11

**Comment by benmoran56** [comment]
Hi, this should be fixed in master. Please give that a try.

**Comment by eruvanos** [comment]
Thanks, it is fixed, no exception running the example anymore.
