### ISSUE TITLE
Caret doesn't render at the beginning of editable text

### ISSUE THREAD

**Issue by Purrrpley** [pyglet/pyglet#512]
When there's an editable piece of text with a caret (created from either `pyglet.gui.TextEntry` and `pyglet.gui.Frame`, or `pyglet.text.layout.IncrementalTextLayout` and `pyglet.text.caret.Caret`) the caret doesn't render at the beginning of the text.

It renders fine if it's not at the beginning:
![image](https://user-images.githubusercontent.com/63091454/145164625-56c69acb-08ce-4653-b43d-9bf574e71be8.png)
... But it doesn't render if it's at the beginning (it is at the beginning in this screenshot, but it won't look like it because it doesn't render):
![image](https://user-images.githubusercontent.com/63091454/145164669-df67e99a-c39e-4eb5-ad0e-19bfc6299f50.png)

I believe this is because when it renders the text box, anything outside of the text box isn't rendered which probably allows for text scrolling to work properly and some other things, but it also causes the caret to not render when it's at the beginning of the string because it's just outside of that area. Using the default font (Arial for me), the caret renders two pixels to the left of the beginning of the character it's in front of, and there seems to be one pixel of padding from the beginning of the text box culling area to the first character, which means the caret is 1 pixel too far to the left to be rendered when it's at the beginning.

This can be solved by moving the caret one pixel to the right, but that changes visuals a bit so isn't a good solution. Another solution is to extend the culling box thing by one pixel to the left by changing this line:
https://github.com/pyglet/pyglet/blob/b9ed5d3ce61735124983971f91f855c514291a85/pyglet/text/layout.py#L603
to this:
```py
glScissor(self._clip_x-1, self._clip_y - self._clip_height, self._clip_width, self._clip_height)
```
Which is better, but this still changes visuals slightly by making text scrolled to the right render one pixel more to the left than it otherwise would have.
Normally:
![image](https://user-images.githubusercontent.com/63091454/145167226-a22ef429-f185-4c01-92be-bd668f70042d.png)
With this change:
![image](https://user-images.githubusercontent.com/63091454/145167162-c40ecc64-a6e6-48fa-9df3-a6cf5adc39f6.png)
(that's a bunch of "m"s making it scroll horizontally and zoomed in using the colour picker tool in [PowerToys](https://github.com/microsoft/PowerToys)

A proper solution would be to move all text to the right by one pixel so that the caret has enough space to render even at the beginning. This would minorly affect existing GUIs, but is better than the solution above because it wouldn't be rendering stuff one pixel to the left of the layout's x coordinate which doesn't really make sense.

You could instead maybe somehow make the caret immune to the culling thing, but this might cause issues with scrolling because if you scroll away from the caret and make the text it's on disappear it might still be visible because the culling doesn't get rid of it. You could maybe solve that by instead only adding a special case for when the caret is at the beginning of text, but that would still make it render one pixel to the left of the layout's x coordinate. Alternatively, you could move the caret one pixel to the right only when it's at the beginning of text which would fix this issue, and not move the text in existing GUIs; but it would make the first character have a different distance to the caret than every other character so imo isn't the best solution, though might be depending on how much you care about backwards-comparability.

I'm not sure whether this issue exists in the `master` (2.0, I think) branch because it seems that the caret doesn't render at all there, whether it's at the beginning or not (using current latest commit da8f0c4d10aeb5aa4de5d5e09b7864b565662b4e), but that seems to be a separate already known issue.

(haven't created an issue/bug report for a decently-sized project before, so I hope I did this right)

**Comment by eruvanos** [comment]
Tested with code from https://github.com/pyglet/pyglet/files/7810712/issuePG.txt

It works now on M1 MacOS.

**Comment by Purrrpley** [comment]
It works for me using v2.0.0 (from PyPI) on Windows 10:
![image](https://user-images.githubusercontent.com/63091454/199206757-ce166068-229f-4336-9d66-4861acb8dfe6.png)

> Tested with code from https://github.com/pyglet/pyglet/files/7810712/issuePG.txt

btw, this errored on run for me... It seems like that's a slightly older (though not shown in git history?) version of the [`text_input.py` example](https://github.com/pyglet/pyglet/blob/master/examples/text/text_input.py), and the latest version of that ran fine for me (thanks to 24108d4).

**Comment by caffeinepills** [comment]
Layouts now have a Z property, so you will need to change `self.layout.position = x, y` to `self.layout.position = x, y, 0` to get older examples working.

**Comment by benmoran56** [comment]
The original issue should be fixed, so I'll close this for now. After accounting for the new Z value, please let us know if you're still having issues.
