### ISSUE TITLE
xlib issue: Could not create UTF8 text property

### ISSUE THREAD

**Issue by matanster** [pyglet/pyglet#520]
There is a [well known issue](https://stackoverflow.com/a/60897278/1509695) possibly occurring on some systems but not others, where the xlib integration code may bail out, coming from [this line of code](https://github.com/pyglet/pyglet/blob/da8f0c4d10aeb5aa4de5d5e09b7864b565662b4e/pyglet/window/xlib/__init__.py#L857). The workaround suggested is changing the system-wide locale or setting the environment LANG variable to `en_US`, however it would be nice if other locales worked too, such that this environment tweak is not necessary. If xlib is friendly enough to allow and I understand the issue correctly.

**Comment by benmoran56** [comment]
Hello, thanks for opening the ticket, and sorry for leaving this hanging for so long. 

I was unable to replicate this issue, with LANG=C, LC_ALL=C, etc.
Can you provide any more information on how to replicate this?

**Comment by pushfoo** [comment]
If anyone runs into this, [the fix from this comment](https://github.com/openai/gym/issues/673#issuecomment-501981467) may be worth trying: add the following in your program before everything else runs.
```py
import os
os.environ['LANG']='en_US'
```

**Comment by pushfoo** [comment]
According to [this post](https://discussion.fedoraproject.org/t/problem-utf8-not-working-anymore/72054/3), appending `.utf8` to a locale makes things work.

A more recent post (2020) in the same thread suggests `sudo localectl set-locale LANG=de_DE.UTF-8` which seems overkill, but gives us enough to start investigating support or warnings for non-US locales. Note that RTL language support might not be coming in the near future since it will require significant reworks of text.

In the meantime, it might be enough to check for any of the known working locales or a utf8 suffix. We'll need to be able to replicate this to make progress, however.

**Comment by matanster** [comment]
> @matanster can you still replicate this issue?

It had stopped happening long ago for me, I made sure my environment has that value, but when I remove that variable from the environment it no longer happens now. Many system updates have transpired in the meanwhile. 

I haven't seen anyone else complaining about this in the context of pyglet on this thread, so frankly I'm not sure this is worth anyone's time unless it ever comes up again, especially given the simple solution to it!

**Comment by pushfoo** [comment]
> but when I remove that variable from the environment it no longer happens now. Many system updates have transpired in the meanwhile

Larger boot drives, faster internet speeds, and wider Linux adoption may have solved it for us in one way or another.

I asked some international users if they could replicate it and to share the output of the code below:
```python
import os
for item in ('LANG', 'LC_CTYPE', 'LC_ALL'):
    value = os.environ.get(item, None)
    print(f"{repr(item):<8} : {value!r}")
```
I haven't gotten any responses yet. If nobody can replicate the issue in the next few weeks, maybe we should mark it as closed.

**Comment by pranavsetpal** [comment]
I am facing the same issue. The workaround works.

I tested this on a new venv with only pyglet installed, simply ran
```python
import pyglet
window = pyglet.window.Window()
```

![image](https://github.com/pyglet/pyglet/assets/68775426/383181e3-b339-4ea3-a3e8-c8c221cc1491)
LC_TYPE and LC_ALL env vars are not set.

**Comment by pushfoo** [comment]
@pranavsetpal Thank you for the response. I have some follow-up questions.

>  Changing LANG to en_US fixes it

Do you mean by setting the `LANG` environment variable outside of Python, or by using the following code [which I posted above](https://github.com/pyglet/pyglet/issues/520#issuecomment-1719398873)?

```Python
import os
os.environ['LANG']='en_US'
```

Can you check if setting the `LANG` environment variable to either of the following work instead?

1. `in_EN.UTF-8`
2. `in_EN.utf8`

I possible, please check setting this from outside Python and by setting it from Python code as in the example above.

**Comment by pranavsetpal** [comment]
Yes, I meant changing the LANG variable outside Python.
I ran `LANG=en_US python test.py` which worked.


> Can you check if setting the `LANG` environment variable to either of the following work instead?

This throws the same error
`pyglet.window.xlib.XlibException: Could not create UTF8 text property`

Also, I just wanted to confirm, you mean `en_IN.UTF8` / `en_IN.utf8` right?
> Can you check if setting the `LANG` environment variable to either of the following work instead?
>     1. `in_EN.UTF-8`
>     2. `in_EN.utf8`

**Comment by pranavsetpal** [comment]
I was running the script while changing the `LANG` var and it seems pyglet will run w/o issues even when `LANG` is simply nonsense

![image](https://github.com/pyglet/pyglet/assets/68775426/161c4608-b539-44b1-bb20-5a6f8635b234)

**Comment by benmoran56** [comment]
@pranavsetpal thanks for looking into this. Since you have an environment where we can replicate the error, it should be easy enough to add a fix.

Out of curiosity, can you check what `xlib._have_utf8` is?  I'm curious if this is affected by setting the LANG, even if it's nonsense. 
```py
>>> import pyglet
>>> 
>>> pyglet.window.xlib._have_utf8
True
```

**Comment by benmoran56** [comment]
On second look, we are only checking if xlib has a specific UTF option available, so I think that will be True on all modern systems. 

Instead, can you share the output of `locale.getlocale()` in both cases? 
```py
import locale

locale.getlocale()
```

I'm thinking this should be enough if a UTF8 compatible locale is actually available or not.

**Comment by pranavsetpal** [comment]
Ran `locale.getlocale()`, here's the output 
![image](https://github.com/pyglet/pyglet/assets/68775426/0cf9dba4-6bc7-4c14-b75b-13d51f542abe)

This doesn't seem like an issue in pyglet, as it correctly detects the locale being not UTF-8. Manually forcing the locale to UTF-8, again, correctly allows pyglet to run.
`en_US.UTF-8` seems to be the fallback locale that was set during installation, hence nonsense LANG did not give any issue.

Interestingly, Calamares has uncommented `en_IN UTF-8` in the `locale.gen`, but on generating the locales, the system generates `en_IN.UTF-8`. Maybe as it's not specified in the LANG var, the system assumes ISO8859-1, and pyglet thus throws the issue.

**Comment by pranavsetpal** [comment]
> There is a [well known issue](https://stackoverflow.com/a/60897278/1509695) 

I tested why the 2nd solution in the link above doesn't work (for me), and changing the env var inside Python doesn't change the locale being used and thus didn't work.

```python
import os
os.environ["LANG"] = "en_US"

import locale
print("Locale:", locale.getlocale())

import pyglet
pyglet.window.Window()
```
Output:
```bash
Locale: ('en_IN', 'ISO8859-1')
Traceback (most recent call last):
...
pyglet.window.xlib.XlibException: Could not create UTF8 text property
```

**Comment by benmoran56** [comment]
Thank you for the information. Using that, I added a potential fix. 

If you are able to test with the latest code in master, can you see if it helps?
It's now relying on the result from the `locale` module to determine if it should use the UTF8 code paths.

**Comment by pranavsetpal** [comment]
It works, but it doesn't seem right. The `_have_utf8` check fails yet it runs.

test.py
```python
import locale
import pyglet

print("Locale:", locale.getlocale())
print("_have_utf8 check:", locale.getlocale()[1] == 'UTF-8')
print("_have_utf8 real :", pyglet.window.xlib._have_utf8)

pyglet.window.Window()
```

Output:
```bash
(venv) [pranav@portable pyglet]$ python test.py 
Locale: ('en_IN', 'ISO8859-1')
_have_utf8 check: False
_have_utf8 real : False
```

**Comment by benmoran56** [comment]
That was the idea.
Ideally, this should allow pyglet programs to still run in systems without UTF8 locales.

This allows you to create a Window without crashing?

**Comment by pranavsetpal** [comment]
Oh, well in that case it works. It creates the window without any issues.

**Comment by benmoran56** [comment]
Great! Thanks again for your help on this.

I suppose we can close this now, as the fix will be in the next point release.

**Comment by pushfoo** [comment]
@matanster If you or your coworkers need to set pyglet-based tools up on their own systems, you might no longer need the locale tweaks you might no longer need the locale workarounds in future releases.

If you're using an RTL language things might still break in but in different ways.
