### ISSUE TITLE
pyglet keyboard events and old frames popping creepily from the past

### ISSUE THREAD

**Issue by matanster** [pyglet/pyglet#523]
Thanks for this wonderful library. 

I have reduced a problem I am encountering, to the following minimal code. The code below should just show a running counter.

However when it's running, pressing keyboard keys will occasionally cause an old frame to show ― one that should have been (only) drawn once before. For example, you will see the drawn text counter go from 1 to 100, but occasionally after a key press, the window will have a smaller number drawn on it, as if it is going back in time or popping an old frame to the display. 

```python
import pyglet

window_dimensions = (640, 400)
window = pyglet.window.Window(*window_dimensions)
window.set_visible()

i = 1


def update(dt):
    global i, window_dimensions
    i = i + 1

    # prepare text label saying the frame number
    text = pyglet.text.Label(
        text = str(i),
        font_name = 'Times New Roman',
        font_size = 16,
        x = window_dimensions[0] // 2, y = 50,
        anchor_x = 'center', anchor_y = 'center')

    window.clear()
    text.draw()


@window.event
def on_key_press(symbol, modifiers):
    pass


# kick it all off
pyglet.clock.schedule_interval(update, 1/2)
pyglet.app.run()
```

Version information:

Pyglet version 1.5.21
Python 3.8.3
Ubuntu 20.04

Am I using the library in any non-idiomatic way causing this behavior? Is more version information necessary?

**Comment by caffeinepills** [comment]
2 things.
1) Your update is creating new labels every 0.5 seconds. Create one label outside, and update the text as needed (`text.text = "New text"`) in your update.
2) You should be putting your drawing in the `on_draw` event such as:
```py
@window.event
def on_draw():
    window.clear()
    text.draw()
 ```
 
 Hope that helps.

**Comment by matanster** [comment]
Yes, thanks, it's exactly what I have done! Just took a while to follow the examples more closely to avoid these mis-usage patterns.
