### ISSUE TITLE
UTF-8 Decoding issue if font name is weird

### ISSUE THREAD

**Issue by pvcraven** [pyglet/pyglet#524]
Over at Arcade I've seen two people post with this error.

```
    UnicodeDecodeError                        Traceback (most recent call last)
    _ctypes/callbacks.c in 'calling callback function'()
    
    ~\AppData\Roaming\Python\Python38\site-packages\pyglet\font\win32query.py in _enum_font_names(logfont, textmetricex, fonttype, param)
        341 
        342     lf = logfont.contents
    --> 343     name = lf.lfFaceName.decode('utf-8')
        344 
        345     # detect font type (vector|raster) and format (ttf)
    
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 0: invalid start byte
```
See: https://github.com/pythonarcade/arcade/issues/1054

I assume the font name isn't decodable with UTF-8.

I'm not sure about the solution. One could just silently skip the font? Or at least print out an error that gives a better idea of what's happening? Or what font it is tripping up on?

**Comment by shenjackyuanjie** [comment]
oh! this problem!
i found it too, you can check #518 to see how to change it. it may help

**Comment by einarf** [comment]
Anyone have the exact byte contents of `lfFaceName` and possibly the exact font that triggers this issue? Would be a lot easier to debug this.

**Comment by shenjackyuanjie** [comment]
> Anyone have the exact byte contents of and possibly the exact font that triggers this issue? Would be a lot easier to debug this.`lfFaceName`

yes i do！
check this out：http://gofile.me/4yON4/haluBRI2f

**Comment by einarf** [comment]
[sarasa-gothic-sc-regular.zip](https://github.com/pyglet/pyglet/files/7832155/sarasa-gothic-sc-regular.zip)

**Comment by shenjackyuanjie** [comment]
yes, this one. it will show chinese in china
![image](https://user-images.githubusercontent.com/54507071/148626518-a27ed59b-ac8f-4102-81a8-c8eb8e82468d.png)
so it's encode in `gb2312`

**Comment by shenjackyuanjie** [comment]
(also, when will #518 be merge?

**Comment by shenjackyuanjie** [comment]
> yes, this one. it will show chinese in china ![image](https://user-images.githubusercontent.com/54507071/148626518-a27ed59b-ac8f-4102-81a8-c8eb8e82468d.png) so it's encode in `gb2312`

`gb2312` is the local encode in china main land
in china Taiwan, it will be `Big5`

**Comment by caffeinepills** [comment]
Potential issues I see is that the default type for all font loaders is utf-8. Quartz only supports utf-8, so making it fallback on just Windows will lead to inconsistent results on cross platform.

**Comment by caffeinepills** [comment]
#584 Should resolve the issue.

Also note, the reason it happens in Arcade is because of a tuple of font names supplied to a Label. This causes a `have_font` check every time it modifies text.

**Comment by caffeinepills** [comment]
Resolved.
