### ISSUE TITLE
Module 'pyglet.window' has no attribute 'Mat4'

### ISSUE THREAD

**Issue by pauljurczak** [pyglet/pyglet#527]
I'm running pyglet 1.5.21 on Ubuntu 20.04 with Python 3.8.10. Example:
https://github.com/pyglet/pyglet/blob/master/examples/3dmodel/model.py produces this error:
```
  File "pyglet-2.py", line 8, in <module>
    window.projection = pyglet.window.Mat4.perspective_projection(0, 720, 0, 480, z_near=0.1, z_far=255)
AttributeError: module 'pyglet.window' has no attribute 'Mat4'
```

**Comment by einarf** [comment]
You have to use the examples in the `pyglet-1.5-maintenance` branch:
https://github.com/pyglet/pyglet/tree/pyglet-1.5-maintenance

 The `master` branch is currently pyglet 2.0 pre-release.
