### ISSUE TITLE
Mesh font with size less than one

### ISSUE THREAD

**Issue by pauljurczak** [pyglet/pyglet#532]
This is a repost of https://stackoverflow.com/questions/70630587/rendering-font-size-smaller-than-1-in-pyglet.

Is there a mesh font option easy to use with Pyglet? It can be an external module.

**Comment by benmoran56** [comment]
I'm not very familiar with mesh fonts, so I don't know of any off libraries off-hand. If there is an external library available, it only needs to provide a list of vertices to be usable with pyglet.

**Comment by pauljurczak** [comment]
Thank you.
