### ISSUE TITLE
Don`t recognise Xbox Series S controller (pyglet 2.0.dev9)

### ISSUE THREAD

**Issue by Alexey045** [pyglet/pyglet#537]
I connect my controller to my laptop and run code from pyglet/examples/input/gamecontroller.py

Code doesn`t see my controller, but recognise it like joystick by pyglet.input.get_joysticks() function.

**Comment by benmoran56** [comment]
You can add the additional controller mappings from here:
https://github.com/gabomdq/SDL_GameControllerDB  [gamecontrollerdb.txt](https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt)

`pyglet.input.controller.add_mappings_from_file()`
or
`pyglet.input.controller.add_mappings_from_string()`

Please note that `input.gamecontroller` has been renamed to `input.controller`, 
so please change that if you pull from master.

**Comment by benmoran56** [comment]
The latest dev releases have native support for XInput, so this should work natively now without mappings. Please follow up if you still have issues, but I'll close this for now.
