### ISSUE TITLE
ffmpeg requirement ?

### ISSUE THREAD

**Issue by xantares** [pyglet/pyglet#54]
I think ffmpeg is missing from the requirements section of README.rst
But I dont know what is the default backend for playing audio on Linux : openal or ffmpeg ?

**Comment by caffeinepills** [comment]
ffmpeg is not a requirement to use or run pyglet. (or play audio, as you can play uncompressed wave files). If you want more supported formats you will have to use ffmpeg.

Please read the docs regarding audio compatibility, which formats are supported, platform specifics and other information.
https://pyglet.readthedocs.io/en/stable/programming_guide/media.html

**Comment by benmoran56** [comment]
The default "backend" for playing is either OpenAL, PulseAudio, or DirectAudio. pyglet interfaces with these directly. 

FFmpeg is only used for decoding audio/video, not playback. As caffeinepills said, it's only optional, and you can playback wav files without it.

**Comment by xantares** [comment]
thanks for clarifying
