### ISSUE TITLE
[2.0] Window.set_size no longer dispatch on_resize (windows 10)

### ISSUE THREAD

**Issue by einarf** [pyglet/pyglet#542]
There seems to be a change in behavior between dev11 and dev12.

If you call `set_size(...)` in the window initializer (subclass) the `on_resize` method is never dispatched. You can however call `set_size()` later and it will work, but not in the window initializer.

The user is doing something like this:

```py
class App(Window):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs, resizable=True)
        # Apply configuration from config.yml
        self.set_icon(c.ICON)
        self.set_caption(c.TITLE)
        self.set_size(c.WIDTH, c.HEIGHT)
        self.set_update_rate(1 / c.FPS)
```

This did work in dev11  and earlier.

The image below shows an image with misconfigured viewport. The white area is even part of the bug here. It's persistent might indicate the underlying framebuffer itself was not really resized at all?

![2 6 7](https://user-images.githubusercontent.com/5418180/152644351-81bc12e6-c8f6-42df-816c-c9a8ba652091.gif)

**Comment by benmoran56** [comment]
This should now be fixed in master.

**Comment by caffeinepills** [comment]
Sorry I just realized this wasn't addressed.

This should be resolved in https://github.com/pyglet/pyglet/pull/583

Works on 1.5 with Windows 10. Is it possible you can test this in master to make sure it's working now?

**Comment by caffeinepills** [comment]
Confirmed working by @einarf
