### ISSUE TITLE
KeyError: 'headless' when running 'CarRacing-v1' env.render()

### ISSUE THREAD

**Issue by imacryptorick** [pyglet/pyglet#546]
code snippet 
```
import gym 
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import VecFrameStack
from stable_baselines3.common.evaluation import evaluate_policy
import pyvirtualdisplay
import os

env.render()
env.reset() #same error with either/both methods 
```
error:

```KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_70911/1491641550.py in <module>
----> 1 env.render()
      2 env.reset()

~/anaconda3/lib/python3.9/site-packages/gym/core.py in render(self, mode, **kwargs)
    284     @metadata.setter
    285     def metadata(self, value):
--> 286         self._metadata = value
    287 
    288     def step(self, action):

~/anaconda3/lib/python3.9/site-packages/gym/core.py in render(self, mode, **kwargs)
    284     @metadata.setter
    285     def metadata(self, value):
--> 286         self._metadata = value
    287 
    288     def step(self, action):

~/anaconda3/lib/python3.9/site-packages/gym/envs/box2d/car_racing.py in render(self, mode)
    398         assert mode in ["human", "state_pixels", "rgb_array"]
    399         if self.viewer is None:
--> 400             from gym.envs.classic_control import rendering
    401 
    402             self.viewer = rendering.Viewer(WINDOW_W, WINDOW_H)

~/anaconda3/lib/python3.9/site-packages/gym/envs/classic_control/rendering.py in <module>
     25 
     26 try:
---> 27     from pyglet.gl import *
     28 except ImportError as e:
     29     raise ImportError(

~/anaconda3/lib/python3.9/site-packages/pyglet/gl/__init__.py in <module>
    214     from .base import Config
    215 
--> 216 elif _pyglet.options['headless']:
    217     from .headless import HeadlessConfig as Config
    218 elif compat_platform in ('win32', 'cygwin'):

KeyError: 'headless'
```
using 
Running on Ubuntu 20.04.3 LTS 
Gnome 3.36.8
Jupyter Notebooks via Anaconda

**Comment by benmoran56** [comment]
Seems like you might have an older version of pyglet installed.

**Comment by imacryptorick** [comment]
I've reinstalled pyglet by running ``` pip install pyglet==1.5.21 ``` but I still get the same error

**Comment by benmoran56** [comment]
There might be a conflict with your environment somewhere. `pyglet.options` is just a dictionary, and definitely exists in the latest releases:

https://github.com/pyglet/pyglet/blob/a8aef80969ad783d62ae8326b6d4d5159bd77208/pyglet/__init__.py#L142

You can try printing out the `pyglet.version` at the top of your program, immediately after importing pyglet, to confirm which version it's picking up.

Also try pip uninstall, multiple times. I don't use Anaconda,  but it's possible you have multiple versions of packages installed.

**Comment by imacryptorick** [comment]
I've checked the version, and it's 1.5.21, seems to work fine with another game "CartPole-v0", is it possible to check whether multiple versions are installed before uninstalling all packages? (or did you mean to just uninstall `pyglet` multiple times?
![Screenshot from 2022-02-20 07-41-24](https://user-images.githubusercontent.com/45295585/154830245-55c70e9a-3be1-4ee7-ba84-29654d1d86c9.png)
)

**Comment by benmoran56** [comment]
I just meant to try uninstalling pyglet more than once. Pip will check all potential locations, so if you have multiple installed it may find them. I'm not sure of another way to check, because it depends a lot on how your environment and paths are set up.

**Comment by benmoran56** [comment]
Closing this due to age, but if you're still having issues please follow up or reopen the ticket. Thanks!
