### ISSUE TITLE
Font loading can be incredibly slow and cause errors in console

### ISSUE THREAD

**Issue by DigiDuncan** [pyglet/pyglet#547]
Booting my app begins with a 10 second lag spike. and a few errors in console of the form:
```
Exception ignored on calling ctypes callback function: <function _enum_font_names at 0x0000023342CB1750>
Traceback (most recent call last):
  File "C:\Users\digid\.conda\envs\Charm-Tests\lib\site-packages\pyglet\font\win32query.py", line 343, in _enum_font_names
    name = lf.lfFaceName.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 8: invalid start byte)
```

It only seems to happen once a call to something that uses fonts is made (e.g.: `draw_text()` from Arcade.)
It seems to happen because pyglet's `_enum_font_names()` is called on every font on the system.
After modifying pyglet's `_enum_font_names()` to count how many times it's called, it's returning... 5369. I may have a lot of fonts. 😅
The errors I were getting were from `pyglet.font.win32query` line 343, and were because of these fonts:

**=== FONTS CONTAINING `\x99` (™) ===**
`b'Abaddon\x99'`
`b'Mephisto\x99'`

**=== FONTS CONTAINING `\xa9` (©) ===**
`b'Key Extended \xa9 SD'`
`b'Key Normal \xa9 SD'`

**Comment by benmoran56** [comment]
Do you have about 5000 fonts installed? We're using [EnumFontFamiliesExA](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-enumfontfamiliesexa), which as far as I can tell is going to call `_enum_font_names` (or whatever callback is assigned) for each font it finds on the system. I'm not sure if there is a way that the performance could be improved or not. It would be interesting to make a minimal test with just this code segment, and get a baseline of the performance. 

You might try the new DirectWrite backed font loader, by setting `pyglet.options["advanced_font_features"] = True` after pyglet is imported. This is not as widely tested yet, but should work fine on modern Windows.

**Comment by DigiDuncan** [comment]
For context, I have 813 fonts installed on my system. I've been collecting fonts for over a decade 😅 
But I wouldn't want a fellow font-collector like me to have this issue, either! I'm glad I ran into it.

Just an off-the-top idea I had to maybe prevent this issue is to have an option to have it only cache fonts the user specifies (so you'd tell it what fonts you plan to use in the app), which could cut down on this a lot.

If that's not possible, of course, my only concern would be that turning on `pyglet.options["advanced_font_features"] = True` may break compatibility with non-Windows platforms, based on the way you worded it?

This also doesn't deal with the error of the characters "™" or "©" causing errors in console when they exist on the system.

**Comment by DigiDuncan** [comment]
Switching to the advanced font features did seem to significantly increase load times!|

However, the fonts with the "™" or "©" characters in the name still cause errors in the console, even with that feature enabled.

**Comment by DigiDuncan** [comment]
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 11: invalid start byte
Exception ignored on calling ctypes callback function: <function _enum_font_names at 0x000002746BB35750>
Traceback (most recent call last):
  File "C:\Users\digid\.conda\envs\Charm-Tests\lib\site-packages\pyglet\font\win32query.py", line 343, in _enum_font_names
    name = lf.lfFaceName.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 8: invalid start byte
```
That font is `b'Key Normal \xa9 SD'`, or rather, "Key Normal © SD". It seems it's not a fan of either the copyright or trademark symbol being in the font name.

You can freely download that font here: https://fonts2u.com/key-normal-sd.font

**Comment by benmoran56** [comment]
Aren't those characters invalid for the font name? I recall reading that the name should be the ascii subset of Unicode8, but I could be wrong. In any case, this doesn't even appear to be valid unicode :thinking: 

On my Linux machine's system font viewer it gets replaced with a "?" mark, so it becomes "Key Normal ? SD". 
This also would indicate that the characters are invalid. 
I suppose we could do something similar in pyglet.

**Comment by caffeinepills** [comment]
Pretty sure win32query is just used for GDI+ So the advanced font features shouldn't even need to load that file.

**Comment by caffeinepills** [comment]
#584 Should resolve this issue and prevent from crashing.

Tested using the font mentioned:
```py
font = pyglet.font.load("Key Normal © SD")

print(font, font.name, font.have_font("Key Normal © SD"))
```
results: `<pyglet.font.win32.GDIPlusFont object at 0x02094B10> Key Normal © SD True`

Also in posters last update they mention this line: 
`` File "C:\Users\digid\.conda\envs\Charm-Tests\lib\site-packages\pyglet\font\win32query.py", line 343, in _enum_font_names
    name = lf.lfFaceName.decode('utf-8')```

Which indicates they never did switch to using DirectWrite. Either way this should be resolved in both font renderers.
(Also note, it seems GDI cannot render this Key Normal font, only DirectWrite does)

**Comment by DigiDuncan** [comment]
> Which indicates they never did switch to using DirectWrite.

I _did_ turn on `pyglet.options["advanced_font_features"] = True`, which did make a noticable change in load times (indicating it was in fact doing _something_,) but it still seemed to run that line.

**Comment by einarf** [comment]
Arcade do curretly force GDI in 2.6. The idea was to swap to directwrite in 2.7

**Comment by caffeinepills** [comment]
Closing as now the original issue of unicode font names has been resolved.
