### ISSUE TITLE
Feature Request - Access file name used to create a sprite

### ISSUE THREAD

**Issue by cogerk** [pyglet/pyglet#549]
### Description:
It would be really useful to be able to access the file name(s?) used to make a sprite.

### Desired behavior:
```
>>>my_sprite = pyglet.sprite.Sprite('sprite_img.png')
>>>my_sprite.file
'sprite_img.png'
```
This could return a list of file names if the sprite has multiple resources (actually not sure if that's possible now that I think about it?) or None is sprite resource doesn't use a file.

### Use Case:
If in a unit test, you would like the fail message to describe which sprite failed to meet test conditions. For example:

```
class Tests(unittest.TestCase):
    def test_sprites_aligned(self):
        for spr in enumerate sprite_list:
            self.assertEqual(spr, 100, f"{spr.file} ")
            self.assertEqual(parent_sprite_y, gem_sprite_y, f"{idx.file} not aligned")
```
Would return on fail something like 
```
0 != 100, sprite_img.png not aligned
```

### Workaround:
For anyone who needs similar functionality today:
```
# Attach image filename to image when loading
def load_image(filename):
    image = pyglet.resource.image(filename)
    image.filename = filename
    return image


img = load_image("Block_Aqua.png")
print(img.filename)


# Attach image filename to sprite via subclass
class LabeledSprite(pyglet.sprite.Sprite):
    def __init__(self, img_file):  # Might also include: x, y, batch etc...
        sprite_img = load_image(img_file)
        super().__init__(sprite_img)  # Might also include: x, y, batch etc...
        self.filename = img.filename


sprite = LabeledSprite("Block_Aqua.png")
print(sprite.filename)

```
h/t to the discord devs for this idea!

**Comment by benmoran56** [comment]
Sorry for the slow reply.

I think the workaround is probably the best way to handle this. Sprites can be created with an image or texture, but these may not necessarily have been loaded from a file. It's possible to generate image data, or load from other sources.
