### ISSUE TITLE
Bug: local FFmpeg ("lib" directory) cannot be found on MacOS

### ISSUE THREAD

**Issue by fladd** [pyglet/pyglet#554]
The documentation mentions that pyglet can find local FFmpeg libraries (i.e. not system-wide installed) in one of two ways:
1. By setting `pyglet.options['search_local_libs'] = True` and putting the binaries in a 'lib' directory next to the calling script
2. By adding the library path to `os.environ["LD_LIBRARY_PATH"]`

On MacOS, neither of these methods work.

The following ZIP file contains a test scenario (including a 'lib' folder with binaries taken from a Homebrew FFmpeg installation) that demonstrates the bug: [pyglet_ffmpeg_bug.zip](https://github.com/pyglet/pyglet/files/8190492/pyglet_ffmpeg_bug.zip)

When running the script `test.py` on my machine (after uninstalling the Homebrew FFmpeg installation), I get the following output:

```
1 floriankrause~/Downloads/pyglet_ffmpeg_bug % python test.py                :(

'LD_LIBRARY_PATH' content
-------------------------

/Users/floriankrause/Downloads/pyglet_ffmpeg_bug/lib

'lib' directory content
-----------------------

['libswscale.5.9.100.dylib', 'LICENSE.md', 'libswscale.dylib', 'libavutil.56.70.100.dylib', 'pkgconfig', '.DS_Store', 'libswscale.5.dylib', 'libswresample.3.dylib', 'libavutil.a', 'libavcodec.a', 'libavformat.58.dylib', 'libavformat.58.76.100.dylib', 'libswresample.3.9.100.dylib', 'COPYING.LGPLv2.1', 'libavformat.dylib', 'libavutil.dylib', 'libavformat.a', 'libavutil.56.dylib', 'libavcodec.dylib', 'libswresample.a', 'libswresample.dylib', 'COPYING.GPLv2', 'COPYING.GPLv3', 'COPYING.LGPLv3', 'libavcodec.58.134.100.dylib', 'libswscale.a', 'libavcodec.58.dylib']

Attempting to import pyglet with ffmepg
---------------------------------------

Pyglet version: 1.5.21

Traceback (most recent call last):
  File "/Users/floriankrause/Downloads/pyglet_ffmpeg_bug/test.py", line 30, in <module>
    from pyglet.media.codecs.ffmpeg import *
  File "/Users/floriankrause/.local/pipx/venvs/zipped-album-player/lib/python3.10/site-packages/pyglet/media/codecs/ffmpeg.py", line 55, in <module>
    from .ffmpeg_lib import *
  File "/Users/floriankrause/.local/pipx/venvs/zipped-album-player/lib/python3.10/site-packages/pyglet/media/codecs/ffmpeg_lib/__init__.py", line 36, in <module>
    from .libavcodec import *
  File "/Users/floriankrause/.local/pipx/venvs/zipped-album-player/lib/python3.10/site-packages/pyglet/media/codecs/ffmpeg_lib/libavcodec.py", line 48, in <module>
    avcodec = pyglet.lib.load_library(
  File "/Users/floriankrause/.local/pipx/venvs/zipped-album-player/lib/python3.10/site-packages/pyglet/lib.py", line 164, in load_library
    raise ImportError('Library "%s" not found.' % names[0])
ImportError: Library "avcodec" not found.
```

**Comment by fladd** [comment]
Could someone maybe confirm this? Or point me to how to get it working?

**Comment by caffeinepills** [comment]
I know 5.0 isn't supported yet. Have you tried printing what pyglet sees in the lib directory? 

Looks like this is the relevant code for searching local lib:
```py
    script_path = pyglet.resource.get_script_home()
    cwd = os.getcwd()
    _local_lib_paths = [script_path, os.path.join(script_path, 'lib'), os.path.join(cwd, 'lib')]
    if pyglet.compat_platform == 'win32':
        os.environ["PATH"] += os.pathsep + os.pathsep.join(_local_lib_paths)
```

You could try playing with this to make sure the dylib files show up in there.

Unfortunately I don't own any Mac hardware to really help with this.

**Comment by benmoran56** [comment]
Importing 5.0 won't work at all yet, until the bindings are updated. 
Try with a 4.x version.

**Comment by fladd** [comment]
The bug is with version 4 of course.

**Comment by benmoran56** [comment]
Sorry, my mistake. 
Try setting `pyglet.options['debug_lib'] = True` immediately after `import pyglet`, and see if you get any useful information. 

I don't have access to a Mac either, but if you are able to do a bit of digging on your side then maybe we can get this improved. 
The source for the MacOS loader is located here: https://github.com/pyglet/pyglet/blob/master/pyglet/lib.py#L174
This code should work fairly well stand-alone as well, for testing. 

There isn't a lot to it. Basically just: 
1. Try several ways to locate the lib.
2. Open the lib with ctypes.cdll.LoadLibrary(....), and return it. 

Just for a quick sanity test, you might want to first try loading the lib directly with ctypes.
If that works, then it's just a matter of making sure the loader can properly index the location.

**Comment by fladd** [comment]
There was a problem with the binaries I used (they were linking to other libs with an absolute path). Once that was fixed, setting LD_LIBRARY_PATH worked.
