### ISSUE TITLE
FPS drops by 30-50% when enabling fullscreen on Raspberry Pi 4 on Raspberry Pi OS Bullseye over VNC

### ISSUE THREAD

**Issue by tomhaines** [pyglet/pyglet#556]
Python: 3.9.2
Pyglet: 1.5.21

RAM: 4GB

Display driver: vc4-fkms-v3d
GPU Mem: 256M

When switching to fullscreen on an RPI4 connected over VNC, FPS drops from around 40 down to 20 or 10. The following code reliably produces this

```python
import pyglet

lbl = pyglet.text.Label('FPS: ',
  font_name='Monospace Regular',
  font_size=14,
  x=10, y=1000)
							  
window = pyglet.window.Window(1920,1080, fullscreen=False)

# Listen for keyboard input events from pyglet
@window.event
def on_text(text) :
  window.set_fullscreen(not window.fullscreen)

@window.event
def on_draw() :
  window.clear()
  
  lbl.draw()

def update_lbl(dt) :
  lbl.text = "FPS: %.2f" % round(pyglet.clock.get_fps(), 2)

pyglet.clock.schedule(update_lbl)

pyglet.app.run()
```

**Comment by tomhaines** [comment]
I have updated this code snippet to use the more appropriate ```FPSDisplay```, and it is illustrating the same behavior. It also now displays ```dt``` illustrating that  there are fewer actual clock ticks happening in full screen than in windowed mode.

Also, to add clarity, the VNC display is set to 1920x1080, which is the same size as the window size, so it's not as though Pyglet is drawing a larger window in full screen

```python
import pyglet
		  
window = pyglet.window.Window(1920,1080, fullscreen=False)
fps_display = pyglet.window.FPSDisplay(window)
fps_display.label.y = 1040

lbl = pyglet.text.Label('DT: ',
  font_name='Monospace Regular',
  font_size=14,
  x=10, y=1000)

# Listen for keyboard input events from pyglet
@window.event
def on_text(text) :
  window.set_fullscreen(not window.fullscreen)

@window.event
def on_draw() :
  window.clear()
  lbl.draw()
  fps_display.draw()

def update_label(dt) : 
  lbl.text = "DT: %f" % dt

pyglet.clock.schedule(update_label)

pyglet.app.run()
```

Please let me know if there is any further info I can provide or debugging I can assist with. The performance I am seeing is great in windowed mode, but too slow in full screen mode. It is a requirement for this app to run in full screen.

**Comment by benmoran56** [comment]
Hi, 

As a first step, you should switch to `clock.schedule_interval(...)`.  If the application is not GPU limited, then using `clock.schedule` will choke the CPU and could cause issues with input handling. 
Before trying anything remote, I would make that change and then get a baseline with a monitor plugged in. 

Regarding VNC, it's difficult to say what the issue might be. Actual network performance of 10-20fps doesn't sound too unusual for VNC - it's just not that fast at streaming over the network, especially at 1080p.
I would guess that when entering fullscreen, that the display refresh rate on the Pi is being locked to the VNC server. This might be something that can be configured on your VNC server, but i'm not sure. Disabling vsync may have some effect, if this is the case. 

As a workaround, you could try doing a borderless Window, with the same size as your desktop resolution:
```py
Window(width=1920, height=1080, style=Window.WINDOW_STYLE_BORDERLESS)
```
This can work well, if your desktop environment can be hidden.

**Comment by tomhaines** [comment]
Hi,

I can confirm that performance returns to normal when disconnected from VNC, so I will look to see what I can improve there. For what it's worth, setting `style=Window.WINDOW_STYLE_BORDERLESS` improved performance marginally over VNC but it is still slower than the default window.

Closing this as the issue is with VNC.
