### ISSUE TITLE
pyglet.media.exceptions.MediaDecodeException: [WinError -1072875852] 

### ISSUE THREAD

**Issue by AsciiP** [pyglet/pyglet#557]
when using
`source = pyglet.resource.load('test.mp4')`
![批注 2022-03-14 073656](https://user-images.githubusercontent.com/98245281/158084220-9784a947-dc4f-4e17-ba97-7ee4dd742878.png)

**Comment by caffeinepills** [comment]
Video codec is most likely not supported, install and use FFmpeg decoder. See the documentation on installation.

**Comment by AsciiP** [comment]
I may have installed FFmpeg correctly, but I still get this error

**Comment by caffeinepills** [comment]
It still may be forcing the old decoder. Verify pyglet sees ffmpeg (`pyglet.media.have_ffmpeg()`) if true, then force use that decoder:

```py
from pyglet.media.codecs.ffmpeg import FFmpegDecoder
ffmpeg_decoder = FFmpegDecoder()
source = pyglet.media.load(filename, decoder=ffmpeg_decoder)
```
