### ISSUE TITLE
new vector object and object coordinates to have matrix math methods

### ISSUE THREAD

**Issue by cenkt** [pyglet/pyglet#560]
I think it would be faster to program if the coordinates of the objects had matrix methods and we had a (unit) vector object again with matrix methods for its coordinates. As vector object can be proxied to speed and/or acceleration then it would make it easier to code movement.

example:
circle_a.plus(vector_a)
vector_a.dot(vector_b)

**Comment by benmoran56** [comment]
By objects, you mean Sprites, Shapes, etc?
It probably wouldn't be too difficult to replace the `Object.position` with a Vec2 by default.

**Comment by cenkt** [comment]
Yes I mean Sprites shapes ect... But what is Vec2?

**Comment by einarf** [comment]
> Yes I mean Sprites shapes ect... But what is Vec2?

https://github.com/pyglet/pyglet/blob/704352d74cfe4842d969ef3985f787aa33190d01/pyglet/math.py#L54

**Comment by cenkt** [comment]
Wow.... why is this math module not in the documents. 

Thnx for the quick response. Great work.

**Comment by benmoran56** [comment]
It was written for pyglet 2.0, where basic matrix classes will be necessary, but we merged it back to 1.5 for more testing and feedback. 

The design probably won't change at this point, so it should be documented.

**Comment by benmoran56** [comment]
I'll close this for now, but feel free to join the Discord or open a new ticket if you want to follow up.
