### ISSUE TITLE
Importing media.codecs fails on Linux without Gstreamer

### ISSUE THREAD

**Issue by fladd** [pyglet/pyglet#561]
It should be possible to import media.codecs without Gstreamer being available (e.g. because you want to only use FFmpeg).

Looking at https://github.com/pyglet/pyglet/blob/48251797f83fcc11a548fe160e223a9e4264e34d/pyglet/media/codecs/__init__.py#L85-L90 it seems that the intention here is also to catch errors on importing Gstreamer. However, while you only catch an ImportError, the error that is raised when Gstreamer (the package "python3-gst-1.0" to be precise) is a ValueError (see screenshot below).

![20220317_222418](https://user-images.githubusercontent.com/2971539/159100228-a05e1e22-bfcc-44bf-aa89-3ef07e51a9a2.jpg)

(The screenshot above is from Raspberry Pi OS, but the same happens in Debian)

**Comment by benmoran56** [comment]
Thanks for the information. 
The design is that the codecs themselves should only raise ImportErrors if they can't be imported for any reason. In this case we should catch the ValueError inside of gstreamer.py, and re-raise it as an ImportError. 

I'll try to get a patch out in the next point release.

**Comment by benmoran56** [comment]
This should be fixed in the latest point release. I'll close this ticket for now, but if you still see issues please reopen it. 

Thanks again!
