### ISSUE TITLE
Label error: can't render any mutiline texts

### ISSUE THREAD

**Issue by shenjackyuanjie** [pyglet/pyglet#563]
![image](https://user-images.githubusercontent.com/54507071/159517361-a99c2136-ba13-43df-9e2b-bea650a82d7f.png)

![image](https://user-images.githubusercontent.com/54507071/159517836-b7034b0d-bdfb-4deb-8a01-cf94ac5744fa.png)

version: 20220322 latest

`Python info and System info by DR crash report maker`

##  Python info
- `Version: 3.8.10`
- `Implementation: CPython`
- `Compiler: MSC v.1928 64 bit (AMD64)`
##  System info
- `System: Windows-10-10.0.19044-SP0`
- `Computer name: shenjack-5600X`
- `machine: AMD64`
- `processor: AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD`
- `release: 10`
- `version: 10.0.19044`

**Comment by caffeinepills** [comment]
Not sure what branch you are using, but this is fixed in the latest 1.5 branch.

Next time master is updated, it should be resolved.

**Comment by shenjackyuanjie** [comment]
> Not sure what branch you are using, but this is fixed in the latest 1.5 branch.
> 
> Next time master is updated, it should be resolved. As a workaround for now you can use `pyglet.options["win32_gdi_font"] = True`
> 
> EDIT: As to why this is happening. The default font renderer for Windows has been changed to DirectWrite, which had an issue with glyphs that have 0 width and 0 height (line breaks, and other 0 space characters). The option lets you force the old font renderer.

got it， i am using the master branch
