### ISSUE TITLE
Exception when using PYGLET_DEBUG_GL_SHADERS

### ISSUE THREAD

**Issue by chardbury** [pyglet/pyglet#567]
The following exception is raised when running with PYGLET_DEBUG_GL_SHADERS set.

```
[snip]
File "/Users/richard/Projects/template/venv/lib/python3.10/site-packages/pyglet/graphics/shader.py", line 394, in _introspect_uniforms
    for uniform in self._uniforms.values():
AttributeError: 'ShaderProgram' object has no attribute '_uniforms'. Did you mean: 'uniforms'?
```

The exception is spot on, I think; it should be `uniforms`. `self._uniforms` is not set until `_introspect_uniforms` returns.

https://github.com/pyglet/pyglet/blob/00c24ca456e2ef9ca9e92e614f26f25ea4039222/pyglet/graphics/shader.py#L383-L395

https://github.com/pyglet/pyglet/blob/00c24ca456e2ef9ca9e92e614f26f25ea4039222/pyglet/graphics/shader.py#L274

**Comment by benmoran56** [comment]
Thanks for opening the ticket. That bug slipped in during a recent cleanup. 
This is now fixed in master, and will be in the next point release.
