### ISSUE TITLE
Audio: Sources not seekable enters infinite loop when playing

### ISSUE THREAD

**Issue by einarf** [pyglet/pyglet#569]
With ffmpeg:

Sources with duration 0 is causing the media thread to be stuck in an infinite loop. It's difficult for most users to understand what is happening when their application locks up. An improvment would be to raise an error and provice a useful error message.

If it's possible to detect this in `play()` or when the source is loaded, even better.

**EDIT**
Note that you need to check that on_draw events are dispatched at the very least. Not creating a window and just loading and playing the file will just indicate that the audio is not playing. In reality your cpu working  hard and the event loop is stuck.

**Comment by caffeinepills** [comment]
This is due to ogg's sometimes have 0 bytes at the beginning. Looks like a PR was made a while back to FFmpeg where 0 data would return end of music (essentially). Changing to only return None if the audio is at the end seems to fix it on my end (Windows 10, FFmpeg):
```py
    def get_audio_data(self, num_bytes, compensation_time=0.0):
        data = b''
        timestamp = duration = 0

        while len(data) < num_bytes:
            if not self.audioq:
                data = None
                break
            audio_packet = self._get_audio_packet()
            buffer, timestamp, duration = self._decode_audio_packet(audio_packet, compensation_time)
            if not buffer:
                break
            data += buffer

        if data is None:
            return None

        audio_data = AudioData(data, len(data), timestamp, duration, [])

        while self._events and self._events[0].timestamp <= (timestamp + duration):
            event = self._events.pop(0)
            if event.timestamp >= timestamp:
                event.timestamp -= timestamp
                audio_data.events.append(event)

        if _debug:
            print('get_audio_data returning ts {0} with events {1}'.format(audio_data.timestamp, audio_data.events))
            print('remaining events are', self._events)

        return audio_data
 ```
