### ISSUE TITLE
MacOS: Memory leaks

### ISSUE THREAD

**Issue by DmitriiTrofimov** [pyglet/pyglet#575]
I have very intensive memory leaks with cocoa.

The code is:
```python
import pyglet

class EventLoop(pyglet.app.EventLoop):
    def __init__(self, max_fps: float = 60) -> None:
        self.max_fps = max_fps
        self.elapsed = 0
        super().__init__()

    def idle(self) -> None:
        dt = self.clock.update_time()
        redraw_all = self.clock.call_scheduled_functions(dt) and self.can_redraw(dt)

        # Redraw all windows
        for window in pyglet.app.windows:
            if redraw_all or (window._legacy_invalid and window.invalid):
                window.switch_to()
                window.dispatch_event('on_draw')
                window.flip()
                window._legacy_invalid = False

        # Update timeout
        return self.clock.get_sleep_time(True)

    def can_redraw(self, dt) -> bool:
        # This function prevents too frequent redrawing
        self.elapsed += dt
        if self.elapsed > 1 / self.max_fps:
            self.elapsed -= 1 / self.max_fps
            return True
        return False

window = pyglet.window.Window(resizable=False, caption="Some caption", width=320, height=320)
window.set_vsync(False)

def update(dt):
    pass

pyglet.app.event_loop = EventLoop()
pyglet.clock.schedule(update)
pyglet.app.run()
```

The one of several memory leak sources is [here](https://github.com/pyglet/pyglet/blob/29663e6a3dcaec472100412f0b590b2e8728ca78/pyglet/libs/darwin/cocoapy/runtime.py#L935). I've exchanged dict with WeakValueDictionary and it has helped a bit, but memory leaks do not completely go away.

**Comment by benmoran56** [comment]
Thanks for opening the ticket. Unfortunately I don't have access to a Mac at the moment, but I think you're on the right track. 

Just for a test, could you try the latest code in `master`? Your test code should work fine if you remove the `_legacy_invalid` parts.

**Comment by einarf** [comment]
I see the same in master branch. A lot of objects accumulating in `ObjCInstance._cached_objects`. Changing to WeakValueDictionary keeps it at ~17-18 elements constantly and the leaks are reduced quite a bit.

Still, after 15-20 minutes the application memory do increase by 100MB ish.

**Comment by caffeinepills** [comment]
Memory leaks should be resolved in https://github.com/pyglet/pyglet/pull/790
