### ISSUE TITLE
media player example code

### ISSUE THREAD

**Issue by matanster** [pyglet/pyglet#576]
I have pulled from master a couple of hours ago to run [the media player example](https://github.com/pyglet/pyglet/blob/master/examples/media/media_player.py) in its own virtual environment, and am getting an error which I would not get when loading the same media files in my pip installed version of pyglet:

`pyglet.media.codecs.wave.WAVEDecodeException: file does not start with RIFF id`

That is, when using my pip installed pyglet version 1.5.21 I am able to `pyglet.media.load` the same mp4 files without encountering this issue. Just wondering if this is any kind of minor regression. 

My version of python: 3.9.5. 

Notwithstanding, the Asteroid code example runs just fine and I could destroy many cookies there :-)

Thanks for the great library and perhaps you may have some idea about this.

**Comment by benmoran56** [comment]
Thanks for opening the ticket. There were some changes in this area recently, so maybe some bugs crept in. I'll have a look at this soon.

**Comment by matanster** [comment]
Thanks a lot and BTW, what are the benefits of using the library (say, the player module or in general) by way of sub-classing its classes? I have seen this a lot but am using the library myself for graphics, and separately also the player module, by instantiating its objects rather than sub-classing them. Anyway, thanks for having a look at that!

**Comment by einarf** [comment]
Somehting broke really bad in alpha 3. I have sound crashes in unit tests etc. Need to look more into it.

**Comment by benmoran56** [comment]
I just pushed a bunch of cleanups to the master branch. 
Could you see how it goes now? 
If you still have issues, could you post the name of the file you're trying to load? 

In answer to your other question, it's really just a matter of preference. If you just want to override one method on a class, then subclassing can be an quick way to do that. I personally prefer to do composition over subclassing most of the time, but there really is no "right" answer. When in comes to Python in particular, you have a lot of freedom with things.

**Comment by matanster** [comment]
Thanks, I wasn't sure of particular ways that the media module has been designed specifically towards specific benefits. 

As to running the player, I am now getting a different crash. Tried it with two random videos I have downloaded using the youtube-dl tool (mp4 files in both cases). 

This is the output I am getting:

FFmpeg Loaded Versions: {'avcodec': 59, 'avformat': 59, 'avutil': 57, 'swresample': 4, 'swscale': 6}
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

It's an Ubuntu 20.04 machine.

I can safely use the pip provided version of pyglet for media playing (although, the image frames sync to the video is broken in most cases other than the first 15 first seconds of the video or so, so I use pyglet's media player only for audio).

**Comment by caffeinepills** [comment]
@matanster Can you test the latest master branch, so we can continue on this issue? Thanks

**Comment by matanster** [comment]
Pulled and ran again now. Different distortions in both image stream and audio now. I somewhat doubt this can be really tested and iterated without direct developer access to the target OS. I tried with two random videos again, both of which downloaded from YouTube with youtube-dl.

**Comment by matanster** [comment]
But actually, with a third video, downloaded using youtube-dl with the same default parameters, it works just fine! I guess mileage may vary depending on the encoding details of the media, so maybe a test suite of sample videos (possibly re-encoded in multiple demonstrative ways) might help to narrow down the breadth of support.

**Comment by benmoran56** [comment]
It's probably an issue with the container type, or the combination of container/codecs. 
Do you have `ffprobe` available? It usually comes with FFmpeg. 
```sh
ffprobe <video>
```
If you can check the three videos, it would be useful to know the 
1. container type (mkv, mp3, webm, etc.)
2. video & audio codecs

**Comment by caffeinepills** [comment]
Also could you paste in your output with a paste in, with the debug media pyglet option enabled, mentioned in my previous post.

**Comment by matanster** [comment]
Till I cycle back to it, here is a listing of links to possibly free to use videos for testing, which I bumped into today ...
https://gist.github.com/jsturgis/3b19447b304616f18657

It could be more widely useful than troubleshooting for a particular video downloaded with a particular tool on a particular machine, which well describes my case. I haven't fully verified the terms of use of each and every video there myself yet. I'd vote for closing this issue per-se, leaving it to be re-opened if other folks run into similar trouble.

**Comment by caffeinepills** [comment]
I went through over half of the videos and they all play without issue on my system.

Can you go through and tell me which of those videos give you issues? We alos will need the pastebin of the debug messages you are getting when the playback starts having issues by enabling `pyglet.options["debug_media"] = True` at the top of your test script.

**Comment by caffeinepills** [comment]
Closing as unresponsive.
