### ISSUE TITLE
Poetry doesn't like pyglet alpha releases

### ISSUE THREAD

**Issue by einarf** [pyglet/pyglet#577]
Poetry installs pyglet 2.0dev2 instead of 2.0a2. It might be related to pyglet using a non-standard version string : https://peps.python.org/pep-0440/#developmental-releases

`2.0devX` is valid, but `2.0aX` is not. Pyglet should change to `2.0.aX` in the next release?

This issue could also affect pipenv, but I haven't tested it yet.

See arcade issue for details:
https://github.com/pythonarcade/arcade/issues/1156

**Comment by benmoran56** [comment]
Closing, since we switched back to `devXX`.
