### ISSUE TITLE
Do pyglet stable working on Windows 11?

### ISSUE THREAD

**Issue by meLeetCrash** [pyglet/pyglet#582]
https://youtu.be/fPxgh4hvMhg

it's video shows my problem with flickering text/image, when i'm press any button

**Comment by meLeetCrash** [comment]
https://youtu.be/fPxgh4hvMhg

**Comment by caffeinepills** [comment]
That's not the proper way to render an image. You are drawing your sprite in in the key press event. Refer to the docs for more information:

https://pyglet.readthedocs.io/en/latest/programming_guide/quickstart.html

**Comment by meLeetCrash** [comment]
@caffeinepills, thanks, i try to do it

**Comment by meLeetCrash** [comment]
AttributeError: 'NoneType' object has no attribute 'set_state_recursive'

`@window.event
def on_draw():
    window.clear()
    first.draw()


@window.event
def on_key_press(symbol, modifiers):
    if symbol == key.S:
        first.delete()`

**Comment by meLeetCrash** [comment]
But with text it's normal work

**Comment by benmoran56** [comment]
Can you post your full code? Use three back ticks to format it:

\`\`\`py

# code here

\`\`\`
