### ISSUE TITLE
Problems with IncrementalTextLayout

### ISSUE THREAD

**Issue by eschan145** [pyglet/pyglet#593]
When I run the example of the multiple text fields, it displays like this:

![image](https://user-images.githubusercontent.com/103769713/163658628-71c21e52-c49f-413b-ae12-ed176744437f.png)

The text is cut halfway in the first two fields. This probably has something to do with the font scaling/sizing. The third field has focus, and the text is displayed completely. With [caffeinepills](https://github.com/caffeinepills) pull request, the selection background color works along with the caret, but it is offset by several pixels. Additionally, the caret doesn't show up on the line start if the document's text is none.

![image](https://user-images.githubusercontent.com/103769713/163728715-3e08d5b8-bb21-4690-8cc8-f693b9412d53.png)

Another enhancement that could be added is keyboard shortcuts, like Control-A to select all of the text, Control-V to paste, Control-X to cut, Control-C to copy...

Also, underlining doesn't work with text styling. Using it gives me an `AssertionError: self.starts`.

I am using a Windows 11 on Python 3.10.

**Comment by shenjackyuanjie** [comment]
oh， it's a font size bug

**Comment by caffeinepills** [comment]
Thanks for looking into the fixes, I am working on some other changes for the font renderer as well.

**Comment by caffeinepills** [comment]
I have updated my pull request, try it now. Thanks

**Comment by eschan145** [comment]
If the `IncrementalTextLayout` is empty at first (no default text), the caret will not show up until you type something.

**Comment by benmoran56** [comment]
This should be working now in the latest releases. If you are still having issues, please let us know!
