### ISSUE TITLE
ApplePersistanceIgnoreState warning on Mac OS X

### ISSUE THREAD

**Issue by olehermanse** [pyglet/pyglet#6]
On a fresh install, Python gives a warning in pyglet examples. It doesn't seem to do anything, and [it can be disabled manually](https://stackoverflow.com/questions/18733965/annoying-message-when-opening-windows-from-python-on-os-x-10-8), but would be nice to fix it in the pyglet cocoa code.

**Pyglet version(s):** 1.4.1, 1.3.0

**Related tickets:** [bitbucket #85](https://bitbucket.org/pyglet/pyglet/issues/85/applepersistenceignorestate-existing-state)

**Minimal example:**

```python3
import pyglet
pyglet.window.Window(resizable=True)
pyglet.app.run()
```

**Output:**

```
$ python3 example.py 
2019-07-16 12:58:19.495 Python[74583:2564767] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)
```

**Comment by benmoran56** [comment]
This is an older version of #182. The likely cause seems to be related to leftover cruft. 
Ignoring, and un-ignoring should do the trick: 
```sh
defaults write org.python.python ApplePersistenceIgnoreState NO
defaults delete org.python.python ApplePersistenceIgnoreState
```
