### ISSUE TITLE
Sprite position requires 3 coordinates

### ISSUE THREAD

**Issue by PawekPL** [pyglet/pyglet#605]
Sprite position requires 3 coordinates, but the widgets only give them 2 when updating the position.

sprite.py
```
@position.setter
    def position(self, position):
        self._x, self._y, self._z = position
        self._vertex_list.translate[:] = position * 4
```

widgets.py | PushButton
```
def _update_position(self):
    self._sprite.position = self._x, self._y
```
![image](https://user-images.githubusercontent.com/44177078/166520114-794dddcb-7fce-4e92-a17c-a7a7a1ab4dfb.png)

**Comment by caffeinepills** [comment]
Thanks, missed the GUI widget for the Sprite update. Should be in master now.
