### ISSUE TITLE
Python crash in 1.4.4 when use also pywin32

### ISSUE THREAD

**Issue by adigrabcad** [pyglet/pyglet#61]
I've tried on clean machine. Install `pip install pywin32==224` and `pip install pyglet==1.4.4`
Then start python in PowerShell and run:
```
import win32ui
from pyglet.gl import gl_info

print "OpenGL Version:",gl_info.get_version()
```
Then press CTRL+C to exit Python ... Python crash.
![image](https://user-images.githubusercontent.com/15086504/65330122-d45bef80-dbb1-11e9-81eb-3f5fc17918f3.png)

Please make sure you have Windows Error Reporting ON. You can enable it via registry editor, as described [here.](https://superuser.com/a/1349113/366315)

More details in another run:
```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\lib\logging\__init__.py", line 1684, in shutdown
    h.release()
  File "C:\Python27\lib\logging\__init__.py", line 722, in release
    self.lock.release()
  File "C:\Python27\lib\threading.py", line 204, in release
    raise RuntimeError("cannot release un-acquired lock")
RuntimeError: cannot release un-acquired lock
```

**Comment by benmoran56** [comment]
Hello, I have replicated this, but I cannot find any pyglet specific errors.

It also seems to only affect Python 2.7.  Is it possible to switch to Python 3 for your project?

**Comment by zipandrar** [comment]
many pyglet function can't work in thread...but work in main thread...... ...

**Comment by adigrabcad** [comment]
@benmoran56 thank you for looking into it. We will probably switch to Python 3 in few months.
Looks like `pywin32` has [similar issue](https://github.com/mhammond/pywin32/issues/1347) with other modules, not only with `pyglet`.

**Comment by benmoran56** [comment]
No problem! Sorry I couldn't really help, but upgrading to Python 3 is a good idea in any case. I'll close this for now, but please feel free to reopen it if you want to add anything. 

One last thing - in case you haven't tried it,  how about the `pywin32-ctypes` module?  It does not contain all of the functionality of `pywin32`, but in my experience it works well.  Maybe there is a chance it does not trigger the same issue.
