### ISSUE TITLE
tablet.py example - weird prints

### ISSUE THREAD

**Issue by ZvikaZ** [pyglet/pyglet#610]
Hi.
I've run https://github.com/pyglet/pyglet/blob/master/examples/input/tablet.py and it's working fine with my Wacom Intuos - beside one weird thing - after every pen event there was printed a number between 0 and 5. It took my sometime to realize that it's a binary code:
- 1: pen touched the tablet
- 2: button 1 pressed
- 4: button 2 pressed
- (I cannot press the two buttons concurrently, thus my maximum result is 1+4)

That's very nice - but how can I disable it?
Or maybe, get it as some variable and decide what to do with it.
I have even removed all `print`s from code, but this is still printed.

**Comment by ZvikaZ** [comment]
I found where this print came from:
[pyglet\input\wintab.py, ](https://github.com/pyglet/pyglet/blob/ab83a0e6f1449650a9ff3d21b1da9b9197abdb11/pyglet/input/wintab.py#L191)

I assume it's some sort of debugging leftover, and can be safely removed.

**Comment by caffeinepills** [comment]
Thanks for the PR! Should be merged in now.
