### ISSUE TITLE
[Feature Request] Vulkan support

### ISSUE THREAD

**Issue by neozhaoliang** [pyglet/pyglet#613]
> Related discussion #267 

Hi, thanks the pyglet team for developing such a beautiful gui framework. I have been using pygelt for more than five years, and pyglet is always my first option when designing interactive animations.

I'm a member of the [taichi develop group](https://github.com/taichi-dev/taichi/). The taichi group maintains the taichi programming language for parallel computing in Python, it's mainly target for computer graphics, physical simulations, and we use gui systems very often. We have developed a vulkan based gui system (it's called ggui in taichi, to distinguish it from another cpu based "gui"). You can see how it works here: https://github.com/taichi-dev/voxel-challenge

However, we have encountered numerous compatibility problems, and we found our event handlers not implemented as elegant as pyglet. Personally I hope that I can try migrate taichi's gui system to pyglet, in some future. So may I ask does pyglet has any plan supporting vulkan? Thanks!

**Comment by benmoran56** [comment]
Sorry for the slow reply. 
The focus at the moment is on pyglet 2.0, which is migrating the internals to modern OpenGL. 
The next step after that will be further cleanup and refactoring. 

When this work is completed, it will become easier to explore a Vulkan backend. 
There is currently no timeline for this. I think after 2.1 is released, we might start discussing it as an option.

**Comment by neozhaoliang** [comment]
Thanks! I'll joint that then.

**Comment by iperov** [comment]
> our event handlers not implemented as elegant as pyglet

elegant is not always mean efficient, correct and scalable

**Comment by iperov** [comment]
The disadvantage of vulkan is the need to compile the shader into SPIR-V code by an external utility which is a binary for each OS. Vulkan drivers cannot compile, unlike OpenGL. 
If you use an external utility to compile shaders, then all the beauty and elegance of pyglet, which is 100% pure python, is lost.
