### ISSUE TITLE
[Question] Embedding a Pyglet 3D window in a simply GUI

### ISSUE THREAD

**Issue by gadese** [pyglet/pyglet#625]
#### Detailed Description

I've looked through all the documentation I could find (including the Issues), but haven't seen anything regarding what I'm looking to do.

I currently have a Pyglet window showing a 3D scene and shapes (actually a mix of Pyglet and RatCave). I would like to build a GUI around this window, with buttons and sliders that would control, for example, the position and color of objects in my 3D scene. Something like this, but replacing the plot with my 3D scene:

![image](https://user-images.githubusercontent.com/42775066/171496729-9ffd145d-dabd-4307-8d1e-3be76d7b4ecd.png)

Should I  be using an external GUI package for this? I know PySimpleGUI does not support embedded Pyglet windows, but I'm unsure if another package might support them. Is this something I can do purely with pyglet? If so, how? Any example would be very appreciated.

Thanks,

**Comment by caffeinepills** [comment]
For simple GUI features you can look at some widget in examples/gui/widgets.py.

If you need something more advanced, maybe look into glooey: https://glooey.readthedocs.io/en/latest/

**Comment by einarf** [comment]
@gadese Moving between 2D and 3D is just about changing the projection matrix. You an draw your 3D first with perspective projection then switch to orthogonal projection and draw the gui after.

**Comment by gadese** [comment]
Is there any chance you could point me to an example doing this?

**Comment by jason-bowen-zheng** [comment]
[fogleman/Minecraft](https://github.com/fogleman/Minecraft) is a good example. The [set_2d](https://github.com/fogleman/Minecraft/blob/master/main.py#L776) and [set_3d](https://github.com/fogleman/Minecraft/blob/master/main.py#790) functions tell you how to change the projection matrix.

> Switching to PyOpenGL is not an option right now.

As you mentioned first, PySimpleGUI does not support embedded pyglet windows(or OpenGL context?). Did it means `I want to use OpenGL in a tk window but I don't know how to do it`?

And I gave you 2 choice about the external GUI packages.
> Embedding OpenGL context is also supported by `Qt` and other high-level GUI suit.

- - -

I also recommend using pure pyglet. Using `pyglet.gui` isn't a good idea. But use glooey to draw 2D widget is the best choice.

**Comment by gadese** [comment]
Thank you, the set_2d and set_3d worked fine.

I ended up running a PyQT GUI and the pyglet window separately, in different windows rather than embedded, because the GUI is more convenient that way. The GUI changes values that are then sent to the pyglet for updates.

For anyone interested, I had to run the pyglet window in a main thread and the QT GUI in a secondary thread using threading.thread.

**Comment by caffeinepills** [comment]
I've seen this asked before, so I created an example.

We don't really support it as it introduces issues outside our control, but it seems to work so far.

```py
import sys
import pyglet
#from PyQt5 import QtGui
#from PyQt5 import QtCore, QtWidgets
#from PyQt5.QtOpenGL import QGLWidget as OpenGLWidget
from PyQt6 import QtGui
from PyQt6 import QtCore, QtWidgets
from PyQt6.QtOpenGLWidgets import QOpenGLWidget as OpenGLWidget
from pyglet.gl import glClear, GL_COLOR_BUFFER_BIT, GL_DEPTH_BUFFER_BIT
import random


"""An example showing how to use pyglet in QT, utilizing the OGLWidget.

   Since this relies on the QT Window, any events called on Pyglet Window
   will NOT be called.
    
   This includes mouse, keyboard, tablet, and anything else relating to the Window
   itself. These must be handled by QT itself.
   
   This just allows user to create and use pyglet related things such as sprites, shapes,
   batches, clock scheduling, sound, etc.           
"""

class MainWidget(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super().__init__()
        self.setWindowTitle("Pyglet and QT Example")
        self.shapes = []

        width, height = 640, 480
        self.opengl = PygletWidget(width, height)
        self.sprite_button = QtWidgets.QPushButton('Create Rectangle', self)
        self.sprite_button.clicked.connect(self.create_sprite_click)

        self.clear_sprite_button = QtWidgets.QPushButton('Clear Shapes', self)
        self.clear_sprite_button.clicked.connect(self.clear_sprite_click)
        
        mainLayout = QtWidgets.QVBoxLayout()
        mainLayout.addWidget(self.opengl)
        mainLayout.addWidget(self.sprite_button)
        mainLayout.addWidget(self.clear_sprite_button)
        self.setLayout(mainLayout)

    def create_sprite_click(self):
        gl_width, gl_height = self.opengl.size().width(), self.opengl.size().height()
        
        width = random.randint(50, 100)
        height = random.randint(50, 100)
        
        x = random.randint(0, gl_width-width)
        y = random.randint(0, gl_height-height)
        color = (random.randint(0, 255), random.randint(0, 255), random.randint(0, 255))
        
        shape = pyglet.shapes.Rectangle(x, y, width, height, color=color, batch=self.opengl.batch)
        shape.opacity = random.randint(100, 255)
        self.shapes.append(shape)
        
    def clear_sprite_click(self):
        for shape in self.shapes:
            shape.delete()
            
        self.shapes.clear()


class PygletWidget(OpenGLWidget):
    def __init__(self, width, height, parent=None):
        super().__init__(parent)
        self.setMinimumSize(width, height)

        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self._pyglet_update)
        self.timer.setInterval(0)
        self.timer.start()

    def _pyglet_update(self):
        # Tick the pyglet clock, so scheduled events can work.
        pyglet.clock.tick()  
        
        # Force widget to update, otherwise paintGL will not be called.
        self.update()  # self.updateGL() for pyqt5

    def paintGL(self):
        """Pyglet equivalent of on_draw event for window"""
        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)
        
        self.batch.draw()

    def initializeGL(self):
        """Call anything that needs a context to be created."""
        self.batch = pyglet.graphics.Batch()
        size = self.size()
        w, h = size.width(), size.height()
        
        self.projection = pyglet.window.Projection2D()
        self.projection.set(w, h, w, h)


if __name__ == '__main__':    
    app = QtWidgets.QApplication(sys.argv)    
    window = QtWidgets.QMainWindow()
    ui = MainWidget(window)    
    ui.show()  # Calls initializeGL. Do not do any GL stuff before this is called.
    app.exec() # exec_ in 5.
```
