### ISSUE TITLE
Documentation is not up to date.

### ISSUE THREAD

**Issue by lostsq** [pyglet/pyglet#628]
Hello,

I was looking into finding a python library that could handle creating a replica of a program I've already created on windows in C#.

The pyglet library seemed to be the answer I was looking for. 

After spending some time testing out a few things I've found that some of the basic parts of the documentation are outdated and no longer work as expected. 

Due to this I've had to forgo using this library since the last thing I would want is to be into it hundreds of hours only to find that things don't work. I've been there and it's not a fun time. 

For a reference of something that is not working please refer to the  graphics doc. Below is a link.
https://pyglet.readthedocs.io/en/master/modules/graphics/index.html

The very first example :
~~
pyglet.graphics.draw(2, pyglet.gl.GL_POINTS,
    ('v2i', (10, 15, 30, 35))
)
~~
Throws back the message "Vertex attribute shorthand notation is deprecated: 'v2i'.  Please use the actual attribute names as defined in the Shader Program."

I am not an expert by any means which is why I was hoping that this library was up to date/working/ect. 

Not sure if I'll try again with this library or something else, but wanted to at least point out the issue so that someone with the knowledge could update the documentation to work. It's a bummer cause this does look like a cool library that could make things far more easy than trying to learn all the opengl stuff.

**Comment by benmoran56** [comment]
Hi, 

The master branch is currently tracking the upcoming 2.0 release. This is still under development, so the documentation has not been fully updated. 

The current stable release is 1.5.24. This is what you will get when you pip install pyglet. 
The latest release can also be found here: https://github.com/pyglet/pyglet/releases/tag/v1.5.24
The default documentation on ReadTheDocs is also for the latest stable release:
https://pyglet.readthedocs.io/en/latest/

**Comment by benmoran56** [comment]
No worries! 
What kind of project are you trying to build? 
pyglet 1.X series is based on OpenGL internally for all of the high level classes, whereas pyglet 2.0 is migrating to OpenGL 3.3+.
