### ISSUE TITLE
Suggestion in loading binaries from FFMpeg

### ISSUE THREAD

**Issue by pvcraven** [pyglet/pyglet#64]
This suggestion for a Pyglet change was made to Arcade:

https://github.com/pvcraven/arcade/issues/485

## Bug Report
This bug is specific to ARM Raspberry Pi 4 devices.

A fix is proposed in Enhancement request section.

When trying to import arcade for the first time after installation in Python 3, an IndexError is thrown when the script pyglet_ffmpeg2/loader.py calls the function `_ensure_linux_symlinks`

### Actual behavior:
`load.py` fails to create symlinks because the path defined in the `bin_folder` variable defined by the function `_locate_binaries` uses
~~~python
path = os.path.join(this_dir, 'linux_x86_64')
~~~
instead of:
~~~python
path = os.path.join(this_dir, 'RPi')
~~~

because `sys.platform` returns 'linux' instead of the expected 'armv7l' in the conditional block:
~~~python
if 'armv7l' in sys.platform:
    path = os.path.join(this_dir, 'RPi')
else:
    path = os.path.join(this_dir, 'linux_x86_64')
~~~
### Expected behavior:
`sys.platform`  should return 'armv7l' and symlinks can be created

### Steps to reproduce/example code:
 - Install Raspbian GNU/Linux 10 (buster) on Raspberry Pi 4
- Upgrade pip3
- Run `pip3 install arcade`
- Start python 3 and import arcade

### What should be added/changed?
In `/usr/local/lib/python3.7/dist-packages/pyglet_ffmpeg2/loader.py`, change the condition on line 50 from this:
~~~python
if 'armv7l' in sys.platform
~~~

to this:
~~~python
if 'armv7l' in sys.platform or 'armv7l' in os.uname()
~~~

### What would it help with?
`os.uname()` returns more comprehensive and useful info on the OS and hardware

In addition, the `os` module is already imported in the load.py file

**Comment by benmoran56** [comment]
Hi Paul, 

Isn't this package under the pythonarcade org?  https://github.com/pythonarcade/pyglet-ffmpeg/
I believe that Dan wrote this originally, but it seems to live there.
In that case I don't think it should be a problem to update :)

**Comment by pvcraven** [comment]
The suggested change was in the pyglet part? I haven't looked too closely.

**Comment by benmoran56** [comment]
Looks like it's in the `pyglet_ffmpeg` package:  https://github.com/pythonarcade/pyglet-ffmpeg/blob/master/pyglet_ffmpeg/loader.py#L50
It looks like a fairly simple fix, so I went ahead and did an online pull request with the Github editor.

**Comment by pvcraven** [comment]
Oh man, I goofed. Sorry to open this under the wrong project.
