### ISSUE TITLE
Bug: pyglet.font.add_file freezes tkinter.filedialog

### ISSUE THREAD

**Issue by klausmcm** [pyglet/pyglet#641]
I'm using the following on Windows 10

```
Python version: 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)]
tkinter version: 8.6.8
```

The following code demonstrates the issue I'm experiencing (font can be obtained from https://dejavu-fonts.github.io/Download.html but this issue should occur with any font file)

``` python
import pyglet
import tkinter.filedialog

# comment out to see a folder dialog box as excpected
pyglet.font.add_file(r"./DejaVuSans.ttf")

folder_name = tkinter.filedialog.askdirectory()  # show the 'get folder' dialog box
```

When running this code, the file dialog window never shows and the program is frozen. Without the call to `add_file`, the file dialog window shows up.

This issue does not appear on Debian (10).

My debugging took me to https://github.com/pyglet/pyglet/blob/v1.5.26/pyglet/font/__init__.py#L61=. On Windows 10, the conditions lead to this `_font_class = GDIPlusFont` and on linux, the conditions lead to this `_font_class = FreeTypeFont`. I don't understand how tkinter is affected by pyglet and maybe I'm looking for the problem in the wrong place in the code.

I'm looking for a solution to this issue. Thank you.

**Comment by caffeinepills** [comment]
Not really a bug. tkinter initializes a different thread mode for COM's than what's required for different areas of our library, which has potential to cause locks.

You can try modifying these lines (in 1.5):
https://github.com/pyglet/pyglet/blob/v1.5.26/pyglet/image/codecs/wic.py#L404
https://github.com/pyglet/pyglet/blob/v1.5.26/pyglet/media/codecs/wmf.py#L836

to `ole32.CoInitializeEx(None, COINIT_APARTMENTTHREADED)` instead.

However, we can't guarantee other COM using pieces of pyglet will work with that changed.

**Comment by klausmcm** [comment]
> Not really a bug

But not really a feature or expected behavior either?

Thank you for identifying the problem and offering a solution.

**Comment by caffeinepills** [comment]
By not really a bug, I mean, it's a setting of another library outside of pyglet's control. From our perspective, the COM mode is set in accordance to what is in Microsofts examples. I would say another library setting a different mode is not something we should expect.

Honestly it may work just fine changing it to apartment mode, I don't know. Keeping to recommended behavior minimizes unexpected behavior when implementing these things.

I'd be fine with changing it, if someone can give a detailed explanation on why and can demonstrate that it doesn't affect the performance or behavior of WIC, WMF, and XInput.

**Comment by klausmcm** [comment]
Gotcha, would love to use this library if something dealing with this issue was released. Otherwise, is there a way I can change the parameter to `COINIT_APARTMENTTHREADED` without having to go into pyglets source code?

**Comment by caffeinepills** [comment]
One quick fix you could do is overwriting the variable itself. 

```py
from pyglet.libs.win32 import constants
constants.COINIT_MULTITHREADED = 0x2
```
Do this at the very top of your script.

**Comment by benmoran56** [comment]
Are you only using tkinter for the file dialogs? If so, have a look at [`examples/file_dialog.py` ](https://github.com/pyglet/pyglet/blob/pyglet-1.5-maintenance/examples/file_dialog.py).
This launches the dialogs in another process, and uses the pyglet EventDispatcher framework to avoid blocking.

**Comment by klausmcm** [comment]
No, I'm trying to include a specific font with my PySimpleGUI application. The suggested approach I have found so far is to use pyglet (https://stackoverflow.com/questions/11993290/truly-custom-font-in-tkinter/30631309#30631309) but turns out that freezes the program when using the folder browse buttons that call the tkinter dialog functions.

I'll give this a try

``` python
from pyglet.libs.win32 import constants
constants.COINIT_MULTITHREADED = 0x2  # 0x2 = COINIT_APARTMENTTHREADED
```

**Comment by klausmcm** [comment]
> One quick fix you could do is overwriting the variable itself.
> 
> ```python
> from pyglet.libs.win32 import constants
> constants.COINIT_MULTITHREADED = 0x2  # 0x2 = COINIT_APARTMENTTHREADED
> ```
> 
> Do this at the very top of your script.

Perfect, this works. I'll use this for now. Thank you!
