### ISSUE TITLE
Text Input Example not working as expected input

### ISSUE THREAD

**Issue by utsekaj42** [pyglet/pyglet#644]
I am trying to use the text input example, but it doesn't seem to let me edit the text.
<https://github.com/pyglet/pyglet/blob/master/examples/text/text_input.py>

I have tried the example from both master and the 1.5 maintenance branch. Both scripts run and display a window with text and input rectangles as expected, but clicking on the text entry fields doesn't seem to do anything and the text is only shown in the terminal from which I run the script. The text in the window remains unchanged.

I am running on Fedora 35 with Wayland and have the following Python and Pyglet installed. 
```
python                    3.10.5          h582c2e5_0_cpython    conda-forge
pyglet                    1.5.16          py310hff52083_1    conda-forge
```

**Comment by benmoran56** [comment]
This should be working now.
Please try it with the latest release. If you are still having issue, let us know. 
Thanks!
