### ISSUE TITLE
More Options for Shapes

### ISSUE THREAD

**Issue by eschan145** [pyglet/pyglet#647]
We could add more options and parameters for `pyglet.shapes`. For example, a user could specify a radius for a rectangle, a triangle, a polygon, etc. Gradients for shapes could also be added, as well as effects, like shadows, glow, etc.

**Comment by einarf** [comment]
I'm guessing this comes from someone who have used arcade shapes. These will be deprecated in favor of pyglet shapes in the future. Before that happens we'll probably try to contibute to pyglet shapes getting it closer to the old arcade shapes.

However.. I don't think the default shapes should provide anything too fancy. Instead the default shapes can be subclassed and modified to your needs. We fell into this trap in arcade and got way too much code to maintain. Shapes should ideally be a mimimal set that can be extended.
