### ISSUE TITLE
Optimize shapes by moving rotation into a shader

### ISSUE THREAD

**Issue by pushfoo** [pyglet/pyglet#648]
This is a follow-up to discord discussion with Ben. He [mentioned that shapes could be sped up by moving rotation from python into a shader](https://discord.com/channels/438622377094414346/477394331112701952/995663585562861589) with this follow-up:
> No worries, it's easy enough to do later for a quick speedup when rotating.
Shapes in general should perform well when batched, but the rotation code could get heavy for something like a star or something with a lot of vertices.
I'm any case, v2.0 is a chance to change things, so now's the time to work on the shapes module 😄

**Comment by benmoran56** [comment]
This has already been implemented in 2.0.
