### ISSUE TITLE
Windows Graphic Device Interface (GDI) Memory Leak when saving images

### ISSUE THREAD

**Issue by justinsavage35** [pyglet/pyglet#655]
Hi all,

I have found an issue when saving multiple pngs on Windows, see [link to trimesh issue](https://github.com/mikedh/trimesh/issues/1550#issue-1192707314).

I believe this issue occurs because both the window classes are not being unregistered,  freeing the memory required for the classes when the window is being closed, see below.

https://github.com/pyglet/pyglet/blob/6da6a9689144ceacf7be295e740bce096eebe3be/pyglet/window/win32/__init__.py#L318-L334

I have solved this by unregistering the “_view_window_class” using “_user32.UnregisterClassW(self._view_window_class.lpszClassName, 0)” below line 324.

On testing to create 15,000 pngs, I have noticed that the Device Contexts (DC) are not being released when the window is closed, see images below.

![GDI_count_4373_blank](https://user-images.githubusercontent.com/47403576/180455857-875c2eb0-f2dd-49d0-abc7-36bf0d8bb940.png)

![GDI_count_7038_blank](https://user-images.githubusercontent.com/47403576/180455671-09953867-8444-46fa-b2c4-814fa8e43066.png)

![GDI_count_10000_blank](https://user-images.githubusercontent.com/47403576/180455576-f5ffc8e7-1967-4c63-89d5-b836f8cef4af.png)

This was found using GDIView.exe (https://www.nirsoft.net/utils/gdi_handles.html).  Once the number of Graphics Device Interface (GDI) reaches 10,000 the test fails since the maximum number of GDI per process is 10,000 (https://devblogs.microsoft.com/oldnewthing/20070718-00/?p=25963 ). The error is  "Unable to share contexts." from line 237, see below.

https://github.com/pyglet/pyglet/blob/6da6a9689144ceacf7be295e740bce096eebe3be/pyglet/gl/win32.py#L220-L260 

From my understanding, the DCs should be cleaned by “ _user32.DestroyWindow” and “_user32.UnregisterClassW” (https://community.khronos.org/t/releasedc/24517/16) however this does not seem to be the case.

Please let me know if you need anymore information.

Thank you in advance,

Justin

**Comment by caffeinepills** [comment]
Can you give more information on this? What version of python, windows, pyglet, etc.

**Comment by justinsavage35** [comment]
Hi [caffeinepills](https://github.com/caffeinepills),

Sorry for the delayed response.

Windows: Windows 10
Python: Python 3.7.9
Pyglet: 1.5.26
Trimesh: 3.12.8

Here is the requirement.txt for all the other libraries, see attached.
[requirements.txt](https://github.com/pyglet/pyglet/files/9181191/requirements.txt)

Here is the python script for running creating 15000 pngs, see attached. The script requires an obj file. “python pyglet_test.py test.obj”

[pyglet_test.zip](https://github.com/pyglet/pyglet/files/9181214/pyglet_test.zip)

**Comment by caffeinepills** [comment]
I was able to reproduce this. I was wondering how saving images are creating additional DC's, but looks like it's constantly creating windows and destroying them. 

Unfortunately even adding `_user32.UnregisterClassW(self._view_window_class.lpszClassName, 0)` did not stop them from permanently growing on my setup. I will look into this a little further.

**Comment by justinsavage35** [comment]
Hi [caffeinepills](https://github.com/caffeinepills),

Thank you for getting back to me and confirming this issue.

Apologies for the confusion, the addition of “_user32.UnregisterClassW(self._view_window_class.lpszClassName, 0)” was to solve the “ZeroDivisionError: float division by zero” error.

On my setup after around 50-100 pngs this error appears, see below.

“””

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "\pypoetry\Cache\virtualenvs\png-test-H5r-B9Au-py3.7\lib\site-packages\pyglet\window\win32\__init__.py", line 775, in f
    result = event_handler(msg, wParam, lParam)
  File "\pypoetry\Cache\virtualenvs\png-test-H5r-B9Au-py3.7\lib\site-packages\pyglet\window\win32\__init__.py", line 1128, in _event_size
    self.dispatch_event('on_resize', self._width, self._height)
  File "\pypoetry\Cache\virtualenvs\png-test-H5r-B9Au-py3.7\lib\site-packages\pyglet\window\__init__.py", line 1352, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "\pypoetry\Cache\virtualenvs\png-test-H5r-B9Au-py3.7\lib\site-packages\pyglet\event.py", line 415, in dispatch_event
    if getattr(self, event_type)(*args):
  File "\pypoetry\Cache\virtualenvs\png-test-H5r-B9Au-py3.7\lib\site-packages\trimesh\viewer\windowed.py", line 610, in on_resize
    width, height = self._update_perspective(width, height)
  File "\pypoetry\Cache\virtualenvs\png-test-H5r-B9Au-py3.7\lib\site-packages\trimesh\viewer\windowed.py", line 599, in _update_perspective
    width / float(height),
ZeroDivisionError: float division by zero

“””

After around 800-900 pngs python crashes.

With the “_user32.UnregisterClassW(self._view_window_class.lpszClassName, 0)” I am able to get to 9700-9800 pngs and this is where the number of Graphics Device Interface (GDI) reaches 10,000 and fails since the maximum number of GDI per process is 10,000.

Unfortunately, I have no solution for the increasing number of DCs and the number of DCs with and without this change is the same.

**Comment by caffeinepills** [comment]
Ok that makes more sense, it makes sense unregistering things we register. I will add some more cleanups on Window close in the future.

After looking further into this I think I may have found a lingering DC that grows without being destroyed. This seems to solve it for me.

Can you verify this for me:

Change these lines
https://github.com/pyglet/pyglet/blob/e032638935f12bc01b6f04361bf429b599ffe5a6/pyglet/canvas/win32.py#L67-L73

to:
```py
    def get_matching_configs(self, template):
        hdc = _user32.GetDC(None)
        canvas = Win32Canvas(self.display, 0, hdc)
        configs = template.match(canvas)
        # XXX deprecate config's being screen-specific
        for config in configs:
            config.screen = self
        user32.ReleaseDC(None, hdc)
        return configs
```
And let me know if that resolved it.

**Comment by justinsavage35** [comment]
Hi [caffeinepills](https://github.com/caffeinepills),

Thank you very much for the fix. I can confirm it is working on my setup.

I shall now close the issue. Thanks.
