### ISSUE TITLE
How to use pyglet with asyncio

### ISSUE THREAD

**Issue by BlockOG** [pyglet/pyglet#656]
Specifically, how to use it with websockets

**Comment by benmoran56** [comment]
Hi,
pyglet is not an asyncio library, and contains it's own event loop. The two are not directly compatible. That said, it's possible to integrate with asyncio code using threads and events, but it's not something we support.

You might want to try a Sans-IO style library. Maybe this would work for you (I haven't tried it myself) https://github.com/python-hyper/wsproto

**Comment by benmoran56** [comment]
Closing due to lack of response, but please reopen the ticket if you still have questions.
