### ISSUE TITLE
Controller mapping crashes for iBuffalo SNES controller on Windows

### ISSUE THREAD

**Issue by bunny-therapist** [pyglet/pyglet#657]
After updating the pyglet version of my game to 2.0.dev18, I can no longer use my iBuffalo SNES controller in my game on Windows.

The reason is that pyglet.input.controller.get_mapping crashes with with a tuple unpacking error. It splits on ":", and expects two elements after the split, but instead it gets three.

I locally edited controller_db.py, lines 766-767 (where I found my controller guid) from:
```
"03000000830500006020000000000000,iBuffalo SNES Controller,a:b0,b:b1,back:b6,dpdown:+a1,dpleft:-a0,dpright:+a0,dpup:-a1,leftshoulder:b4,rightshoulder:b5,start:b7,x:b2,y:b3,hint:SDL_GAMECONTROLLER_USE_BUTTON_LABELS:=1,",
"03000000830500006020000000000000,iBuffalo SNES Controller,a:b1,b:b0,back:b6,dpdown:+a1,dpleft:-a0,dpright:+a0,dpup:-a1,leftshoulder:b4,rightshoulder:b5,start:b7,x:b3,y:b2,hint:!SDL_GAMECONTROLLER_USE_BUTTON_LABELS:=1,",
```
to
```
"03000000830500006020000000000000,iBuffalo SNES Controller,a:b0,b:b1,back:b6,dpdown:+a1,dpleft:-a0,dpright:+a0,dpup:-a1,leftshoulder:b4,rightshoulder:b5,start:b7,x:b2,y:b3,",
"03000000830500006020000000000000,iBuffalo SNES Controller,a:b1,b:b0,back:b6,dpdown:+a1,dpleft:-a0,dpright:+a0,dpup:-a1,leftshoulder:b4,rightshoulder:b5,start:b7,x:b3,y:b2,",
```
i.e., I removed the "hint" part at the end, which contains three colons. This change solved the issue for me.

I am not sure what the purpose of the "hint" part is, but it does not work with the get_mapping function.

**Comment by benmoran56** [comment]
Thanks for opening the ticket. It looks like that hint field is relatively recent, so we'll have to update the parser code. We don't want it to crash in any case, so I'll add some handling for that as well.

**Comment by benmoran56** [comment]
This is fixed in master, and will be in the next dev release.

**Comment by benmoran56** [comment]
Closing because this is in the latest dev release. 
Also, I added a unit test that parses all of the internal mappings, to prevent this type of issue in the future. 
Thanks!
