### ISSUE TITLE
Library loader for mac doesn't always work

### ISSUE THREAD

**Issue by pvcraven** [pyglet/pyglet#66]
MachOLibraryLoader.find_library in lib.py has the following line:
`if '.' not in libname:`
Loading of ffmpeg library right now involves passing 'avbin' and 'avbin.56' to the load library function, which calls this find_library. If the `avbin.56` is passed, we don't properly search for 'libavbin.56.dylib'.

I think the line needs to be:
`if '.dylib' not in libname:`

**Comment by benmoran56** [comment]
Hi Paul, 
I had a look at the code, and I think your fix should be fine. The intention is just to catch "name.dynlib" files, but the original check did not account for names like "avbin.56".

**Comment by benmoran56** [comment]
Thanks Paul, I merged in your PR.
