### ISSUE TITLE
Add support for mocking GL Contexts

### ISSUE THREAD

**Issue by pushfoo** [pyglet/pyglet#665]
During discord discussion of #660 , Ben initially suggested moving the included tests to integration rather than the unit folder. However, these tests do not use the GL functionality directly, and only need a valid-seeming context to instantiate the shapes.

We agreed that having a way to mock the GL context would be helpful to keep these tests pure, possibly using monkey patching.

**Comment by benmoran56** [comment]
Fixed in master, so closing.
