### ISSUE TITLE
Enhancement: Add support for setting a Vec's contents from another Vec

### ISSUE THREAD

**Issue by pushfoo** [pyglet/pyglet#679]
This doesn't have to optimize for execution speed if the doc explains that it's a tool for brevity and flexibility.

For example, implementing `__setitem__` should allow users to do any of the following:
```py
# set a mutable vector to the value of another or even an iterable
current_position[:] = SPAWN_POINT

# use 2d position vectors to set initial 3d positions before adding elevation
destination = Vec3()
destination[:2] = vec2_instance
```
This is more concise than setting the coordinates manually.

Would this cause any problems if implemented? I can add it if there are no problems apparent with the idea.

**Comment by benmoran56** [comment]
A naive implementation might look something like this: 
```py
    def __setitem__(self, key, value):
        if type(key) is slice:
            for i, attr in enumerate(['x', 'y', 'z', 'w'][key]):
                setattr(self, attr, value[i])
        else:
            setattr(self, ['x', 'y', 'z', 'w'][key], value)
```

**Comment by benmoran56** [comment]
I just went ahead and implemented the solution above. It doesn't cause any performance impact _unless_ you use it, and we can always change it later if a better solution is found. If you know of a faster way to do it, please feel free to have a crack at it.
