### ISSUE TITLE
add on_activate event to KeyStateHandler

### ISSUE THREAD

**Issue by csd4ni3l** [pyglet/pyglet#681]
Please add on_activate event to KeyStateHandler, with reset to data dict(setting the data dict to a new empty one), because when you leave the window and you holded down a key then when you release it its still holded down, and the only way to stop it is to press the key once

**Comment by LennyPhoenix** [comment]
Thoughts on just adding `on_deactivate` to the mouse and key handlers?

```py
    def on_deactivate(self):
        self.clear()
```

**Comment by csd4ni3l** [comment]
okay

**Comment by LennyPhoenix** [comment]
> Thoughts on just adding `on_deactivate` to the mouse and key handlers?
> 
> ```py
>     def on_deactivate(self):
>         self.clear()
> ```

To elaborate on this, I don't think `on_activate` should be used in this situation, as any key releases while the window is unfocused are lost. If we attempt to retrigger keys when the window is focused this just leads to similar problems of keys getting stuck. (E.g. if the user presses a key, unfocused the window, and then released the key before refocusing)

**Comment by csd4ni3l** [comment]
using on_deactivate is better

**Comment by csd4ni3l** [comment]
ok you are right

**Comment by csd4ni3l** [comment]
should i close this?

**Comment by benmoran56** [comment]
Thanks for reminding, I'll close it on my end.

**Comment by matanster** [comment]
Actually I have a similar case where the key release event will only be dispatched once the same key is pressed again, rather than immediately after my key press handler has completed. (pyglet 2.0.5). Does that make any sense? 

I'll try to make a minimal reproducible example reproducing this behavior.

**Comment by matanster** [comment]
Submitted possibly related (but possibly not) https://github.com/pyglet/pyglet/issues/911
