### ISSUE TITLE
Broken link to Observer Design Pattern in events page of Programming Guide

### ISSUE THREAD

**Issue by pushfoo** [pyglet/pyglet#683]
## Branches affected:
* [1.5.X](https://pyglet.readthedocs.io/en/latest/programming_guide/events.html#implementing-the-observer-pattern)
* [2.0.0](https://pyglet.readthedocs.io/en/master/programming_guide/events.html#implementing-the-observer-pattern)

## What's wrong
The "Observer design pattern" link at [the opening of the "Implementing the Observer pattern" section](https://github.com/pyglet/pyglet/blob/master/doc/programming_guide/events.rst#implementing-the-observer-pattern) appears to be an attempt at a book citation, but is being handled as a link:

The book cited seems to be the 1994 1st edition of *Design Patterns: Elements of Reusable Object-Oriented Software* by Gamma Erich, et al.
ISBN-10 : 0201633612
ISBN-13: 978-0201633610

### 1. Link a web page instead of the book
I'm not sure what the best one would be. This is probably the easiest option.

### 2. Pull in a citation management plugin for doc builds
We might have had one of these in the past. The previous relevant commits in this file are from 2019 and 2008.

**Comment by benmoran56** [comment]
Thanks for opening the ticket.
Since this is rarely used in the documentation, I would prefer just linking a web page to adding Sphinx dependencies.
Perhaps a wiki article, or this one:
https://gameprogrammingpatterns.com/observer.html

**Comment by benmoran56** [comment]
I removed this for now in the master branch.
