### ISSUE TITLE
Can pyglet call glutWireSphere?

### ISSUE THREAD

**Issue by qichikimochi** [pyglet/pyglet#686]
Can pyglet call glutWireSphere?

**Comment by benmoran56** [comment]
pyglet does not include the GLUT library bindings, so it's not possible without an external GLUT module.
You can however make your own shapes, as illustrated in these examples: 
1.5 branch:
https://github.com/pyglet/pyglet/blob/pyglet-1.5-maintenance/examples/opengl/opengl.py
2.0 branch:
https://github.com/pyglet/pyglet/blob/master/examples/opengl/opengl.py

**Comment by qichikimochi** [comment]
Thanks for your return. The program of torus have error.


 
From: Benjamin
Date: 2022-09-22 14:25
To: pyglet/pyglet
CC: qichikimochi; Author
Subject: Re: [pyglet/pyglet] Can pyglet call glutWireSphere? (Issue #686)
pyglet does not include the GLUT library bindings, so it's not possible without an external GLUT module.
You can however make your own shapes, as illustrated in these examples:
1.5 branch:
https://github.com/pyglet/pyglet/blob/pyglet-1.5-maintenance/examples/opengl/opengl.py
2.0 branch:
https://github.com/pyglet/pyglet/blob/master/examples/opengl/opengl.py

**Comment by benmoran56** [comment]
Which error? Make sure you have the right pyglet branch.

**Comment by qichikimochi** [comment]
1.
line 152, in <module>
    setup()
line 89, in setup
    on_resize(*window.size)
       
2.when use "on_resize(*window.get_size())" replace "on_resize(*window.size)" 

line 70, in on_resize
    window.projection = Mat4.perspective_projection(width/height, z_near=0.1, z_far=255, fov=60)
TypeError: perspective_projection() missing 3 required positional arguments: 'right', 'bottom', and 'top'




 
From: Benjamin
Date: 2022-09-22 16:28
To: pyglet/pyglet
CC: qichikimochi; Author
Subject: Re: [pyglet/pyglet] Can pyglet call glutWireSphere? (Issue #686)
Which error? Make sure you have the right pyglet branch.

**Comment by benmoran56** [comment]
Make sure you're using the latest 2.0.dev23 release if you're using the examples from the master branch.

**Comment by qichikimochi** [comment]
i am using pyglet 1.5.26. where can i get the latest 2.0.dev23?

       




 
From: Benjamin
Date: 2022-09-22 17:08
To: pyglet/pyglet
CC: qichikimochi; Author
Subject: Re: [pyglet/pyglet] Can pyglet call glutWireSphere? (Issue #686)
Make sure you're using the latest 2.0.dev23 release if you're using the examples from the master branch.

**Comment by qichikimochi** [comment]
Thanks

       




 
From: Benjamin
Date: 2022-09-22 17:08
To: pyglet/pyglet
CC: qichikimochi; Author
Subject: Re: [pyglet/pyglet] Can pyglet call glutWireSphere? (Issue #686)
Make sure you're using the latest 2.0.dev23 release if you're using the examples from the master branch.
