### ISSUE TITLE
Vec2 x, y are floats

### ISSUE THREAD

**Issue by janscas** [pyglet/pyglet#689]
I see that the new implementation of Vec2 explicitly sets x, y as floats.

But sometimes that's not the case.

¿What's the rationale behind this change?
¿Can Vec2 type definition be ints or floats at least?

**Comment by benmoran56** [comment]
Hi, 

Using `int` is still fine. The typing annotation is just to avoid clutter. 
According to PEP484 on type hinting, "when an argument is annotated as having type float, an argument of type int is acceptable".
https://peps.python.org/pep-0484/#the-numeric-tower

Alternatively we could do something like `Union[float, int]`, or I think `numbers.Real`, but I'm not sure if that's really clearer. 
Are you having an issue with some code inspector?

**Comment by janscas** [comment]
Yes, pycharm complains sometimes

**Comment by janscas** [comment]
Check this:

`for x in range(vector.x - spotting, vector.x + (spotting + 1))`

Pycharm says: "Expected type 'SupportsIndex', got 'float' instead"

**Comment by TomFryers** [comment]
`Union[float, int]` and `numbers.Real` wouldn't help. `Vec2` would have to take a type parameter (`int` or `float`), which is a bit of a pain (I've done it for hexagonal vectors [here](https://gitlab.com/Tom_Fryers/hexagonal/-/blob/master/hexagonal/__init__.py)).

**Comment by benmoran56** [comment]
`numbers.Real` indeed didn't work. However, `number = Union[float, int]` does seem to appease mypy and Pycharm.

**Comment by TomFryers** [comment]
Are you using a different version of Mypy? [I get `No overload variant of "range" matches argument type "float"`](https://mypy-play.net/?mypy=latest&python=3.10&gist=29d67d9b2466760398086d68fb9fb86a).

**Comment by benmoran56** [comment]
```sh
$ python --version
Python 3.10.7

$ mypy --version
mypy 0.971 (compiled: no)
```
With the current code on Github: 
I get some invalid noise because mypy confuses `-m math` with the built-in math module, but other than that I'm only seeing errors related to overriding the `__new__` and `__add__` methods of the tuple subclasses.

**Comment by janscas** [comment]
I don’t know about mypy but pycharm complains anyway. I think Union[float, int] will fix that and not harm anybody.

**Comment by janscas** [comment]
@benmoran56 that change effectively removes any complain in pycharm

**Comment by benmoran56** [comment]
It seems to placate PyCharm for me as well. I'm curious about what difference is causing Tom's mypy message, but I think the most important thing is to keep IDE code inspection happy. Perhaps this issue can be closed now?

Since typing in Python is still evolving, and the associated tools as well, we can of course revisit these things in the future.
After dropping EOL Python releases, we can finally take advantage of the newer syntax.

**Comment by janscas** [comment]
Great for me thanks
