### ISSUE TITLE
Proposal: add support for .dds files which has not power-of-two sides.

### ISSUE THREAD

**Issue by Yuriy-Leonov** [pyglet/pyglet#69]
I've create example which describes issue with example [in this repository](https://github.com/Yuriy-Leonov/pyglet_dds_power_of_two)
There are several files in `.dds` extension. (31_21.dds, 32_32.dds, 40_20.dds)

These files cound be opened in GIMP as well. 
Mipmap exists only in `32_32.dds` (but I don't think it's an issue).
`31_21.dds` and `40_20.dds` don't containt mipmaps.

Back to current issue:
If try to load `31_21.dds` or `40_20.dds` with pyglet (version 1.4.4) (example: [manage_files/pyglet_load_files.py](https://github.com/Yuriy-Leonov/pyglet_dds_power_of_two/blob/master/manage_files/pyglet_load_files.py)) following exception is raised:

```
Traceback (most recent call last):
  File "pyglet_load_files.py", line 9, in try_to_load_file
    pyglet.image.load(path)
  File "<path>/v_pyglet/lib/python3.6/site-packages/pyglet/image/__init__.py", line 198, in load
    image = decoder.decode(file, filename)
  File "<path>/v_pyglet/lib/python3.6/site-packages/pyglet/image/codecs/dds.py", line 223, in decode
    'GL_EXT_texture_compression_s3tc', decoder)
  File "<path>/v_pyglet/lib/python3.6/site-packages/pyglet/image/__init__.py", line 1234, in __init__
    raise ImageException('Dimensions of %r must be powers of 2' % self)
  File "<path>/v_pyglet/lib/python3.6/site-packages/pyglet/image/__init__.py", line 399, in __repr__
    return '<%s %dx%d>' % (self.__class__.__name__, self.width, self.height)
AttributeError: 'CompressedImageData' object has no attribute 'width'
```

Based on [wiki](https://en.wikipedia.org/wiki/S3_Texture_Compression)
```
license fees have been levied and collected for the use of S3TC technology until October 2017
```
Such format of files could be used free.

PS: This topic was created based on conversation in discord.

**Comment by benmoran56** [comment]
Hi Yuriy, 

Thank you very much for the detailed issue! It turns out, that the fix was quite simple. All that needed to be done was to remove the check to force power-of-two. After that the images appear to load correctly.  You can see the change here: https://github.com/pyglet/pyglet/commit/8be0b7cb664a9fb709df4aec2ce726e22f7198ff#diff-08c2139d2672193f631d98733ab9f206L1233-L1235

This is now in master, and will be in a point release in the near future. Could you let me know if it works for you?

**Comment by Yuriy-Leonov** [comment]
Hi Benjamin.

Looks like it works(based on provided case)! :) I'll test it in more detail with my game, when it will be added to nearest release.

BTW: I've added [pyglet_create_textures_from_file.py](https://github.com/Yuriy-Leonov/pyglet_dds_power_of_two/blob/master/manage_files/pyglet_create_textures_from_file.py) with creating textures for "sprites".
It produces interesting results (on by sight):
```
python pyglet_create_textures_from_file.py 
<TextureGrid 32x32> <TextureRegion 16x16>
<TextureGrid 32x16> <TextureRegion 15x8>
<TextureGrid 64x32> <TextureRegion 20x10>
```
But it will be tested later and if I found some moments - I will contact contributors via discord and github! :)

**Conclusion**: GREAT! 👍 
PS: should I close ticket? Or it will be closed with release?

**Comment by benmoran56** [comment]
Excellent! 

You can close the ticket, but feel free to open it again if you find any problems.
