### ISSUE TITLE
Pyglet 1.5 on_mouse_press and on_mouse_scroll not registering

### ISSUE THREAD

**Issue by dylan-berndt** [pyglet/pyglet#690]
I have a simple pyglet application and I am trying to get mouse input, however the on_mouse_press and on_mouse_scroll methods are not registering in the pyglet event dispatcher.
````
import pyglet

class Window(pyglet.window.Window):
    def __init__(self, size, title):
        super().__init__(size.x, size.y)
        self.set_caption(title)
        pyglet.clock.schedule_interval(update, 1.0/120)
        pyglet.app.run()

    def on_mouse_press(self, x, y, symbol, modifiers):
        print("press")

    def on_mouse_scroll(self, x, y, scroll_x, scroll_y):
        print("scroll")

def update(dt):
    pass
````

- This outputs nothing, but when I apply the on_mouse_press method to a pyglet Caret class elsewhere, on_mouse_press works inside of the Caret class after pushing the Caret handlers.
- I have also tried using @Window.event to specify an on_mouse_press method for Window, but this also doesn't work.
- Using the EventLogger also does not show any on_mouse_press or on_mouse_scroll events (Unless using the Caret method), however it does print on_mouse_release events. 
- I'm currently on pyglet 1.5.27, Windows 10, although I was using pyglet 1.5.23, and I tried downgrading to 1.3.2 as some others had, but it doesn't contain some necessary aspects of pyglet for my project.

**Comment by benmoran56** [comment]
Hi, putting `app.run()` inside of your `Windows.__init__` may be causing issues, because the code will block there. That may be preventing the Window methods from being picked up. The recommended way to do it is:

```py

window = MyWindow(size, title)

# last line in your main file:
pyglet.app.run()
```

Give that a try and see if it fixes your issue.

**Comment by dylan-berndt** [comment]
That worked. Thanks
