### ISSUE TITLE
Transparent Window not working on Windows 11

### ISSUE THREAD

**Issue by fregapple** [pyglet/pyglet#693]
Hi there! I see that in 1.5.20 you added experimental support for transparent windows / overlay. However, I can't find anything in the official docs on how to set it up!

I have this as my code:

```
import pyglet

window = pyglet.window.Window(style=pyglet.window.Window.WINDOW_STYLE_OVERLAY)

label = pyglet.text.Label('Hello, World',
                          font_name='Times New Roman',
                          font_size=36,
                          x=window.width//2, y=window.height//2,
                          anchor_x='center', anchor_y='center')

@window.event 
def on_draw():
    window.clear()
    label.draw()

pyglet.app.run()
```

However, it looks like this when run:

![image](https://user-images.githubusercontent.com/82219216/195791002-65e7a7f3-61ea-4f46-8790-bcea3f08c54c.png)

Is there some other command I need to make the background Transparent?

**Comment by benmoran56** [comment]
Hi, 
There is a new window style argument. There is an example here that should work on Linux and Windows. (macOS support is not yet implemented)
https://github.com/pyglet/pyglet/blob/master/examples/window/transparent_window.py

**Comment by fregapple** [comment]
Hey, yeah I just found it. Howerver it doesn't appear transparent:

![image](https://user-images.githubusercontent.com/82219216/195793309-3f860a31-3f46-4fb5-ae67-b66fdb5dea8e.png)

**Comment by benmoran56** [comment]
If you're using Wayland on Linux, unfortunately that's not yet implemented either. It will run using XWayland.

**Comment by fregapple** [comment]
Sorry, I am running Windows 11 Pro. I should have mentioned that

**Comment by fregapple** [comment]
Using python ver - 3.9.13

**Comment by fregapple** [comment]
I just trialed the example for the overlay window as well and comes back the same! Perhaps a windows 11 issue?

**Comment by benmoran56** [comment]
Thanks for the information. Yes, it's likely that more work is necessary for Windows 11 support, as the existing code was tested on 10. Nobody is currently working on this, but let's leave this ticket open for now.

**Comment by fregapple** [comment]
No worries! Look forward checking it out when it is working.

**Comment by caffeinepills** [comment]
Could you try doing a `pyglet.gl.glClearColor(0.0, 0.0, 0.0, 0.0)` after window creation and see if that works?

**Comment by fregapple** [comment]
Hi, after:
`window = Window(500, 500, style=Window.WINDOW_STYLE_TRANSPARENT)`

or after:
`pyglet.app.run()`

I tried after each and still came up the same.

**Comment by eschan145** [comment]
It works for me. I'm also on Windows 11, Python 3.10

**Comment by benmoran56** [comment]
@eschan145 Thanks for commenting. Would you mind sharing your GPU type? 
@fregapple Would you also mind sharing your info, for the sake of comparison? 
If you call pyglet.info, you can get the info from the `Window.context` section:

```sh
python -m pyglet.info
```

```sh
...
window.context._info
------------------------------------------------------------------------------
gl_info.get_version(): (4, 6)
gl_info.get_vendor(): AMD
gl_info.get_renderer(): AMD Radeon RX 580 Series (polaris10, LLVM 14.0.6, DRM 3.48, 6.0.2-arch1-1)
...
```

**Comment by fregapple** [comment]
I'll confirm my details when I get home. But I have a Nvidia RTX 2080ti.

**Comment by gureito** [comment]
it doesn't work here as well. with and without the clearing color change. 

i wonder if it's the opengl context version --i mean compared to @benmoran56 (4,6) i've gotten a (3,3)-- ? i'm tempted to investigate this further, but i need to figure out some availability first 😅

in any case, the anecdotal evidence here seems to say that nvidia's 20xx don't like this feature 😅

```
pyglet.window
------------------------------------------------------------------------------
display: <pyglet.canvas.win32.Win32Display object at 0x000001B0C233BF40>
screens[0]: Win32Screen(x=0, y=0, width=2048, height=1152)
config['double_buffer'] = 1
config['stereo'] = 0
config['buffer_size'] = 32
config['aux_buffers'] = 4
config['sample_buffers'] = 0
config['samples'] = 0
config['red_size'] = 8
config['green_size'] = 8
config['blue_size'] = 8
config['alpha_size'] = 0
config['depth_size'] = 24
config['stencil_size'] = 0
config['accum_red_size'] = 16
config['accum_green_size'] = 16
config['accum_blue_size'] = 16
config['accum_alpha_size'] = 16
config['major_version'] = 3
config['minor_version'] = 3
config['forward_compatible'] = None
config['opengl_api'] = 'gl'
config['debug'] = None
context: Win32ARBContext(id=1858677809376, share=Win32Context(id=1858684309024, share=None))

window.context._info
------------------------------------------------------------------------------
gl_info.get_version(): (3, 3)
gl_info.get_vendor(): NVIDIA Corporation
gl_info.get_renderer(): NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2
```

**Comment by fregapple** [comment]
Hey sorry I have been away, and also put together a new machine. So I can test the theory of if the 20XX cards opengl version could be the problem.

Will update during the week if I have time or on the weekend.



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by fregapple** [comment]
Hey sorry I have been away, and also put together a new machine. 
So I can test the theory of if the 20XX cards opengl version could be the problem. 

Will update during the week if I have time or on the weekend.

**Comment by fregapple** [comment]
So interestingly, with my new setup
```
window.context._info
------------------------------------------------------------------------------
gl_info.get_version(): (3, 3)
gl_info.get_vendor(): NVIDIA Corporation
gl_info.get_renderer(): NVIDIA GeForce RTX 4090/PCIe/SSE2
```

However, I know for a fact that my opengl version is 4.6. So not sure why pyglet is showing otherwise

**Comment by fregapple** [comment]
With that, perhaps this is a NVIDIA issue? I see that gureito also has his stating 3.3, when his 2070 would definitely support up to 4.6 like Benmoran's AMD card.

**Comment by benmoran56** [comment]
Thanks for the additional tests. 
For your context version, that's normal. pyglet only requests a 3.3 context, but it's up to the driver to return a higher version if it wants to.

**Comment by dankope** [comment]
Can confirm I am also having this issue on 30 series card.
```
window.context._info
------------------------------------------------------------------------------
gl_info.get_version(): (3, 3)
gl_info.get_vendor(): NVIDIA Corporation
gl_info.get_renderer(): NVIDIA GeForce RTX 3080/PCIe/SSE2
```

**Comment by dankope** [comment]
Ok I figured it out. It seems that instead of using `LWA_ALPHA` which sets the window transparency we should use `LWA_COLORKEY` which uses the color as a mask (which from reading the code we assume to be black, so 0).

An example of this as shown below.
```py
window = Window(340, 340, style=Window.WINDOW_STYLE_TRANSPARENT)

# Correct `_hwnd`.
win32gui.SetLayeredWindowAttributes(window._hwnd, 0, 0, win32con.LWA_COLORKEY)

# Correct `_view_hwnd`.
win32gui.SetWindowLong(
    window._view_hwnd,
    win32con.GWL_EXSTYLE,
    win32gui.GetWindowLong(window._view_hwnd, win32con.GWL_EXSTYLE)
    | win32con.WS_EX_LAYERED,
)
win32gui.SetLayeredWindowAttributes(window._view_hwnd, 0, 0, win32con.LWA_COLORKEY)
```

We need to set the `EX_LAYERED` manually for the child window (_view_hwnd) because it is not set for us (see line 226).
https://github.com/pyglet/pyglet/blob/080720a256c1704d8df9715cc461338f5e266231/pyglet/window/win32/__init__.py#L225-L234

I'll see if I can submit a PR to fix this issue. That is if this fix does not break anything for anyone else haha.

**Comment by benmoran56** [comment]
Great! 

If you have time to make a pull request, that may make it easier to get some AMD and Intel users to try as well.

**Comment by fregapple** [comment]
Fantastic! I'll give this a shot within the week.

My partner and I are adjusting to parenthood so haven't working on anything the past few weeks

**Comment by fregapple** [comment]
Not sure what went wrong for me, but when using your sample code in conjunction with the example, all I end up with is the Yellow Circle with a white background now. Still not transparent!
![image](https://user-images.githubusercontent.com/82219216/208267362-961bb76a-fc57-49d4-8c81-44a29fbe1045.png)

**Comment by dankope** [comment]
> Not sure what went wrong for me, but when using your sample code in conjunction with the example, all I end up with is the Yellow Circle with a white background now. Still not transparent!

I cannot replicate this, however you may still be able to get away with setting the color key to white like so:
```py
import win32con, win32gui, win32api
import pyglet
from pyglet.graphics import Batch
from pyglet.window import Window

batch = Batch()
window = Window(340, 340, style=Window.WINDOW_STYLE_TRANSPARENT)

# Correct `_hwnd`.
win32gui.SetLayeredWindowAttributes(
    window._hwnd, win32api.RGB(255, 255, 255), 0, win32con.LWA_COLORKEY
)
# Correct `_view_hwnd`.
win32gui.SetWindowLong(
    window._view_hwnd,
    win32con.GWL_EXSTYLE,
    win32gui.GetWindowLong(window._view_hwnd, win32con.GWL_EXSTYLE)
    | win32con.WS_EX_LAYERED,
)
win32gui.SetLayeredWindowAttributes(
    window._view_hwnd, win32api.RGB(255, 255, 255), 0, win32con.LWA_COLORKEY
)

pyglet.gl.glClearColor(255, 255, 255, 255.0)
circle = pyglet.shapes.Circle(250, 250, 100, color=(255, 255, 0), batch=batch)

@window.event
def on_draw():
    window.clear()
    batch.draw()

pyglet.app.run()
```

**Comment by fregapple** [comment]
Thanks! That worked for me
![image](https://user-images.githubusercontent.com/82219216/208270749-d584ce35-3c48-43a8-9a86-6d0711b35996.png)

**Comment by IagoBeuller** [comment]
Maybe need set the OpenGL GDI compatibility: Prefer compatible
As I need to in raylib:
https://github.com/raysan5/raylib/issues/2932

**Comment by IagoBeuller** [comment]
Maybe need set the OpenGL GDI compatibility: Prefer compatible
As I need to in raylib:

OpenGL GDI compatibility: Auto
![image](https://user-images.githubusercontent.com/46376262/220900174-981f3e6e-b4f3-4694-bebf-aafabfa12635.png)

OpenGL GDI compatibility: Prefer compatible
![image](https://user-images.githubusercontent.com/46376262/220900281-c1ceabda-2761-4fd2-aa50-c81a952555da.png)


[Update]: I tested the example below with OpenGL GDI compatibility set to "Auto" in NVIDIA Panel and I got black background, then I set OpenGL GDI compatibility to "Prefer compatible" and the transparency worked.
https://github.com/pyglet/pyglet/blob/master/examples/window/transparent_window.py

**Comment by benmoran56** [comment]
Thanks for adding this information, @IagoBeuller.
Nvidia drivers have the "final say", no matter what the application is asking for.

**Comment by fregapple** [comment]
Thanks for the response, I'll check it out myself n the coming days :)

**Comment by R1senDev** [comment]
> Maybe need set the OpenGL GDI compatibility

@IagoBeuller, do you know why I don't have this setting in NVIDIA Control Panel?

**Comment by Austin12325** [comment]
Just experienced this issue on pyglet 2.0.17, Nvidia Driver version 555.99. Changing Vulkan/OpenGL present method to "Prefer layered on DXGI Swapchain" resolved the issue. Both transparent and overlay windows are displaying correctly.
