### ISSUE TITLE
The program gets stuck when interval=0

### ISSUE THREAD

**Issue by DreamAlone666** [pyglet/pyglet#701]
Hi. pyglet 2.0 add a new `interval` to `run` to control the redraw. I am doing some benchmark and want it to draw as frequently as possible, so I set the `interval` to 0. However, it gets stuck after opening the window. My update function is never called and the `FPSDisplay` is never drawn.

**Comment by DreamAlone666** [comment]
Moreover, I also observe the fps is not as expected as the `interval` I set.

I create 1000 `Rectangle` and draw it in a scheduled function. A `FPSDisplay` is drawn as well to show the fps, with vsync=False.
pyglet 1.5 draws them at about 100 fps, while pyglet 2.0 only draws them at about 6 fps(default `interval`, should be 60 fps).

But when I set the interval to a very small number like 1/999999999999, pyglet 2.0 can also draws them at more than 100 fps.

I don't know whether I have done something wrong, but the fps is always slower than it should be.

**Comment by benmoran56** [comment]
Thanks for opening the ticket.
We can make it accept `0` or `None`, to mean "draw as fast as possible". I will try to make a patch for that soon.

We are also aware of the slow drawing issue, and are looking into it.

**Comment by eschan145** [comment]
When I run it at an update rate of `1/60`, it goes up to something like 20K to 200K fps. I'm using `pyglet.clock.get_frequency()`.

Windows 11, Pyglet from Github, Python 3.10.

**Comment by benmoran56** [comment]
Some of the docstrings might be out of date.   The `get_frequency` method is measuring the internal clock frequency, which is not the same as FPS.
Try using the FPSDisplay (it will take a few seconds to average).

**Comment by benmoran56** [comment]
@eschan145 Can you confirm if this works now, using the latest code from `master`?

**Comment by DreamAlone666** [comment]
Hi? Does the slow drawing problem get solved?
I try the the latest code, the fps is still slower than the `interval`=1/60(get about 30 fps) on my computer,
while the pyglet 1.5 and  pyglet 2.0 with `interval`=0 are more than 60 fps.

**Comment by benmoran56** [comment]
@DreamAlone666 Can you try the latest code from the [win32resolution](https://github.com/pyglet/pyglet/tree/win32resolution) branch? We added some changes to request a higher timer precision from the OS. This should hopefully fix the problem.

**Comment by DreamAlone666** [comment]
I have tried it. The good news is that it did allow FPS to be accurately maintained at the set level, but only if I used `schedule_interval` with the update function and the same interval as `run`.

If I used `schedule`, the situation didn't improve much.
I guess that's because the scheduled function snatches some time during the redraw interval, resulting in a slower redraw time?

Pyglet 1.5 doesn't have this problem because the scheduled function and draw should be called in the same frame, if I'm not mistaken.
Pyglet 2.0 separates redraw and updates, which really makes FPS stable and separates logic from rendering, though the `interval` can still be set to `0` to `schedule` them together.

Is there any convenient way to align the update and redraw rate apart from setting them manually?

**Comment by benmoran56** [comment]
Thank you for testing, and reporting your results. 

In pyglet 1.5, the Windows would be redrawn whenever _any_ function was scheduled (or any platform event was received). This was OK for GUI like applications, but not ideal for games.

In pyglet 2.0 if you want something scheduled exactly with the window redraw, you can simply call your code by adding a handler to the `Window.on_draw` or `Window.on_refresh` events. 
```py
def on_draw():
    your_code
    batch.draw()

def on_refresh(dt):
    your_code
    batch.draw()
```

Please note that `on_refresh` is an experimental feature, and is undocumented. It may go away in the future, or `on_draw` might be changed to have a `delta time` parameter. It's not yet decided.

**Comment by DreamAlone666** [comment]
Thanks for advice.

I have already thought about using `on_draw`, but as you show, the code can not access `delta time` unless caculate it manually.
 
It's my personal thought that a redraw event with `delta time` is of good use(at least for me), whether is `on_draw` or `on_refresh`. 
Beacuse in general, games will always redraw after updating instead of seperating them.

**Comment by benmoran56** [comment]
Yes, perhaps in the future delta time will be added to `on_draw`, and `on_refresh` can be deprecated.
In the mean time you can use `on_refresh`, but just be aware that it _could_ change in the future.
