### ISSUE TITLE
AttributeError: 'HIDDevice' object has no attribute 'get_guid'

### ISSUE THREAD

**Issue by ericries** [pyglet/pyglet#705]
I am running the latest pyglet (via github) on macos 12.5.1 with python 3.9.13 (but it also happens with the pip version)
```
Python 3.9.13 (main, Aug 25 2022, 18:24:45) 
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyglet
>>> controllers = pyglet.input.get_controllers()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/EricRies2/Projects/pyglet/pyglet/input/darwin_hid.py", line 732, in get_controllers
    [_create_controller(device, display) for device in _hid_manager.devices]
  File "/Users/EricRies2/Projects/pyglet/pyglet/input/darwin_hid.py", line 732, in <listcomp>
    [_create_controller(device, display) for device in _hid_manager.devices]
  File "/Users/EricRies2/Projects/pyglet/pyglet/input/darwin_hid.py", line 724, in _create_controller
    mapping = get_mapping(device.get_guid())
AttributeError: 'HIDDevice' object has no attribute 'get_guid'
>>> 
```

**Comment by benmoran56** [comment]
Hi @ericries,
Thanks for opening the ticket. This was a bug.
Please give it a try with the latest code from master.

**Comment by ericries** [comment]
thanks for the fix!

while I have you hear, is there an easy way to be notified when a new controller (or other usb device) is detected? or do I need to poll the relevant method?

**Comment by ericries** [comment]
Just reporting back on the fix. Good news is I no longer get that error message. Bad news is that the devices in question (nintendo joycons connected via bluetooth) do not show up in any of the lists (get_controllers, get_joysticks are both empty and get_devices shows only apple devices)

happy to try anything else you'd like and report back

**Comment by benmoran56** [comment]
Thanks for confirming. In answer to your first question, yes, there is a new [ControllerManager](https://pyglet.readthedocs.io/en/latest/programming_guide/input.html#controllermanager) class that handles hot-swapping. This has not yet been tested well on macOS, so there may be bugs. This example shows basic Controller usage, including the ControllerManager class: https://github.com/pyglet/pyglet/blob/master/examples/input/controller.py

In answer to your Joycon question, some development may be necessary if `get_devices` doesn't show them. This is the lowest level query in pyglet, so for some reason it's not detecting them as an input device.
If you're willing to do some poking around on your end, we can potentially find a solution. It goes without saying of course, but first please confirm that the Joycons are indeed paired and work in some other application or game on your system. 

The macOS input code is all located in https://github.com/pyglet/pyglet/blob/master/pyglet/input/darwin_hid.py. 
There is a [HIDManager](https://github.com/pyglet/pyglet/blob/master/pyglet/input/darwin_hid.py#L494) class that handles the low level device querying.  If you look at the [get_devices](https://github.com/pyglet/pyglet/blob/master/pyglet/input/darwin_hid.py#L713) function, it's basically just checking the HIDManager instance for devices. 
For a start, I would just confirm that HIDManager doesn't have any devices detected. 
From there, I would perhaps put some print statements around the HIDManager's `_py_matching_callback` and `_register_matching_callback` methods, to see if you get any activity when connecting/disconnecting your Joycon.

**Comment by ericries** [comment]
easy enough, I'm happy to take a look. Before I wrote my last I confirmed
they were working and accessible (via the joycon-python module:
https://pypi.org/project/joycon-python/), I should have mentioned that in
the issue. I'll put some print statements in there and see what comes up,
and then report back to you

**Comment by ericries** [comment]
You were right, they are showing up in the list of HIDDevices but not as pyglet devices. Here's the raw output (I set HIDDevice to dump_info during __init__) and then just print the list of devices and controllers right after
[out.txt](https://github.com/pyglet/pyglet/files/9999187/out.txt)

**Comment by benmoran56** [comment]
Thanks for confirming, and for digging into this on your side. 
If they're showing up in `get_devices()`, then the low level code is OK.
The next step is to get them to display as Joysticks. If we look at the `get_joysicks()` function, it's using some specific checks to check conformity: 
```py
def get_joysticks(display=None):
    return [Joystick(PygletDevice(display, device, _hid_manager)) for device in _hid_manager.devices
            if device.is_joystick() or device.is_gamepad() or device.is_multi_axis()]
```
We can see the code for those conformity checks here:
https://github.com/pyglet/pyglet/blob/7dd74be9bdeabcffccd2b0471354c12745b5c6c5/pyglet/input/darwin_hid.py#L378

Looking at that code, I'm guessing that there is an additional type of conformity check we need to do. 

By the way, can you list the guids for the JoyCons?  First fetch the devices out of the `get_devices()` list, and then call the `.get_guid()` method on them.

**Comment by benmoran56** [comment]
I found the latest USB HID Usage Tables document here: https://usb.org/sites/default/files/hut1_3_0.pdf
Looking at page 32, we can see the IDs for game input devices. We're currently checking for two specific things: 
```py
    def is_joystick(self):
        return self.conforms_to(0x01, 0x04)

    def is_gamepad(self):
        return self.conforms_to(0x01, 0x05)
```

Looking at the tables, there are some other potential device IDs that we might need to include: 
```
0x08 Multi-axis Controller
0x09 Tablet PC System Controls
0x0D Portable Device Control
```
If possible, please check if the JoyCons conform to those ids:
`device.conforms_to(0x01, ABOVE_ID)`

**Comment by ericries** [comment]
It only conforms to 0x05:

```
[PygletDevice(name=Apple Internal Keyboard / Trackpad),
 PygletDevice(name=Apple Internal Keyboard / Trackpad),
 PygletDevice(name=Joy-Con (L)),
 PygletDevice(name=Apple Internal Keyboard / Trackpad),
 PygletDevice(name=Headset),
 PygletDevice(name=Apple Internal Keyboard / Trackpad),
 PygletDevice(name=None),
 PygletDevice(name=None),
 PygletDevice(name=BTM),
 PygletDevice(name=Joy-Con (R)),
 PygletDevice(name=Apple Internal Keyboard / Trackpad),
 PygletDevice(name=Keyboard Backlight)]
[]
[]
Device: Joy-Con (L)
get_guid(): None
conforms_to(0x01, 0x0): False
conforms_to(0x01, 0x1): False
conforms_to(0x01, 0x2): False
conforms_to(0x01, 0x3): False
conforms_to(0x01, 0x4): False
conforms_to(0x01, 0x5): True
conforms_to(0x01, 0x6): False
conforms_to(0x01, 0x7): False
conforms_to(0x01, 0x8): False
conforms_to(0x01, 0x9): False
conforms_to(0x01, 0xa): False
conforms_to(0x01, 0xb): False
conforms_to(0x01, 0xc): False
conforms_to(0x01, 0xd): False
conforms_to(0x01, 0xe): False
conforms_to(0x01, 0xf): False
conforms_to(0x01, 0x10): False
conforms_to(0x01, 0x11): False
conforms_to(0x01, 0x12): False
Device: Joy-Con (R)
get_guid(): None
conforms_to(0x01, 0x0): False
conforms_to(0x01, 0x1): False
conforms_to(0x01, 0x2): False
conforms_to(0x01, 0x3): False
conforms_to(0x01, 0x4): False
conforms_to(0x01, 0x5): True
conforms_to(0x01, 0x6): False
conforms_to(0x01, 0x7): False
conforms_to(0x01, 0x8): False
conforms_to(0x01, 0x9): False
conforms_to(0x01, 0xa): False
conforms_to(0x01, 0xb): False
conforms_to(0x01, 0xc): False
conforms_to(0x01, 0xd): False
conforms_to(0x01, 0xe): False
conforms_to(0x01, 0xf): False
conforms_to(0x01, 0x10): False
conforms_to(0x01, 0x11): False
conforms_to(0x01, 0x12): False

```

**Comment by ericries** [comment]
As I'm debugging, I found one oddity. get_guid is returning None because self.transport is 'Bluetooth' and not 'BLUETOOTH' like the code expects. If I make the fix, the joy-cons now report guids as 050000004a6f792d436f6e20284c2900 and 050000004a6f792d436f6e2028522900

**Comment by benmoran56** [comment]
Great, at least we're making progress. Can you confirm that the joystick example works? https://github.com/pyglet/pyglet/blob/master/examples/input/joystick.py

Good find on the `transport` capitalization. That must be something new, but easy enough to fix. 

Controllers are a subset of Joysticks, so they need a specific mapping in order to work. pyglet has built-in mappings, but you can also add your own. Can you try using this tool to create a mapping string?
https://generalarcade.com/gamepadtool/

**Comment by ericries** [comment]
When I say "copy mapping string" for each controller, it gives me:

`030000007e0500000720000001000000,Joy-Con (R),+leftx:h0.2,+lefty:h0.4,-leftx:h0.8,-lefty:h0.1,a:b0,b:b1,back:b12,leftshoulder:b4,leftstick:b11,rightshoulder:b5,start:b9,x:b2,y:b3,platform:Mac OS X,
`
and
`030000007e0500000620000001000000,Joy-Con (L),+leftx:h0.2,+lefty:h0.4,-leftx:h0.8,-lefty:h0.1,a:b0,b:b1,back:b13,leftshoulder:b4,leftstick:b10,rightshoulder:b5,start:b8,x:b2,y:b3,platform:Mac OS X,`

**Comment by benmoran56** [comment]
Closing due to lack of follow-up, but please re-open or create a new ticket if you are still having issues.
