### ISSUE TITLE
Mat4.look_at not as expected

### ISSUE THREAD

**Issue by gizmoore** [pyglet/pyglet#708]
I started with [the example/openGL](https://github.com/pyglet/pyglet/blob/master/examples/3dmodel/model.py)

I noticed instead of using the look_at to set the view matrix, the example used:
window.view = Mat4.from_translation(Vec3(0, 0, -5))

I tried to get the same result using:
window.view = Mat4.look_at(Vec3(0, 0, -5), Vec3(0, 0, 0), Vec3(0, 1, 0))

But it didn't match.  I tried some other cases and also tried comparing with Euclid Matrix4.new_look_at().transposed(). If I create simple camera positions with translate and rotate, they match the Euclid look_at matrix, but not the Mat4.look_at.

Please let me know if I have the wrong idea on how the look_at should work.

[test_Mat4.zip](https://github.com/pyglet/pyglet/files/10042174/test_Mat4.zip)

**Comment by benmoran56** [comment]
This method was a fairly recent addition, and as you pointed out is not being used internally in pyglet (or the examples) yet.

I think the intention of this method was to mimic what something like GLM produces, so for good measure we should give this a check against PyGLM.

**Comment by einarf** [comment]
https://glm.g-truc.net/0.9.5/api/a00176.html#ga454fdf3163c2779eeeeeb9d75907ce97

I'm not sure if PyGLM have implemented `look_at` (yet).

**Comment by benmoran56** [comment]
It looks like they have. I did a quick comparison, and it does confirm that pyglet's implementation is off. 
```
>>> v1 = 0, 0, -5
>>> v2 = 0, 0, 0
>>> v3 = 0, 1, 0
>>> 
>>> pm = Mat4.look_at(Vec3(*v1), Vec3(*v2), Vec3(*v3))
>>> print(list(pm))
[-1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 5.0, 1.0]
>>> 
>>> gm = glm.lookAt(glm.vec3(*v1), glm.vec3(*v2), glm.vec3(*v3))
>>> print([e for sublist in gm.to_list() for e in sublist])
[-1.0, 0.0, -0.0, 0.0, 0.0, 1.0, -0.0, 0.0, 0.0, -0.0, -1.0, 0.0, -0.0, -0.0, -5.0, 1.0]
>>> 
>>> em = euclid.Matrix4.new_look_at(euclid.Vector3(*v1), euclid.Vector3(*v2), euclid.Vector3(*v3))
>>> print([float(e) for e in list(em)])
[-1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, -5.0, 1.0]
```

**Comment by einarf** [comment]
Ah nice. Definitely keeping them indentical is a good idea.

**Comment by benmoran56** [comment]
@gizmoore This should now be fixed in master. Can you let us know how it goes?
`Mat4.look_at` should now function the same as `glm.lookAt` (with some small differences due to float precision).

I also updated the `examples/3dmodel/model.py` example to use this method. It's not "interactive", but might be useful as a starting point for someone.

**Comment by gizmoore** [comment]
> @gizmoore This should now be fixed in master. Can you let us know how it goes? `Mat4.look_at` should now function the same as `glm.lookAt` (with some small differences due to float precision).
> 
> I also updated the `examples/3dmodel/model.py` example to use this method. It's not "interactive", but might be useful as a starting point for someone.

This works great now, thanks for fixing so quickly.
