### ISSUE TITLE
Consistent attribute names for default shaders

### ISSUE THREAD

**Issue by gizmoore** [pyglet/pyglet#709]
The names of the pyglet.model.MaterialGroup default shader and the pyglet.graphics.shader default shader use different attribute names for "position",  Does there need to be multiple "default" shaders?  If so, could they use common attribute names to help in understanding the examples?  To me, "position" is a better name than "vertices", colors better than vertex_colors, etc.

pyglet.graphics.shader, default shader:
# Default Shader source:

_vertex_source = """#version 330 core
    in vec3 position;
    in vec4 colors;
    in vec3 tex_coords;
    out vec4 vertex_colors;
    out vec3 texture_coords;

model.MaterialGroup: (also TexturedMaterialGroup)
class MaterialGroup(BaseMaterialGroup):
    default_vert_src = """#version 330 core
    in vec3 vertices;
    in vec3 normals;
    in vec4 colors;
    out vec4 vertex_colors;
    out vec3 vertex_normals;
    out vec3 vertex_position;

**Comment by benmoran56** [comment]
Thanks for opening the ticket. 

The inconsistency is just a leftover from migrating from GL2 -> GL3, with the odd names (vertices, etc.) being the static names from legacy GL.  I'll mark this as "Enhancement" and leave it open until someone gets to this.
