### ISSUE TITLE
Enhancement: optimize `Vec2.rotate`

### ISSUE THREAD

**Issue by cspotcode** [pyglet/pyglet#711]
Looking at current `Vec2` implementation, `rotate` method calls:

sin
cos
atan2
sqrt

This can be simplified to a sin and cos call, removing atan2 and sqrt

```python
# assume x, y, and r
s = math.sin(r)
c = math.cos(r)
return (c * x - s * y, s * x + c * y)
```

**Comment by benmoran56** [comment]
Thanks for the tip! This will be in the next point release.
