### ISSUE TITLE
migrating 1.x=>2.x graphics.Batch.add method

### ISSUE THREAD

**Issue by xantares** [pyglet/pyglet#715]
hello,

I did not find how to migrate to pyglet 2.x from the documentation the following code:
```
batch = pyglet.graphics.Batch()
test_polygon = batch.add(4, pyglet.gl.GL_QUADS, None, ('v2i', (
            100, 100,
            100, 200,
            200, 200,
            200, 100)),
                  ('c3B', (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)))
test_polygon.delete()
```

it says "AttributeError: 'Batch' object has no attribute 'add'"

it looks like the objects should be passed via pyglet.graphics.draw now,
but this method only has 2 positional arguments, how do I pass these lists of vertices ?

**Comment by caffeinepills** [comment]
Please read the new rendering guide on how to do this in the migration guide:
https://pyglet.readthedocs.io/en/latest/programming_guide/migration.html#graphics-module

The graphics module has been updated as wel:
https://pyglet.readthedocs.io/en/latest/programming_guide/graphics.html

Essentially, you will need to create a `ShaderProgram`. From there you can create a vertex list from the shader itself, and assign the batch during this process.

(Also note that GL_QUADS is deprecated and not supported in OpenGL 3.3. You will have to use triangles to create a square with indexed rendering.  You can see an example of this in the sprite.py file.)

**Comment by xantares** [comment]
I tried, the example from https://pyglet.readthedocs.io/en/latest/programming_guide/migration.html#graphics-module
doesnt work as that 'position' keyword is not available:
```
import pyglet
from pyglet.graphics.shader import Shader, ShaderProgram

batch = pyglet.graphics.Batch()

#     test_polygon = batch.add_indexed(4, pyglet.gl.GL_QUADS, None, ('v2i', (
#             100, 100,
#             100, 200,
#             200, 200,
#             200, 100)),
#                   ('c3B', (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)))

vertex_source="#version 150 core\nvoid main()\n{}"
fragment_source="#version 150 core\nvoid main()\n{}"
vert_shader = Shader(vertex_source, 'vertex')
frag_shader = Shader(fragment_source, 'fragment')
program = ShaderProgram(vert_shader, frag_shader)

group = None
vertex_positions = (100, 100, 100, 200, 200, 200, 100, 100, 200, 200, 200, 100)
tex_coords = (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)


vlist = program.vertex_list(6, pyglet.gl.GL_TRIANGLES, batch,
                            position=('v2i', vertex_positions),
                            tex_coords=('c3B', tex_coords))
...
  File "/usr/lib/python3.10/site-packages/pyglet/graphics/shader.py", line 580, in vertex_list
    raise ShaderException(f"\nThe attribute `{name}` doesn't exist. Valid names: \n{list(attributes)}")
pyglet.graphics.shader.ShaderException: 
The attribute `position` doesn't exist. Valid names: 
[]
```

then from https://pyglet.readthedocs.io/en/latest/programming_guide/graphics.html:

```
vlist = program.vertex_list(3, pyglet.gl.GL_TRIANGLES)
print(vlist.position)
...
File /usr/lib/python3.10/site-packages/pyglet/graphics/vertexdomain.py:343, in VertexList.__getattr__(self, name)
    341 domain = self.domain
    342 if self._cache_versions.get(name, None) != domain.version:
--> 343     attribute = domain.attribute_names[name]
    344     self._caches[name] = attribute.get_region(attribute.buffer, self.start, self.count)
    345     self._cache_versions[name] = domain.version

KeyError: 'position'

```

**Comment by benmoran56** [comment]
Hi,  it looks like you're still mixing legacy and modern code. For instance this won't work:
```py
vlist = program.vertex_list(6, pyglet.gl.GL_TRIANGLES, batch,
                            position=('v2i', vertex_positions),
                            tex_coords=('c3B', tex_coords))
```
The old `v2i`, `v3f`, etc. syntax doesn't apply anymore. The names are user defined now, and the count is specified in the Shader source code itself.

Read through this section of the documentation, and create a ShaderProgram using the example Shader source:  https://pyglet.readthedocs.io/en/latest/programming_guide/graphics.html#creating-a-shader-program

If you follow that section, you end up with a Program that has two attributes with default formats of 'f' (floats). You can see that they have predetermined `count`s as well, which are what is defined in the Shader source code. 
```py
>>> for attribute in program.attributes.items():
...     print(attribute)
... 
('position', {'type': 35664, 'size': 1, 'location': 0, 'count': 2, 'format': 'f'})      #  in vec2 position;
('colors', {'type': 35666, 'size': 1, 'location': 1, 'count': 4, 'format': 'f'})         #  in vec4 colors;
```
It's possible to set the data in another format (since data can be easily converted internally), but it's not possible to change the attribute count in a Program. The "format" syntax is described in the documentation, and that part at least is the same as pyglet 1.5. 

Some examples (mostly taken from the documentation):
```py
# Create a vertex list without any initial data:
vlist = program.vertex_list(6, pyglet.gl.GL_TRIANGLES, batch)
# set the data later  (6 vertices * count of 2  ==  12 values):
vlist.position = (100, 100, 100, 200, 200, 200, 100, 100, 200, 200, 200, 100)

# Create a vertex list, and change the colors `format` to `Bn` (bytes, normalized):
vlist = program.vertex_list(6, pyglet.gl.GL_TRIANGLES, colors='Bn')
# set the data later (6 vertices * count of 4 == 24 values):
vlist.colors = (255,) * 24

# Create a vertex list and provide initial data for `position`. The format will remain as `f`, but it still must be provided:
position_data =  (100, 100, 100, 200, 200, 200, 100, 100, 200, 200, 200, 100)
vlist = program.vertex_list(6, pyglet.gl.GL_TRIANGLES, position=('f', position_data), colors='Bn')
```

You can also find a complete example on Github, that shows making a textured quad and custom Group:
https://github.com/pyglet/pyglet/blob/master/examples/opengl/opengl_shader.py

**Comment by xantares** [comment]
ok, I made it works, thanks.

but why didnt we have to create the shader part before ?
my snippet was just about drawing some triangles and now it seems much more complicated:


```
import pyglet
from pyglet.graphics.shader import Shader, ShaderProgram

batch = pyglet.graphics.Batch()

vertex_source = """#version 150 core
    in vec2 position;
    in vec4 colors;
    out vec4 vertex_colors;

    uniform mat4 projection;

    void main()
    {
        gl_Position = projection * vec4(position, 0.0, 1.0);
        vertex_colors = colors;
    }
"""

fragment_source = """#version 150 core
    in vec4 vertex_colors;
    // out vec4 final_color;

    void main()
    {
        // final_color = vertex_colors;
        gl_FragColor = vertex_colors;
    }
"""

vert_shader = Shader(vertex_source, 'vertex')
frag_shader = Shader(fragment_source, 'fragment')
program = ShaderProgram(vert_shader, frag_shader)

group = None
tex_coords = (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
for attribute in program.attributes.items():
    print(attribute)

position_data = (100, 100, 100, 200, 200, 200, 100, 100, 200, 200, 200, 100)

vlist = program.vertex_list(6, pyglet.gl.GL_TRIANGLES, position=('i', position_data), colors=('Bn', [0] * 12))
print (vlist.position)

window = pyglet.window.Window()

@window.event
def on_draw():
    window.clear()
    batch.draw()

pyglet.app.run()
```

**Comment by benmoran56** [comment]
In legacy OpenGL <=2.1,  the vertex types and names were pre-defined internally. It was simpler, but very limited. It is indeed more complicated now in modern OpenGL, but also much more powerful and flexible. 

You may have seen it already, but to address simple drawing we added the `pyglet.shapes` module.
If your needs are more advanced, you might also be able to re-used the shapes module's default shader. It's still a good idea to understand things first, but that might save some time. 
```py
program = pygelt.shapes.get_default_shader()`
```

**Comment by xantares** [comment]
oh, thats good to know, thanks
