### ISSUE TITLE
Is there some way to smoothly pause & resume the built-in EventLoop?

### ISSUE THREAD

**Issue by gwwo** [pyglet/pyglet#716]
I'm working on integrating pyglet into my custom OpenAI's Gym environment to animating stuff.

As I figured out, this requires calling into the EventLoop to start scheduled drawing for a while, and then return to the environment logic. I've already implemented the keyboard input & animation logic as a standalone pyglet application, which call into the EventLoop once for a lifetime.

To enable pause & resume, I naively override the EventLoop class as follow. But there are two issues: the last frame drawing sometimes is delayed upon `woke up`; the keyboard inputs are buffed during `sleeping` and will fire upon `woke up`.

```py
class EventLoop(pyglet.app.EventLoop):
    def run(self, interval=1 / 60):
        self.clock.schedule_interval(self._redraw_windows, interval)
        self.has_exit = False
        from pyglet.window import Window
        Window._enable_event_queue = False

        # Dispatch pending events
        for window in pyglet.app.windows:
            window.switch_to()
            window.dispatch_pending_events()

        platform_event_loop = pyglet.app.platform_event_loop
        platform_event_loop.start()
        self.dispatch_event('on_enter')
        self.is_running = True

        self.resume()

    def pause(self):
        self.has_pause = True

    def resume(self):
        platform_event_loop = pyglet.app.platform_event_loop

        self.has_pause = False
        while not self.has_exit:
            timeout = self.idle()
            if self.has_pause:
                return
            platform_event_loop.step(timeout)

        self.is_running = False
        self.dispatch_event('on_exit')
        platform_event_loop.stop()

if __name__ == "__main__":

    game_window = GameUI()
    event_loop = EventLoop()
    event_loop.clock.schedule_interval(game_window.elapse, 1 / 120.0)

    # the game logic will pause the loop periodically,
    # after certain amount of keydown-and-then-animating cycles.
    game_window.loop = event_loop 

    event_loop.run()

    while True:
        print('start sleeping')
        time.sleep(4)
        print('woke up')
        event_loop.resume()
```

I also tried `EventLoop.exit()` and then re-call `EventLoop.run()` in an attempt to resume. This practice lead to laggy framerate after the resurrection.

Thanks for any advice!

**Comment by benmoran56** [comment]
Changing the EventLoop is fine. You can also set it directly on the `pyglet.app` module:
```py
pyglet.app.event_loop = MyEventLoop
pyglet.app.run()
```
Unfortunately, starting and resetting the PlatformEventLoop like that might lead to unpredictable results on some platforms. 
Instead of doing it this way, you could separate your start/pause logic into some functions. For instance:
```py
def start():
    pyglet.clock.schedule_interval(myfunc, 1/120.0)
    window.push_handlers(my_handler)

def stop():
    pyglet.clock.unschedule(myfunc)
    window.remove_handlers(my_handler)
```
Would something like this work for your design?

**Comment by gwwo** [comment]
> Changing the EventLoop is fine. You can also set it directly on the `pyglet.app` module:
> 
> ```python
> pyglet.app.event_loop = MyEventLoop
> pyglet.app.run()
> ```
> 
> Unfortunately, starting and resetting the PlatformEventLoop like that might lead to unpredictable results on some platforms. Instead of doing it this way, you could separate your start/pause logic into some functions. For instance:
> 
> ```python
> def start():
>     pyglet.clock.schedule_interval(myfunc, 1/120.0)
>     window.push_handlers(my_handler)
> 
> def stop():
>     pyglet.clock.unschedule(myfunc)
>     window.remove_handlers(my_handler)
> ```
> 
> Would something like this work for your design?

Thanks for your comments! @benmoran56 

Sorry that the example snippet I gave is a little misleading, as it was based on my implementation at that moment where the game logic was still being called inside `event_loop.run()` 

What I really wanted is to separate the game logic and the ui logic. Like below:

```py
game = Game(...).reset()
window = GameUI(game)
while not window.is_closed:
    action = window.listen_until() # return when keyboard input detected
    game.step(action) # step into the next state
    window.sync() # start animating the state transition
    # animation finished
```

I eventually got it done in [here](https://github.com/gwwo/wellcooked/blob/a4fdd9afc7b385298d026f3225a295f708e47b69/game_ui.py#L140-L167) by manually orcheastrating `Clock.tick()` and `Window.dispatch_events()`.

**Comment by caffeinepills** [comment]
I think this might be what you're looking for:
https://pyglet.readthedocs.io/en/latest/programming_guide/eventloop.html#dispatching-events-manually
