### ISSUE TITLE
Option to hide text within IncrementalTextLayout

### ISSUE THREAD

**Issue by eruvanos** [pyglet/pyglet#723]
**Is your feature request related to a problem? Please describe.**
Developers would like to create a login screen for their games within Arcade. Currently there seems to be no easy way to create a password input field, hiding the text a user inserts as their password.

**Describe the solution you'd like**
Provide a property to hide show only starts instead of the real text in IncrementalTextLayout, so that passwords are not displayed on the screen.

**Comment by caffeinepills** [comment]
I can see the use case, but not sure if it's something we should include.

If you are just looking to hide the displayed text, I think the simplest way is to just subclass the document in this manner:

```
class HiddenDocument(pyglet.text.document.UnformattedDocument):

    def __init__(self, text=''):
        self._real_text = u''
        super().__init__(text)

    def insert_text(self, start, text, attributes=None):
        self._insert_text(start, text, attributes)
        self.dispatch_event('on_insert_text', start, self.hide_text(text))

    def _insert_text(self, start, text, attributes):
        self._real_text = u''.join((self._real_text[:start], text, self._real_text[start:]))
        self._text = self.hide_text(self._real_text)

        len_text = len(text)
        for element in self._elements:
            if element._position >= start:
                element._position += len_text

    def delete_text(self, start, end):
        self._delete_text(start, end)
        self.dispatch_event('on_delete_text', start, end)

    def _delete_text(self, start, end):
        for element in list(self._elements):
            if start <= element._position < end:
                self._elements.remove(element)
            elif element._position >= end:  # fix bug 538
                element._position -= (end - start)

        self._real_text = self._real_text[:start] + self._real_text[end:]
        self._text = self.hide_text(self._real_text)

    @property
    def real_text(self):
        return self._real_text

    @staticmethod
    def hide_text(text):
        return "".rjust(len(text), "*")
```

From there you can just use the `real_text` property to get the actual text.

**Comment by eschan145** [comment]
@caffeinepills you can use a bullet point symbol (`•`) instead of an asterisk. It's more common in passwords.

**Comment by caffeinepills** [comment]
@eruvanos Is this sufficient for what you need?

**Comment by eruvanos** [comment]
Hi, I am sorry for the delayed answer, thank you very much for the code. 
This is enough for us.
