### ISSUE TITLE
[Feature Request] font.load add attribute filename

### ISSUE THREAD

**Issue by JeremieBergeron** [pyglet/pyglet#725]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I wanna create a font instance, but I cannot get it's path on the drive.
I wanna get it's path because I wanna use fonttools to get many information I cannot get with pyglet.

**Describe the solution you'd like**
I would like that when we load a font, we could have an attribute ``filename``.

Ex:
```py
from pyglet import font
font= font.load('Arial', 16)
font.filename
```

This is usefull when you wanna use pyglet to find a font in the system.
After that, we can use tool like fonttools to have way more information about the font.

**Comment by moi15moi** [comment]
On linux (a.k.a FontConfig), it has been added: https://github.com/pyglet/pyglet/commit/96195f62120fa0c49f2ea94cb8d63e422a373912

On Windows (DirectWrite), see the PR #737 

On Mac (CoreText), nothing has been done, but it could be implemented with the method [CTFontDescriptorCopyAttribute](https://developer.apple.com/documentation/coretext/1510346-ctfontdescriptorcopyattribute) with this parameter [kCTFontURLAttribute](https://developer.apple.com/documentation/coretext/kctfonturlattribute)

**Comment by JeremieBergeron** [comment]
On linux (a.k.a FontConfig), it has been added: https://github.com/pyglet/pyglet/commit/96195f62120fa0c49f2ea94cb8d63e422a373912

On Windows (DirectWrite), see the PR #737 

On Mac (CoreText), nothing has been done, but it could be implemented with the method [CTFontDescriptorCopyAttribute](https://developer.apple.com/documentation/coretext/1510346-ctfontdescriptorcopyattribute) with this parameter [kCTFontURLAttribute](https://developer.apple.com/documentation/coretext/kctfonturlattribute)

**Comment by caffeinepills** [comment]
Sorry, we lacked a way to test any Mac changes for a while. This should be added in #790
