### ISSUE TITLE
Multiple window initialization

### ISSUE THREAD

**Issue by gizmoore** [pyglet/pyglet#726]
**Describe the bug**
I was attempting to modify the examples/window/multiple_windows.py demo to use common objects and a common update function, see attached demo multiple_windows_share.py.  But I ran into an issue if I didn't create at least one shape after the window was created, see multiple_windows_share_FAIL.py.  I probably am missing something, but I thought I could initialize/load GL objects pretty much anytime and they'd go into the shadow object state.  The object creation seems like its working, but the draw fails for the second window. 

**System Information:**
Windows 10, Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz   2.71 GHz, 32.0 GB (31.6 GB usable)
    super().dispatch_event(*args)
  File "C:\Users\gm991e\AppData\Roaming\Python\Python39\site-packages\pyglet\event.py", line 415, in dispatch_event
    if handler(*args):
  File "C:\Users\gm991e\Downloads\pyglet-2.0\examples\window\multiple_windows_share_fail.py", line 58, in on_draw
    drawScene()
  File "C:\Users\gm991e\Downloads\pyglet-2.0\examples\window\multiple_windows_share_fail.py", line 32, in drawScene
    s2.draw()
  File "C:\Users\gm991e\AppData\Roaming\Python\Python39\site-packages\pyglet\shapes.py", line 270, in draw
    self._vertex_list.draw(GL_TRIANGLES)
  File "C:\Users\gm991e\AppData\Roaming\Python\Python39\site-packages\pyglet\graphics\vertexdomain.py", line 276, in draw
    self.domain.draw_subset(mode, self)
  File "C:\Users\gm991e\AppData\Roaming\Python\Python39\site-packages\pyglet\graphics\vertexdomain.py", line 236, in draw_subset
    self.vao.bind()
  File "C:\Users\gm991e\AppData\Roaming\Python\Python39\site-packages\pyglet\graphics\vertexarray.py", line 58, in bind
    glBindVertexArray(self._id)
  File "C:\Users\gm991e\AppData\Roaming\Python\Python39\site-packages\pyglet\gl\lib_wgl.py", line 101, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\gm991e\AppData\Roaming\Python\Python39\site-packages\pyglet\gl\lib.py", line 114, in errcheck
    raise GLException('(0x%x): %s' % (error, msg))
pyglet.gl.lib.GLException: (0x502): Invalid operation. The specified operation is not allowed in the current state.

**How To Reproduce**
The two tests are in the zip file.
[window.zip](https://github.com/pyglet/pyglet/files/10232153/window.zip)

**Comment by gizmoore** [comment]
I looked into this further, it's really a limitation of OpenGL, in that they don't allow VAOs to be shared: https://www.khronos.org/opengl/wiki/OpenGL_Object#Container_objects
The VBOs *could* be shared across contexts, but the way pyglet 2.0 works now, it creates the VBOs when the VAO is created.  So I believe that you can't really share geometry data across contexts in pyglet right now.  It would be nice if there was a 2-step process for initializing geometry data/objects in pyglet:
- create_vertex_buffers(...)  // potentially in a shared context
- create_attribute_objects(VBOs,...) // per window context, required by OpenGL

**Comment by gizmoore** [comment]
Instead of a 2-step initialization, I added this code around line 143 of pyglet/graphics/vertexdomain.py:

```
import copy
def clone(self):
        myClone = copy.copy(self) # shallow copy, can use previously defined buffers (maybe in a shared context)
        myClone.vao = vertexarray.VertexArray() # must be in current context
        return myClone
```



[test_multiple_windows_share_FAIL.zip](https://github.com/pyglet/pyglet/files/10377451/test_multiple_windows_share_FAIL.zip)
Then I updated the example code to use the cloned VertexDomain for the second window.  I did some prints to make sure I was using the buffer data from the window 1 context.  It all seems to work.

**Comment by matanster** [comment]
Just saying this became easier to follow after reading about [shared context](https://pyglet.readthedocs.io/en/latest/programming_guide/context.html#sharing-objects-between-contexts).

**Comment by matanster** [comment]
[As per the documentation](https://pyglet.readthedocs.io/en/latest/modules/window.html#pyglet.window.Window), for drawing a pyglet drawing batch in a multi-window application, this type of error is avoided by abiding by the guideline from the documentation:

> To render into a window, you must first call _`switch_to`_, to make it the current OpenGL context. If you use only one window in the application, there is no need to do this.

Whereas the practical interpretation is I believe that the _`switch_to`_ must be called as early as before populating/associating the (pyglet) drawing batch with anything and not just at some later stage before calling its `.draw()`

**Comment by caffeinepills** [comment]
Closing this as the issue was discovered and fixed in an older PR #917

**Comment by matanox** [comment]
Thanks. We still have to use `switch_to` don't we?

**Comment by caffeinepills** [comment]
> Thanks. We still have to use `switch_to` don't we?

Yes, that's unavoidable for any multiwindow app.
