### ISSUE TITLE
Unit test mistakenly assume that `Arial` is the default font on all platforms. 

### ISSUE THREAD

**Issue by benmoran56** [pyglet/pyglet#73]
On Linux, the default font is usually not Arial, causing many of the unit and integration tests to fail. Many of these tests could be rewritten and modernized.

**Comment by flowerbug** [comment]
as a temporary workaround can the package msttcorefonts be used because that does install Arial fonts and then the person trying to run the tests might make it their default font and then have those tests pass?

i am on a Debian linux system but i don't know what i'm doing well enough to take on this sort of project.

**Comment by benmoran56** [comment]
That would work, but maybe it would add more complexity into running tests. If possible, it's good if contributors can easy run their own tests when doing pull requests, and this might just be another thing that people don't want to bother with. 

After thinking about it, the only reason to check if the loaded font is Arial, is to confirm that the loading mechanism is working as expected. Perhaps we could do another type of check to query which font is actually default on each platform, then confirm that one instead.

**Comment by tomaskrizek** [comment]
It doesn't seem like there's an easy way to detect available fonts cross-platform. In matplotlib, [`font_manager.py#findSystemFonts()`](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/font_manager.py) uses a set of directories which are known to contain fonts (for each platform) and then tries to find font files in these dirs. Using fontconfig [directly](https://stackoverflow.com/a/14634033) to list available fonts seems to be quite difficult too.

The `Arial` font is mentioned in multiple tests. I think there could be a pytest fixture to select the default font and pass it to other tests. The fixture could work as follows:
- define a larger set of widely used fonts (Arial, Helvetica, Dejavu Sans, Liberation Sans, ..)
- try to load fonts from set one by one
- if at least a single font is successfully loaded, use it as a default font for all font tests
- if it fails, make pytest skip the affected tests

**Comment by benmoran56** [comment]
Removed the overly specific tests in latest releases.
