### ISSUE TITLE
Matrix multiplication ordering is confusing

### ISSUE THREAD

**Issue by tmewett** [pyglet/pyglet#733]
Perhaps bug, perhaps just my confusion about conventions:

The transformations provided by the pyglet.math matrix classes right-multiply with other matrices. That is, as seen in the 3dmodel example:

```python
model_logo.matrix = rot_x @ rot_y @ rot_z @ trans
```

The "composition" happens left-to-right.

This should imply matrices right-multiply (row) vectors too, so that we would have e.g. `vec @ rot @ trans`. However the Vec classes do not implement `@`, and instead the matrices left-multiply with vectors as if they were right-multiplying (note the sums down the columns):

```python
    def __matmul__(self, other):
        if isinstance(other, Vec4):
            # Columns:
            c0 = self[0::4]
            c1 = self[1::4]
            c2 = self[2::4]
            c3 = self[3::4]
            return Vec4(sum(map(_mul, c0, other)),
                        sum(map(_mul, c1, other)),
                        sum(map(_mul, c2, other)),
                        sum(map(_mul, c3, other)))
```

So one has to write `(rot @ trans) @ vec` to get what is really vec * rot * trans.

In OpenGL, GLSL vectors are actually column vectors, i.e. matrices **left**-multiply. (But it's a bit confusing since by default matrices must be fed into uniforms in column-major order, so in memory they are stored transposed.)

I feel that pyglet should try to be consistent here, at least internally, but ideally the same as GLSL. At least it would be good to have `@` be associative, which it isn't in `(rot @ trans) @ vec`.

Demo:

```
>>> from pyglet.math import Mat3, Vec3
>>> swap_xy = Mat3((0,1,0, 1,0,0, 0,0,1))
>>> scale_x = Mat3((2,0,0, 0,1,0, 0,0,1))
>>> swap_xy @ scale_x
Mat3(0, 1, 0)
    (2, 0, 0)
    (0, 0, 1)
>>> (swap_xy @ scale_x) @ Vec3(0,1,0)
Vec3(2, 0, 0)
```

Thanks 🙇‍♂️

**Comment by benmoran56** [comment]
Hi Tom,
Thanks for opening the ticket. 

I did write much of the matrix code, but I'm far from an expert. My understanding is that the matrix@matrix code should be correct. The matrix@vec code, however, is not used internally by pyglet and has not been tested as much. 

Just to make sure I'm understanding things correctly, let me ask some follow up questions. 

```py
# for example
swap_xy = Mat3((0,1,0, 1,0,0, 0,0,1))
scale_x = Mat3((2,0,0, 0,1,0, 0,0,1))
vec = Vec3(0,1,0)
```

**A.**  The following order of operations is identical in pyglet.math (always left -> right):
```py
        -->       -->
 swap_xy @ swap_x  @ vec
(swap_xy @ swap_x) @ vec
```
**B.**  The following operations are not (yet) implemented:
```py
vec @ swap_xy @ swap_x
```

Comparing to how things work in GLSL, are you saying that the example in **A** is incorrect, and that it's producing a result that might be expected from **B**?

**Comment by tmewett** [comment]
Hi :) Yes the mat@mat code is correct. The mat@vec code is not mathematically valid. It could be made valid if vec is treated as a column vector, and hence the code is changed to sum along the rows, not columns, of mat. However this would still leave the matrices for the transformations (`from_rotation` etc.) as wrong (transposed).

For (A): mathematically, it shouldn't be the case that multiplication has to happen left-to-right. Matrix multiplication is associative, meaning the order of evaluation doesn't change results. This isn't the case in pyglet.math:

```
>>> (swap_xy @ scale_x) @ Vec3(0,1,0)
Vec3(2, 0, 0)
>>> swap_xy @ (scale_x @ Vec3(0,1,0))
Vec3(1, 0, 0)
```

So yes, the example in (A) produces what might be thought of as (B).

Additionally, (B), which is valid, is the reverse of how GLSL does multiplication. If you wrote out the matrices and code in GLSL you'd have to write `scale_x * swap_xy * vec` - i.e. GLSL considers vectors as columns, pyglet considers vectors as rows. This is a more minor/aesthetic issue IMO.

**Comment by einarf** [comment]
I would compare with PyGLM to be sure since we're kind of trying to match that

**Comment by tmewett** [comment]
To clarify, not matching an existing API is a secondary issue. The main problem now is that `mat@vec` in pyglet is not mathematically valid.

AFAICT, GLM seems to have the same API as GLSL.

To avoid API breakages, I think the course of action should be to

1. document the matrix conventions used in pyglet.math and how they should be multiplied
2. implement `vec@mat`
3. deprecate `mat@vec` ?

**Comment by benmoran56** [comment]
For a start I updated the reprs so that they properly illustrate the rows/columns.

A did some review of the module today, and think I may have misunderstood some things before. For starters, we of course need to send the data to OpenGL as an array, which as I understand it is arranged as:
```
(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)
```
And my current understanding is that the same data is arranged in column major order in glsl:
```
| 0| 4| 8|12|
| 1| 5| 9|13|
| 2| 6|10|14|
| 3| 7|11|15|
```
If that's correct, then the rows/columns is backwards in the `__matmul__` method. Need to read up a bit more.

**Comment by tmewett** [comment]
Unfortunately I think the other change in 9a19a74f57be277e6dcccf76375802ef1e8b2da4, reversing the row and column method definitions, makes things even more inconsistent.

Yes you're right that OpenGL works column major by default, but since it also multiplies matrices on the other side to pyglet, this cancels out and it means that a given matrix behaves the same in both pyglet and OpenGL (because (AB)^T = B^T A^T).

Perhaps we can discuss this more short-form on the Discord?
