### ISSUE TITLE
examples/text/html_label.py exception (with fix)

### ISSUE THREAD

**Issue by gizmoore** [pyglet/pyglet#734]
**Describe the bug**
Running the test html_label.py, I get an exception at line 475 of https://github.com/pyglet/pyglet/blob/v2.0.2.1/pyglet/text/layout.py

Changing the code from:
        self.element.place(layout, x, y, z)
to:
        self.element.place(layout, x, y)

Fixed the issue

**System Information:**
Windows 10, x64

**How To Reproduce**
cd examples/text
python html_label.py

**Comment by caffeinepills** [comment]
Added a fix in PR #736
