### ISSUE TITLE
typo in examples/text/font_comparison.py

### ISSUE THREAD

**Issue by gizmoore** [pyglet/pyglet#735]
**Describe the bug**
line 153 of https://github.com/pyglet/pyglet/blob/v2.0.2.1/examples/text/font_comparison.py
"candidates" is spelled "canditates", this is only apparent if you define the "safe" flag as "False".

Also, i changed pyglet_safe(fontentry) to:
return not fontentry.name[0].isdigit() and not fontentry.name[0] == '@' and fontentry.vector and fontentry.family != wq.FF_DONTCARE

I'm not sure what the font that started with a number was, and the fonts that start with '@' are vertical fonts and didn't seem to work either.  Without this change, I was getting an exception on the first font that attempted to load and the test exited.  If the first font is loaded, and then you get exceptions on fonts after that, the test continues ok..you can skip past the fonts with exceptions.

**System Information:**
Windows 10, x64

**How To Reproduce**
examples/text/font_comparison.py

**Comment by caffeinepills** [comment]
This is a really old font example using a deprecated font renderer, but I will put in a patch to make it work.

However, I am not sure if it's better to remove this, rebuild it to work with all font renderers, or make it work with the newer default Windows font renderer.

@benmoran56 What do you think?

**Comment by benmoran56** [comment]
I'll close this ticket since you you fixed it. 

As for the example itself, it would be useful to have a generic comparison example.
First of all, we would have to expose the functionality to list all system fonts. That could be useful to have anyway, just for people who want to see what we're picking up.
