### ISSUE TITLE
Missing GL Function glFenceSync

### ISSUE THREAD

**Issue by Jukitsu** [pyglet/pyglet#751]
The GL function glFenceSync is missing since Pyglet 2.0, causing NameErrors;
(More info on the function at https://registry.khronos.org/OpenGL-Refpages/gl4/html/glFenceSync.xhtml)
The function itself was supported in Pyglet 1.5 but is core since OpenGL 3.2, so it should be supported by Pyglet 2.0.

pyglet.gl.gl.py:
![image](https://user-images.githubusercontent.com/84381972/212499144-32e72049-440f-450a-bf93-b759d286171b.png)

Note however that the enum GL_SYNC_GPU_COMMANDS_COMPLETE is defined.

**How To Reproduce**
Type glFenceSync(gl.GL_SYNC_GPU_COMMANDS_COMPLETE, 0) and notice the NameError.

**Comment by einarf** [comment]
They are in the ignore list in the script generating the bindings. Probably not too hard to fix.
https://github.com/pyglet/pyglet/blob/d473d563ce18d3b51931e89702a98cc3c2466011/tools/gengl.py#L108-L118

PRs are welcome.

**Comment by einarf** [comment]
If you want to test : https://github.com/pyglet/pyglet/pull/752

**Comment by benmoran56** [comment]
Thanks @einarf!

This is now merged in, and will be in the next point release.
In the mean time, you can grab the latest code from the repository, or you can pip install directly from Github:
```py
pip install --upgrade --user git+https://github.com/pyglet/pyglet
```
