### ISSUE TITLE
MacOS file_drop suooprt

### ISSUE THREAD

**Issue by shenjackyuanjie** [pyglet/pyglet#755]
I am testing DR on my MacOS device
and found this on testing
https://github.com/pyglet/pyglet/blob/master/pyglet/window/cocoa/__init__.py#L173-#L175
will it be done in pyglet 2.1?

**Comment by caffeinepills** [comment]
https://github.com/caffeinepills/pyglet/tree/macosx_dev You can test out my test branch here with drop support.

**Comment by shenjackyuanjie** [comment]
> https://github.com/caffeinepills/pyglet/tree/macosx_dev You can test out my test branch here with drop support.
OK. tested on this action
https://github.com/shenjackyuanjie/Difficult-Rocket/actions/runs/3973123615
now looks good, good to merge

**Comment by shenjackyuanjie** [comment]
I will keep this until @caffeinepills branch merged

**Comment by caffeinepills** [comment]
This should be added in https://github.com/pyglet/pyglet/pull/790

**Comment by shenjackyuanjie** [comment]
> This should be added in #790

waiting for merge~

**Comment by caffeinepills** [comment]
Merged in. Will be in the next pyglet release.
