### ISSUE TITLE
Confirmation of ffmpeg 5.* support

### ISSUE THREAD

**Issue by DManowitz** [pyglet/pyglet#759]
According to the [documentation](https://pyglet.readthedocs.io/en/latest/programming_guide/media.html#id4), pyglet only supports ffmpeg 4.X.  However, looking at issue #603 or #541, it appears that some versions of pyglet should support ffmpeg 5.X.  If so, please update the documentation with the correct information.

**Comment by caffeinepills** [comment]
> Decoding of compressed audio and video is provided by FFmpeg v4 or v5, an optional component available for Linux, Windows and Mac OS X. FFmpeg needs to be installed separately.

Is specified at the top of the media page.

We will update the installation area as well. Thanks for your issue.

**Comment by DManowitz** [comment]
What is the minimum version of pyglet that supports ffmpeg 5.X?

**Comment by caffeinepills** [comment]
1.5.24

**Comment by benmoran56** [comment]
Docs have been updating, so closing this. Thanks for opening the ticket @DManowitz.
