### ISSUE TITLE
OpenGL 3.3 Code not working on Ubuntu Linux

### ISSUE THREAD

**Issue by pvcraven** [pyglet/pyglet#76]
This code doesn't work under Ubuntu for me:

``` python
import pyglet


class Game(pyglet.window.Window):
    def __init__(self):

        config = pyglet.gl.Config(major_version=3,
                                  minor_version=3,
                                  double_buffer=True,
                                  sample_buffers=1,
                                  samples=4)

        super().__init__(config=config)

    def on_resize(self, width: float, height: float):
        # pass
        super().on_resize(width, height)


game = Game()
pyglet.app.run()
```

Fails with:
```
/home/paul/arcade/venv/bin/python /home/paul/arcade/arcade/test.py
Traceback (most recent call last):
  File "/home/paul/arcade/arcade/test.py", line 21, in <module>
    pyglet.app.run()
  File "/home/paul/arcade/venv/lib/python3.6/site-packages/pyglet/app/__init__.py", line 144, in run
    event_loop.run()
  File "/home/paul/arcade/venv/lib/python3.6/site-packages/pyglet/app/base.py", line 164, in run
    self._legacy_setup()
  File "/home/paul/arcade/venv/lib/python3.6/site-packages/pyglet/app/base.py", line 253, in _legacy_setup
    window.dispatch_pending_events()
  File "/home/paul/arcade/venv/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 880, in dispatch_pending_events
    EventDispatcher.dispatch_event(self, *self._event_queue.pop(0))
  File "/home/paul/arcade/venv/lib/python3.6/site-packages/pyglet/event.py", line 423, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/home/paul/arcade/arcade/test.py", line 17, in on_resize
    super().on_resize(width, height)
  File "/home/paul/arcade/venv/lib/python3.6/site-packages/pyglet/window/__init__.py", line 805, in on_resize
    self._projection.set(width, height, viewport_width, viewport_height)
  File "/home/paul/arcade/venv/lib/python3.6/site-packages/pyglet/window/__init__.py", line 266, in set
    gl.glMatrixMode(gl.GL_PROJECTION)
  File "/home/paul/arcade/venv/lib/python3.6/site-packages/pyglet/gl/lib.py", line 106, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid operation'
```
It will work with the default config. It will work with if you do a `pass` with the `on_resize()` instead of calling the super resize.

Using Pyglet 1.4.5 release.

I think it runs under Windows and MacOS ok.

**Comment by einarf** [comment]
Almost looks like you actually got a core context considering `glMatrixMode(gl.GL_PROJECTION)` raises invalid operation.

I solve this problem in moderngl by overriding `on_resize` to avoid the fixed pipeline calls.

**Comment by pvcraven** [comment]
If I over-ride on_resize, I can't use Pyglet's displaying of text for some reason.

**Comment by einarf** [comment]
You have to set your own viewport in the new method. 

```python
viewport_width, viewport_height = self.get_framebuffer_size()
glViewport(0, 0,viewport_width, viewport_height)
```

**Comment by einarf** [comment]
... as in .. do what I wrote above instead of `super().on_resize(width, height)` 😄

**Comment by benmoran56** [comment]
I've accidentally broken it at the moment, but you should give this a try on the `shaders` branch as well, since the `text` module is about 2/3 working on modern OpenGL contexts. In pyglet 1.4, it's using a lot of legacy GL code. It might work if you get a compatibility context, but I don't think most Linux drivers will do that.

**Comment by einarf** [comment]
Ah right. Sorry for giving false hope. There are of course more fixed pipeline stuff down the line.

**Comment by pvcraven** [comment]
@benmoran56 are you going to do a pre-release of the shaders branch?

**Comment by benmoran56** [comment]
Yes, some time in the next days, I'm going to merge `shaders` into master, and push out a 2.0.0-dev1 (or 2.0.0a1) release.

**Comment by pvcraven** [comment]
Great, thanks for the update.

**Comment by benmoran56** [comment]
@pvcraven I pushed out a dev release of pyglet 2.0 to PyPi. You should be able to get it with the `--pre` flag:
`pip install --upgrade --user pyglet --pre`

There might be other issues still left to solve, but it *should* cover most of your use case I think. Let me know how it goes!

**Comment by benmoran56** [comment]
@pvcraven I'll close this for now since the dev release is working (as per our conversation on Discord). If (when :smile:) you run into issues with that branch, please open a new ticket.
