### ISSUE TITLE
How to repeatedly play a sound at arbitrary intervals?

### ISSUE THREAD

**Issue by matanster** [pyglet/pyglet#760]
# Issue description

The media player seemingly silently fails to play a sound from a sound file, when `.play()` is called from within the `update` method of the window: the sound file will play fine for the first time, but will remain silent (no sound) on the next calls. 

The code below is a distillation into minimally reproducible code, whereas in my full code the `.seek(0)` and `.play()` methods are called from within my `update` callback function at more arbitrary intervals depending on user interaction. 

The result of `player.playing` is True, but no sound is produced other than the first time around the loop. 

Is my minimally reproducible code below pathological in its use of pyglet api or in managing the player from within the `update` callback? Does the problem reproduce for you? 

Thank you for pyglet, and thanks for your comments!

```python
import time
import pyglet

class PlayDebug():
    def __init__(self):

        print(f'using audio driver {pyglet.media.get_audio_driver()}')
        print(f'pyglet ffmpeg integration: {pyglet.media.have_ffmpeg()}')

        audio_file_path = 'media-resources/licensed-sounds/006224189-organic-whoosh-25.wav'
        source = pyglet.media.load(audio_file_path)
        print(f'media duration (obtained from audio track): {source.duration}')
        self.player = pyglet.media.Player()
        self.player.queue(source)
        self.player.volume = 0.5

        self.last = time.time()

        def update(dt):
            if time.time() - self.last > source.duration + 1:
                self.player.seek(0)
                self.player.play()
                print(self.player.playing)
                self.last = time.time()

        self.update_interval = 1 / 20
        pyglet.clock.schedule_interval(update, self.update_interval)
        pyglet.app.run()


p = PlayDebug()
```

## System Information:

I started with pyglet 1.5.21 and upgraded to 2.0.3, the issue persists after the upgrade.
The output of `python -m pyglet.info` follows.

Platform
------------------------------------------------------------------------------
platform:  Linux-5.4.0-137-generic-x86_64-with-glibc2.31
release:   5.4.0-137-generic
machine:   x86_64

Python
------------------------------------------------------------------------------
implementation: CPython
sys.version: 3.9.5 (default, Nov 23 2021, 15:27:38) 
[GCC 9.3.0]
sys.maxint: 9223372036854775807
os.getcwd(): /home/matan/ssd/intel-optane/projects/ergonomy/nui/subprojects/nui

pyglet
------------------------------------------------------------------------------
pyglet.version: 2.0.3
pyglet.compat_platform: linux
pyglet.__file__: /home/matan/ssd/intel-optane/projects/ergonomy/nui/subprojects/nui/venv/lib/python3.9/site-packages/pyglet/__init__.py
pyglet.options['audio'] = ('xaudio2', 'directsound', 'openal', 'pulse', 'silent')
pyglet.options['debug_font'] = False
pyglet.options['debug_gl'] = True
pyglet.options['debug_gl_trace'] = False
pyglet.options['debug_gl_trace_args'] = False
pyglet.options['debug_gl_shaders'] = False
pyglet.options['debug_graphics_batch'] = False
pyglet.options['debug_lib'] = False
pyglet.options['debug_media'] = False
pyglet.options['debug_texture'] = False
pyglet.options['debug_trace'] = False
pyglet.options['debug_trace_args'] = False
pyglet.options['debug_trace_depth'] = 1
pyglet.options['debug_trace_flush'] = True
pyglet.options['debug_win32'] = False
pyglet.options['debug_input'] = False
pyglet.options['debug_x11'] = False
pyglet.options['shadow_window'] = True
pyglet.options['vsync'] = None
pyglet.options['xsync'] = True
pyglet.options['xlib_fullscreen_override_redirect'] = False
pyglet.options['search_local_libs'] = True
pyglet.options['win32_gdi_font'] = False
pyglet.options['headless'] = False
pyglet.options['headless_device'] = 0
pyglet.options['win32_disable_shaping'] = False
pyglet.options['dw_legacy_naming'] = False

pyglet.window
------------------------------------------------------------------------------
display: <pyglet.canvas.xlib.XlibDisplay object at 0x7fe734938910>
screens[0]: XlibScreen(display=<pyglet.canvas.xlib.XlibDisplay object at 0x7fe734938910>, x=1920, y=0, width=1920, height=1080, xinerama=1)
screens[1]: XlibScreen(display=<pyglet.canvas.xlib.XlibDisplay object at 0x7fe734938910>, x=0, y=0, width=1920, height=1080, xinerama=1)
config['double_buffer'] = 1
config['stereo'] = 0
config['buffer_size'] = 24
config['aux_buffers'] = 0
config['sample_buffers'] = 0
config['samples'] = 0
config['red_size'] = 8
config['green_size'] = 8
config['blue_size'] = 8
config['alpha_size'] = 0
config['depth_size'] = 24
config['stencil_size'] = 0
config['accum_red_size'] = 0
config['accum_green_size'] = 0
config['accum_blue_size'] = 0
config['accum_alpha_size'] = 0
config['major_version'] = 3
config['minor_version'] = 3
config['forward_compatible'] = None
config['opengl_api'] = 'gl'
config['debug'] = None
context: XlibContext(id=140631000030224, share=XlibContext(id=140630996258000, share=None))

window.context._info
------------------------------------------------------------------------------
gl_info.get_version(): (4, 6)
gl_info.get_vendor(): Intel
gl_info.get_renderer(): Mesa Intel(R) UHD Graphics 630 (CFL GT2)
gl_info.get_extensions():
   GL_3DFX_texture_compression_FXT1
   GL_AMD_conservative_depth
   GL_AMD_depth_clamp_separate
   GL_AMD_draw_buffers_blend
   GL_AMD_gpu_shader_int64
   GL_AMD_multi_draw_indirect
   GL_AMD_performance_monitor
   GL_AMD_pinned_memory
   GL_AMD_query_buffer_object
   GL_AMD_seamless_cubemap_per_texture
   GL_AMD_shader_stencil_export
   GL_AMD_shader_trinary_minmax
   GL_AMD_texture_texture4
   GL_AMD_vertex_shader_layer
   GL_AMD_vertex_shader_viewport_index
   GL_ANGLE_texture_compression_dxt3
   GL_ANGLE_texture_compression_dxt5
   GL_ARB_ES2_compatibility
   GL_ARB_ES3_1_compatibility
   GL_ARB_ES3_2_compatibility
   GL_ARB_ES3_compatibility
   GL_ARB_arrays_of_arrays
   GL_ARB_base_instance
   GL_ARB_blend_func_extended
   GL_ARB_buffer_storage
   GL_ARB_clear_buffer_object
   GL_ARB_clear_texture
   GL_ARB_clip_control
   GL_ARB_compressed_texture_pixel_storage
   GL_ARB_compute_shader
   GL_ARB_compute_variable_group_size
   GL_ARB_conditional_render_inverted
   GL_ARB_conservative_depth
   GL_ARB_copy_buffer
   GL_ARB_copy_image
   GL_ARB_cull_distance
   GL_ARB_debug_output
   GL_ARB_depth_buffer_float
   GL_ARB_depth_clamp
   GL_ARB_derivative_control
   GL_ARB_direct_state_access
   GL_ARB_draw_buffers
   GL_ARB_draw_buffers_blend
   GL_ARB_draw_elements_base_vertex
   GL_ARB_draw_indirect
   GL_ARB_draw_instanced
   GL_ARB_enhanced_layouts
   GL_ARB_explicit_attrib_location
   GL_ARB_explicit_uniform_location
   GL_ARB_fragment_coord_conventions
   GL_ARB_fragment_layer_viewport
   GL_ARB_fragment_shader
   GL_ARB_fragment_shader_interlock
   GL_ARB_framebuffer_no_attachments
   GL_ARB_framebuffer_object
   GL_ARB_framebuffer_sRGB
   GL_ARB_get_program_binary
   GL_ARB_get_texture_sub_image
   GL_ARB_gl_spirv
   GL_ARB_gpu_shader5
   GL_ARB_gpu_shader_fp64
   GL_ARB_gpu_shader_int64
   GL_ARB_half_float_pixel
   GL_ARB_half_float_vertex
   GL_ARB_indirect_parameters
   GL_ARB_instanced_arrays
   GL_ARB_internalformat_query
   GL_ARB_internalformat_query2
   GL_ARB_invalidate_subdata
   GL_ARB_map_buffer_alignment
   GL_ARB_map_buffer_range
   GL_ARB_multi_bind
   GL_ARB_multi_draw_indirect
   GL_ARB_occlusion_query2
   GL_ARB_parallel_shader_compile
   GL_ARB_pipeline_statistics_query
   GL_ARB_pixel_buffer_object
   GL_ARB_point_sprite
   GL_ARB_polygon_offset_clamp
   GL_ARB_post_depth_coverage
   GL_ARB_program_interface_query
   GL_ARB_provoking_vertex
   GL_ARB_query_buffer_object
   GL_ARB_robust_buffer_access_behavior
   GL_ARB_robustness
   GL_ARB_sample_shading
   GL_ARB_sampler_objects
   GL_ARB_seamless_cube_map
   GL_ARB_seamless_cubemap_per_texture
   GL_ARB_separate_shader_objects
   GL_ARB_shader_atomic_counter_ops
   GL_ARB_shader_atomic_counters
   GL_ARB_shader_ballot
   GL_ARB_shader_bit_encoding
   GL_ARB_shader_clock
   GL_ARB_shader_draw_parameters
   GL_ARB_shader_group_vote
   GL_ARB_shader_image_load_store
   GL_ARB_shader_image_size
   GL_ARB_shader_objects
   GL_ARB_shader_precision
   GL_ARB_shader_stencil_export
   GL_ARB_shader_storage_buffer_object
   GL_ARB_shader_subroutine
   GL_ARB_shader_texture_image_samples
   GL_ARB_shader_texture_lod
   GL_ARB_shader_viewport_layer_array
   GL_ARB_shading_language_420pack
   GL_ARB_shading_language_include
   GL_ARB_shading_language_packing
   GL_ARB_spirv_extensions
   GL_ARB_stencil_texturing
   GL_ARB_sync
   GL_ARB_tessellation_shader
   GL_ARB_texture_barrier
   GL_ARB_texture_buffer_object
   GL_ARB_texture_buffer_object_rgb32
   GL_ARB_texture_buffer_range
   GL_ARB_texture_compression_bptc
   GL_ARB_texture_compression_rgtc
   GL_ARB_texture_cube_map_array
   GL_ARB_texture_filter_anisotropic
   GL_ARB_texture_float
   GL_ARB_texture_gather
   GL_ARB_texture_mirror_clamp_to_edge
   GL_ARB_texture_multisample
   GL_ARB_texture_non_power_of_two
   GL_ARB_texture_query_levels
   GL_ARB_texture_query_lod
   GL_ARB_texture_rectangle
   GL_ARB_texture_rg
   GL_ARB_texture_rgb10_a2ui
   GL_ARB_texture_stencil8
   GL_ARB_texture_storage
   GL_ARB_texture_storage_multisample
   GL_ARB_texture_swizzle
   GL_ARB_texture_view
   GL_ARB_timer_query
   GL_ARB_transform_feedback2
   GL_ARB_transform_feedback3
   GL_ARB_transform_feedback_instanced
   GL_ARB_transform_feedback_overflow_query
   GL_ARB_uniform_buffer_object
   GL_ARB_vertex_array_bgra
   GL_ARB_vertex_array_object
   GL_ARB_vertex_attrib_64bit
   GL_ARB_vertex_attrib_binding
   GL_ARB_vertex_buffer_object
   GL_ARB_vertex_shader
   GL_ARB_vertex_type_10f_11f_11f_rev
   GL_ARB_vertex_type_2_10_10_10_rev
   GL_ARB_viewport_array
   GL_ATI_blend_equation_separate
   GL_ATI_texture_float
   GL_EXT_EGL_image_storage
   GL_EXT_EGL_sync
   GL_EXT_abgr
   GL_EXT_blend_equation_separate
   GL_EXT_demote_to_helper_invocation
   GL_EXT_draw_buffers2
   GL_EXT_draw_instanced
   GL_EXT_framebuffer_blit
   GL_EXT_framebuffer_multisample
   GL_EXT_framebuffer_multisample_blit_scaled
   GL_EXT_framebuffer_object
   GL_EXT_framebuffer_sRGB
   GL_EXT_memory_object
   GL_EXT_memory_object_fd
   GL_EXT_packed_depth_stencil
   GL_EXT_packed_float
   GL_EXT_pixel_buffer_object
   GL_EXT_polygon_offset_clamp
   GL_EXT_provoking_vertex
   GL_EXT_semaphore
   GL_EXT_semaphore_fd
   GL_EXT_shader_framebuffer_fetch
   GL_EXT_shader_framebuffer_fetch_non_coherent
   GL_EXT_shader_integer_mix
   GL_EXT_shader_samples_identical
   GL_EXT_texture_array
   GL_EXT_texture_compression_dxt1
   GL_EXT_texture_compression_rgtc
   GL_EXT_texture_compression_s3tc
   GL_EXT_texture_filter_anisotropic
   GL_EXT_texture_integer
   GL_EXT_texture_sRGB
   GL_EXT_texture_sRGB_R8
   GL_EXT_texture_sRGB_decode
   GL_EXT_texture_shadow_lod
   GL_EXT_texture_shared_exponent
   GL_EXT_texture_snorm
   GL_EXT_texture_swizzle
   GL_EXT_timer_query
   GL_EXT_transform_feedback
   GL_EXT_vertex_array_bgra
   GL_EXT_vertex_attrib_64bit
   GL_IBM_multimode_draw_arrays
   GL_INTEL_blackhole_render
   GL_INTEL_conservative_rasterization
   GL_INTEL_performance_query
   GL_INTEL_shader_atomic_float_minmax
   GL_INTEL_shader_integer_functions2
   GL_KHR_blend_equation_advanced
   GL_KHR_blend_equation_advanced_coherent
   GL_KHR_context_flush_control
   GL_KHR_debug
   GL_KHR_no_error
   GL_KHR_parallel_shader_compile
   GL_KHR_robust_buffer_access_behavior
   GL_KHR_robustness
   GL_KHR_texture_compression_astc_ldr
   GL_KHR_texture_compression_astc_sliced_3d
   GL_MESA_framebuffer_flip_y
   GL_MESA_pack_invert
   GL_MESA_shader_integer_functions
   GL_MESA_texture_signed_rgba
   GL_NV_compute_shader_derivatives
   GL_NV_conditional_render
   GL_NV_copy_image
   GL_NV_depth_clamp
   GL_NV_fragment_shader_interlock
   GL_NV_packed_depth_stencil
   GL_NV_texture_barrier
   GL_OES_EGL_image
   GL_S3_s3tc

pyglet.gl.glx_info
------------------------------------------------------------------------------
context.is_direct(): 1
glx_info.get_server_vendor(): SGI
glx_info.get_server_version(): 1.4
glx_info.get_server_extensions():
   GLX_ARB_create_context
   GLX_ARB_create_context_no_error
   GLX_ARB_create_context_profile
   GLX_ARB_create_context_robustness
   GLX_ARB_fbconfig_float
   GLX_ARB_framebuffer_sRGB
   GLX_ARB_multisample
   GLX_EXT_create_context_es_profile
   GLX_EXT_create_context_es2_profile
   GLX_EXT_fbconfig_packed_float
   GLX_EXT_framebuffer_sRGB
   GLX_EXT_import_context
   GLX_EXT_libglvnd
   GLX_EXT_no_config_context
   GLX_EXT_texture_from_pixmap
   GLX_EXT_visual_info
   GLX_EXT_visual_rating
   GLX_MESA_copy_sub_buffer
   GLX_OML_swap_method
   GLX_SGI_make_current_read
   GLX_SGI_swap_control
   GLX_SGIS_multisample
   GLX_SGIX_fbconfig
   GLX_SGIX_pbuffer
   GLX_SGIX_visual_select_group
   GLX_INTEL_swap_event
glx_info.get_client_vendor(): Mesa Project and SGI
glx_info.get_client_version(): 1.4
glx_info.get_client_extensions():
   GLX_ARB_context_flush_control
   GLX_ARB_create_context
   GLX_ARB_create_context_no_error
   GLX_ARB_create_context_profile
   GLX_ARB_create_context_robustness
   GLX_ARB_fbconfig_float
   GLX_ARB_framebuffer_sRGB
   GLX_ARB_get_proc_address
   GLX_ARB_multisample
   GLX_EXT_buffer_age
   GLX_EXT_create_context_es2_profile
   GLX_EXT_create_context_es_profile
   GLX_EXT_fbconfig_packed_float
   GLX_EXT_framebuffer_sRGB
   GLX_EXT_import_context
   GLX_EXT_no_config_context
   GLX_EXT_swap_control
   GLX_EXT_swap_control_tear
   GLX_EXT_texture_from_pixmap
   GLX_EXT_visual_info
   GLX_EXT_visual_rating
   GLX_ATI_pixel_format_float
   GLX_INTEL_swap_event
   GLX_MESA_copy_sub_buffer
   GLX_MESA_multithread_makecurrent
   GLX_MESA_query_renderer
   GLX_MESA_swap_control
   GLX_NV_float_buffer
   GLX_OML_swap_method
   GLX_OML_sync_control
   GLX_SGIS_multisample
   GLX_SGIX_fbconfig
   GLX_SGIX_pbuffer
   GLX_SGIX_visual_select_group
   GLX_SGI_make_current_read
   GLX_SGI_swap_control
   GLX_SGI_video_sync
glx_info.get_extensions():
   GLX_ARB_create_context
   GLX_ARB_create_context_no_error
   GLX_ARB_create_context_profile
   GLX_ARB_create_context_robustness
   GLX_ARB_fbconfig_float
   GLX_ARB_framebuffer_sRGB
   GLX_ARB_get_proc_address
   GLX_ARB_multisample
   GLX_EXT_buffer_age
   GLX_EXT_create_context_es2_profile
   GLX_EXT_create_context_es_profile
   GLX_EXT_fbconfig_packed_float
   GLX_EXT_framebuffer_sRGB
   GLX_EXT_import_context
   GLX_EXT_no_config_context
   GLX_EXT_swap_control
   GLX_EXT_swap_control_tear
   GLX_EXT_texture_from_pixmap
   GLX_EXT_visual_info
   GLX_EXT_visual_rating
   GLX_INTEL_swap_event
   GLX_MESA_copy_sub_buffer
   GLX_MESA_query_renderer
   GLX_MESA_swap_control
   GLX_OML_swap_method
   GLX_OML_sync_control
   GLX_SGIS_multisample
   GLX_SGIX_fbconfig
   GLX_SGIX_pbuffer
   GLX_SGIX_visual_select_group
   GLX_SGI_make_current_read
   GLX_SGI_swap_control
   GLX_SGI_video_sync

pyglet.media
------------------------------------------------------------------------------
audio driver: <pyglet.media.drivers.openal.adaptation.OpenALDriver object at 0x7fe73494e100>

pyglet.media.ffmpeg
------------------------------------------------------------------------------
FFmpeg version: 4.2.7-0ubuntu0.1

pyglet.media.drivers.openal
------------------------------------------------------------------------------
Library: <CDLL 'libopenal.so.1', handle 1a540a0 at 0x7fe71626f280>
Version: 1.1
Extensions:
   ALC_ENUMERATE_ALL_EXT
   ALC_ENUMERATION_EXT
   ALC_EXT_CAPTURE
   ALC_EXT_DEDICATED
   ALC_EXT_disconnect
   ALC_EXT_EFX
   ALC_EXT_thread_local_context
   ALC_SOFT_device_clock
   ALC_SOFT_HRTF
   ALC_SOFT_loopback
   ALC_SOFT_output_limiter
   ALC_SOFT_pause_device

pyglet.input.wintab
------------------------------------------------------------------------------
WinTab not available.

**Comment by caffeinepills** [comment]
Once a song is done playing, it will be removed from the queue. You will have to requeue it for it to play again.

``py
       def update(dt):
            if time.time() - self.last > source.duration + 1:
                self.player.queue(source)
                self.player.seek(0)
                self.player.play()
                print(self.player.playing)
                self.last = time.time()
````

You should also utilize the `on_eos` event from the player to determine if the source is done playing before you queue another, rather than using a schedule to check if the duration is over.

**Comment by matanster** [comment]
Okay, re-queing the source works as expected. But outside this toy example, I would like to seek to the beginning of the source when my real program's logic determines it is the right time to replay according to its own eventing context, regardless of whether the source reached its end or not at that arbitrary time. 

Therefore, would `seek`, `pause` and `play` idiomatically enable such restarts of playing the same sound source regardless of whether it has reached its end by the time we want to play the same sound source from its beginning? Or is re-queing and keeping track of the `eos` events the only intended way for using the api for such a purpose please?

I would assume some performance benefits in not re-queuing every time, and avoiding tracking `eos` would avoid some complexity if `freeze` and `play` worked like I imagined them to. What might I be missing?

**Comment by matanster** [comment]
Okay, Got it, if it's done playing it's no longer on the queue. I'll seek some example of capturing the eos event. Thank you.

**Comment by benmoran56** [comment]
If you are going to be playing the same sounds multiple times, you will also want to pass the `streaming=False` argument when loading the source.

**Comment by matanster** [comment]
Thanks. Actually an example of using `on_eos` would be very welcome, if I have to manage the state by handling that event in order to restart the media like suggested.

I seem to be getting that part wrong in incorporating it as follows:

```python
import time
import pyglet

class PlayDebug():
    def __init__(self):

        print(f'using audio driver {pyglet.media.get_audio_driver()}')
        print(f'pyglet ffmpeg integration: {pyglet.media.have_ffmpeg()}')

        audio_file_path = 'media-resources/licensed-sounds/006224189-organic-whoosh-25.wav'
        source = pyglet.media.load(audio_file_path, streaming=False)
        print(f'media duration (obtained from audio track): {source.duration}')
        self.player = pyglet.media.Player()
        self.player.queue(source)
        self.player.volume = 0.5

        self.last = time.time()

        def update(dt):
            if time.time() - self.last > source.duration + 1:
                print(self.player.playing)
                self.player.seek(0)
                self.player.play()
                print(self.player.playing)
                self.last = time.time()

        def on_eos():
            print('in eos event')
            self.player.queue(source)

        self.player.on_eos = on_eos


        self.update_interval = 1 / 20
        pyglet.clock.schedule_interval(update, self.update_interval)
        pyglet.app.run()

p = PlayDebug()
```

It just goes into recursion in entering `on_eos` , after the first time playing the media. 

Is there a canonical way for this please?

Many thanks!

**Comment by benmoran56** [comment]
The issue may be caused because you're replacing the default eos handler. Instead of replacing it, just push your custom handler.

**Comment by matanster** [comment]
Is there a blueprint?

**Comment by caffeinepills** [comment]
To do an on_eos you would just do 

```py
    def __init__(self):
        self.player = pyglet.media.Player()
        self.player.queue(source)
        self.player.volume = 0.5

        self.last = time.time()
        
        @self.player.event
        def on_eos():
                print("A source was finished playing")```

**Comment by matanster** [comment]
Thank you, that seems to work hooking in an `on_eos` like so. I wouldn't call it re-implementing the Player, but indeed enabling the replay of a sound over and again in a more idiomatic way (and without breaking any already supported player scenario) could be a nice code contribution. 

Or just returning an error on a seek when there the source has finished and gone out of context. 

Hooking into the `eos` is simple enough to solve the scenario, anyway, so thank you.
