### ISSUE TITLE
pyglet.gl.ContextException: Could not create GL context

### ISSUE THREAD

**Issue by SarthakJain333** [pyglet/pyglet#768]
Facing issues while I'm trying to render my open ai gym environment . Googled this error and tried everything available on stackoverflow but nothing worked. Btw I'm on ubuntu.

**Comment by benmoran56** [comment]
Hi, 
We need more information to go on. Please post the output of `python -m pyglet.info`. 

> **System Information:**
Some bugs can be specific to a platform, or related to drivers. To help
us troubleshoot, share the output of the `python -m pyglet.info` command. If this
is not possible, please provide the OS type and release, as well as the type of
GPU (ie. Windows 10, AMD xxxx GPU).

**Comment by benmoran56** [comment]
@threadprogrammer It looks like you don't have any OpenGL drivers installed. 
Check the output of  `glxinfo |grep OpenGL`  to see what the current status is. 
If you don't have glxinfo, it is in the `mesa-utils` package on Ubuntu.

**Comment by threadprogrammer** [comment]
This is the glxinfo OpenGL  output:
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) UHD Graphics 620 (KBL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 22.2.5
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.2.5
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.2.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

**Comment by benmoran56** [comment]
That looks fine actually. 
Try running the hello_world.py example, and post the traceback:
https://github.com/pyglet/pyglet/blob/master/examples/hello_world.py

**Comment by threadprogrammer** [comment]
hello_world.py output:
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
Traceback (most recent call last):
  File "/home/tdeep/anaconda3/envs/rlbook/lib/python3.7/site-packages/pyglet/__init__.py", line 352, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'Window'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hello_world.py", line 3, in <module>
    window = pyglet.window.Window()
  File "/home/tdeep/anaconda3/envs/rlbook/lib/python3.7/site-packages/pyglet/__init__.py", line 358, in __getattr__
    __import__(import_name)
  File "/home/tdeep/anaconda3/envs/rlbook/lib/python3.7/site-packages/pyglet/window/__init__.py", line 1868, in <module>
    gl._create_shadow_window()
  File "/home/tdeep/anaconda3/envs/rlbook/lib/python3.7/site-packages/pyglet/gl/__init__.py", line 209, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/tdeep/anaconda3/envs/rlbook/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py", line 171, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/tdeep/anaconda3/envs/rlbook/lib/python3.7/site-packages/pyglet/window/__init__.py", line 595, in __init__
    context = config.create_context(gl.current_context)
  File "/home/tdeep/anaconda3/envs/rlbook/lib/python3.7/site-packages/pyglet/gl/xlib.py", line 217, in create_context
    return XlibContextARB(self, share)
  File "/home/tdeep/anaconda3/envs/rlbook/lib/python3.7/site-packages/pyglet/gl/xlib.py", line 323, in __init__
    super(XlibContext13, self).__init__(config, share)
  File "/home/tdeep/anaconda3/envs/rlbook/lib/python3.7/site-packages/pyglet/gl/xlib.py", line 231, in __init__
    raise gl.ContextException('Could not create GL context')
pyglet.gl.ContextException: Could not create GL context

**Comment by benmoran56** [comment]
You might find this helpful: 
https://stackoverflow.com/questions/72110384/libgl-error-mesa-loader-failed-to-open-iris

Alternatively, just use Ubuntu's default Python interpreter.

**Comment by threadprogrammer** [comment]
Thanks for your support

**Comment by ClayShoaf** [comment]
I'm also getting this error when trying to run https://github.com/3b1b/manim.
I ran `python -m pyglet.info` and it spit out a lot of `Could not create GL context` errors. I didn't want to paste the whole thing here, because it is very long.
My `glxinfo` gives
```
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Mobile Intel® GM45 Express Chipset (CTG)
OpenGL version string: 2.1 Mesa 23.0.3
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 23.0.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:
```

I will say that when I use `pyglet==1.5` I don't get the `Could not create GL context` error (but it kicks other errors, probably related to missing features in the older version). I am using pyenv and I've tried with 3.8 as well as 3.10

**Comment by benmoran56** [comment]
@ClayShoaf pyglet requires OpenGL 3.3 since v2.0, which may not be supported by your hardware. At the least your drivers are not supporting it.
