### ISSUE TITLE
is there any plan to support OpenGL ES for android/IOS

### ISSUE THREAD

**Issue by tigerking** [pyglet/pyglet#77]
is there any plan to support OpenGL ES for android/IOS

**Comment by benmoran56** [comment]
No plans at the moment, but this could change once pyglet 2.0 is released as we are re-basing the core on OpenGL 3.3+.  OpenGL ES 3.0 would likely be possible, as OpenGL 4.3 is a superset of it.

For mobile platforms, Windowing and input classes would need to be written. I don't think anyone is thinking about that at the moment, but such work would be accepted.

**Comment by benmoran56** [comment]
Closing this for now, but please let me know if you have any other questions.

**Comment by hyuri** [comment]
iOS and Android would be awesome. Any updates on this?

Especially now that the [BeeWare](https://github.com/beeware) folks have been getting iOS and Android as officially supported platforms in CPython.
