### ISSUE TITLE
Working with Shaders part of docs is blank

### ISSUE THREAD

**Issue by raytopianprojects** [pyglet/pyglet#775]
Working with Shaders part of docs is blank. Not sure if this section was meant to be removed or something else.
https://pyglet.readthedocs.io/en/latest/programming_guide/shaders.html

**Comment by benmoran56** [comment]
Thanks for opening the ticket.
It was accidentally included, so i'll remove that. Documentation on Shaders can be found in:
https://pyglet.readthedocs.io/en/latest/programming_guide/graphics.html

**Comment by raytopianprojects** [comment]
Thank you!
