### ISSUE TITLE
glRotatef and glTranslatef migration for pyglet version 2

### ISSUE THREAD

**Issue by curtispuetz** [pyglet/pyglet#776]
I am developing a 3D game with pyglet and based on mouse movement I was using glRotatef to change the direction I was looking, and based on keyboard presses I was changing my player position and using glTranslatef to change that position. I am trying to migrate to pyglet v2, and what I described does work anymore in pyglet v2. I read in your docs that you are instead supposed to modify the 'projection' or 'view' matrices of the window. I can not figure out how to do that however, can you help me?

I had these lines of code in my 'on_draw' method:
```
glRotatef(-rot_x, 1, 0, 0)
glRotatef(-rot_y, 0, 1, 0)
glTranslatef(-x, -y, -z)
```
What would I change these to now in pyglet v2?

**Comment by benmoran56** [comment]
Hi,
Firstly have a quick look at https://pyglet.readthedocs.io/en/latest/programming_guide/migration.html#window-projection-and-cameras.

The big difference is that there is no longer an internal matrix stack that gets manipulated. You need to create your own projection and view matrixes. Setting these matrixes on the Window instance will ensure that they are set for all of pyglet's default objects (sprites, shapes, text).
For a custom 3D engine, you will need to build your own Shaders, and set the  projection and view matrixes on that shader instance. 

The new math.Mat4 type has convenience methods for manipulating matrices in similar ways to the old GL functions. https://pyglet.readthedocs.io/en/latest/modules/math.html
