### ISSUE TITLE
Incomplete Opengl Interface

### ISSUE THREAD

**Issue by iewnfod** [pyglet/pyglet#779]
**Describe the bug**
Some interface in Opengl cannot use in pyglet on my computer. 
Also, I cannot find a pyglet.gl.glu package. 
This is my code: 
```python3
from pyglet.gl import *
glMatrixMode(GL_PROJECTION)
glLoadIdentity()
gluPerspective(65, width / height, 0.1, 60)
glMatrixMode(GL_MODELVIEW)
glLoadIdentity()
```
All of the function I used is not defined when I try to run. 

**System Information:**
* Platform: 2020 Macbook Pro, M1 8 cores, 8G RAM
* System: MacOS Ventura 13.1
* Python Version: Python 3.10
* Pyglet Version: pyglet 2.0.4

**Comment by einarf** [comment]
You should pin your pyglet version to 1.5.x if you want to use the fixed pipeline. Pyglet 2 is using OpenGL 3.3 core were the fixed pipeline no longer exist. We do have a `gl_compat` module exposing functions and enums from a compatibility context, but there are no GLU.

**Comment by iewnfod** [comment]
I can get all functions from ```gl_compat``` now, but ```gluPerspective``` is still missing. I also try to use pyglet 1.5, which contain ```gluPerspective```, but it seems that it does not support python 3.10. It gives out a error:
```
AttributeError: dlsym(0x3e357a420, class_getMethodImplementation_stret): symbol not found. Did you mean: 'class_getMethodImplementation'?
```

**Comment by einarf** [comment]
Yes, there are no GLU in pyglet 2.0. You're not really supposed to mix fixed and programmable pipeline there unless you know exactly the consequences of that. (How to handle bound shaders and vertex arrays to fall back to the fixed pipleine etc)

More info in migration guide if you are planning to jump over to 2.0 later : https://pyglet.readthedocs.io/en/latest/programming_guide/migration.html

For the other error you should probably make a new issue speciying the exact pyglet version, your operating system and sharing the entire stack trace, not just the error itself.

**Comment by einarf** [comment]
Closing this because the lack of activity. Be free to open new issue or comment further on this one (reopen)
