### ISSUE TITLE
Issue with using .dds files which has not power-of-two sides. Scenarios: sprite(2d), sprite_grid(2d), texture(3d), texture_grid(3d)

### ISSUE THREAD

**Issue by Yuriy-Leonov** [pyglet/pyglet#78]
I've updated [repository](https://github.com/Yuriy-Leonov/pyglet_dds_power_of_two) with new description of issue and provided examples.

pyglet version is 1.4.5 

Following text is copied from README in repository:

> There are two files(300px*250px):<br>
> source [example.png](https://github.com/Yuriy-Leonov/pyglet_dds_power_of_two/blob/master/creating_sprites/example.png):
> 
> ![pyglet window](https://github.com/Yuriy-Leonov/pyglet_dds_power_of_two/blob/master/creating_sprites/screenshots/gimp_open_png.png?raw=true)
> 
> and generated [example.dds](https://github.com/Yuriy-Leonov/pyglet_dds_power_of_two/blob/master/creating_sprites/example.dds):
> 
> ![pyglet window](https://github.com/Yuriy-Leonov/pyglet_dds_power_of_two/blob/master/creating_sprites/screenshots/gimp_open_dds.png?raw=true)
> 
> They look similar in GIMP(or other editors) 
> 
> But is they are loaded in pyglet - following picture could be seen([draw_dds_not_power_of_two.py](https://github.com/Yuriy-Leonov/pyglet_dds_power_of_two/blob/master/creating_sprites/draw_dds_not_power_of_two.py)):
> 
> ![pyglet window](https://github.com/Yuriy-Leonov/pyglet_dds_power_of_two/blob/master/creating_sprites/screenshots/pyglet_window.png?raw=true)
> 
> And here is example with using such files in 3d render([draw_3d.py](https://github.com/Yuriy-Leonov/pyglet_dds_power_of_two/blob/master/creating_sprites/draw_3d.py)):
> 
> ![pyglet window](https://github.com/Yuriy-Leonov/pyglet_dds_power_of_two/blob/master/creating_sprites/screenshots/3d_pyglet_window.png?raw=true) 
> 
> Related folder - [creating_sprites](https://github.com/Yuriy-Leonov/pyglet_dds_power_of_two/blob/master/creating_sprites)<br>
> Related files:<br>
> [draw_dds_not_power_of_two.py](https://github.com/Yuriy-Leonov/pyglet_dds_power_of_two/blob/master/creating_sprites/draw_dds_not_power_of_two.py)<br>
> [draw_3d.py](https://github.com/Yuriy-Leonov/pyglet_dds_power_of_two/blob/master/creating_sprites/draw_3d.py)

**It describes 4 scenarios of using:**
- as 2d sprite (low row on 3rd screenshot)
- as 2d sprite grid (up row on 3rd screenshot)
- as texture in 3d (low row on 4th screenshot)
- as texture grid in 3d (up row on 4th screenshot)

**Expected:**
Left and right sides of 3rd and 4th pictures look same :)

PS: I would be glad to provide more details if required.

**Comment by benmoran56** [comment]
Thanks for the detailed examples, and forgive the delay. I'll have a look at this soon.

**Comment by benmoran56** [comment]
I've done some work on this, and think I've figured out the issue. I need a little more time to test, but I may have a fix soon.

**Comment by benmoran56** [comment]
This should be fixed in pyglet-1.4-maintenance. Could you give it a try, and let me know if it works? If so I'll get it into the next release:

```pip install --upgrade --user git+https://github.com/pyglet/pyglet.git@pyglet-1.4-maintenance```

**Comment by Yuriy-Leonov** [comment]
will check this evening

**Comment by Yuriy-Leonov** [comment]
Confirm:

3D
![pyglet window](https://github.com/Yuriy-Leonov/pyglet_dds_power_of_two/blob/master/creating_sprites/screenshots/3d_pyglet_window_solved.png?raw=true)

2D
![pyglet window](https://github.com/Yuriy-Leonov/pyglet_dds_power_of_two/blob/master/creating_sprites/screenshots/pyglet_window_solved.png?raw=true)

Installing:
```
pip install --upgrade  git+https://github.com/pyglet/pyglet.git@pyglet-1.4-maintenanceCollecting git+https://github.com/pyglet/pyglet.git@pyglet-1.4-maintenance
  Cloning https://github.com/pyglet/pyglet.git (to revision pyglet-1.4-maintenance) to /tmp/pip-req-build-8w3hreon
  Running command git clone -q https://github.com/pyglet/pyglet.git /tmp/pip-req-build-8w3hreon
  Running command git checkout -b pyglet-1.4-maintenance --track origin/pyglet-1.4-maintenance
  Switched to a new branch 'pyglet-1.4-maintenance'
  Branch 'pyglet-1.4-maintenance' set up to track remote branch 'pyglet-1.4-maintenance' from 'origin'.
Installing collected packages: pyglet
  Running setup.py install for pyglet ... done
Successfully installed pyglet-1.4.7
```
Contains following commit - https://github.com/pyglet/pyglet/commit/b71ecba0a79bdbdd24bc40d579aa9e30b4c5e64c

Current issue is solved.

@benmoran56 Thank you for such solution.

**Comment by benmoran56** [comment]
Great!
