### ISSUE TITLE
Pyglet with Rust (feature only)

### ISSUE THREAD

**Issue by shenjackyuanjie** [pyglet/pyglet#789]
https://discord.com/channels/438622377094414346/1081040945111367772

check the talk here

I know pyglet is focus on pure Python implement with no requrement

but I'm willing to rewrite some part of it in rust

witch can make pyglet more faster on repeated call
such as `sprite.x` `sprite.y` (they use `@propety`), rust can make them more faster

(also, looks like `proprty.setter` call spend most time when set alot of sprite's position

# about progress
you can check here for some progress

https://github.com/shenjackyuanjie/Difficult-Rocket/tree/main/libs/pyglet_rs

currently, I am working on patching `math.vector`

**Comment by shenjackyuanjie** [comment]
btw  #713  show us why we need to maybe rewrite some part of pyglet by other language

**Comment by benmoran56** [comment]
This kind of idea can be done as a separate module. In the past, there was the Rabbyt module: https://pypi.org/project/Rabbyt/
This was a fast Sprite class replacement, written in C (I could be wrong about this). 
Unfortunately Rabbyt is long unmaintained, but a similar approach is possible.

**Comment by shenjackyuanjie** [comment]
hmmmmmm
yea, just like `pyglet-rs` to improve some part of pyglet
and add some patch to it

**Comment by Cleptomania** [comment]
It may be of interest if anyone starts working on this(and maybe I will at some point in tandem with Arcade). We are building https://github.com/pythonarcdae/arcade-accelerate which is a Rust extension that monkey patches over Arcade functions, you may be able to gather some inspiration from that on how to do the patching as that was a complicated part to figure out.

**Comment by shenjackyuanjie** [comment]
BTW, I'm learning how to write subclass in pyo3, thanks for your example!

**Comment by shenjackyuanjie** [comment]
I think this issue can be closed, after all it's "use less"
