### ISSUE TITLE
Missing GL_SAMPLER_CUBE in _uniform_setters 

### ISSUE THREAD

**Issue by OhGoOnThen** [pyglet/pyglet#791]
Hello all,

I am new to using Pyglet and want to make a skybox. I have working code using PyOpenGL but it does not work under Pyglet.

I am using this fragment shader :

fragment_source = """#version 330 core
    in vec3 vPos;
    out vec4 FragColor;

    uniform samplerCube skybox;

    void main()
    {
        FragColor = texture(skybox, vPos);
    }
"""

vert_shader = Shader(vertex_source, 'vertex')
frag_shader = Shader(fragment_source, 'fragment')
program = ShaderProgram(vert_shader, frag_shader)

The error I am getting is:
    gl_type, gl_setter_legacy, gl_setter_dsa, length, count = _uniform_setters[uniform_type]
KeyError: 35680

the problem is with the key for samplerCube. Digging a bit in the code I found that  in  Pyglet.shader.py  in _uniformsetters the following key is missing: (gl.pyGL# GL enumerant (token) definitions: SAMPLER_CUBE = 35680)

    GL_SAMPLER_CUBE: 

Adding the below to _uniform_setters removes the error:

 GL_SAMPLER_CUBE: (GLint, glUniform1iv, glProgramUniform1iv, 1, 1),

I am not sure about the values as I am just guessing.

Can this key be added? or is there maybe another way to create a skybox under pyglet that I do not know about and the key has been depreciated?

**Comment by einarf** [comment]
https://github.com/pyglet/pyglet/pull/792

**Comment by einarf** [comment]
Merged. Should be in master branch now.

**Comment by OhGoOnThen** [comment]
Great! Thank you!
