### ISSUE TITLE
Request example to place 3D model within 2D interface

### ISSUE THREAD

**Issue by JackDesBwa** [pyglet/pyglet#801]
**Application context:**
I have a 2D interface made of sprites, labels and shapes built with pyglet, in which I would like to insert a 3D model. The interface is already updated with incoming data, and the goal is to rotate the 3D model on itself based on those data too.
I found how to display a 3D model in the `examples/` directory of the repository, and managed to display my own model, but I have trouble to insert it in the existing 2D interface though I only spent little time on it yet. My knowledge about the underlying mechanisms and conventions used in pyglet (how the camera is setup, in which plan objects are inserted, and so on) and about opengl is limited, thus it would help if there existed an example of similar operation.

**Request of examples:**
I think of 3 examples that could help people beyond my own application:
- Insert a 3D model in front of the 2D interface
  → This is my use here, and even two independent renders blended together could be okay
- Insert a 3D model in the depth of the 2D interface
  → If the model can be inserted so that the negative coordinates in depth are hidden by the opaque parts of the 2D interface, and positive coordinates show above, it could lead to interesting interfaces.
  → Of course, the preceding example is not needed if this one applies.
- Insert 2D interface elements in the 3D world
  → In this case, the camera would display a 3D world in which the flat elements already available in pyglet are placed in depth too (z + rotations).
  → In this scenario, it could be interesting to have an example with objects in the 3D space + an overlay in 2D relative to the screen

**PS:** I just saw that there were major changes in the library since last time I used it, and I did not read about them yet, so I hope that this proposition still makes sense.

**Comment by einarf** [comment]
The way you mix 2D and 3D is pretty straight forward. It's all about setting the right projection. You can draw these in any order you like. This is for pyglet 2.0.

2D 

```py
# Setup
window.projection = Mat4.orthogonal_projection(...)
# Draw your 2D stuff here
```

3D 

```py
# setup states
glEnable(CULL_FACE)
glEnable(DEPTH_TEST)
window.projection = perspective_projection(...)

# Draw your 3D stuff here

# cleanup states
glEnable(CULL_FACE)
glEnable(DEPTH_TEST)

**Comment by einarf** [comment]
We also have a discord server linked in the project's readme. It's much easier to ask questions there : https://github.com/pyglet/pyglet

**Comment by JackDesBwa** [comment]
Ok, thanks!

I do not have a discord account, but the little info you gave helped a lot. I was able to insert the 3D model in my interface.

For people who read this issue and need a more structured answer, here is a complete example, using `logo3d.obj` and `box.obj` (and their `*.mtl`) from the [`examples/3dmodel`](https://github.com/pyglet/pyglet/tree/master/examples/3dmodel/) directory, which displays a label on top of the 3D scene:
```
#!/usr/bin/env python3

import pyglet
from pyglet.math import Mat4, Vec3

window = pyglet.window.Window(width=720, height=480, resizable=True)

batch2D = pyglet.graphics.Batch()
label = pyglet.text.Label("--", x=10, y=10, font_size=25, color=(210, 210, 210, 255), anchor_x='left', batch=batch2D)

batch3D = pyglet.graphics.Batch()
model_logo = pyglet.resource.model("logo3d.obj", batch=batch3D)
model_box = pyglet.resource.model("box.obj", batch=batch3D)

time = 0

@window.event
def on_draw():
    window.viewport = (0, 0, *window.get_framebuffer_size())
    window.clear()

    pyglet.gl.glEnable(pyglet.gl.GL_DEPTH_TEST)
    pyglet.gl.glEnable(pyglet.gl.GL_CULL_FACE)
    window.projection = Mat4.perspective_projection(window.aspect_ratio, z_near=0.1, z_far=255)
    batch3D.draw()

    pyglet.gl.glDisable(pyglet.gl.GL_DEPTH_TEST)
    pyglet.gl.glDisable(pyglet.gl.GL_CULL_FACE)
    window.projection = Mat4.orthogonal_projection(0, window.width, 0, window.height, -1, 1)
    batch2D.draw()

def animate(dt):
    global time
    time += dt

    label.text = str(round(time, 2))

    move_origin_mat = Mat4.from_translation(Vec3(0, 0, -5))

    rot_x = Mat4.from_rotation(time, Vec3(1, 0, 0))
    rot_y = Mat4.from_rotation(time/2, Vec3(0, 1, 0))
    rot_z = Mat4.from_rotation(time/3, Vec3(0, 0, 1))
    trans = Mat4.from_translation(Vec3(1.25, 0, 2))
    model_logo.matrix = trans @ rot_x @ rot_y @ rot_z @ move_origin_mat

    rot_x = Mat4.from_rotation(time, Vec3(1, 0, 0))
    rot_y = Mat4.from_rotation(time/3, Vec3(0, 1, 0))
    rot_z = Mat4.from_rotation(time/2, Vec3(0, 0, 1))
    trans = Mat4.from_translation(Vec3(-1.75, 0, 0))
    model_box.matrix = trans @ rot_x @ rot_y @ rot_z @ move_origin_mat

pyglet.clock.schedule_interval(animate, 1/60)
pyglet.app.run()
```

I close the issue because my original problem is solved, but other examples I suggested might be useful nonetheless.
