### ISSUE TITLE
Objects not drawing unless used directly, even when added to a batch 

### ISSUE THREAD

**Issue by ChatBotMatt** [pyglet/pyglet#803]
I'm trying to create some Rectangles and draw them as part of a batch. 

However, this only actually works if if "use" the Rectangle in some way (assigning it to a variable, adding it to a list, etc.) for some reason, even if that list/variable/etc. is completely unused otherwise.

Minimal reproducible example: 
```python
import pyglet

def main()
	window = pyglet.window.Window()
	
	batch = pyglet.graphics.Batch()
	
	do_work = False # Set to True to make it draw properly, False to not. 
	
	for i in range(5):
		if do_work:
			alive_cell = pyglet.shapes.Rectangle(x=50 + i * 30, y=50 + i * 30, width=10, height=10, color=(0, 255, 0), batch=batch)
		else:
			pyglet.shapes.Rectangle(x=50 + i * 30, y=50 + i * 30, width=10, height=10, color=(0, 255, 0), batch=batch)
		
	@window.event
	def on_draw():
		window.clear()
		batch.draw()
		
	pyglet.app.run()

if __name__ == '__main__':
	main()
```

Expected outcome: Regardless of how `do_work` is set, it should draw 5 green rectangles on the screen at different positions (in a diagonal line), when the batch is drawn. 

Actual outcome: This only occurs when they're added to a list (or assigned to a variable, etc.), which can be done by setting `do_work` to True.

**Comment by caffeinepills** [comment]
Objects that are no longer referenced are GCd. When this happens, the objects (in this case Rectangles) are automatically deleted from a batch. This is normal behavior. Add the rectangles to a list that doesn't fall out of scope or store in another location.

**Comment by ChatBotMatt** [comment]
I thought that might be it, but I tried calling `gc.disable()` to disable the garbage collector, and confirmed that it was disabled. The behaviour still happened.

**Comment by caffeinepills** [comment]
It's GC. If you want to stop GC'ing objects you can by overriding the `__del__` behavior.
```py
import pyglet

class NoGCRectangle(pyglet.shapes.Rectangle):
    def __del__(self):
        print("I Was GC'd")
        #if self._vertex_list is not None:
        #    self._vertex_list.delete()

def main():
    window = pyglet.window.Window()

    batch = pyglet.graphics.Batch()

    do_work = False  # Set to True to make it draw properly, False to not.

    for i in range(5):
        if do_work:
            alive_cell = pyglet.shapes.Rectangle(x=50 + i * 30, y=50 + i * 30, width=10, height=10, color=(0, 255, 0),
                                                 batch=batch)
        else:
            NoGCRectangle(x=50 + i * 30, y=50 + i * 30, width=10, height=10, color=(0, 255, 0), batch=batch)

    @window.event
    def on_draw():
        window.clear()
        batch.draw()

    pyglet.app.run()


if __name__ == '__main__':
    main()
    
```

Do this at your own risk otherwise you will have objects you will no longer be able to delete without creating a whole new batch.

**Comment by ChatBotMatt** [comment]
I see, thanks! 

To clarify, is Pyglet doing its own "manual GC" somewhere then?

**Comment by caffeinepills** [comment]
In python you can hook into when the object is deleted by the user or gc with the `__del__` function. In this case we use it to remove from the batch to prevent leaking objects.
