### ISSUE TITLE
Add RGBA support to Caret

### ISSUE THREAD

**Issue by pushfoo** [pyglet/pyglet#805]
**tl;dr the rest of the codebase accepts RGBA, but [Caret hasn't been updated yet](https://github.com/pyglet/pyglet/blob/master/pyglet/text/caret.py)**

Other areas of the codebase (shapes, gui, the rest of text) have been updated to accept `Tuple[int, int, int, int]` for colors. However, `Caret` has not:

https://github.com/pyglet/pyglet/blob/5bc0f80e0446bc4ebb2b381370802f60320c0d8a/pyglet/text/caret.py#L70-L91

If there's no technical reason blocking it, can we add it?

**Comment by benmoran56** [comment]
Sure, that's valid. How about doing it the same way as Shapes, so we can support both RGB and RGBA, not breaking backwards compatibility?
