### ISSUE TITLE
Audio plays loop since update

### ISSUE THREAD

**Issue by moan0s** [pyglet/pyglet#81]
I updated pyglet from version 1.3.2 to version 1.4.5 and tired to execute the following code that is supposed to play a sine wave for 0.5 secondes.
```
import pyglet
from pyglet.media.synthesis import ADSREnvelope, Sine
duration_in_ms:float=500
frequency:int=440
volume=1
adsr = ADSREnvelope(attack=duration_in_ms/8000,
                    decay=duration_in_ms/2000,
                    release=duration_in_ms/8000,
                    sustain_amplitude=volume)
sine = Sine(duration=duration_in_ms/1000, frequency=frequency,
            sample_size=16, sample_rate=44100, envelope=adsr)

player = pyglet.media.Player()
player.queue(sine)
player.play() 
```
When executing this the player plays the sound in a loop (which it should not do as player.loop is false). It is possible to stop the plying with `player.pause()`
The same code in pyglet 1.3.2 (with fixed imports) works fine.
Import for pyglet 1.3.2: `from pyglet.media.sources.procedural import ADSREnvelope, Sine`
Any ideas?

**Comment by benmoran56** [comment]
If you add `pyglet.app.run()` to the end, does it work as expected?

**Comment by GerJuli** [comment]
Yes it does. Why is there a difference?

**Comment by Torxed** [comment]
> Yes it does. Why is there a difference?

`pyglet.app.run()` in short, handles all the event queues and setting up things. It's the main loop that handles all the necessary events in order for audio and video to play.

**Comment by benmoran56** [comment]
In pyglet 1.3 and before, there was a rather ugly background thread being spawned for refilling the Player's buffers.  In an effort to clean up and simplify the codebase, these updates were moved to the main EventLoop. 

In cases where you just want to play a single sound and then exit, you could do something like: 
```py
player.on_eos = pyglet.app.exit

pyglet.app.run()
```
That will cause the "end of source" event to exit the app loop. Would that work for your use case?

**Comment by GerJuli** [comment]
Yes this will work for me, yet it seems more complicated as in the old version where the following worked just fine.
```python3
sound = pyglet.media.load(filepath, streaming=False)
sound.play()
```
The [documentation ](https://pyglet.readthedocs.io/en/stable/modules/media.html#pyglet.media.player.Player.on_eos)for `on_eos()` says that if `loop = False` the next source will be played. Next source will then reset the source to beginning.
I feel like this is not inteded behaviour as `on_eos()` respects the `loop=False flag`, while` next source()` which will be called when` loop=false` ignores it and plays the same sound again if the player is a source.

I reduced the functions to the important parts:
```
def on_eos(self):
        if self.loop:
            was_playing = self._playing
            self.pause()
            self._mclock.reset()

            if self.source:
                # Reset source to the beginning
                self.seek(0.0)
            self._audio_player.clear()
            self._set_playing(was_playing)

        else:
            self.next_source()
```

``` 
def next_source(self):
        """Move immediately to the next source in the current playlist.
        If the playlist is empty, discard it and check if another playlist
        is queued. There may be a gap in playback while the audio buffer
        is refilled.
        """
        was_playing = self._playing
        self.pause()
        self._mclock.reset()

        if self.source:
            # Reset source to the beginning
            self.seek(0.0)
            self.source.is_player_source = False
```

**Comment by agricolab** [comment]
The offending code snippet runs without looping on Linux, even when pyglet 1.4.5 is installed.

**Comment by benmoran56** [comment]
It's possible that it runs on Linux because the particular audio driver buffer size might be bigger (and so the entire sample gets put into the buffer on play), but you can't count on that behavior. Especially for slightly longer samples it probably won't work. 

The reason your example code does not work is because "sound" is a `pyglet.media.Source`, and does not have an `on_eos` event.  Doing `Source.play()` will return a "throwaway" `pyglet.media.Player` instance, which does have the event. This should work: 
```py
sound = pyglet.media.load(filepath, streaming=False)
player = sound.play()
player.on_eos = pyglet.app.exit
pyglet.app.run()
```

**Comment by benmoran56** [comment]
Hi @GerJuli have you had a chance to try that last example?

**Comment by agricolab** [comment]
Hey @benmoran56, thanks for the reply and sorry for the delay. I am working together with @GerJuli on this issue. 

Your solution works, i.e. it ensures that the sound is only played once. Yet, this means that playing sound is now a blocking call, as pyglet.app returns when the sound was played fully. 

For our use case, we require the function starting to play the sound to return immediatly.

Sadly, the pyglet event loop requires the main thread. I tried wrapping the player (i.e. 
```
def thread_play(sound): 
    player = sound.play()
    player.on_eos = pyglet.app.exit
    pyglet.app.run()

t = Thread(target=thread_play, args=(sound, ))
t.start()
```
but it threw (interestingly only during the second execution), the expected ```RuntimeError: EventLoop.run() must be called from the same thread that imports pyglet.app```.

We were trying to find different workaround, but if you have any idea how to play a non-looping, non-blocking sound?

**Comment by agricolab** [comment]
Okay i found a solution that might work for us: 
```
def play_and_stop(sound):
    from threading import Timer
    player = sound.play()
    t = Timer(player.source.duration, player.next_source)
    t.start()

play_and_stop(sound)
```

**Comment by benmoran56** [comment]
Hi @agricolab, @GerJuli, 

Sorry for leaving this hanging for so long. Instead of the full pyglet event loop (app.run),  at a bare minimum you just need to call `pyglet.clock.tick` at a frequent interval. Every 0.2 seconds should be enough. If you are integrating with another another framework's event loop, you can just schedule to tick the pyglet clock in the background. If you are not using any over event loop, you could also make a background thread to tick the clock. Something like this should work: 

```
class Ticker(threading.Thread):
    def __init__(self, delay=0.15):
        threading.Thread.__init__(self)
        self._delay = delay
        self.stopped = threading.Event()
        self.daemon = True
        self.start()

    def run(self):
        while not self.stopped.wait(self._delay):
            pyglet.clock.tick()


ticker = Ticker()
```

You could start that at the top of your program, and then be able to play audio as needed. 
Does that work for you?

**Comment by agricolab** [comment]
Dear @benmoran56, thanks for the advice. Our solution with stopping in the background was also working, and we are currently using that. We will give your solution a try as soon as we can!

**Comment by benmoran56** [comment]
Hi @agricolab, @GerJuli, 

The upcoming pyglet 1.5 release has restored the ability to play back audio without manually ticking the clock. The Player events will not be dispatched, but playback should be fine now. 

If you want to test it out, the `pyglet-1.5-maintenance` branch has the latest code. A release will happen soon.

**Comment by agricolab** [comment]
Dear @benmoran56 finally came around to test it with pyglet 1.5. Works perfectly, allowing me to get rid of the timer hack. Thanks!

**Comment by benmoran56** [comment]
Unfortunately the background update thread had to be rolled back due to some yet unsolved bugs. This was in interest of getting 1.5.0 released, since it was a major cleanup release otherwise. 

For the time being, manually ticking the clock is necessary if you are not running the pyglet event loop.

**Comment by benmoran56** [comment]
Closing this now due to lack of response, but please follow up with a new ticket if needed.
