### ISSUE TITLE
Running "Hello World" under wsl2 returns "AttributeError: partially initialized module 'pyglet' has no attribute 'window'"

### ISSUE THREAD

**Issue by Victornovikov** [pyglet/pyglet#812]
Is there a way to make pyglet work under wsl2

FWIW i can run `glxgears` without any issues.

**Comment by benmoran56** [comment]
I'm not really sure if this is possible or not.
What kind of GL context do you see with `glxinfo |grep OpenGL` ?

Also, can you paste the full traceback?

**Comment by shenjackyuanjie** [comment]
![image](https://user-images.githubusercontent.com/54507071/233080986-fef4fcb3-9e1c-42bf-b297-c738960a4653.png)

hmmm
I can't find GL in my windows10 wsl2

**Comment by Victornovikov** [comment]
```
 $ glxinfo |grep OpenGL

OpenGL vendor string: Microsoft Corporation
OpenGL renderer string: D3D12 (NVIDIA GeForce RTX 3090)
OpenGL core profile version string: 4.2 (Core Profile) Mesa 22.2.5
OpenGL core profile shading language version string: 4.20
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.2 (Compatibility Profile) Mesa 22.2.5
OpenGL shading language version string: 4.20
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 22.2.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:
[1]    10540 segmentation fault  glxinfo |
       10541 done                grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox} OpenGL
```

Here is the traceback

```
Traceback (most recent call last):
  File "/home/vn/marl-interfere/pyglet.py", line 1, in <module>
    import pyglet
  File "/home/vn/marl-interfere/pyglet.py", line 3, in <module>
    window = pyglet.window.Window()
AttributeError: partially initialized module 'pyglet' has no attribute 'window' (most likely due to a circular import)
```


The code I am running:

```
import pyglet
window = pyglet.window.Window()
label = pyglet.text.Label('Hello, world', 
                          font_name='Times New Roman', 
                          font_size=36,
                          x=window.width//2, y=window.height//2,
                          anchor_x='center', anchor_y='center')
@window.event
def on_draw():
    window.clear()
    label.draw()
pyglet.app.run()

```
<img width="500" alt="image" src="https://user-images.githubusercontent.com/9024433/233125013-a141800d-7712-4d24-9f21-8136c571573b.png">

**Comment by shenjackyuanjie** [comment]
> ```
>  $ glxinfo |grep OpenGL
> 
> OpenGL vendor string: Microsoft Corporation
> OpenGL renderer string: D3D12 (NVIDIA GeForce RTX 3090)
> OpenGL core profile version string: 4.2 (Core Profile) Mesa 22.2.5
> OpenGL core profile shading language version string: 4.20
> OpenGL core profile context flags: (none)
> OpenGL core profile profile mask: core profile
> OpenGL core profile extensions:
> OpenGL version string: 4.2 (Compatibility Profile) Mesa 22.2.5
> OpenGL shading language version string: 4.20
> OpenGL context flags: (none)
> OpenGL profile mask: compatibility profile
> OpenGL extensions:
> OpenGL ES profile version string: OpenGL ES 3.1 Mesa 22.2.5
> OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
> OpenGL ES profile extensions:
> [1]    10540 segmentation fault  glxinfo |
>        10541 done                grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox} OpenGL
> ```
> 
> Here is the traceback
> 
> ```
> Traceback (most recent call last):
>   File "/home/vn/marl-interfere/pyglet.py", line 1, in <module>
>     import pyglet
>   File "/home/vn/marl-interfere/pyglet.py", line 3, in <module>
>     window = pyglet.window.Window()
> AttributeError: partially initialized module 'pyglet' has no attribute 'window' (most likely due to a circular import)
> ```
> 
> The code I am running:
> 
> ```
> import pyglet
> window = pyglet.window.Window()
> label = pyglet.text.Label('Hello, world', 
>                           font_name='Times New Roman', 
>                           font_size=36,
>                           x=window.width//2, y=window.height//2,
>                           anchor_x='center', anchor_y='center')
> @window.event
> def on_draw():
>     window.clear()
>     label.draw()
> pyglet.app.run()
> ```
> 
> <img alt="image" width="500" src="https://user-images.githubusercontent.com/9024433/233125013-a141800d-7712-4d24-9f21-8136c571573b.png">

you should rename your python file. the code you write will try to import `pyglet` from `pyglet.py` witch is your code, try to rename it to `pyglet_test.py`

**Comment by Victornovikov** [comment]
🤦🏻‍♂️ 
Yes, now the error makes more sense.

```
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
Traceback (most recent call last):
  File "/home/vn/miniconda3/envs/torch/lib/python3.10/site-packages/pyglet/__init__.py", line 304, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'Window'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vn/marl-interfere/pyg.py", line 3, in <module>
    window = pyglet.window.Window()
  File "/home/vn/miniconda3/envs/torch/lib/python3.10/site-packages/pyglet/__init__.py", line 310, in __getattr__
    __import__(import_name)
  File "/home/vn/miniconda3/envs/torch/lib/python3.10/site-packages/pyglet/window/__init__.py", line 1887, in <module>
    gl._create_shadow_window()
  File "/home/vn/miniconda3/envs/torch/lib/python3.10/site-packages/pyglet/gl/__init__.py", line 165, in _create_shadow_window
    _shadow_window = ShadowWindow()
  File "/home/vn/miniconda3/envs/torch/lib/python3.10/site-packages/pyglet/gl/__init__.py", line 159, in __init__
    super().__init__(width=1, height=1, visible=False)
  File "/home/vn/miniconda3/envs/torch/lib/python3.10/site-packages/pyglet/window/xlib/__init__.py", line 133, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/vn/miniconda3/envs/torch/lib/python3.10/site-packages/pyglet/window/__init__.py", line 538, in __init__
    context = config.create_context(gl.current_context)
  File "/home/vn/miniconda3/envs/torch/lib/python3.10/site-packages/pyglet/gl/xlib.py", line 105, in create_context
    return XlibContext(self, share)
  File "/home/vn/miniconda3/envs/torch/lib/python3.10/site-packages/pyglet/gl/xlib.py", line 127, in __init__
    raise gl.ContextException('Could not create GL context')
pyglet.gl.ContextException: Could not create GL context
```

**Comment by caffeinepills** [comment]
I tested WSL2 with Ubuntu 22.03 on Windows 11 and was able to run without any issues on 2.0.17.

If you still have issues, try with the latest version and open a new case.
