### ISSUE TITLE
Example Game version 4 - multiple keyboard inputs

### ISSUE THREAD

**Issue by Andesouler** [pyglet/pyglet#820]
platform:  Windows-10-10.0.19041-SP0
release:   10
machine:   AMD64
sys.version: 3.9.1 [MSC v.1927 64 bit (AMD64)]
pyglet.version: 2.0.5
pyglet.compat_platform: win32

Hi guys, I'm following the Asteroid game example provided by the pyglet documentation. I followed the guide up to version 4 and I encountered a problem running the application. Bearing in mind that the code can be viewed at the link: https://github.com/pyglet/pyglet/tree/ae8228d56ed6f0855f6280cc44b22d057d92dc4d/examples/game/version4. 
Arrived at version 4. the game involves the rotation and forward thrust of our ship by pressing the relative arrow keys, and the use of the space bar to shoot. I noticed that if you press "Up+Left+Space" at the same time the ship stops firing while if you press "Up+Right+Space" the ship performs all three inputs.
does anyone know what inhibits the space bar?

Alternatively, I attach my version with the same functionality as the game code.
[example.game.version4.zip](https://github.com/pyglet/pyglet/files/11377464/example.game.version4.zip)

**Comment by benmoran56** [comment]
This is likely just an issue with key rollover on your keyboard. Switching to WASD should fix it.
You can also try this online test to confirm:
https://www.mechanical-keyboard.org/key-rollover-test/

**Comment by benmoran56** [comment]
Great, I thought that might be it.
