### ISSUE TITLE
Docs: TextLayout.content_width doesn't show up in search

### ISSUE THREAD

**Issue by encukou** [pyglet/pyglet#824]
**Describe the bug**
When [searching the docs for content_width](https://pyglet.readthedocs.io/en/latest/search.html?q=content_width), `TextLayout.content_width` doesn't show up.
It's documented [with the class](https://pyglet.readthedocs.io/en/latest/modules/text/layout.html?highlight=content_width#pyglet.text.layout.TextLayout) under “Ivariables”.

It might be good to link to these from `width`, `height` and [the guide](https://pyglet.readthedocs.io/en/latest/programming_guide/text.html) to make them more discoverable.

**System Information:**
N/A

**How To Reproduce**
Search docs for content_width.

**Comment by caffeinepills** [comment]
Closing, this is in the docs now and clarified from width and height. From 2f52052
