### ISSUE TITLE
Screenshot flipped in v1.4

### ISSUE THREAD

**Issue by donkirkby** [pyglet/pyglet#83]
Thanks for publishing Pyglet. We recently added support for it to the [Live Coding in Python] project, but your 1.4 releases have broken that support.

We followed an example from the [docs] to save a screenshot, but after upgrading to Pyglet 1.4, the images are vertically flipped.

Here's a minimal code example to reproduce the problem:

    import pyglet
    
    window = pyglet.window.Window()
    label = pyglet.text.Label(f'Pyglet v{pyglet.version}', y=10)
    
    @window.event
    def on_draw():
        window.clear()
        label.draw()
        pyglet.image.get_buffer_manager().get_color_buffer().save('screenshot.png')
        pyglet.app.exit()
    
    pyglet.app.run()
    print('Done.')

Here are the screenshots from before and after the upgrade to Pyglet 1.4:

![screenshot v1.3.2]
![screenshot v1.4.0]

Is this a bug? Is there a better way to save a screenshot? Is there a workaround where I can manually flip the image?

I tried this workaround, but it made no difference.

    import pyglet
    
    window = pyglet.window.Window()
    label = pyglet.text.Label(f'Pyglet v{pyglet.version}', y=10)
    
    @window.event
    def on_draw():
        window.clear()
        label.draw()
        buf = pyglet.image.get_buffer_manager().get_color_buffer()
        texture = buf.get_texture()
        flipped = texture.get_transform(flip_y=True)
        flipped.save('screenshot.png')
        pyglet.app.exit()
    
    pyglet.app.run()
    print('Done.')

[Live Coding in Python]: https://github.com/donkirkby/live-py-plugin/issues/222
[docs]: https://pyglet.readthedocs.io/en/stable/programming_guide/image.html#saving-an-image
[screenshot v1.3.2]: https://user-images.githubusercontent.com/1639148/67163706-1dc16b00-f327-11e9-8109-0919569e2b08.png
[screenshot v1.4.0]: https://user-images.githubusercontent.com/1639148/67163698-f9658e80-f326-11e9-8054-7b6de169a55c.png

**Comment by benmoran56** [comment]
Looks like a bug. I'll have a look.

**Comment by benmoran56** [comment]
Hi @donkirkby, it looks like this was indeed a bug, and it been fixed in the `pyglet-1.4-maintenance` branch. If you like, you can install that branch directly via: 
`pip install --upgrade --user git+https://github.com/pyglet/pyglet.git@pyglet-1.4-maintenance`

I'll see about pushing out a new release in the coming days, after which you can just do a:
`pip install --upgrade --user pyglet` to pull down the new release from PyPi.

**Comment by benmoran56** [comment]
I went ahead and pushed out the 1.4.6 release, so you can update via pip. Please let me know if you still have issues.

**Comment by donkirkby** [comment]
It works now, thanks for the amazing 10 hour turn around!
