### ISSUE TITLE
1.3->1.4 class event handler lifespan change

### ISSUE THREAD

**Issue by xantares** [pyglet/pyglet#84]
I'm trying to upgrade an application from pyglet 1.3 to 1.4 (https://github.com/samcv/brainworkshop/issues/15),
an I've got a different behavior for event handler that are tied to a class:
now with 1.4 the class that holds the event handler is destroyed.

I made a minimal script to show this:
- with 1.3 the Menu class is not destroyed until the app closes, and keyboard events are caught
- with 1.4 the Menu class is destroyed right on start, so no keyboard event are caught
```
import pyglet

window = pyglet.window.Window(width=640, height=480)

class Menu:
    def __del__(self):
        print('Menu.del')
    def __init__(self):
        window.push_handlers(self.on_key_press)
    def on_key_press(self, key, mod):
        print("Key Pressed")
        return pyglet.event.EVENT_HANDLED

Menu()
pyglet.app.run()
```

Is this an intentional change ? Or does my app rely on undefined behavior ?

**Comment by ccanepa** [comment]
Not a pyglet developer, but I think is an intentional change, see issue #43 

If you are going from 1.3 to 1.4 you may need to fix some other things, see
https://github.com/pyglet/pyglet/blob/master/RELEASE_NOTES#L76
and
https://github.com/los-cocos/cocos/blob/master/docgen/compatibility_notes.txt#L18

**Comment by benmoran56** [comment]
Thanks Claudio.

Yes, the big change is that the event system now only holds weak references to handlers. https://docs.python.org/3.5/library/weakref.html
This was a necessary change to avoid garbage collection issues with deleted objects. 

All you should need to do is keep a reference to the objects. In your code, try doing `menu = Menu()`.  This will create a reference, and prevent your instance from falling out of scope.

**Comment by xantares** [comment]
thanks!
