### ISSUE TITLE
Clock swallows legitimate `ReferenceError` from consumer code

### ISSUE THREAD

**Issue by cspotcode** [pyglet/pyglet#854]
**Describe the bug**

Pyglet's clock swallows legitimate errors raised by user code.  It should instead allow those errors to surface just like most other errors.

https://github.com/pyglet/pyglet/blob/2881781dcc751e1674f4306e1cde67871a3e09d6/pyglet/clock.py#L225-L229

```python
import weakref
import pyglet

class Empty:
    pass

class App(pyglet.window.Window):
    def on_draw(self):
        print('tick')
        a = Empty()
        b = weakref.proxy(a)
        b.foo = 123
        a = None
        b.bar = 123
        print('why is this silently skipped?')

app = App()
pyglet.app.run()
```

In this contrived example, a legitimate logic error causes `b.bar` to fail.  But pyglet swallows this error, silently skipping the second print statement.

Output:
```
> python ./reproduction.py
tick
tick
tick
tick
tick
```
...

**System Information:**

pyglet 2.0.7

**How To Reproduce**
A small code example that illustrates the bug is very useful to help triage.

Code example above.

**Comment by benmoran56** [comment]
This was part of a weakref experiment that was later rolled back. Will be fixed in the next point release. 
Thanks for the ticket.
