### ISSUE TITLE
Controller events not creating shapes

### ISSUE THREAD

**Issue by DeeplyBrinedCode** [pyglet/pyglet#870]
**Describe the bug**
I am making a small game, and I have a line of code set up to create an object when a button is pressed. The object is fairly simple, as it really just consists of an image created via pyglet.shapes.Rectangle(). I then add that object to a list and draw all objects in the list. The problem is that for some reason when I try to define a shape with this method, I get **AttributeError: 'VertexDomain' object has no attribute 'attributes'**. This works totally fine with on_key_press for my keyboard, but copy-pasting the same exact code onto a controller function it doesn't work.

**System Information:**
I am running the code on windows 11 on a laptop running a AMD Ryzen 7 4800H processor. My OS is 22621.1413. I'm using a blue tooth x-box controller, although the problem persists when I plug it into my laptop 

**How To Reproduce**
```
import pyglet
from pyglet import input
from pyglet.window import key

# define window and controllers
window = pyglet.window.Window()
controller_manager = pyglet.input.ControllerManager()
controllers = controller_manager.get_controllers()
if controllers:
    controller = controllers[0]
controller.open()

# create batch and list for shapes
shape_batch = pyglet.graphics.Batch()
shapes = []


# if you press A on the keyboard, the code works just fine
@window.event
def on_key_press(symbol, modifier):
    if symbol == key.A:
        shape = pyglet.shapes.Rectangle(0, 0, 100, 100, [200, 200, 200], batch=shape_batch)
        shapes.append(shape)


# if you press A on the controller however, you get a litany of errors
@controller.event
def on_button_press(controller, button):
    if button == 'a':
        shape = pyglet.shapes.Rectangle(0, 0, 100, 100, [200, 200, 200], batch=shape_batch)
        shapes.append(shape)


# draw shapes
@window.event
def on_draw():
    window.clear()
    shape_batch.draw()


pyglet.app.run()


```

**Comment by benmoran56** [comment]
This doesn't produce any error on my machine.
Which pyglet release are you using? You can paste the output of `python -m pyglet.info`

**Comment by benmoran56** [comment]
Actually I was able to reproduce it on my Windows VM. 
PS4 Controller (DirectInput), no issue. 
Xbox 360 Controller (Xinput), issues.
