### ISSUE TITLE
remove float()

### ISSUE THREAD

**Issue by gran4** [pyglet/pyglet#871]
**Describe the bug**
Please provide a clear and concise description of what the bug is. 
What is happening, and what do you expect to happen. 

look at things like line 142 in atlas.py
`return 1.0 - self.used_area / float(possible_area)`

why do we have to do `float(possible_area)`?
It turns into a float anyways

**Comment by shenjackyuanjie** [comment]
it's now fixed
so closed it pls~ @gran4

**Comment by gran4** [comment]
ok
