### ISSUE TITLE
anchor position of sprite

### ISSUE THREAD

**Issue by jason-bowen-zheng** [pyglet/pyglet#876]
I have found that the following code works well in pyglet 1.5.x:
```python
# put the sprite in the center of window
sprite = Sprite(image.load(...), x=width // 2, y=height // 2)
sprite.image.anchor_x = sprite.image.width // 2
sprite.image.anchor_y = sprite.image.height // 2
```
but in pyglet 2.0.7, we should type this:
```python
the_image = image.load(...)
the_image.anchor_x = the_image.width // 2
the_image.anchor_y = the_image.height // 2
sprite = Sprite(the_image, x=width // 2, y=height // 2)
```

This is the solution:
```python
@position.setter
def position(self, position):
    self._x, self._y, self._z = position
    self._vertex_list.translate[:] = position * 4 # turn this line
    self._update_position() # to this line
```

**Comment by caffeinepills** [comment]
The proper solution to this is to re-set the image after changing the image properties.
```py
sprite = Sprite(image.load(...), x=width // 2, y=height // 2)
image.anchor_x = image.width // 2
image.anchor_y = image.height // 2
sprite.image = image
```

**Comment by romikforest** [comment]
Seems like it's impossible to change an anchor point after the sprite creation for 2.x versions. Pyglet always animate around the anchor point that the image had before the sprite creation.

**Comment by romikforest** [comment]
Maybe it's important: I use headless mode. I can set anchor point values and they print out correctly, but the real animation ignores them.

**Comment by benmoran56** [comment]
After changing the anchor points, did you re-assign the image to the Sprite, like `caffeinepills` posted above?

**Comment by romikforest** [comment]
I tried it in different ways. I also tried reassign. And I tried changing anchor point on image.sprite and image._texture. In all cases, I can print the updated values using python `print`. But the animation itself ignores them.
