### ISSUE TITLE
multiple window applications

### ISSUE THREAD

**Issue by matanox** [pyglet/pyglet#893]
Hi and thank you for pyglet!

I am looking at the [simple code example](https://github.com/pyglet/pyglet/blob/master/examples/window/multiple_windows.py) for managing multiple windows, where I think no `on_update` dispatch interval is explicitly involved. 

Assume your application updates on interval, since it needs to respond to streaming data. So you may have one update callback registered, a la:

```
pyglet.clock.schedule_interval(my_update_callback, some_update_interval)
```

As much as I recall this callback scheduling is typically in all examples registering a window's update callback, not just any function, but I can't recall or be sure whether a window's `on_update` is also called in additional circumstances, which becomes more crucial as my application's scope evolves from a single to multi-window application, so I'm happy for feedback about that, about whether or not a window's `on_update` is also called in other cases.

Now assume you wanted to update the state of all pyglet windows upon an update to one of them. E.g. you're not an application enabling opening multiple documents each living in isolation kind of application, but rather an application where some windows have to immediately reflect aspects of the state of one of the windows. 

My current implementation for this scenario processes state for all windows through a single window's `on_update`, and I also draw for all windows from that same window's `on_draw`. This is all reliant on the use of `.switch_to()` for switching the drawing context among the windows before drawing or bliting. This seems to work well under _initial testing on a single machine_. 

But I'm happy to have your comments.

And sorry for the edits.

Kindly,
Matan

**Comment by matanster** [comment]
A small side comment ― given the [current implementation regarding `on_draw`](https://groups.google.com/g/pyglet-users/c/wyWCzLYgL1w), if correct, it becomes a little harder to reason about this at present; the callback for `on_draw` will continuously fire ― masking incorrect code patterns that would otherwise fail if or when `on_draw` being called at the screen refresh rate becomes only an option. 

So just happy to have your comments.

**Comment by benmoran56** [comment]
Hi, thanks for opening the ticket.
The current implementation is a stopgap solution, as in previous releases the windows would redraw on any scheduled event or platform event (anything that woke the clock). This meant things like moving the mouse or analog stick would cause the framerate to fluctuate, and made it difficult to schedule multiple things on the clock at different rates. 

The current plan for pyglet 2.1 is to make it more explicit.
Some of this work is already in the master branch (undocumented), so you can try it out:

1. Pass `None` to `pyglet.app.run(None)`, and it will not internally schedule window draws. 
2. Create `on_draw` handlers as usual.
3. Call `Window.draw(dt)` manually whenever you need, or, schedule window redraws on the clock: `clock.schedule_interval(my_window.draw, 1/120)`

**Comment by matanster** [comment]
Really huge thanks for writing in. I have already accomplished phenomenal things with pyglet. I guess that providing more elastic behaviors like you mention requires a lot of thought and careful delineation, perhaps in particular among the desire of some users to have a constant frame rate (is that what's implied in your comments) perhaps in the gaming target domain, v.s. other users that build graphical applications where that is a much much lesser concern v.s. perhaps CPU utilization. 

I would imagine that looking at other game, animation and graphics platforms may reveal some patterns that tend to work to avoid the issue with frame rate fluctuation vis-a-vis mouse movement and the need to redraw (is there any other way to cope with the mouse pointer changing pixels other than redrawing on the engine side?)

**Comment by matanster** [comment]
Either way I think it will be important to put a large notice about these changes on the release where they are being introduced! it's anyone's choice when to upgrade so no issues with changes requiring changes to already written applications, especially if it's for better ways of implementation of pyglet applications.

**Comment by matanster** [comment]
Just about these 3 items, 

> 1. Pass `None` to `pyglet.app.run(None)`, and it will not internally schedule window draws.
> 2. Create `on_draw` handlers as usual.
> 3. Call `Window.draw(dt)` manually whenever you need, or, schedule window redraws on the clock: `clock.schedule_interval(my_window.draw, 1/120)`

- Is item (1) meant as the way for avoiding a constant frame rate redraw as we have now? 
- Would item (3) mean that your window will not be redrawn if it has become partially hidden by another window and then re-exposed? or is that implicitly taken care of without having to use a user level `on_draw`?

**Comment by benmoran56** [comment]
1. Yes. You can see the existing code here, which shows exactly what's happening: https://github.com/pyglet/pyglet/blob/master/pyglet/app/base.py#L114

3. If you plan to redraw your Windows manually, It might be necessary to use the Window `on_expose` event to handle such cases. It will let you know when the contents of the Window may have been invalidated. I'm not sure if this is necessary on all platforms, but it's probably a safe bet.

**Comment by matanox** [comment]
Thanks again
