### ISSUE TITLE
Rendering texts by using images

### ISSUE THREAD

**Issue by zhengxyz123** [pyglet/pyglet#896]
I want to create a class like `UserDefinedFont` to render texts by using images.

But the different point is that there are 255 images (assume `unicode_00.png` through `unicode_ff.png`) and every image provide 16x16 characters.

Are there some efficient ways to draw texts?

By the way, if I change `texture_mag_filter` to `GL_NEAREST`, are there some affects?

**Comment by caffeinepills** [comment]
You can do so with `pyglet.font.create_font`.

```py
mapping = {
    '0': grid[(10, 0)],
    ' ': grid[(11, 0)],
    ...
}

font = pyglet.font.create_font("CustomOne", mapping, default_char=" ")

label = pyglet.text.Label("Hello World!", font_name="CustomOne")
```

**Comment by jason-bowen-zheng** [comment]
Thank you, but, there are more than one images used(actually there are 255 images for all unicode characters).

**Comment by benmoran56** [comment]
You don't have to use ImageGrid. You can just use any ImageData object. (ImageGrid is just easy if the characters are all on a single monospace image). 

`mapping` is just a dictionary of `char: image`, so you can just use  `pyglet.resource.image` to load the individual characters. 
For example: 
```py

mapping = {}

for character in "abcdefg":
    mapping[character] = pyglet.resource.image(f"{character}.png").get_image_data()
```

**Comment by jason-bowen-zheng** [comment]
I think you misunderstood my meanings.

There are several images:
![unicode_page_00](https://github.com/pyglet/pyglet/assets/58848782/71135e30-0b07-415f-a5a5-f192cd21df33)
![unicode_page_4f](https://github.com/pyglet/pyglet/assets/58848782/3a0770d6-60d1-468b-a7cc-14a7bce98c8e)

Which have totally `16*16*256=65536` characters in 256 images.

Briefly, My question is: how to draw these 65536 characters efficiently? Using `create_font` isn't a wise decision.

It seems that `create_font` can only draw texts in the same font size. What should I do if I want to draw texts in different sizes?

**Comment by caffeinepills** [comment]
That's beyond the scope of what `create _font` does. If you want font features and everything related to a font, you will have to put your images in a third party font creation utility and turn it into a font file and load it as a custom font.

**Comment by jason-bowen-zheng** [comment]
I have made a [demo](https://github.com/minecraft-py/minecraft/blob/master/minecraft/gui/font.py) using `create_font`, which is complicated.

So, I think, can we change the way `create_font` acts:
```python
def get_texture(c):
    ...
    return texture_of_characters

create_font(name="foo", search_texture=get_texture)
```
`get_texture` takes a character as input and return its texture.

Besides, the font created by `create_font` can't change its font size. If it is feasible, how should it be implemented?

**Comment by caffeinepills** [comment]
While your demo is a way to make it work, pyglet out of the box doesn't have external dependencies, so we can't include a feature only supported by Pillow.

**Comment by caffeinepills** [comment]
Maybe it could be useful as an example? Although we don't have external dependencies, after thinking about it, we do have some features gated behind another library, for instance video requires ffmpeg.

I'm not sure where to draw the line here, but maybe your demo as an example could be useful? What is your stance on it @benmoran56

**Comment by benmoran56** [comment]
It could be useful as an example.

**Comment by jason-bowen-zheng** [comment]
@benmoran56 I have another way to display **all** unicode characters without dict which was mentioned in this issue.

So my plan is: I will open a PR about new `create_font` and write an example.

**Comment by caffeinepills** [comment]
Behavior added in https://github.com/pyglet/pyglet/pull/1067 part of v2.0.14. Example will come later.
