### ISSUE TITLE
`pyglet.clock.schedule` runs every tick, not every frame

### ISSUE THREAD

**Issue by matenestor** [pyglet/pyglet#897]
I have a question about possible bug or a miscommunication in the documentation. There is probably something wrong with scheduling, or am I doing something wrong?

According to the docs, the function [`pyglet.clock.schedule`](https://pyglet.readthedocs.io/en/latest/modules/clock.html#pyglet.clock.Clock.schedule) should run every frame. But later it says, that the `dt` argument gives "elapsed time, in seconds, since the **last clock tick**". That is confusing, because that time is different from the time since the last frame.

> schedule(func, *args, **kwargs) 
>
> Schedule a function to be called **every frame**.
>
> The function should have a prototype that includes dt as the first argument, which gives the elapsed time, in seconds, since the **last clock tick**. Any additional arguments given to this function are passed on to the callback:
> ...
> Parameters: func : callable
>     The function to call **each frame**.

I have the following code below. I schedule my update function `change_color` to change a rectangle color with `pyglet.clock.schedule` and I expect the rectangle to smoothly change color through a color wheel. But instead the color starts flashing, because it is being changed too fast.

After looking at the output of `dt` times it is clear that the function is not run every frame, but it seems like every tick. Otherwise there would be times around 0.016 s, because the FPS is set to 60, and not:

```text
2.003205008804798e-05 s
1.972599420696497e-05 s
1.968804281204939e-05 s
...
```

The code:

```python
from colorsys import hls_to_rgb

import pyglet


def hsl_to_pyglet(hue, saturation=100, lightness=50, alpha=255):
    r, g, b = hls_to_rgb(hue / 360, lightness / 100, saturation / 100)
    return int(r*255), int(g*255), int(b*255), alpha


FPS = 1/60
window = pyglet.window.Window()
fps_display = pyglet.window.FPSDisplay(window, hsl_to_pyglet(0, 0, 80))

SIZE = 100
color = 0
rect = pyglet.shapes.Rectangle(
    window.width // 2 - SIZE // 2, window.height // 2 - SIZE // 2,
    SIZE, SIZE,
    hsl_to_pyglet(color)
)


def change_color(dt):
    global color

    print(dt, "s")

    color += 1
    if color == 361:
        color = 0
    rect.color = hsl_to_pyglet(color)


@window.event
def on_draw():
    window.clear()
    rect.draw()
    fps_display.draw()


if __name__ == '__main__':
    # behavior as expected, since it really changes color every frame
    # pyglet.clock.schedule_interval(change_color, FPS)

    # changes color every tick
    pyglet.clock.schedule(change_color)

    pyglet.app.run(FPS)

```

**Comment by benmoran56** [comment]
Thanks for opening the ticket. This wording was left over from when schedules were framerate limited.
As you noticed, `schedule` is not framerate bound, and will essentially be called as fast as possible. I will make a quick update to the docstring to fix the wording. 

clock.schedule is usually only useful for benchmarking, if your application is otherwise limited (GPU bound, etc.), or you are using a custom Clock.

**Comment by benmoran56** [comment]
New docs are now available on ReadTheDocs, so closing this ticket. 
If you still have further questions or issues, please feel free to reopen it or comment.
