### ISSUE TITLE
NotImplementedError: abstract - Problem with conda and other IDEs

### ISSUE THREAD

**Issue by olehermanse** [pyglet/pyglet#9]
When generating documentation, pyglet sets `sys.is_epydoc` to `True`. Classes like window check this variable, to see if it's a "real" run, or just documentation generation. This turns out to be problematic since some IDEs also set this variable to `True` as well.

**Related tickets:** [bitbucket #163](https://bitbucket.org/pyglet/pyglet/issues/163/remove-is_epydoc-checks) [bitbucket #172](https://bitbucket.org/pyglet/pyglet/issues/172/macos-notimplementederror-abstract)

**Example:**

```python3
#!/usr/bin/env python
import sys
sys.is_epydoc = True  # Simulate what some IDEs do
import pyglet

window = pyglet.window.Window()
label = pyglet.text.Label('Hello, world!',
                          font_name='Arial',
                          font_size=36,
                          x=window.width // 2,
                          y=window.height // 2,
                          anchor_x='center',
                          anchor_y='center')


@window.event
def on_draw():
    window.clear()
    label.draw()


pyglet.app.run()
```

**Output:**

```bash
$ python3 examples/hello_world.py 
Traceback (most recent call last):
  File "examples/hello_world.py", line 6, in <module>
    window = pyglet.window.Window()
  File "/usr/local/lib/python3.7/site-packages/pyglet/window/__init__.py", line 577, in __init__
    screen = display.get_default_screen()
  File "/usr/local/lib/python3.7/site-packages/pyglet/canvas/base.py", line 109, in get_default_screen
    return self.get_screens()[0]
  File "/usr/local/lib/python3.7/site-packages/pyglet/canvas/base.py", line 101, in get_screens
    raise NotImplementedError('abstract')
NotImplementedError: abstract
```

**Comment by einarf** [comment]
Could switch over using an environment variable. Worked pretty well for me at least.

**Comment by benmoran56** [comment]
I wonder if all of this stuff is necessary anymore. Would the "autodoc_inherit_docstrings" option (which is now default) do what we want? I'll have to try that.

**Comment by olehermanse** [comment]
@einarf @benmoran56 Maybe I don't understand the problem well enough, but couldn't we just inject a variable with another more specific name? Like `sys.is_pyglet_doc_run = True`. Then just check using `if hasattr(sys, "is_pyglet_doc_run") and sys.is_pyglet_doc_run:` ?

**Comment by benmoran56** [comment]
What I mean is that in the codebase, we have "if _is_epydoc:" checks in many places. Some docstrings are only defined in the case of a documentation build. Instead of that,  maybe we can just put those docstrings and methods on the base classes themselves. Then, using the right Sphinx options (autodoc_inherit_docstrings?),  we can avoid having special definitions *just for* docs. 

In the mean time, I just changed the name as you suggested :)

**Comment by olehermanse** [comment]
> Some docstrings are only defined in the case of a documentation build. 

@benmoran56 Why?

**Comment by benmoran56** [comment]
@olehermanse this was done to prevent platform specific subclasses from being documented.
