### ISSUE TITLE
GpuMat or Pytorch tensor to pyglet

### ISSUE THREAD

**Issue by Sash0check** [pyglet/pyglet#901]
Hello, can i display cv2 gpumat or pytorch tensor in pyglet window without transfering texture to cpu?

**Comment by benmoran56** [comment]
pyglet windows are just OpenGL contexts, so a texture is required to display. What you can do is create a single texture that gets drawn every frame. You then make an `ImageData` object from your raw bytes, and update the texture with it wherever necessary.

**Comment by benmoran56** [comment]
Closing this for now, but please follow up if you have any additional questions.
