### ISSUE TITLE
`on_mouse_scroll` uses wrong parameters

### ISSUE THREAD

**Issue by jason-bowen-zheng** [pyglet/pyglet#904]
The [Frame](https://github.com/pyglet/pyglet/blob/193b8639b677cabad691516b059ef1f23f3adf0c/pyglet/gui/frame.py#L71) and [WidgetBase](https://github.com/pyglet/pyglet/blob/193b8639b677cabad691516b059ef1f23f3adf0c/pyglet/gui/widgets.py#L125)(and one widget) use the wrong parameters compared to [Window](https://github.com/pyglet/pyglet/blob/193b8639b677cabad691516b059ef1f23f3adf0c/pyglet/window/__init__.py#L1580).

The first two must act like the window, so they should use
```python
def on_mouse_scroll(self, x, y, scroll_x, scroll_y):
    ...
```

**Comment by benmoran56** [comment]
That's a good catch. Thanks for opening the issue.

**Comment by benmoran56** [comment]
Fixed in master.
