### ISSUE TITLE
Jetson TX2?

### ISSUE THREAD

**Issue by darioringach** [pyglet/pyglet#93]
Is it possible to install pyglet on Jetson TX2 dev kit?
--
Dario

**Comment by benmoran56** [comment]
Hi Dario,
I can't confirm without hardware, but it may work. pyglet uses full desktop OpenGL (not ES), and Nvidea does list modern OpenGL support on it's page.  The current stable release of pyglet uses OpenGL 2.0 features. *If* the Jetson drivers also support this, it will work. If they support only OpenGL 4.x, then the upcoming pyglet v2.0 release is necessary, as pyglet is moving to support OpenGL 3.3+.  That release is not yet ready, but work is progressing.

**Comment by benmoran56** [comment]
If you have any more questions feel free to ask. I'll close this for now.
