### ISSUE TITLE
Win32ARBContext uses WGL_DEBUG_BIT_ARB instead of WGL_CONTEXT_DEBUG_BIT_ARB as debug flag 

### ISSUE THREAD

**Issue by yonibr** [pyglet/pyglet#945]
See: https://github.com/pyglet/pyglet/blob/66466f80cb9b2437971851bbaf0a997faf7343bb/pyglet/gl/win32.py#L247

**Comment by caffeinepills** [comment]
Thanks, sorry for the delay. It's been put in master and will be fixed next version.
