### ISSUE TITLE
Bug: Caret no longer visible in interactive tests

### ISSUE THREAD

**Issue by pushfoo** [pyglet/pyglet#948]
### Summary

The tests in https://github.com/pyglet/pyglet/pull/826 worked when they were initially implemented. At some point since, the caret stopped being visible in them.

Reverting to the commit for that PR restores visibility. The caret is also still visible in the examples below, even on recent commits:

* [examples/gui/widgets.py](https://github.com/pyglet/pyglet/blob/master/examples/gui/widgets.py)
* [examples/text/text_input.py](https://github.com/pyglet/pyglet/blob/master/examples/text/text_input.py)

End-users might not be directly affected. This issue was discovered while working on #943.

### System Information

[Output of `python -m pyglet.info` as a gist](https://gist.github.com/pushfoo/32d76300efc8edd861cea13660b445bf)

### Steps to Reproduce

1. Be on a recent commit (commit introduced unknown)
2. Run `pytest tests/interactive/text/test_caret_color.py`
3. Step through each test

**Comment by shenjackyuanjie** [comment]
weird
on your PR at remote(the cmd+a shortcut)
I still can see Caret

**Comment by pushfoo** [comment]
> I still can see Caret

Specifically when running the interactive tests?

**Comment by shenjackyuanjie** [comment]
I do can on your PR/master
on both Windows/WSL or Mac

**Comment by pushfoo** [comment]
This may be a Linux, GPU, or driver specific issue then. Thank you for investigating.

**Comment by shenjackyuanjie** [comment]
hmmmm
wait. I mean I can see it inside a TextEntry(
![image](https://github.com/pyglet/pyglet/assets/54507071/3b273559-56ff-4608-ba1a-91bfa1ae9cb7)

this is what happened when I try to run the test

**Comment by shenjackyuanjie** [comment]
![image](https://github.com/pyglet/pyglet/assets/54507071/4cfc4a35-f2c1-4e89-99c0-ce79a1d8f901)
My bad

![image](https://github.com/pyglet/pyglet/assets/54507071/b6e1ece2-5086-44ce-8634-162849853167)

no caret at all

**Comment by pushfoo** [comment]
This appears to be fixed on Linux by https://github.com/pyglet/pyglet/pull/971.

@shenjackyuanjie Can you confirm for Windows or Mac?

**Comment by shenjackyuanjie** [comment]
in coming

**Comment by shenjackyuanjie** [comment]
## Windows
- platform win32 -- Python 3.8.18+, pytest-7.4.2, pluggy-1.0.0
- platform win32 -- Python 3.10.11, pytest-7.4.2, pluggy-1.0.0
- platform win32 -- Python 3.11.4, pytest-7.4.2, pluggy-1.3.0
- platform win32 -- Python 3.12.0, pytest-7.4.2, pluggy-1.3.0

Test passed

**Comment by shenjackyuanjie** [comment]
![image](https://github.com/pyglet/pyglet/assets/54507071/6e1d0d8e-047d-4a43-b226-72d3926b40c3)

## notice

when I use the caret
I can spotted that the last word "window" is hidden

**Comment by pushfoo** [comment]
Can you provide precise replication steps? I can't get it to do that on my system.

**Comment by shenjackyuanjie** [comment]
> Can you provide precise replication steps? I can't get it to do that on my system

Fixed ~

**Comment by shenjackyuanjie** [comment]
I think we can close this now
