### ISSUE TITLE
Python 3.12 needs thorough testing

### ISSUE THREAD

**Issue by benmoran56** [pyglet/pyglet#961]
Hi everyone, 

Python 3.12 has just been released and, as with all major versions releases, there are potentials for bugs and regressions. 
https://www.python.org/downloads/release/python-3120/

There are no known compatibility issues (due to deprecated APIs, etc.), but nevertheless it's a good idea to get some feedback with real world use cases.

If you are able to test Python 3.12.0 with your project, please report back your results (and your OS details).
Useful feedback would be any new issues (that did not exist in previous Python releases), or if "everything works fine".

**Comment by benmoran56** [comment]
Tested this quite a bit on Arch Linux. 
The unit/integration tests complete as expected.
No bugs, or behavioral issues found with a few large projects.

**Comment by ccanepa** [comment]
tests/unit green on win11
integration and interactive multiple failures, but same results with 3.11 and 3.8; were the tests passing at some time?

anyway, I created two issues about those failures.

**Comment by pushfoo** [comment]
> were the tests passing at some time?

There are some known failures for interactive tests at the moment. Example: #948.

**Comment by benmoran56** [comment]
Thanks for the feedback, Claudio.

**Comment by einarf** [comment]
Arcade unit tests and general testing there have worked fine in 3.12 so far. That might only touch 25% of pyglet, but it's something at least.

**Comment by pushfoo** [comment]
Python 3.12 built with optimizations enabled doesn't seem to break any part of non-interactive tests under Debian 11:

I built CPython's [`v3.12.0` tag](https://github.com/python/cpython/releases/tag/v3.12.0) the with `--enable-optimizations` flag. For both our `master` and `development` branches:

  * Unit tests all pass
  * The only integration test failures are pre-existing ones

**Comment by shenjackyuanjie** [comment]
## `tests\interactive\text\test_caret_color.py`

> ## Windows
> * platform win32 -- Python 3.8.18+, pytest-7.4.2, pluggy-1.0.0
> * platform win32 -- Python 3.10.11, pytest-7.4.2, pluggy-1.0.0
> * platform win32 -- Python 3.11.4, pytest-7.4.2, pluggy-1.3.0
> * platform win32 -- Python 3.12.0, pytest-7.4.2, pluggy-1.3.0
> 
> Test passed

**Comment by shenjackyuanjie** [comment]
![image](https://github.com/pyglet/pyglet/assets/54507071/4e1f03d0-4cb7-4067-9aa8-efd6768be946)

## notice

when I use the caret
I can spotted that the last word "window" is hidden

**Comment by shenjackyuanjie** [comment]
Mac test at #976
