### ISSUE TITLE
ImportError: cannot import name 'gluErrorString' from 'pyglet.gl'

### ISSUE THREAD

**Issue by alicecox15** [pyglet/pyglet#983]
Hello! 

I am very new to Python but am trying to convert a .psydat file to a .csv using the code below:

from psychopy.misc import fromFile
fpath = '/Users/my_user/myexperiments/myexperiment/participant_expname_date.psydat'
psydata = fromFile(fpath)
save_path = '/Users/my_user/Desktop/test_out.csv'
psydata.saveAsWideText(save_path, delim=',')

However, I get the following error message when running the 3rd row of code (using fromFile):
ImportError: cannot import name 'gluErrorString' from 'pyglet.gl' (/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pyglet/gl/__init__.py)

Any help would be great! I am using Python 3.12, PsychoPy 2022.2.4 and Pyglet 1.5.0 (I have tried using the the latest Pyglet also)

**Comment by caffeinepills** [comment]
GLU only exists in pyglet 1.5, verify your install.

It will be missing from Pyglet 2.0 as it's deprecated.

**Comment by alicecox15** [comment]
I have pyglet 1.5.0 installed, not Pyglet 2.0 or 1.5.28

**Comment by benmoran56** [comment]
Judging by your trackback, it looks like you're on a Mac. 
pyglet 1.5.0 is unlikely to work on recent releases of macOS, due to changes in library paths, etc.
First give it a try with the latest 1.5.x release, which is 1.5.28.

**Comment by caffeinepills** [comment]
Closing as stale.
