### ISSUE TITLE
ImportError: cannot import name 'resources' from 'game'

### ISSUE THREAD

**Issue by Kewei12345** [pyglet/pyglet#985]
ImportError: cannot import name 'resources' from 'game'

This error occurred when I tried to follow your tutorial in the section "Making the player and asteroid sprites"
https://pyglet.readthedocs.io/en/latest/programming_guide/examplegame.html#programming-guide-game

This is the way how the files are arranged which I followed
![image](https://github.com/pyglet/pyglet/assets/148737548/b9b2608b-0c5d-467d-93a6-238c67150078)

**Comment by Wojciech-Smelcerz** [comment]
It looks like there is no 'resources.py' inside "game" directory.

**Comment by caffeinepills** [comment]
This has been open for a while, but this is user error. There is no load.py or resources.py in the game folder.

I don't have an issue running the game examples. If you still have issues with this, copy the files from the examples/game folder. Running the file examples\game\version1\asteroid.py works just fine on my end.
