### ISSUE TITLE
Regression: UI frame contents no longer redraw

### ISSUE THREAD

**Issue by pushfoo** [pyglet/pyglet#989]
### tl;dr

UI in `examples/gui/widgets.py` no longer updates widgets, but labels still work.

### Issue Details

Branches affected: `master`, but not `development`

Steps to replicate:
1. Checkout a commit after ece645e1a6790320
2. Run `examples/gui/widgets.py`
3. Interact with widgets
4. Observe that values update but the widgets do not

### System Details

| Detail | Value |
|---------|---------|
| OS     | Debian 11 / x86_64 |
| GPU  | Intel UHD Graphics 620 |
| DE     | Gnome 3 on Wayland |

**Comment by benmoran56** [comment]
I can replicate this.

**Comment by pushfoo** [comment]
The interactive tests still work, btw. 

I suspect this might be some group-order related issue because I had something similar happen when experimenting with widget-like behavior and groups. I don't understand it well enough yet to debug this efficiently.

**Comment by pushfoo** [comment]
This appears fixed on my side with the latest commit, ty! :+1:

**Comment by benmoran56** [comment]
Great, thanks. I'll close this now.
