### ISSUE TITLE
Got an error when loading mp3 with pyglet.media

### ISSUE THREAD

**Issue by Freakwill** [pyglet/pyglet#99]
Got the following error when loading a .mp3 file with `pyglet.media`

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyglet/media/codecs/ffmpeg.py", line 579, in __del__
    ffmpeg_free_packet(self._packet)
AttributeError: 'FFmpegSource' object has no attribute '_packet'

pyglet: latest version
python: 3.7
os: macOS

**Comment by benmoran56** [comment]
Does this happen with any mp3 file? If so, could you share a short code example of what you're doing?

**Comment by vishalmote** [comment]
> Got the following error when loading a .mp3 file with `pyglet.media`
> 
> Traceback (most recent call last):
> File "/usr/local/lib/python3.7/site-packages/pyglet/media/codecs/ffmpeg.py", line 579, in **del**
> ffmpeg_free_packet(self._packet)
> AttributeError: 'FFmpegSource' object has no attribute '_packet'
> 
> pyglet: latest version
> python: 3.7
> os: macOS


I am facing same issue on rpi3b+

OS rasbian
python 2.7
ffmpeg 4.2
pyglet latest

following is sample code :

```
import pyglet
vidPath = 'sample.mp4'
window = pyglet.window.Window(resizable=True)
window.set_size(1280, 720)
window.set_location(0,-10)

player = pyglet.media.Player()
source = pyglet.media.StreamingSource()
mediaLoad = pyglet.media.load(vidPath)
player.queue(mediaLoad)
player.play()

@window.event
def on_draw():
    if(player.source and player.source.video_format):
        player.get_texture().blit(0,0)

pyglet.app.run()

```


and following is exception I am facing :


```
Traceback (most recent call last):
  File "vishal_code.py", line 9, in <module>
    mediaLoad = pyglet.media.load(vidPath)
  File "/home/pi/.local/lib/python2.7/site-packages/pyglet/media/__init__.py", line 133, in load
    loaded_source = decoder.decode(file, filename, streaming)
  File "/home/pi/.local/lib/python2.7/site-packages/pyglet/media/codecs/ffmpeg.py", line 1042, in decode
    return FFmpegSource(filename, file)
  File "/home/pi/.local/lib/python2.7/site-packages/pyglet/media/codecs/ffmpeg.py", line 461, in __init__
    self._file = ffmpeg_open_filename(asbytes_filename(filename))
  File "/home/pi/.local/lib/python2.7/site-packages/pyglet/media/codecs/ffmpeg.py", line 144, in ffmpeg_open_filename
    raise FFmpegException('Error opening file ' + filename.decode("utf8"))
pyglet.media.codecs.ffmpeg.FFmpegException: Error opening file sample.mp4
Exception AttributeError: "'FFmpegSource' object has no attribute '_packet'" in <bound method FFmpegSource.__del__ of <pyglet.media.codecs.ffmpeg.FFmpegSource object at 0x6e0b2870>> ignored

```
