### ISSUE TITLE
vertex_list and vertex_list_indexed only allows for 2 vertex data attributes

### ISSUE THREAD

**Issue by totex** [pyglet/pyglet#998]
I want to add texture coordinates to a vertex list, but it results in an error:
```
program.vertex_list(4, GL_TRIANGLE_FAN,
                    batch=batch,
                    vertices=('f', (-0.5, -0.5, 0.5, -0.5, 0.5, 0.5, -0.5, 0.5)),
                    colors=('Bn', (255, 0, 0, 255, 0, 255, 0, 255, 0, 0, 255, 255, 255, 255, 255, 255)),
                    texture_coords=('f', (0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0)))
```

This prints the following error:
```
pyglet.graphics.shader.ShaderException: 
The attribute `texture_coords` doesn't exist. Valid names: 
['colors', 'vertices']
```

My vertex shader attributes are set like this:
```
#version 330
layout(location = 0) in vec2 vertices;
layout(location = 1) in vec4 colors;
layout(location = 2) in vec2 texture_coords; 
```

A vertex list should accept multiple data attributes: vertices, colors, texture coordinates, normals, bone transforms, bone weights

**Comment by benmoran56** [comment]
Most OpenGL drivers will optimize out any attributes (or uniforms) that are not being used or are redundant.
The `ShaderProgram.attributes` dictionary can be checked to see which attributes exist after linking.

**Comment by totex** [comment]
You are right. The texture coordinates were not used. I've added the logic to use them, and the attributes now returns the dict:
```
('colors', {'type': 35666, 'size': 1, 'location': 1, 'count': 4, 'format': 'f'})
('texture_coords', {'type': 35664, 'size': 1, 'location': 2, 'count': 2, 'format': 'f'})
('vertices', {'type': 35664, 'size': 1, 'location': 0, 'count': 2, 'format': 'f'})
```
Thank you, it works now.

**Comment by benmoran56** [comment]
@totex 
I added this information to the traceback message, so it can give a hint to the issue. That should be in the next point release. 

Also, I just noticed in your code, but you're using GL_TRIANGLE_FAN. 
Unfortunately, this is not usable with a Batch at this time. The way pyglet combines multiple vertex lists internally inside of the VertexDomain (internal to Batch) makes certain primitives impossible. Please see this section for more information:
https://pyglet.readthedocs.io/en/latest/programming_guide/graphics.html#creating-vertex-lists
